package br.com.petrobras.sistam.desktop.agenciamento.formularios.capitania;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.SRadioPanel;
import br.com.petrobras.fcorp.swing.components.STextArea;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Agenciamento;
import br.com.petrobras.sistam.desktop.components.SistamDateChooser;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;

public class ParteSaidaDialog extends SDialog {
    private ParteSaidaDialogModel model;
    
    public ParteSaidaDialog(java.awt.Frame parent, Agenciamento agenciamento) {
        super(parent, true);
        model = new ParteSaidaDialogModel(agenciamento);
        initComponents();
        setLocationRelativeTo(parent);
    }

    public ParteSaidaDialogModel getModel() {
        return model;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        GenericAction actionGerarFormulario = new GenericAction();
        SPanel pnlCabecalho = new SPanel();
        SLabel labelNome = new SLabel();
        SLabel labelViagem = new SLabel();
        SLabel labelNomeConteudo = new SLabel();
        SLabel labelViagemConteudo = new SLabel();
        SPanel pnlCentral = new SPanel();
        SPanel pnlInfComplementares = new SPanel();
        SLabel sLabel9 = new SLabel();
        SRadioPanel radioPanelTripulantes = new SRadioPanel();
        SLabel sLabel10 = new SLabel();
        SRadioPanel radioPanelPassageiros = new SRadioPanel();
        SLabel sLabel3 = new SLabel();
        JScrollPane jScrollPane1 = new JScrollPane();
        STextArea sTextArea1 = new STextArea();
        SistamDateChooser sistamDateChooser2 = new SistamDateChooser();
        SLabel sLabel4 = new SLabel();
        SPanel pnlBotoes = new SPanel();
        SButton btImprimir = new SButton();

        actionGerarFormulario.setIcon(new ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        actionGerarFormulario.setMethodName("gerarFormulario");
        actionGerarFormulario.setTarget(model);
        actionGerarFormulario.setText("Gerar Formulário");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Emitir Parte de Saída");

        pnlCabecalho.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        pnlCabecalho.setName("pnlCabecalho"); // NOI18N
        pnlCabecalho.setPreferredSize(new Dimension(400, 40));

        ResourceBundle bundle = ResourceBundle.getBundle("sistam-labels"); // NOI18N
        labelNome.setText(bundle.getString("lblNome")); // NOI18N
        labelNome.setName("labelNome"); // NOI18N

        labelViagem.setText(bundle.getString("lblViagem")); // NOI18N
        labelViagem.setName("labelViagem"); // NOI18N

        labelNomeConteudo.setName("labelNomeConteudo"); // NOI18N
        labelNomeConteudo.setRequiredField(true);

        Binding binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agenciamento.embarcacao.nomeCompleto}"), labelNomeConteudo, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        labelViagemConteudo.setName("labelViagemConteudo"); // NOI18N
        labelViagemConteudo.setRequiredField(true);

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agenciamento.vgm}"), labelViagemConteudo, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        GroupLayout pnlCabecalhoLayout = new GroupLayout(pnlCabecalho);
        pnlCabecalho.setLayout(pnlCabecalhoLayout);
        pnlCabecalhoLayout.setHorizontalGroup(
            pnlCabecalhoLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(labelNomeConteudo, GroupLayout.PREFERRED_SIZE, 333, GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(labelViagem, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(labelViagemConteudo, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCabecalhoLayout.setVerticalGroup(
            pnlCabecalhoLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCabecalhoLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(labelNomeConteudo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelViagemConteudo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                        .addGroup(pnlCabecalhoLayout.createParallelGroup(Alignment.BASELINE)
                            .addComponent(labelNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelViagem, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(pnlCabecalho, BorderLayout.PAGE_START);

        pnlCentral.setName("pnlCentral"); // NOI18N

        pnlInfComplementares.setBorder(BorderFactory.createTitledBorder(bundle.getString("anexos"))); // NOI18N
        pnlInfComplementares.setName("pnlInfComplementares"); // NOI18N

        sLabel9.setText(bundle.getString("lbListaTripulantesAlteracao")); // NOI18N
        sLabel9.setName("sLabel9"); // NOI18N

        radioPanelTripulantes.setName("radioPanelTripulantes"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.listaSimNao}"), radioPanelTripulantes, BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.tripulantes}"), radioPanelTripulantes, BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        GroupLayout radioPanelTripulantesLayout = new GroupLayout(radioPanelTripulantes);
        radioPanelTripulantes.setLayout(radioPanelTripulantesLayout);
        radioPanelTripulantesLayout.setHorizontalGroup(
            radioPanelTripulantesLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        radioPanelTripulantesLayout.setVerticalGroup(
            radioPanelTripulantesLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        sLabel10.setText(bundle.getString("lblListaPassageirosAlteracao")); // NOI18N
        sLabel10.setName("sLabel10"); // NOI18N

        radioPanelPassageiros.setName("radioPanelPassageiros"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.listaSimNao}"), radioPanelPassageiros, BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.passageiros}"), radioPanelPassageiros, BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        GroupLayout radioPanelPassageirosLayout = new GroupLayout(radioPanelPassageiros);
        radioPanelPassageiros.setLayout(radioPanelPassageirosLayout);
        radioPanelPassageirosLayout.setHorizontalGroup(
            radioPanelPassageirosLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        radioPanelPassageirosLayout.setVerticalGroup(
            radioPanelPassageirosLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        GroupLayout pnlInfComplementaresLayout = new GroupLayout(pnlInfComplementares);
        pnlInfComplementares.setLayout(pnlInfComplementaresLayout);
        pnlInfComplementaresLayout.setHorizontalGroup(
            pnlInfComplementaresLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlInfComplementaresLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(radioPanelTripulantes, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlInfComplementaresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sLabel10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(radioPanelPassageiros, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInfComplementaresLayout.setVerticalGroup(
            pnlInfComplementaresLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlInfComplementaresLayout.createSequentialGroup()
                .addGroup(pnlInfComplementaresLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(radioPanelTripulantes, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInfComplementaresLayout.createParallelGroup(Alignment.LEADING)
                    .addGroup(pnlInfComplementaresLayout.createSequentialGroup()
                        .addComponent(sLabel10, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(radioPanelPassageiros, GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)))
        );

        sLabel3.setText(bundle.getString("lblObservacao")); // NOI18N
        sLabel3.setName("sLabel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        sTextArea1.setColumns(20);
        sTextArea1.setDocument(new GenericDocument(200) );
        sTextArea1.setLineWrap(true);
        sTextArea1.setRows(2);
        sTextArea1.setWrapStyleWord(true);
        sTextArea1.setName("sTextArea1"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.voFormulario.observacao}"), sTextArea1, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(sTextArea1);

        sistamDateChooser2.setName("sistamDateChooser2"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.dataDocumento}"), sistamDateChooser2, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel4.setText("Data do Documento: ");
        sLabel4.setName("sLabel4"); // NOI18N

        GroupLayout pnlCentralLayout = new GroupLayout(pnlCentral);
        pnlCentral.setLayout(pnlCentralLayout);
        pnlCentralLayout.setHorizontalGroup(
            pnlCentralLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCentralLayout.createParallelGroup(Alignment.LEADING)
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addComponent(pnlInfComplementares, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addGroup(pnlCentralLayout.createParallelGroup(Alignment.LEADING)
                            .addGroup(pnlCentralLayout.createSequentialGroup()
                                .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)))
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(sistamDateChooser2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCentralLayout.setVerticalGroup(
            pnlCentralLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCentralLayout.createParallelGroup(Alignment.LEADING, false)
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(pnlInfComplementares, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(pnlCentralLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sistamDateChooser2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(pnlCentral, BorderLayout.CENTER);

        pnlBotoes.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        pnlBotoes.setName("pnlBotoes"); // NOI18N
        pnlBotoes.setPreferredSize(new Dimension(400, 40));

        btImprimir.setAction(actionGerarFormulario);
        btImprimir.setName("btImprimir"); // NOI18N
        pnlBotoes.add(btImprimir);

        getContentPane().add(pnlBotoes, BorderLayout.PAGE_END);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
