package br.com.petrobras.sistam.common.enums;

import java.io.Serializable;

/**
 * Classe RecursoCA
 */


public enum RecursoCA implements Serializable {

    CAIXA_ENTRADA,
    SALVAR_AGENCIAMENTO,
    CANCELAR_AGENCIAMENTO,
    CANCELAR_AGENCIAMENTO_ADM,
    VISUALIZAR_AGENCIAMENTO_ADM,
    CONSULTAR_AGENCIAMENTO,
    INFORMAR_MANOBRA,
    LIBERACAO_ANVISA,
    SALVAR_CERTIFICADO,
    INFORMAR_OPERACAO,
    EXCLUIR_OPERACAO,
    SALVAR_DOCUMENTACAO_CABOTAGEM,
    EXCLUIR_DOCUMENTACAO_CABOTAGEM,
    SALVAR_TAXA,
    SALVAR_DOCUMENTO,
    EXCLUIR_DOCUMENTO,
    ANEXAR_ARQUIVO,
    SALVAR_VISITA,
    EXCLUIR_PENDENCIA,
    ADMINISTRACAO,
    SALVAR_EMBARCACAO,
    SALVAR_EMPRESA,
    SALVAR_AGENCIA,
    SALVAR_PORTO,
    SALVAR_PORTO_COMPLEMENTO,
    INCLUIR_AGENCIA,
    ENVIAR_MOVIMENTACAO,
    RELATORIO,
    MOVIMENTACAO_NAVIO,
    PAINEL_COMPLETO,
    PAINEL_SIMPLIFICADO,
    RELATORIO_PRODUTIVIDADE,
    RELATORIO_TAXAS,
    SALVAR_SERVICO_PROTECAO,
    SALVAR_SERVICO_MEDICO_ODONTOLOGICO, 
    RELATORIO_TIMESHEET, 
    RELATORIO_ATENDIMENTO_EMBARCACAO, 
    SALVAR_EMPRESA_PROTECAO, 
    SALVAR_PESSOA_PROTECAO,
    RELATORIO_MANOBRAS, 
    RELATORIO_VISITAS, 
    RELATORIO_ANALISE_GERAL_SISCOMEX_CARGA, 
    RELATORIO_SERVICO_SUPRIMENTO_AOS_NAVIOS;
}


