package br.com.petrobras.sistam.desktop.agenciamento.formularios.policiaFederal;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SDateChooser;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SNumericTextField;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.SRadioPanel;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.renderers.ImageBooleanRenderer;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Agenciamento;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;

public class FormularioPasseSaidaPoliciaFederalDialog extends SDialog {
    private FormularioPasseSaidaPoliciaFederalModel model;
    
    public FormularioPasseSaidaPoliciaFederalDialog(java.awt.Frame parent, Agenciamento agenciamento) {
        super(parent, true);
        model = new FormularioPasseSaidaPoliciaFederalModel(agenciamento);
        initComponents();        
        setLocationRelativeTo(parent);  
        model.getSaidaPoliciaFederalVO().addPropertyChangeListener(model); 
       
    }

    public FormularioPasseSaidaPoliciaFederalModel getModel() {
        return model;
    }
    
    public void gerarFormulario(){
        model.validar();
        model.carregarVO();
        model.gerarFormulario();
        dispose();
    }  
     

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        actionGerarFormulario = new GenericAction();
        ImageBooleanRenderer imageBooleanGerado = new ImageBooleanRenderer();
        SPanel pnlPrincipal = new SPanel();
        SPanel pnlBotoes = new SPanel();
        SButton sButton1 = new SButton();
        SPanel panelInformacoesComplementares = new SPanel();
        pnlListaPasseAcessoPoliciaFederal = new SRadioPanel();
        SLabel sLabel1 = new SLabel();
        SLabel sLabel2 = new SLabel();
        STextField txtAgenteArmador = new STextField();
        SLabel sLabel9 = new SLabel();
        STextField txtEscalas2 = new STextField();
        SPanel panelEmTransito = new SPanel();
        SLabel sLabel4 = new SLabel();
        SLabel sLabel5 = new SLabel();
        SNumericTextField sntfTransito = new SNumericTextField();
        SNumericTextField sntfClandestino2 = new SNumericTextField();
        SLabel sLabel14 = new SLabel();
        SDateChooser sDateChooser3 = new SDateChooser();
        SPanel panelChegadaEmbarcacao = new SPanel();
        SLabel sLabel6 = new SLabel();
        SNumericTextField sntfClandestino1 = new SNumericTextField();
        SNumericTextField sntfClandestino = new SNumericTextField();
        SLabel sLabel3 = new SLabel();
        SLabel sLabel7 = new SLabel();
        SNumericTextField sntfClandestino3 = new SNumericTextField();
        SLabel sLabel8 = new SLabel();
        SNumericTextField sntfTransito1 = new SNumericTextField();
        SPanel panelSaidaEmbarcacao = new SPanel();
        SLabel sLabel11 = new SLabel();
        SNumericTextField sntfClandestino4 = new SNumericTextField();
        SLabel sLabel10 = new SLabel();
        SNumericTextField sntfTransito2 = new SNumericTextField();
        SLabel sLabel12 = new SLabel();
        SNumericTextField sntfClandestino5 = new SNumericTextField();
        SLabel sLabel13 = new SLabel();
        SNumericTextField sntfClandestino6 = new SNumericTextField();

        actionGerarFormulario.setIcon(new ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        actionGerarFormulario.setMethodName("gerarFormulario");
        actionGerarFormulario.setTarget(this);
        actionGerarFormulario.setText("Gerar Formulário");
        actionGerarFormulario.setToolTipText("Gera o formulário");

        imageBooleanGerado.setFalseIcon(new ImageIcon(getClass().getResource("/icons/props.png"))); // NOI18N
        imageBooleanGerado.setTrueIcon(new ImageIcon(getClass().getResource("/icons/document-accept.png"))); // NOI18N

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário Polícia Federal");

        pnlPrincipal.setBorder(BorderFactory.createEtchedBorder());
        pnlPrincipal.setName("pnlPrincipal"); // NOI18N

        pnlBotoes.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        pnlBotoes.setName("pnlBotoes"); // NOI18N

        sButton1.setAction(actionGerarFormulario);
        sButton1.setName("sButton1"); // NOI18N
        pnlBotoes.add(sButton1);

        panelInformacoesComplementares.setBorder(BorderFactory.createTitledBorder("Passe de Saída de Embarcação"));
        panelInformacoesComplementares.setName("panelInformacoesComplementares"); // NOI18N

        pnlListaPasseAcessoPoliciaFederal.setBorder(BorderFactory.createTitledBorder(""));
        pnlListaPasseAcessoPoliciaFederal.setHorizontalGap(8);
        pnlListaPasseAcessoPoliciaFederal.setName("pnlListaPasseAcessoPoliciaFederal"); // NOI18N

        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.listaPasseAcessoPoliciaFederal}"), pnlListaPasseAcessoPoliciaFederal, BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.saidaPoliciaFederalVO.tipoPasseAcessoPoliciaFederal}"), pnlListaPasseAcessoPoliciaFederal, BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        GroupLayout pnlListaPasseAcessoPoliciaFederalLayout = new GroupLayout(pnlListaPasseAcessoPoliciaFederal);
        pnlListaPasseAcessoPoliciaFederal.setLayout(pnlListaPasseAcessoPoliciaFederalLayout);
        pnlListaPasseAcessoPoliciaFederalLayout.setHorizontalGroup(
            pnlListaPasseAcessoPoliciaFederalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlListaPasseAcessoPoliciaFederalLayout.setVerticalGroup(
            pnlListaPasseAcessoPoliciaFederalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        sLabel1.setText("Escalas:");
        sLabel1.setName("sLabel1"); // NOI18N

        sLabel2.setText("Carga:");
        sLabel2.setName("sLabel2"); // NOI18N

        txtAgenteArmador.setDocument(new GenericDocument(35));
        txtAgenteArmador.setName("txtAgenteArmador"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.carga}"), txtAgenteArmador, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sLabel9.setText("GRU:");
        sLabel9.setName("sLabel9"); // NOI18N

        txtEscalas2.setDocument(new GenericDocument(35));
        txtEscalas2.setName("txtEscalas2"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.nrEscala}"), txtEscalas2, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        panelEmTransito.setBorder(BorderFactory.createTitledBorder("Em Trânsito"));
        panelEmTransito.setName("panelEmTransito"); // NOI18N

        sLabel4.setText("Clandestinos/Impedidos:");
        sLabel4.setName("sLabel4"); // NOI18N

        sLabel5.setText("Outros:");
        sLabel5.setName("sLabel5"); // NOI18N

        sntfTransito.setIntegerPlaces(new Short((short)4));
        sntfTransito.setText("sNumericTextField1");
        sntfTransito.setName("sntfTransito"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.outrosTransito}"), sntfTransito, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        sntfClandestino2.setIntegerPlaces(new Short((short)4));
        sntfClandestino2.setName("sntfClandestino2"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.clandestinoImpedidosTransito}"), sntfClandestino2, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        GroupLayout panelEmTransitoLayout = new GroupLayout(panelEmTransito);
        panelEmTransito.setLayout(panelEmTransitoLayout);
        panelEmTransitoLayout.setHorizontalGroup(
            panelEmTransitoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, panelEmTransitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmTransitoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sLabel4, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel5, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmTransitoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sntfClandestino2, GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addComponent(sntfTransito, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelEmTransitoLayout.setVerticalGroup(
            panelEmTransitoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelEmTransitoLayout.createSequentialGroup()
                .addGroup(panelEmTransitoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfClandestino2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEmTransitoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfTransito, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        );

        sLabel14.setText("Data do Documento:");
        sLabel14.setName("sLabel14"); // NOI18N

        sDateChooser3.setName("sDateChooser3"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.saidaPoliciaFederalVO.dataDocumento}"), sDateChooser3, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        panelChegadaEmbarcacao.setBorder(BorderFactory.createTitledBorder("Desembarque neste Porto"));
        panelChegadaEmbarcacao.setName("panelChegadaEmbarcacao"); // NOI18N

        sLabel6.setText("Tripulantes:");
        sLabel6.setName("sLabel6"); // NOI18N

        sntfClandestino1.setIntegerPlaces(new Short((short)4));
        sntfClandestino1.setName("sntfClandestino1"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.tripulanteChegadaEmbarcao}"), sntfClandestino1, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        sntfClandestino.setIntegerPlaces(new Short((short)4));
        sntfClandestino.setText("sNumericTextField1");
        sntfClandestino.setName("sntfClandestino"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.passageiroChegadaEmbarcao}"), sntfClandestino, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        sLabel3.setText("Passageiros:");
        sLabel3.setName("sLabel3"); // NOI18N

        sLabel7.setText("Clandestinos/Impedidos:");
        sLabel7.setName("sLabel7"); // NOI18N

        sntfClandestino3.setIntegerPlaces(new Short((short)4));
        sntfClandestino3.setText("sNumericTextField1");
        sntfClandestino3.setName("sntfClandestino3"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.clandestinoImpedidosChegadaEmbarcacao}"), sntfClandestino3, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        sLabel8.setText("Outros:");
        sLabel8.setName("sLabel8"); // NOI18N

        sntfTransito1.setIntegerPlaces(new Short((short)4));
        sntfTransito1.setText("sNumericTextField1");
        sntfTransito1.setName("sntfTransito1"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.outrosChegadaEmbarcacao}"), sntfTransito1, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        GroupLayout panelChegadaEmbarcacaoLayout = new GroupLayout(panelChegadaEmbarcacao);
        panelChegadaEmbarcacao.setLayout(panelChegadaEmbarcacaoLayout);
        panelChegadaEmbarcacaoLayout.setHorizontalGroup(
            panelChegadaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelChegadaEmbarcacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChegadaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sLabel6, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel3, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel7, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel8, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelChegadaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(sntfClandestino3, GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addComponent(sntfClandestino, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfTransito1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfClandestino1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelChegadaEmbarcacaoLayout.setVerticalGroup(
            panelChegadaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelChegadaEmbarcacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChegadaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfClandestino1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelChegadaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfClandestino, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelChegadaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfClandestino3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelChegadaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel8, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfTransito1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelSaidaEmbarcacao.setBorder(BorderFactory.createTitledBorder("Embarque neste Porto"));
        panelSaidaEmbarcacao.setName("panelSaidaEmbarcacao"); // NOI18N

        sLabel11.setText("Clandestinos/Impedidos:");
        sLabel11.setName("sLabel11"); // NOI18N

        sntfClandestino4.setIntegerPlaces(new Short((short)4));
        sntfClandestino4.setName("sntfClandestino4"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.clandestinoImpedidosSaidaEmbarcacao}"), sntfClandestino4, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        sLabel10.setText("Técnicos:");
        sLabel10.setName("sLabel10"); // NOI18N

        sntfTransito2.setIntegerPlaces(new Short((short)4));
        sntfTransito2.setText("sNumericTextField1");
        sntfTransito2.setName("sntfTransito2"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.tecnicosSaidaEmbarcacao}"), sntfTransito2, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        sLabel12.setText("Tripulantes:");
        sLabel12.setName("sLabel12"); // NOI18N

        sntfClandestino5.setIntegerPlaces(new Short((short)4));
        sntfClandestino5.setName("sntfClandestino5"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.tripulanteSaidaEmbarcao}"), sntfClandestino5, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        sLabel13.setText("Passageiros:");
        sLabel13.setName("sLabel13"); // NOI18N

        sntfClandestino6.setIntegerPlaces(new Short((short)4));
        sntfClandestino6.setText("sNumericTextField1");
        sntfClandestino6.setName("sntfClandestino6"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.passageiroSaidaEmbarcao}"), sntfClandestino6, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        GroupLayout panelSaidaEmbarcacaoLayout = new GroupLayout(panelSaidaEmbarcacao);
        panelSaidaEmbarcacao.setLayout(panelSaidaEmbarcacaoLayout);
        panelSaidaEmbarcacaoLayout.setHorizontalGroup(
            panelSaidaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelSaidaEmbarcacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSaidaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sLabel12, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel13, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel11, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel10, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSaidaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(sntfClandestino6, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfClandestino5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfTransito2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfClandestino4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSaidaEmbarcacaoLayout.setVerticalGroup(
            panelSaidaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, panelSaidaEmbarcacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSaidaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel12, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfClandestino5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSaidaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel13, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfClandestino6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSaidaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel11, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfClandestino4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSaidaEmbarcacaoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel10, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfTransito2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        GroupLayout panelInformacoesComplementaresLayout = new GroupLayout(panelInformacoesComplementares);
        panelInformacoesComplementares.setLayout(panelInformacoesComplementaresLayout);
        panelInformacoesComplementaresLayout.setHorizontalGroup(
            panelInformacoesComplementaresLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacoesComplementaresLayout.createSequentialGroup()
                .addGroup(panelInformacoesComplementaresLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(GroupLayout.Alignment.LEADING, panelInformacoesComplementaresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelInformacoesComplementaresLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(sLabel9, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel14, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInformacoesComplementaresLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(panelInformacoesComplementaresLayout.createSequentialGroup()
                                .addComponent(sDateChooser3, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(pnlListaPasseAcessoPoliciaFederal, GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)))
                    .addGroup(panelInformacoesComplementaresLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addGroup(GroupLayout.Alignment.TRAILING, panelInformacoesComplementaresLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(panelInformacoesComplementaresLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(sLabel1, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(sLabel2, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelInformacoesComplementaresLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEscalas2, GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                                .addComponent(txtAgenteArmador, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelInformacoesComplementaresLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(panelInformacoesComplementaresLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(panelEmTransito, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelSaidaEmbarcacao, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelChegadaEmbarcacao, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(17, 17, 17))
        );
        panelInformacoesComplementaresLayout.setVerticalGroup(
            panelInformacoesComplementaresLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacoesComplementaresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformacoesComplementaresLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEscalas2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesComplementaresLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAgenteArmador, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEmTransito, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelChegadaEmbarcacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSaidaEmbarcacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesComplementaresLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(pnlListaPasseAcessoPoliciaFederal, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesComplementaresLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sLabel14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sDateChooser3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        GroupLayout pnlPrincipalLayout = new GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBotoes, GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addComponent(panelInformacoesComplementares, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInformacoesComplementares, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(pnlPrincipal, BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    GenericAction actionGerarFormulario;
    SRadioPanel pnlListaPasseAcessoPoliciaFederal;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
