package br.com.petrobras.sistam.desktop.agenciamento;

import br.com.petrobras.fcorp.swing.base.SInternalFrame;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STable;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.dialog.DialogMessages;
import br.com.petrobras.fcorp.swing.components.renderers.DateCellRenderer;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Agencia;
import br.com.petrobras.sistam.common.entity.Agenciamento;
import br.com.petrobras.sistam.common.entity.Embarcacao;
import br.com.petrobras.sistam.common.entity.Porto;
import br.com.petrobras.sistam.common.enums.StatusEmbarcacao;
import br.com.petrobras.sistam.desktop.SistamApp;
import br.com.petrobras.sistam.desktop.components.SistamDateCellRenderer;
import br.com.petrobras.sistam.desktop.components.SistamDateChooser;
import br.com.petrobras.sistam.desktop.components.TimeZoneComboBox;
import br.com.petrobras.sistam.desktop.components.lookups.embarcacao.EmbarcacaoLookup;
import br.com.petrobras.sistam.desktop.components.lookups.porto.PortoLookup;
import br.com.petrobras.snarf.desktop.assync.AssyncInvoker;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.ResourceBundle;
import java.util.TimeZone;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.JTableBinding.ColumnBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * Classe ConsultaAgenciamentoFrame
 */
public class ConsultaAgenciamentoFrame extends SInternalFrame  {

    private ConsultaAgenciamentoModel model;
    
    public ConsultaAgenciamentoFrame() {
        this.model = new ConsultaAgenciamentoModel();
        initComponents();
        carregarCombos();
    }
    
    public ConsultaAgenciamentoModel getModel() {
        return model;
    }
    
    private void carregarCombos() {
        AssyncInvoker.create(model, "carregarAgencias")
                .disabling(cboAgencia)
                .settingLoadingIconOn(lblAgencia)
                .schedule();
    }
    
    public void visualizar() {
        AgenciamentoEmbarcacaoFrame frame;
        if(model.validarVisualizacaoConsultaAgenciamento()){
            frame = (AgenciamentoEmbarcacaoFrame) SistamApp.getSistamApp().getMainFrame().openInternalFrame(model.buscarAgenciamentoParaConsulta(), AgenciamentoEmbarcacaoFrame.class, true);
        }else{
            frame = (AgenciamentoEmbarcacaoFrame) SistamApp.getSistamApp().getMainFrame().openInternalFrame(model.buscarAgenciamentoParaConsulta(), AgenciamentoEmbarcacaoFrame.class, true);
            frame.colocarEmModoVisualizacao();            
        }
        
    }
    
    public void consultar() {
        model.consultar();
        if (model.getAgenciamentos() != null && model.getAgenciamentos().size() == Agenciamento.PROP_LIMITE_CONSULTA_REGISTROS) {
            DialogMessages.info(this, "Podem existir mais registros do que os mostrados na lista. Refine sua consulta.");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        GenericAction actionConsultar = new GenericAction();
        GenericAction actionVisualizar = new GenericAction();
        DateCellRenderer dateCellRenderer = new DateCellRenderer();
        SistamDateCellRenderer sistamDateCellRenderer1 = new SistamDateCellRenderer();
        SPanel pnlFiltro = new SPanel();
        SButton sButton1 = new SButton();
        JPanel jPanel4 = new JPanel();
        lblAgencia = new SLabel();
        cboAgencia = new SComboBox();
        comboPorto = new SComboBox();
        JLabel jLabel1 = new JLabel();
        timeZoneComboBox = new TimeZoneComboBox();
        lblAgencia1 = new SLabel();
        JPanel jPanel5 = new JPanel();
        PortoLookup portoLookup1 = new PortoLookup();
        PortoLookup portoLookup2 = new PortoLookup();
        JLabel jLabel2 = new JLabel();
        JLabel jLabel3 = new JLabel();
        JPanel jPanel6 = new JPanel();
        SLabel sLabel11 = new SLabel();
        SLabel labelAreaDenavegacao = new SLabel();
        SComboBox comboAreaDeNavegacao = new SComboBox();
        SComboBox sComboBox5 = new SComboBox();
        JPanel jPanel7 = new JPanel();
        SLabel sLabel10 = new SLabel();
        STextField sTextField1 = new STextField();
        JPanel jPanel8 = new JPanel();
        SistamDateChooser dtEstimadaSaida4 = new SistamDateChooser();
        SLabel sLabel71 = new SLabel();
        SistamDateChooser dtEstimadaSaida5 = new SistamDateChooser();
        SPanel sPanel1 = new SPanel();
        SLabel sLabel2 = new SLabel();
        cboAgencia1 = new SComboBox();
        SLabel sLabel1 = new SLabel();
        EmbarcacaoLookup embarcacaoLookup1 = new EmbarcacaoLookup();
        SLabel sLabel20 = new SLabel();
        STextField sTextField2 = new STextField();
        SPanel sPanel2 = new SPanel();
        JPanel jPanel3 = new JPanel();
        SistamDateChooser dtEstimadaSaida2 = new SistamDateChooser();
        SLabel sLabel70 = new SLabel();
        SistamDateChooser dtEstimadaSaida3 = new SistamDateChooser();
        JPanel jPanel2 = new JPanel();
        SistamDateChooser dtEstimadaSaida = new SistamDateChooser();
        SLabel sLabel69 = new SLabel();
        SistamDateChooser dtEstimadaSaida1 = new SistamDateChooser();
        SPanel pnlPrincipal = new SPanel();
        JScrollPane jScrollPane1 = new JScrollPane();
        STable sTable1 = new STable();
        SPanel pnlBotoes = new SPanel();
        SButton sButton2 = new SButton();

        actionConsultar.setIcon(new ImageIcon(getClass().getResource("/icons/listagem_busca.png"))); // NOI18N
        actionConsultar.setMethodName("consultar");
        actionConsultar.setNeededSecurityResources(new String[] {});
        actionConsultar.setTarget(this);
        actionConsultar.setText("Consultar");

        actionVisualizar.setIcon(new ImageIcon(getClass().getResource("/icons/find.png"))); // NOI18N
        actionVisualizar.setMethodName("visualizar");
        actionVisualizar.setNeededSecurityResources(new String[] {});
        actionVisualizar.setTarget(this);
        actionVisualizar.setText("Visualizar");

        Binding binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${not empty model.agenciamentoSelecinado}"), actionVisualizar, BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        dateCellRenderer.setPattern("dd/MM/yyyy HH:mm");

        sistamDateCellRenderer1.setPattern("dd/MM/yyyy HH:mm");

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.timeZoneSelecionado}"), sistamDateCellRenderer1, BeanProperty.create("timeZone"));
        bindingGroup.addBinding(binding);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Agenciamento");
        setFrameIcon(new ImageIcon(getClass().getResource("/icons/find.png"))); // NOI18N

        pnlFiltro.setBorder(BorderFactory.createTitledBorder("Filtro para consulta de Agenciamento(s)"));
        pnlFiltro.setName("pnlFiltro"); // NOI18N

        sButton1.setAction(actionConsultar);
        sButton1.setName("sButton1"); // NOI18N

        jPanel4.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jPanel4.setName("jPanel4"); // NOI18N

        ResourceBundle bundle = ResourceBundle.getBundle("sistam-labels"); // NOI18N
        lblAgencia.setText(bundle.getString("lblAgencia")); // NOI18N
        lblAgencia.setName("lblAgencia"); // NOI18N

        cboAgencia.setName("cboAgencia"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.agencias}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE, this, eLProperty, cboAgencia);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.agencia}"), cboAgencia, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        comboPorto.setName("comboPorto"); // NOI18N

        eLProperty = ELProperty.create("${model.portos}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE, this, eLProperty, comboPorto);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.porto}"), comboPorto, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        comboPorto.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                comboPortoActionPerformed(evt);
            }
        });
        comboPorto.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                comboPortoActionPerformed(evt);
            }
        });

        jLabel1.setText("Porto:");
        jLabel1.setName("jLabel1"); // NOI18N

        timeZoneComboBox.setEnabled(false);
        timeZoneComboBox.setName("timeZoneComboBox"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.timeZoneSelecionado}"), timeZoneComboBox, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        lblAgencia1.setText("Fuso Horário:");
        lblAgencia1.setName("lblAgencia1"); // NOI18N

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jLabel1, Alignment.TRAILING)
                    .addComponent(lblAgencia, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgencia1, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(comboPorto, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboAgencia, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timeZoneComboBox, GroupLayout.PREFERRED_SIZE, 195, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(lblAgencia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAgencia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(timeZoneComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgencia1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(comboPorto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel5.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        jPanel5.setName("jPanel5"); // NOI18N

        portoLookup1.setName("portoLookup1"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.portoOrigem}"), portoLookup1, BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        portoLookup2.setName("portoLookup2"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.portoDestino}"), portoLookup2, BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jLabel2.setText("Porto Destino:");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Porto Origem:");
        jLabel3.setName("jLabel3"); // NOI18N

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(portoLookup2, GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(portoLookup1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(portoLookup1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(portoLookup2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel6.setName("jPanel6"); // NOI18N

        sLabel11.setText(bundle.getString("lblAreaNavegacao")); // NOI18N
        sLabel11.setName("sLabel11"); // NOI18N

        labelAreaDenavegacao.setText("Tipo Contrato:");
        labelAreaDenavegacao.setName("labelAreaDenavegacao"); // NOI18N

        comboAreaDeNavegacao.setName("comboAreaDeNavegacao"); // NOI18N

        eLProperty = ELProperty.create("${model.tiposContrato}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE, this, eLProperty, comboAreaDeNavegacao);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.tipoContrato}"), comboAreaDeNavegacao, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        sComboBox5.setName("sComboBox5"); // NOI18N

        eLProperty = ELProperty.create("${model.areasNavegacao}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE, this, eLProperty, sComboBox5);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.areaNavegacao}"), sComboBox5, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sLabel11, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(sComboBox5, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE))
                    .addGroup(Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelAreaDenavegacao, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(comboAreaDeNavegacao, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(labelAreaDenavegacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAreaDeNavegacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(sLabel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sComboBox5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        jPanel7.setName("jPanel7"); // NOI18N

        sLabel10.setText("Processo:");
        sLabel10.setName("sLabel10"); // NOI18N

        sTextField1.setDocument(new GenericDocument(10));
        sTextField1.setName("sTextField1"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.numeroProcesso}"), sTextField1, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel8.setBorder(BorderFactory.createTitledBorder("Data de Inclusão do Processo"));
        jPanel8.setName("jPanel8"); // NOI18N

        dtEstimadaSaida4.setName("dtEstimadaSaida4"); // NOI18N
        dtEstimadaSaida4.setTimeZoneComboBox(timeZoneComboBox);

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.dataInclusaoIni}"), dtEstimadaSaida4, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel71.setText("até");
        sLabel71.setName("sLabel71"); // NOI18N

        dtEstimadaSaida5.setName("dtEstimadaSaida5"); // NOI18N
        dtEstimadaSaida5.setTimeZoneComboBox(timeZoneComboBox);

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.dataInclusaoFim}"), dtEstimadaSaida5, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        GroupLayout jPanel8Layout = new GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtEstimadaSaida4, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(sLabel71, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(dtEstimadaSaida5, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(Alignment.BASELINE)
                .addComponent(dtEstimadaSaida4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel71, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(dtEstimadaSaida5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        GroupLayout jPanel7Layout = new GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(sLabel10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(sTextField1, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(sLabel10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jPanel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sPanel1.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sPanel1.setName("sPanel1"); // NOI18N

        sLabel2.setText("Situação:");
        sLabel2.setName("sLabel2"); // NOI18N

        cboAgencia1.setName("cboAgencia1"); // NOI18N

        eLProperty = ELProperty.create("${model.listaStatus}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE, this, eLProperty, cboAgencia1);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.statusEmbarcacao}"), cboAgencia1, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        sLabel1.setText(bundle.getString("embarcacao")); // NOI18N
        sLabel1.setName("sLabel1"); // NOI18N

        embarcacaoLookup1.setName("embarcacaoLookup1"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.embarcacao}"), embarcacaoLookup1, BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        sLabel20.setText(bundle.getString("lblViagem")); // NOI18N
        sLabel20.setName("sLabel20"); // NOI18N

        sTextField2.setDocument(new GenericDocument(10));
        sTextField2.setName("sTextField2"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.vgm}"), sTextField2, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        GroupLayout sPanel1Layout = new GroupLayout(sPanel1);
        sPanel1.setLayout(sPanel1Layout);
        sPanel1Layout.setHorizontalGroup(
            sPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sPanel1Layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(sLabel1, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel2, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(sPanel1Layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(sPanel1Layout.createSequentialGroup()
                        .addComponent(embarcacaoLookup1, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(sLabel20, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(sTextField2, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cboAgencia1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sPanel1Layout.setVerticalGroup(
            sPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, sPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(embarcacaoLookup1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel20, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAgencia1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        sPanel2.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sPanel2.setName("sPanel2"); // NOI18N

        jPanel3.setBorder(BorderFactory.createTitledBorder("Data de Saída"));
        jPanel3.setName("jPanel3"); // NOI18N

        dtEstimadaSaida2.setName("dtEstimadaSaida2"); // NOI18N
        dtEstimadaSaida2.setTimeZoneComboBox(timeZoneComboBox);

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.dataSaidaIni}"), dtEstimadaSaida2, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel70.setText("até");
        sLabel70.setName("sLabel70"); // NOI18N

        dtEstimadaSaida3.setName("dtEstimadaSaida3"); // NOI18N
        dtEstimadaSaida3.setTimeZoneComboBox(timeZoneComboBox);

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.dataSaidaFim}"), dtEstimadaSaida3, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtEstimadaSaida2, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(sLabel70, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(dtEstimadaSaida3, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
                .addComponent(dtEstimadaSaida2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel70, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(dtEstimadaSaida3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(BorderFactory.createTitledBorder("Data de Chegada"));
        jPanel2.setName("jPanel2"); // NOI18N

        dtEstimadaSaida.setName("dtEstimadaSaida"); // NOI18N
        dtEstimadaSaida.setTimeZoneComboBox(timeZoneComboBox);

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.dataChegadaIni}"), dtEstimadaSaida, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel69.setText("até");
        sLabel69.setName("sLabel69"); // NOI18N

        dtEstimadaSaida1.setName("dtEstimadaSaida1"); // NOI18N
        dtEstimadaSaida1.setTimeZoneComboBox(timeZoneComboBox);

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.dataChegadaFim}"), dtEstimadaSaida1, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtEstimadaSaida, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(sLabel69, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(dtEstimadaSaida1, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(Alignment.TRAILING)
            .addGroup(Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(dtEstimadaSaida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel69, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtEstimadaSaida1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        GroupLayout sPanel2Layout = new GroupLayout(sPanel2);
        sPanel2.setLayout(sPanel2Layout);
        sPanel2Layout.setHorizontalGroup(
            sPanel2Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(sPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sPanel2Layout.createParallelGroup(Alignment.LEADING, false)
                    .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sPanel2Layout.setVerticalGroup(
            sPanel2Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, sPanel2Layout.createSequentialGroup()
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        GroupLayout pnlFiltroLayout = new GroupLayout(pnlFiltro);
        pnlFiltro.setLayout(pnlFiltroLayout);
        pnlFiltroLayout.setHorizontalGroup(
            pnlFiltroLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFiltroLayout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(sButton1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFiltroLayout.createParallelGroup(Alignment.LEADING)
                        .addGroup(pnlFiltroLayout.createSequentialGroup()
                            .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(sPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlFiltroLayout.createSequentialGroup()
                            .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.UNRELATED)
                            .addComponent(sPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFiltroLayout.setVerticalGroup(
            pnlFiltroLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, pnlFiltroLayout.createSequentialGroup()
                .addGroup(pnlFiltroLayout.createParallelGroup(Alignment.TRAILING, false)
                    .addComponent(jPanel4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sPanel2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(pnlFiltroLayout.createParallelGroup(Alignment.TRAILING, false)
                    .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sPanel1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sButton1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlFiltro, BorderLayout.PAGE_START);

        pnlPrincipal.setBorder(BorderFactory.createTitledBorder("Agenciamento(s)"));
        pnlPrincipal.setName("pnlPrincipal"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        sTable1.setSortable(true);
        sTable1.setName("sTable1"); // NOI18N

        eLProperty = ELProperty.create("${model.agenciamentos}");
        JTableBinding jTableBinding = SwingBindings.createJTableBinding(UpdateStrategy.READ_WRITE, this, eLProperty, sTable1);
        ColumnBinding columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${embarcacao}"));
        columnBinding.setColumnName("Embarcacao");
        columnBinding.setColumnClass(Embarcacao.class);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${vgmEntradaSaida}"));
        columnBinding.setColumnName("Vgm (E/S)");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${numeroProcessoformatado}"));
        columnBinding.setColumnName("Processo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${dataInclusao}"));
        columnBinding.setColumnName("Data Inclusao");
        columnBinding.setColumnClass(Date.class);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${statusEmbarcacao}"));
        columnBinding.setColumnName("Status Embarcacao");
        columnBinding.setColumnClass(StatusEmbarcacao.class);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${agencia}"));
        columnBinding.setColumnName("Agencia");
        columnBinding.setColumnClass(Agencia.class);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${porto}"));
        columnBinding.setColumnName("Porto");
        columnBinding.setColumnClass(Porto.class);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${portoOrigem}"));
        columnBinding.setColumnName("Porto Origem");
        columnBinding.setColumnClass(Porto.class);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${portoDestino}"));
        columnBinding.setColumnName("Porto Destino");
        columnBinding.setColumnClass(Porto.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agenciamentoSelecinado}"), sTable1, BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(sTable1);
        sTable1.getColumnModel().getColumn(3).setCellRenderer(sistamDateCellRenderer1);

        GroupLayout pnlPrincipalLayout = new GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(pnlPrincipal, BorderLayout.CENTER);

        pnlBotoes.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        pnlBotoes.setName("pnlBotoes"); // NOI18N
        pnlBotoes.setPreferredSize(new Dimension(565, 50));

        sButton2.setAction(actionVisualizar);
        sButton2.setName("sButton2"); // NOI18N
        pnlBotoes.add(sButton2);

        getContentPane().add(pnlBotoes, BorderLayout.PAGE_END);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPortoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_comboPortoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPortoActionPerformed
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    SComboBox cboAgencia;
    SComboBox cboAgencia1;
    SComboBox comboPorto;
    SLabel lblAgencia;
    SLabel lblAgencia1;
    TimeZoneComboBox timeZoneComboBox;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
