package br.com.petrobras.sistam.desktop.agenciamento;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STextArea;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Desvio;
import br.com.petrobras.sistam.desktop.components.SistamDateChooser;
import br.com.petrobras.sistam.desktop.components.SistamTimeChooser;
import br.com.petrobras.sistam.desktop.components.TimeZoneComboBox;
import br.com.petrobras.sistam.desktop.components.lookups.porto.PortoLookup;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

public class DesvioDialog extends SDialog {
    private DesvioDialogModel model;
   
    public DesvioDialog(java.awt.Frame parent, Desvio desvio) {
        super(parent, true);
        this.model = new DesvioDialogModel(desvio);
        initComponents();
        setLocationRelativeTo(parent);
        
        timeZoneComboBox1.setSelectedItem(desvio.getAgenciamento().getAgencia().obterTimezone());
    }
    
    public DesvioDialogModel getModel() {
        return model;
    }
    
    public void confirmar() {
        model.confirmar();
        dispose();
    }
    
    public void colocarEmModoVisualizacao() {
        lookupPortoDestinoEfetivio.setEnabled(false);
        comboMotivo.setEnabled(false);
        botaoConfirmar.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        GenericAction actionConfirmar = new GenericAction();
        timeZoneComboBox1 = new TimeZoneComboBox();
        JScrollPane jScrollPane2 = new JScrollPane();
        STextArea sTextArea2 = new STextArea();
        SPanel pnlEscalas = new SPanel();
        SPanel pnlTipoServico = new SPanel();
        SLabel sLabel1 = new SLabel();
        comboMotivo = new SComboBox();
        SLabel sLabel2 = new SLabel();
        SLabel sLabel3 = new SLabel();
        lookupPortoDestinoEfetivio = new PortoLookup();
        SLabel labelValorPortoDestino = new SLabel();
        SLabel sLabel4 = new SLabel();
        SLabel sLabel5 = new SLabel();
        SistamDateChooser sistamDateChooser1 = new SistamDateChooser();
        STextField sTextField1 = new STextField();
        SistamTimeChooser sistamTimeChooser1 = new SistamTimeChooser();
        SLabel sLabel6 = new SLabel();
        JScrollPane jScrollPane1 = new JScrollPane();
        STextArea sTextArea1 = new STextArea();
        JScrollPane jScrollPane3 = new JScrollPane();
        STextArea sTextArea3 = new STextArea();
        SLabel sLabel7 = new SLabel();
        SPanel pnlBotoes = new SPanel();
        botaoConfirmar = new SButton();

        actionConfirmar.setIcon(new ImageIcon(getClass().getResource("/icons/concluir.png"))); // NOI18N
        actionConfirmar.setMethodName("confirmar");
        actionConfirmar.setTarget(this);
        actionConfirmar.setText("Confirmar");
        actionConfirmar.setToolTipText("Confirma o desvio");

        timeZoneComboBox1.setName("timeZoneComboBox1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        sTextArea2.setColumns(20);
        sTextArea2.setRows(5);
        sTextArea2.setName("sTextArea2"); // NOI18N
        jScrollPane2.setViewportView(sTextArea2);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Desvio de Rota do Agenciamento");

        pnlEscalas.setName("pnlEscalas"); // NOI18N

        pnlTipoServico.setBorder(BorderFactory.createTitledBorder("Informações"));
        pnlTipoServico.setName("pnlTipoServico"); // NOI18N

        sLabel1.setText("Motivo:");
        sLabel1.setName("sLabel1"); // NOI18N

        comboMotivo.setName("comboMotivo"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.listaMotivos}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, comboMotivo);
        bindingGroup.addBinding(jComboBoxBinding);
        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.desvio.motivo}"), comboMotivo, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        sLabel2.setText("Porto Destino Anterior:");
        sLabel2.setName("sLabel2"); // NOI18N

        sLabel3.setText("Porto Destino Efetivo:");
        sLabel3.setName("sLabel3"); // NOI18N

        lookupPortoDestinoEfetivio.setText("portoLookup2");
        lookupPortoDestinoEfetivio.setName("lookupPortoDestinoEfetivio"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.novoPortoDestino}"), lookupPortoDestinoEfetivio, BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        lookupPortoDestinoEfetivio.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                lookupPortoDestinoEfetivioActionPerformed(evt);
            }
        });

        labelValorPortoDestino.setName("labelValorPortoDestino"); // NOI18N
        labelValorPortoDestino.setRequiredField(true);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.desvio.portoDestinoAlterado.nomeCompleto}"), labelValorPortoDestino, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sLabel4.setText("Desviado Em:");
        sLabel4.setName("sLabel4"); // NOI18N

        sLabel5.setText("Por:");
        sLabel5.setName("sLabel5"); // NOI18N

        sistamDateChooser1.setEnabled(false);
        sistamDateChooser1.setName("sistamDateChooser1"); // NOI18N
        sistamDateChooser1.setTimeChooser(sistamTimeChooser1);
        sistamDateChooser1.setTimeZoneComboBox(timeZoneComboBox1);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.desvio.data}"), sistamDateChooser1, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sTextField1.setEnabled(false);
        sTextField1.setName("sTextField1"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.desvio.usuarioFormatado}"), sTextField1, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sistamTimeChooser1.setEnabled(false);
        sistamTimeChooser1.setName("sistamTimeChooser1"); // NOI18N

        sLabel6.setText("Destino Intermediário Efetivo:");
        sLabel6.setName("sLabel6"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        sTextArea1.setColumns(20);
        sTextArea1.setDocument(new GenericDocument(120,
            GenericDocument.OPTION_APPLY_UPPERCASE));
    sTextArea1.setLineWrap(true);
    sTextArea1.setRows(2);
    sTextArea1.setName("sTextArea1"); // NOI18N

    binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.novoDestinoIntermediario}"), sTextArea1, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jScrollPane1.setViewportView(sTextArea1);

    jScrollPane3.setName("jScrollPane3"); // NOI18N

    sTextArea3.setColumns(20);
    sTextArea3.setLineWrap(true);
    sTextArea3.setRows(2);
    sTextArea3.setEnabled(false);
    sTextArea3.setName("sTextArea3"); // NOI18N

    binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.desvio.destinoIntermediarioAlterado}"), sTextArea3, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jScrollPane3.setViewportView(sTextArea3);

    sLabel7.setText("Destino Intermediário Anterior:");
    sLabel7.setName("sLabel7"); // NOI18N

        GroupLayout pnlTipoServicoLayout = new GroupLayout(pnlTipoServico);
    pnlTipoServico.setLayout(pnlTipoServicoLayout);
    pnlTipoServicoLayout.setHorizontalGroup(
        pnlTipoServicoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(pnlTipoServicoLayout.createSequentialGroup()
            .addContainerGap(12, Short.MAX_VALUE)
            .addGroup(pnlTipoServicoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(sLabel2, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel7, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel3, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel6, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel1, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel4, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel5, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlTipoServicoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addComponent(labelValorPortoDestino, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboMotivo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lookupPortoDestinoEfetivio, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sTextField1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1)
                .addGroup(pnlTipoServicoLayout.createSequentialGroup()
                    .addComponent(sistamDateChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(sistamTimeChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    pnlTipoServicoLayout.setVerticalGroup(
        pnlTipoServicoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(pnlTipoServicoLayout.createSequentialGroup()
            .addGap(5, 5, 5)
            .addGroup(pnlTipoServicoLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
                .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(labelValorPortoDestino, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlTipoServicoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(sLabel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlTipoServicoLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
                .addComponent(lookupPortoDestinoEfetivio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlTipoServicoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(sLabel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlTipoServicoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(comboMotivo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(pnlTipoServicoLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
                .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sistamDateChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sistamTimeChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(pnlTipoServicoLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
                .addComponent(sLabel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    pnlBotoes.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
    pnlBotoes.setName("pnlBotoes"); // NOI18N

    botaoConfirmar.setAction(actionConfirmar);
    botaoConfirmar.setName("botaoConfirmar"); // NOI18N
    pnlBotoes.add(botaoConfirmar);

        GroupLayout pnlEscalasLayout = new GroupLayout(pnlEscalas);
    pnlEscalas.setLayout(pnlEscalasLayout);
    pnlEscalasLayout.setHorizontalGroup(
        pnlEscalasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(pnlEscalasLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlEscalasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(pnlTipoServico, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBotoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    pnlEscalasLayout.setVerticalGroup(
        pnlEscalasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(pnlEscalasLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(pnlTipoServico, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(pnlBotoes, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    getContentPane().add(pnlEscalas, BorderLayout.CENTER);

    bindingGroup.bind();

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lookupPortoDestinoEfetivioActionPerformed(ActionEvent evt) {//GEN-FIRST:event_lookupPortoDestinoEfetivioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lookupPortoDestinoEfetivioActionPerformed
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    SButton botaoConfirmar;
    SComboBox comboMotivo;
    PortoLookup lookupPortoDestinoEfetivio;
    TimeZoneComboBox timeZoneComboBox1;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
