package br.com.petrobras.sistam.desktop.agenciamento.formularios.policiaFederal;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SDateChooser;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SNumericTextField;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STextArea;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.renderers.ImageBooleanRenderer;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Agenciamento;
import br.com.petrobras.sistam.desktop.util.DesktopUtil;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

public class FormularioRequerimentoPasseSaidaPoliciaFederalDialog extends SDialog {
    private FormularioRequerimentoPasseSaidaPoliciaFederalModel model;
    
    public FormularioRequerimentoPasseSaidaPoliciaFederalDialog(java.awt.Frame parent, Agenciamento agenciamento) {
        super(parent, true);
        model = new FormularioRequerimentoPasseSaidaPoliciaFederalModel(agenciamento);
        initComponents();        
        setLocationRelativeTo(parent);  
        model.getRequerimentoPasseSaidaPoliciaFederalVO().addPropertyChangeListener(model); 
       
    }

    public FormularioRequerimentoPasseSaidaPoliciaFederalModel getModel() {
        return model;
    }
    
    public void gerarFormulario(){
        model.validar();
        model.carregarVO();
        model.gerarFormulario();
        dispose();
    } 
     

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        actionGerarFormulario = new GenericAction();
        ImageBooleanRenderer imageBooleanGerado = new ImageBooleanRenderer();
        SPanel pnlPrincipal = new SPanel();
        SPanel pnlBotoes = new SPanel();
        SButton sButton1 = new SButton();
        SPanel panelPessoas1 = new SPanel();
        SPanel panelPessoas = new SPanel();
        SComboBox sComboBox1 = new SComboBox();
        SDateChooser sDateChooser2 = new SDateChooser();
        SLabel sLabel8 = new SLabel();
        SLabel sLabel2 = new SLabel();
        SLabel sLabel3 = new SLabel();
        STextField txtAgenteArmador = new STextField();
        SLabel sLabel4 = new SLabel();
        SComboBox sComboBox2 = new SComboBox();
        SLabel sLabel5 = new SLabel();
        JScrollPane jScrollPane1 = new JScrollPane();
        STextArea sTextArea1 = new STextArea();
        STextField txtAgenteArmador1 = new STextField();
        SDateChooser sDateChooser3 = new SDateChooser();
        SLabel sLabel9 = new SLabel();

        actionGerarFormulario.setIcon(new ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        actionGerarFormulario.setMethodName("gerarFormulario");
        actionGerarFormulario.setTarget(this);
        actionGerarFormulario.setText("Gerar Formulário");
        actionGerarFormulario.setToolTipText("Gera o formulário");

        imageBooleanGerado.setFalseIcon(new ImageIcon(getClass().getResource("/icons/props.png"))); // NOI18N
        imageBooleanGerado.setTrueIcon(new ImageIcon(getClass().getResource("/icons/document-accept.png"))); // NOI18N

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário Polícia Federal");

        pnlPrincipal.setBorder(BorderFactory.createEtchedBorder());
        pnlPrincipal.setName("pnlPrincipal"); // NOI18N

        pnlBotoes.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        pnlBotoes.setName("pnlBotoes"); // NOI18N

        sButton1.setAction(actionGerarFormulario);
        sButton1.setName("sButton1"); // NOI18N
        pnlBotoes.add(sButton1);

        panelPessoas1.setBorder(BorderFactory.createTitledBorder("Requerimento do Passe de Saída"));
        panelPessoas1.setName("panelPessoas1"); // NOI18N

        panelPessoas.setBorder(BorderFactory.createTitledBorder("Representante Legal"));
        panelPessoas.setName("panelPessoas"); // NOI18N

        sComboBox1.setName("sComboBox1"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.agenciamento.agencia.representantes}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, sComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);
        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.requerimentoPasseSaidaPoliciaFederalVO.listaRepresentante}"), sComboBox1, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        GroupLayout panelPessoasLayout = new GroupLayout(panelPessoas);
        panelPessoas.setLayout(panelPessoasLayout);
        panelPessoasLayout.setHorizontalGroup(
            panelPessoasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sComboBox1, GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPessoasLayout.setVerticalGroup(
            panelPessoasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sDateChooser2.setName("sDateChooser2"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.requerimentoPasseSaidaPoliciaFederalVO.dataEntradaNoPorto}"), sDateChooser2, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel8.setText("Data da Entrada no Porto:");
        sLabel8.setName("sLabel8"); // NOI18N

        sLabel2.setText("Nº do Passe de Entrada:");
        sLabel2.setName("sLabel2"); // NOI18N

        sLabel3.setText("Operação:");
        sLabel3.setName("sLabel3"); // NOI18N

        txtAgenteArmador.setDocument(new GenericDocument(50));
        txtAgenteArmador.setName("txtAgenteArmador"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.carga}"), txtAgenteArmador, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sLabel4.setText("Tipo de Requerimento:");
        sLabel4.setName("sLabel4"); // NOI18N

        sComboBox2.setName("sComboBox2"); // NOI18N

        eLProperty = ELProperty.create("${model.listaTipoRequerimento}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, sComboBox2);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.requerimentoPasseSaidaPoliciaFederalVO.tipoRequerimentoPasseSaidaPoliciaFederal}"), sComboBox2, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        sLabel5.setText("Justificativa:");
        sLabel5.setName("sLabel5"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        sTextArea1.setColumns(20);
        sTextArea1.setDocument(new GenericDocument(300));
        sTextArea1.setLineWrap(true);
        sTextArea1.setRows(5);
        sTextArea1.setName("sTextArea1"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.justificativa}"), sTextArea1, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(sTextArea1);

        txtAgenteArmador1.setDocument(new GenericDocument(50));
        txtAgenteArmador1.setName("txtAgenteArmador1"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.numeroPasseEntrada}"), txtAgenteArmador1, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sDateChooser3.setName("sDateChooser3"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.requerimentoPasseSaidaPoliciaFederalVO.dataDocumento}"), sDateChooser3, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel9.setText("Data do Documento:");
        sLabel9.setName("sLabel9"); // NOI18N

        GroupLayout panelPessoas1Layout = new GroupLayout(panelPessoas1);
        panelPessoas1.setLayout(panelPessoas1Layout);
        panelPessoas1Layout.setHorizontalGroup(
            panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPessoas1Layout.createSequentialGroup()
                        .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(sLabel2, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel3, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel8, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel4, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel5, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel9, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(txtAgenteArmador, GroupLayout.PREFERRED_SIZE, 350, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAgenteArmador1, GroupLayout.PREFERRED_SIZE, 350, GroupLayout.PREFERRED_SIZE)
                                .addComponent(sComboBox2, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 350, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 350, GroupLayout.PREFERRED_SIZE))
                            .addComponent(sDateChooser2, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                            .addComponent(sDateChooser3, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelPessoas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPessoas1Layout.setVerticalGroup(
            panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoas1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel2, GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtAgenteArmador1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAgenteArmador, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sDateChooser2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sLabel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sDateChooser3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPessoas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GroupLayout pnlPrincipalLayout = new GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(panelPessoas1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotoes, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPessoas1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlPrincipal, BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    GenericAction actionGerarFormulario;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
