-- SEQUENCES
CREATE SEQUENCE STAM.SQ_AGEC_SQ_AGENCIAMENTO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE;
CREATE SEQUENCE STAM.SQ_MANO_SQ_MANOBRA INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE;
CREATE SEQUENCE STAM.SQ_AGOR_SQ_AGENCIA_ORGAO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE ;
CREATE SEQUENCE STAM.SQ_AGPE_SQ_PENDENCIA INCREMENT BY 1 MAXVALUE 9999999999999999999999999999  MINVALUE 1 START WITH 250  NOCACHE ;
CREATE SEQUENCE STAM.SQ_EMES_SQ_ESCALA INCREMENT BY 1 MAXVALUE 9999999999999999999999999999  MINVALUE 1 START WITH 250  NOCACHE ;
CREATE SEQUENCE STAM.SQ_EMAN_SQ_MANOBRA INCREMENT BY 1 MAXVALUE 9999999999999999999999999999  MINVALUE 1 START WITH 250  NOCACHE ;
CREATE SEQUENCE STAM.SQ_EMSM_SQ_SERVICO_MANOBRA INCREMENT BY 1 MAXVALUE 9999999999999999999999999999  MINVALUE 1 START WITH 250  NOCACHE ;
CREATE SEQUENCE STAM.SQ_AGTA_SQ_AGENCIAMENTO_TAXA INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250  NOCACHE ;
CREATE SEQUENCE STAM.SQ_EMCE_SQ_CERTIFICADO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250  NOCACHE ;
CREATE SEQUENCE STAM.SQ_AGDO_SQ_AGENCIAMENTO_DOC INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250  NOCACHE ;
CREATE SEQUENCE STAM.SQ_AGAN_SQ_AGENCIAMENTO_ANEXO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250  NOCACHE ;
CREATE SEQUENCE STAM.SQ_VISI_SQ_VISITA INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1  START WITH 250  NOCACHE;
CREATE SEQUENCE STAM.SQ_PRSE_SQ_PROTECAO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1  START WITH 250  NOCACHE;
CREATE SEQUENCE STAM.SQ_EMMA_SQ_EMPRESA_MARITIMA INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1  START WITH 250  NOCACHE;
CREATE SEQUENCE STAM.SQ_EMSE_SQ_EMPRESA_SERVICO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1  START WITH 250  NOCACHE;
CREATE SEQUENCE STAM.SQ_POAT_SQ_PONTO_ATRACACAO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1  START WITH 250  NOCACHE;
CREATE SEQUENCE STAM.SQ_OPER_SQ_OPERACAO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250 NOCACHE ;
CREATE SEQUENCE STAM.SQ_DOCA_SQ_DOC_CABOTAGEM INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250 CACHE 20 ;
CREATE SEQUENCE STAM.SQ_DOOP_SQ_DOC_OPERACAO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250 CACHE 20;
CREATE SEQUENCE STAM.SQ_DOLC_SQ_DOC_LONGO_CURSO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250 NOCACHE;
CREATE SEQUENCE STAM.SQ_DEST_SQ_DESTINATARIO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250 NOCACHE;
CREATE SEQUENCE STAM.SQ_AGAC_SQ_ACOMPANHAMENTO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE;
CREATE SEQUENCE STAM.SQ_HOSP_SQ_HOSPEDE INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250 NOCACHE;
CREATE SEQUENCE STAM.SQ_PASS_SQ_PASSAGEIRO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250 NOCACHE;
CREATE SEQUENCE STAM.SQ_PEAC_SQ_PESSOA INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250 NOCACHE;
CREATE SEQUENCE STAM.SQ_EMPR_SQ_EMPRESA_PROTECAO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250 NOCACHE;
CREATE SEQUENCE STAM.SQ_EMPS_SQ_EMP_PROTECAO_SERV INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250 NOCACHE;
CREATE SEQUENCE STAM.SQ_PESS_SQ_PESSOA INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250 NOCACHE;
CREATE SEQUENCE STAM.SQ_SUTE_SQ_EMPRESA INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250 NOCACHE;
CREATE SEQUENCE STAM.SQ_SUTR_SQ_SOLICITACAO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250 NOCACHE;
CREATE SEQUENCE STAM.SQ_RECU_SQ_RESP_CUSTO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 START WITH 250 NOCACHE;

-- TABLES - SIGO

CREATE GLOBAL TEMPORARY TABLE STAM.PROGRAMACAO_NAVIO
(
    EMBA_CD_ID           VARCHAR2(4 CHAR) NULL ,
    EMBA_NM_COMPLETO     VARCHAR2(30 CHAR) NULL ,
    ESPT_CD_ID           NUMBER NULL ,
    PORT_CD_ID           VARCHAR2(4 CHAR) NULL ,
    ESPT_DT_ETA          VARCHAR2(16 CHAR) NULL ,
    CHEGADA              VARCHAR2(4000 CHAR) NULL ,
    SAIDA                VARCHAR2(4000 CHAR) NULL ,
    POOP_CD_ID           VARCHAR2(4 CHAR) NULL ,
    POOP_NM_COMPLETO     VARCHAR2(40 CHAR) NULL ,
    VIAG_CD_ID_ENTRADA   VARCHAR2(6 CHAR) NULL ,
    VIAG_CD_ID_SAIDA     VARCHAR2(6 CHAR) NULL 
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE STAM.AGENCIA_SIGO
(
  PORT_CD_ID VARCHAR2(4 CHAR),
  PORT_NM_COMPLETO VARCHAR2(100 CHAR),
  PAIS_NM_COMPLETO VARCHAR2(40 CHAR),
  AGEN_CD_ID NUMBER NOT NULL,
  AGEN_NM_COMPLETO VARCHAR2(200 CHAR) NOT NULL,
  AGEN_TX_ENDERECO VARCHAR2(1000 CHAR),
  PAIS_CD_IBGE VARCHAR2(3 CHAR),
  AGEN_TX_TELEFONE VARCHAR2(200 CHAR),
  AGEN_TX_FAX VARCHAR2(200 CHAR),
  AGEN_TX_TLX VARCHAR2(200 CHAR),
  AGEN_TX_EMAIL VARCHAR2(200 CHAR),
  AGEN_TX_WEBSITE VARCHAR2(100 CHAR),
  AGEN_TX_OBSERVACAO VARCHAR2(2000 CHAR),
  AGEN_TX_MATRIZ NUMBER,
  AGEN_TX_CODP VARCHAR2(15 CHAR),
  AGEN_CD_HUB NUMBER,
  AGEN_IN_TIPO NUMBER(1, 0),
  AGEN_IN_BLIST NUMBER(1, 0),
  AGCO_CD_ID NUMBER,
  AGCO_NM_AGENTE VARCHAR2(200 CHAR),
  AGCO_NM_DEPARTAMENTO VARCHAR2(200 CHAR),
  AGCO_TX_TELEFONE VARCHAR2(200 CHAR),
  AGCO_TX_CELULAR VARCHAR2(200 CHAR),
  AGCO_TX_EMAIL VARCHAR2(200 CHAR),
  AGEN_CD_MATRIZ NUMBER,
  AGEN_NM_MATRIZ VARCHAR2(200 CHAR),
  AGEN_NM_HUB VARCHAR2(200 CHAR),
  AGPO_IN_PRINCIPAL NUMBER
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.PORTO_SIGO
(
	PORT_CD_ID           VARCHAR2(4) NOT NULL ,
	PORT_NM_COMPLETO     VARCHAR2(100 CHAR) NULL ,
	PORT_NM_APELIDO      VARCHAR2(30 CHAR) NULL ,
	PAIS_CD_IBGE         VARCHAR2(3 CHAR) NULL ,
	PORT_NR_FUSO         NUMBER(4) NOT NULL ,
	PORT_MD_LATITUDE     VARCHAR2(15 CHAR) NULL ,
	PORT_MD_LONGITUDE    VARCHAR2(15 CHAR) NULL ,
	MIRE_CD_ID           VARCHAR2(4 CHAR) NULL ,
	MIRE_NM_COMPLETO     VARCHAR2(20 CHAR) NULL ,
	PAIS_NM_COMPLETO     VARCHAR2(40 CHAR) NULL ,
	PORT_TX_OBSERVACAO   VARCHAR2(255 CHAR) NULL ,
	PORT_NR_DIFERENCA_HV NUMBER(4) NULL ,
	PORT_CD_CLIENTE_R3   VARCHAR2(10 CHAR) NULL ,
	POAL_CD_ID           VARCHAR2(10 CHAR) NULL ,
	POAL_NM_COMPLETO     VARCHAR2(40 CHAR) NULL ,
	REGI_NM_COMPLETO     VARCHAR2(20 CHAR) NULL 
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.PONTO_ATRACACAO_SIGO
(
	POAT_CD_ID           NUMBER(4) NOT NULL ,
	POAT_NM_COMPLETO     VARCHAR2(50 CHAR) NULL ,
	POOP_CD_ID           VARCHAR2(4 CHAR) NULL ,
	TPOA_CD_TIPO         NUMBER(4) NOT NULL ,
	TPOA_NM_COMPLETO     VARCHAR2(50 CHAR) NULL ,
	POAT_MD_TPB          VARCHAR2(50 CHAR) NULL ,
	POAT_MD_CAL_MAX      VARCHAR2(50 CHAR) NULL ,
	POAT_MD_COMPRIM      VARCHAR2(50 CHAR) NULL ,
	POAT_MD_LATITUDE     VARCHAR2(15 CHAR) NULL ,
	POAT_MD_LONGITUDE    VARCHAR2(15 CHAR) NULL ,
	POAT_MD_LATITUDE2    VARCHAR2(15 CHAR) NULL ,
	POAT_MD_LONGITUDE2   VARCHAR2(15 CHAR) NULL ,
	POOP_NM_COMPLETO     VARCHAR2(40 CHAR) NULL ,
	POOP_CD_ID_LOCAL_OPER VARCHAR2(20 CHAR) NULL ,
	CLPO_CD_ID           VARCHAR2(2 CHAR) NULL ,
	CLPO_NM_COMPLETO     VARCHAR2(30 CHAR) NULL ,
	POAT_NM_CURTO        VARCHAR2(8 CHAR) NULL ,
	POAT_TX_OBSERVACAO   VARCHAR2(255 CHAR) NULL 
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE STAM.PONTO_OPERACIONAL_SIGO
(
	POOP_CD_ID           VARCHAR2(4 CHAR) NOT NULL ,
	POOP_NM_COMPLETO     VARCHAR2(40 CHAR) NULL ,
	PORT_CD_ID           VARCHAR2(4 CHAR) NULL ,
	CLPO_CD_ID           VARCHAR2(2 CHAR) NULL ,
	POOP_CD_ID_LOCAL_OPER VARCHAR2(20 CHAR) NULL ,
	POOP_MD_LATITUDE     VARCHAR2(15 CHAR) NULL ,
	POOP_MD_LONGITUDE    VARCHAR2(15 CHAR) NULL ,
	CLPO_NM_COMPLETO     VARCHAR2(30 CHAR) NULL ,
	PORT_NM_COMPLETO     VARCHAR2(100 CHAR) NULL ,
	PORT_NR_FUSO         NUMBER(4) NOT NULL ,
	ORGA_CD_CBI          VARCHAR2(3 CHAR) NULL ,
	ORGA_SG_ID           VARCHAR2(15 CHAR) NULL ,
	ORGA_NM_COMPLETO     VARCHAR2(78 CHAR) NULL ,
	POOP_TX_OBSERVACAO   VARCHAR2(255 CHAR) NULL,
   CONSTRAINT  PK_POOP PRIMARY KEY (POOP_CD_ID)
) ON COMMIT PRESERVE ROWS;

-- TABLES - STAM
CREATE GLOBAL TEMPORARY TABLE STAM.AGENCIA
(
      AGEN_SQ_AGENCIA NUMBER(6, 0) NOT NULL,
      AGEN_TX_ENDERECO VARCHAR2(1000 CHAR) NOT NULL,
      AGEN_TX_TELEFONE VARCHAR2(150 CHAR) NOT NULL,
      AGEN_TX_FAX VARCHAR2(100 CHAR),
      AGEN_TX_EMAIL VARCHAR2(100 CHAR) NOT NULL,
      AGEN_TX_CIDADE VARCHAR2(100 CHAR) NOT NULL,
      AGEN_CD_ESTADO VARCHAR2(2 CHAR) NOT NULL,
      AGEN_TX_BAIRRO VARCHAR2(60 CHAR),
      AGEN_CD_CEP VARCHAR2(9 CHAR),
      AGEN_SG_AGENCIA VARCHAR2(3 CHAR) NOT NULL,
      AGEN_TX_NR_CNPJ VARCHAR2(14 CHAR),
      AGEN_NM_AGENCIA VARCHAR2(50 CHAR) NOT NULL,
      AGEN_CD_TIMEZONE VARCHAR2(30 CHAR) NULL, 
      AGEN_TX_NR_AFE VARCHAR2(10 CHAR) NULL,
   CONSTRAINT  PK_AGEN PRIMARY KEY (AGEN_SQ_AGENCIA)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.AGENCIA_CONTATO
(
	AGEN_SQ_AGENCIA      NUMBER(6) NOT NULL ,
	AGCO_SQ_CONTATO      NUMBER(6) NOT NULL ,
	AGCO_NM_CONTATO      VARCHAR2(100 CHAR) NOT NULL ,
	AGCO_TX_NR_CPF          VARCHAR2(11 CHAR) NULL, 
        AGCO_IN_ATIVO VARCHAR2(1 CHAR)  DEFAULT 'S' NOT NULL,
   CONSTRAINT  PK_AGCO PRIMARY KEY (AGCO_SQ_CONTATO)
)ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE STAM.AGENCIA_PORTO
(
    PORT_CD_ID VARCHAR2(4 CHAR) NOT NULL,
    AGEN_SQ_AGENCIA NUMBER(6, 0) NOT NULL,
    AGPO_TX_MUNICIPIO VARCHAR2(50 CHAR) NOT NULL,
    AGPO_SQ_AGENCIA_PORTO NUMBER(6, 0) NOT NULL,
        CONSTRAINT PK_AGPO PRIMARY KEY (AGPO_SQ_AGENCIA_PORTO)
)ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.AGENCIA_ORGAO
(
        AGOR_SQ_AGENCIA_ORGAO   NUMBER(5) NOT NULL ,
	AGOR_NM_ORGAO           VARCHAR2(30 CHAR) NOT NULL ,
	AGEN_SQ_AGENCIA         NUMBER(6) NOT NULL ,
   CONSTRAINT  PK_AGOR PRIMARY KEY (AGOR_SQ_AGENCIA_ORGAO)
)ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.AGENCIAMENTO 
(
  AGEC_SQ_AGENCIAMENTO NUMBER(8, 0) NOT NULL 
, PORT_CD_ID VARCHAR2(4 BYTE) NOT NULL 
, EMBA_CD_ID VARCHAR2(4 BYTE) NOT NULL 
, AGEN_SQ_AGENCIA NUMBER(6, 0) NOT NULL 
, AGEC_CD_AGENCIAMENTO NUMBER(10, 0) NOT NULL 
, AGEC_NR_ANO_PROCESSO NUMBER(4, 0) NOT NULL 
, AGEC_IN_STATUS_EMBARCACAO NUMBER(3, 0) NOT NULL 
, AGEC_IN_SITUACAO_PROCESSO NUMBER(3, 0) NOT NULL 
, AGEC_IN_EXCLUIDO VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL 
, PORT_CD_ID_ORIGEM VARCHAR2(4 CHAR) NOT NULL 
, PORT_CD_ID_DESTINO VARCHAR2(4 CHAR) 
, AGEC_CD_VIAGEM VARCHAR2(25 BYTE) NOT NULL 
, AGEC_DT_ETA DATE NOT NULL 
, AGEC_DT_ESTIMADA_SAIDA DATE 
, AGEC_TX_DUV VARCHAR2(15 BYTE) 
, AGEC_NR_ESCALA_MERCANTE NUMBER(12, 0) 
, AGEC_DT_SAIDA DATE 
, AGEC_DT_CHEGADA DATE 
, AGEC_IN_NAVEGACAO NUMBER(1, 0) 
, AGEC_MD_CALADO_ENTRADA_VANTE NUMBER(8, 2) 
, AGEC_MD_CALADO_ENTRADA_RE NUMBER(8, 2) 
, AGEC_MD_CALADO_SAIDA_VANTE NUMBER(8, 2) 
, AGEC_MD_CALADO_SAIDA_RE NUMBER(8, 2) 
, AGEC_DT_ETA_PROX_DESTINO DATE 
, AGEC_TX_ESCALA VARCHAR2(1200 BYTE) 
, AGEC_IN_TIPO_CONTRATO VARCHAR2(3 BYTE) DEFAULT 'TCP' NOT NULL 
, AGEC_TX_NR_PROCESSO_DESPACHO VARCHAR2(20 BYTE) 
, AGEC_DT_INCLUSAO DATE NOT NULL 
, AGEC_NM_CADASTRADOR VARCHAR2(50 BYTE) NOT NULL 
, AGEC_CD_CHAVE_CADASTRADOR VARCHAR2(4 BYTE) NOT NULL 
, AGEC_TX_LONGITUDE_ENTRADA VARCHAR2(14 BYTE) 
, AGEC_TX_LATITUDE_ENTRADA VARCHAR2(14 BYTE) 
, AGEC_IN_CARGA VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL 
, AGEC_IN_PROTECAO VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL 
, AGEC_IN_ARMADOR VARCHAR2(1 BYTE) DEFAULT 'T' NOT NULL 
, AGEC_NR_VERSAO_REGISTRO NUMBER(3, 0) DEFAULT 1 NOT NULL 
, AGEC_TX_DESTINO VARCHAR2(150 BYTE)
, AGEC_TX_OBSERVACAO VARCHAR2(512 BYTE)
, AGEC_CD_VIAGEM_SAIDA VARCHAR2(25 CHAR)
, AGEC_IN_NAVEGACAO_SAIDA NUMBER(1, 0)
, AGEC_IN_FROTA VARCHAR2(1 CHAR) NOT NULL
, AGEC_IN_PLATAFORMA VARCHAR2(1 CHAR) NOT NULL
, CONSTRAINT PK_AGEC PRIMARY KEY (AGEC_SQ_AGENCIAMENTO)

)ON COMMIT PRESERVE ROWS;



CREATE GLOBAL TEMPORARY TABLE STAM.AGENCIAMENTO_SANITARIA
(
  AGEC_SQ_AGENCIAMENTO NUMBER(8, 0) NOT NULL 
, AGSA_IN_AGUA_LASTRO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL 
, AGSA_IN_SUB_AGUA_LASTRO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL 
, AGSA_TX_LONGITUDE_SUBST_AGUA VARCHAR2(14 CHAR) 
, AGSA_TX_LATITUDE_SUBST_AGUA VARCHAR2(14 CHAR) 
, AGSA_IN_DESLASTRO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL 
, AGSA_IN_TANQUE_TRATAMENTO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL 
, AGSA_MD_CAP_ARMAZ_EFLUENTE NUMBER(8, 2) 
, AGSA_IN_AGUA_POTAVEL VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL 
, AGSA_IN_TRAT_AGUA_POTAVEL VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL 
, AGSA_QN_AUTONOMIA_RETENCAO NUMBER(6, 2) 
, AGSA_IN_CARGA_PERIGOSA VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL 
, AGSA_IN_DESINSETIZACAO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL 
, AGSA_IN_RESIDUOS_SOLIDOS VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL 
, AGSA_NM_PRODUTO_DESINSETIZACAO VARCHAR2(80 CHAR) 
, AGSA_DT_DESINSETIZACAO DATE 
, AGSA_IN_ABASTECIMENTO_AGUA VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL 
, AGSA_IN_ABAST_ALIMENTO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL 
, AGSA_NR_VERSAO_REGISTRO NUMBER(3, 0) DEFAULT 1 NOT NULL 
, AGSA_NM_PORTO VARCHAR2(100 CHAR),
        
        CONSTRAINT  PK_AGSA PRIMARY KEY (AGEC_SQ_AGENCIAMENTO)
)ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.AGENCIAMENTO_VIAGEM
(
      AGEC_SQ_AGENCIAMENTO NUMBER(8, 0) NOT NULL,
      AGVI_NM_COMANDANTE_ENTRADA VARCHAR2(100 CHAR),
      AGVI_TX_NACIONALIDADE_ENTRADA VARCHAR2(80 CHAR),
      AGVI_IN_OBITO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
      AGVI_IN_SEPULTAMENTO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
      AGVI_IN_DOENCA VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
      AGVI_IN_FEBRE_HEMORRAGIA VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
      AGVI_IN_ICTERICIA VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
      AGVI_IN_DIARREIA VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
      AGVI_IN_DISF_NEURO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
      AGVI_IN_DIFICUL_RESP VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
      AGVI_IN_ACIDENTE VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
      AGVI_TX_ACIDENTE VARCHAR2(200 CHAR),
      AGVI_IN_ROEDORES VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
      AGVI_TX_COMPART_ROEDOR VARCHAR2(100 CHAR),
      AGVI_IN_CONSUMO_MEDICAM VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
      AGVI_TX_MEDICAMENTO VARCHAR2(100 CHAR),
      AGVI_NR_PASSAGEIROS_ENTRADA NUMBER(6, 0),
      AGVI_NR_TRIPULANTES_ENTRADA NUMBER(6, 0),
      AGVI_NR_PASSAGEIROS_SAIDA NUMBER(6, 0),
      AGVI_NR_TRIPULANTES_SAIDA NUMBER(6, 0),
      AGVI_NM_COMANDANTE_SAIDA VARCHAR2(100 CHAR),
      AGVI_NR_VERSAO_REGISTRO NUMBER(3)  DEFAULT 1 NOT NULL,
      AGVI_TX_NACIONALIDADE_SAIDA VARCHAR2(80 CHAR),
        CONSTRAINT  PK_AGVI PRIMARY KEY (AGEC_SQ_AGENCIAMENTO)
)ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.AGENCIAMENTO_TAXA
(
      AGEC_SQ_AGENCIAMENTO NUMBER(8, 0) NOT NULL,
      AGTA_SQ_AGENCIAMENTO_TAXA NUMBER(8, 0) NOT NULL,
      AGTA_VL_TAXA NUMBER(15, 2) NOT NULL,
      AGTA_DT_PAGAMENTO DATE NOT NULL,
      AGTA_NR_DOCUMENTO NUMBER(8, 0),
      AGTA_NR_PEDIDO_SAP NUMBER(11, 0),
      AGTA_NR_FRS_SAP NUMBER(11, 0),
      AGTA_NR_NL_SAP NUMBER(11, 0) NOT NULL,
      AGTA_IN_TIPO_TAXA NUMBER(2, 0) NOT NULL,
      AGTA_NR_DOC_CONTABIL NUMBER(8, 0),
      AGTA_CD_CHAVE_ALTERACAO VARCHAR2(4) NOT NULL ,
      AGTA_NM_USU_ALTERACAO VARCHAR2(60) NOT NULL ,
      AGTA_DT_ALTERACAO    DATE NOT NULL, 
      RECU_SQ_RESP_CUSTO NUMBER(8, 0) NOT NULL,
      CONSTRAINT PK_AGTA PRIMARY KEY (AGTA_SQ_AGENCIAMENTO_TAXA)
)ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.AGENCIAMENTO_DOCUMENTO 
(
  AGDO_SQ_AGENCIAMENTO_DOC NUMBER(8, 0) NOT NULL 
, AGDO_IN_TIPO_DOCUMENTO NUMBER(2, 0) NOT NULL 
, AGDO_CD_CHAVE_EMITENTE VARCHAR2(4 CHAR) NOT NULL 
, AGDO_NM_EMITENTE VARCHAR2(50 CHAR) NOT NULL 
, AGDO_DT_EMISSAO DATE NOT NULL 
, AGDO_DT_PROTOCOLO DATE 
, AGDP_TX_NUMERO_PROTOCOLO VARCHAR2(30 CHAR) 
, AGEC_SQ_AGENCIAMENTO NUMBER(8, 0) 
, AGCO_SQ_CONTATO NUMBER(6, 0) 
, MANO_SQ_MANOBRA NUMBER(6, 0) 
, OPER_SQ_OPERACAO NUMBER(8, 0) 
, AGDO_DT_FORMULARIO DATE 
, AGDO_TX_NR_CTAC VARCHAR2(16 CHAR) 
, PORT_CD_ID VARCHAR2(4 CHAR)
, AGDO_DT_ETA DATE
, AGDO_DT_CHEGADA DATE
, CONSTRAINT PK_AGDO PRIMARY KEY 
  (
    AGDO_SQ_AGENCIAMENTO_DOC 
  )
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.EMPRESA_MARITIMA 
(
     EMMA_SQ_EMPRESA_MARITIMA NUMBER(8, 0) NOT NULL,
     EMMA_NR_CNPJ VARCHAR2(20 CHAR) NOT NULL , 
     EMMA_NM_RAZAO_SOCIAL VARCHAR2(100 CHAR) NOT NULL ,
     EMMA_TX_EMAIL VARCHAR2(100 CHAR) NULL ,
     EMMA_TX_NR_FAX VARCHAR2(20 CHAR) NULL ,
     EMMA_TX_NR_TELEFINE VARCHAR2(50 CHAR) NULL,
     AGEN_SQ_AGENCIA NUMBER(6, 0) NOT NULL,
     EMMA_IN_EMPRESA_ATIVA VARCHAR2(1 CHAR)  DEFAULT 'S',
     EMMA_CD_ESTADO           VARCHAR2(2 CHAR) NOT NULL,   
     EMMA_TX_CIDADE           VARCHAR2(100 CHAR) NOT NULL,   
     CONSTRAINT PK_EMMA PRIMARY KEY (EMMA_NR_CNPJ)
)ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE STAM.MANOBRA
(
  MANO_SQ_MANOBRA NUMBER(6, 0) NOT NULL,
  AGEC_SQ_AGENCIAMENTO NUMBER(8, 0) NOT NULL,
  MANO_DT_INICIO DATE,
  MANO_DT_TERMINO DATE, 
  MANO_TX_OBSERV_INTERNA VARCHAR2(2000 CHAR),
  MANO_TX_OBSERV_IMPRESSAO VARCHAR2(2000 CHAR),
  MANO_IN_SITUACAO NUMBER(1, 0) NOT NULL,
  MANO_MD_CALADO_VANTE NUMBER(8, 2) NOT NULL,
  MANO_MD_CALADO_RE NUMBER(8, 2) NOT NULL,
  MANO_DT_CHEGADA_DESTINO DATE,
  MANO_DT_PARTIDA_ORIGEM DATE,
  POAT_SQ_PONTO_ATRAC_ORIGEM NUMBER(6, 0) NOT NULL,
  POAT_SQ_PONTO_ATRAC_DESTINO NUMBER(6, 0) NOT NULL,
  MANO_IN_FINALIDADE_MANOBRA NUMBER(2, 0) NOT NULL,
  MANO_TX_CANCELAMENTO VARCHAR2(512 CHAR),
  MANO_DT_INICIO_OPERACAO DATE,
  MANO_DT_FIM_OPERACAO DATE,
  POAT_SQ_PONTO_ATRAC_ESCALA NUMBER(6, 0),
  MANO_IN_MOVIMENTADA VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
  RECU_SQ_RESP_CUSTO NUMBER(8, 0) NOT NULL,
  CONSTRAINT PK_MANO PRIMARY KEY
  (
    MANO_SQ_MANOBRA
  )
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE STAM.EMPRESA_MANOBRA
(
  EMAN_SQ_MANOBRA NUMBER(8, 0) NOT NULL,
  EMAN_IN_SERVICO VARCHAR2(1 CHAR) NOT NULL,
  EMAN_DT_PROGRAMADA DATE NOT NULL,
  EMAN_DT_ENVIO DATE,
  EMAN_TX_OBSERVACAO VARCHAR2(256 CHAR),
  MANO_SQ_MANOBRA NUMBER(6, 0) NOT NULL,
  EMMA_SQ_EMPRESA_MARITIMA  NUMBER(8, 0) NOT NULL,
  EMMA_TX_CIDADE VARCHAR2(100 BYTE), 
  EMMA_CD_ESTADO VARCHAR2(2 BYTE),
    CONSTRAINT  PK_EMAN PRIMARY KEY (EMAN_SQ_MANOBRA)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.EMPRESA_SERVICO
(
   EMSE_SQ_EMPRESA_SERVICO   NUMBER(5, 0) NOT NULL,
   EMMA_SQ_EMPRESA_MARITIMA  NUMBER(8, 0) NOT NULL,
   EMSE_IN_SERVICO           VARCHAR2(1 CHAR) NOT NULL,
   EMSE_NM_SERVICO           VARCHAR2(60 CHAR) NOT NULL,   
   CONSTRAINT PK_EMSE PRIMARY KEY (EMSE_SQ_EMPRESA_SERVICO)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.EMPRESA_SERVICO_MANOBRA
(
     EMAN_SQ_MANOBRA NUMBER(8, 0) NOT NULL,
     EMSM_SQ_SERVICO_MANOBRA NUMBER(8, 0) NOT NULL,
     EMSM_DT_INICIO DATE NOT NULL,
     EMSM_DT_TERMINO DATE NOT NULL,
     EMSM_TX_OBSERVACAO VARCHAR2(256 CHAR),
     EMSE_SQ_EMPRESA_SERVICO NUMBER(5, 0) NOT NULL, 
        CONSTRAINT PK_EMSM PRIMARY KEY (EMSM_SQ_SERVICO_MANOBRA)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.OPERACAO
(
    OPER_SQ_OPERACAO NUMBER(8, 0) NOT NULL,
    AGEC_SQ_AGENCIAMENTO NUMBER(8, 0) NOT NULL,
    PROD_CD_ID VARCHAR2(3 CHAR) NOT NULL,
    OPER_IN_TIPO_OPERACAO NUMBER(3, 0) NOT NULL,
    OPER_QN_ESTIMADA NUMBER(15, 4) NOT NULL,
    OPER_IN_MEDIDA VARCHAR2(1 CHAR) NOT NULL,
    OPER_DT_INICIO DATE,
    OPER_DT_FINAL DATE,
    OPER_TX_ANEXO_UNICO VARCHAR2(13 CHAR), 
	CONSTRAINT PK_OPPR PRIMARY KEY  (OPER_SQ_OPERACAO)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.DOCUMENTACAO_CABOTAGEM
(
  DOCA_SQ_DOC_CABOTAGEM          NUMBER(8, 0) NOT NULL,
  AGEC_SQ_AGENCIAMENTO           NUMBER(8, 0) NOT NULL,
  AGEN_CD_ID                     NUMBER,
  PORT_CD_ID                     VARCHAR2(4 CHAR),
  DOCA_TX_MANIFESTO_ELETRONICO   VARCHAR2(13 CHAR) NOT NULL,
  DOCA_IN_TIPO_OPERACAO          NUMBER(1, 0) NOT NULL,  
  DOCA_TX_CONHECIMENTO_ELETRONIC VARCHAR2(15 BYTE),
  DOCA_TX_NR_CTAC VARCHAR2(16 BYTE),
  
  CONSTRAINT PK_DOOP PRIMARY KEY (DOCA_SQ_DOC_CABOTAGEM)
) 
ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE STAM.DOCUMENTACAO_OPERACAO
(
  DOOP_SQ_DOC_OPERACAO             NUMBER(8, 0) NOT NULL, 
  DOCA_SQ_DOC_CABOTAGEM            NUMBER(8, 0) NOT NULL, 
  OPER_SQ_OPERACAO                 NUMBER(8, 0) NOT NULL, 
  DOOP_MD_PRODUTO_KG               NUMBER(15, 4), 
  DOOP_MD_PRODUTO_LT               NUMBER(15, 4), 
  DOOP_VL_FRETE                    NUMBER(15, 2), 
  DOOP_TX_CONHECIMENTO_ELETRONIC   VARCHAR2(15 CHAR) NOT NULL, 
  DOOP_TX_NR_CTAC                  VARCHAR2(16 CHAR), 
  DOOP_IN_NF_RECEBIDA              VARCHAR2(1 CHAR) DEFAULT 'N', 
  DOOP_IN_SITUACAO_AFRM            VARCHAR2(1 CHAR), 
  DOOP_IN_CTAC_RECEBIDA            VARCHAR2(1 CHAR) DEFAULT 'N', 
  DOOP_IN_SIUTACAO_CARGA           VARCHAR2(1 CHAR), 
  DOOP_IN_ANEXO_UNICO_RECEBIDO     VARCHAR2(1 CHAR), 
  DOOP_TX_PROTOCOLO_DMM            VARCHAR2(13 CHAR), 
  DOOP_DT_PROTOCOLO_DMM            DATE,
  DOOP_TX_TERMINAL_DESCARGA VARCHAR2(100 CHAR),
 
  CONSTRAINT PK_DOPR PRIMARY KEY (DOOP_SQ_DOC_OPERACAO )
) 
ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE STAM.DOCUMENTACAO_LONGO_CURSO 
(
  DOLC_SQ_DOC_LONGO_CURSO           NUMBER(8, 0) NOT NULL, 
  DOLC_TX_MANIFESTO_ELETRONICO      VARCHAR2(13 CHAR) NOT NULL, 
  DOLC_TX_CONHECIMENTO_ELETRONIC    VARCHAR2(15 CHAR) NOT NULL, 
  DOLC_NM_CIDADE                    VARCHAR2(60 CHAR) NOT NULL, 
  DOLC_IN_BL_RECEBIDO               VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL, 
  OPER_SQ_OPERACAO                  NUMBER(8, 0) NOT NULL, 
  PORT_CD_ID                        VARCHAR2(4 CHAR) NOT NULL, 
  
  CONSTRAINT PK_OPLC PRIMARY KEY (DOLC_SQ_DOC_LONGO_CURSO)
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE STAM.EMBARCACAO
(
  EMBA_CD_ID                       VARCHAR2(4 CHAR) NOT NULL,
  EMBA_IN_CLASSIFICACAO            NUMBER(1, 0) DEFAULT 1 NOT NULL,
  EMBA_TX_NR_INSCRICAO             VARCHAR2(15 CHAR),
  EMBA_DT_ULTIMA_INSPECAO          DATE,
  EMBA_DT_VALIDADE_PROVISORIA      DATE,
  EMBA_DT_VALIDADE_CONFORMIDADE    DATE,
  EMBA_IN_TEM_HELIPORTO            VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
  EMBA_NR_REGISTRO                 NUMBER(8, 0),
  EMBA_DT_REGISTRO                 DATE,
  EMBA_NM_COMPLETO                 VARCHAR2(30 CHAR) NOT NULL,
  EMBA_NM_APELIDO                  VARCHAR2(13 CHAR) NOT NULL,
  EMBA_TX_IMO                      VARCHAR2(9 CHAR) NOT NULL,
  EMBA_MD_CAP_AGUA                 NUMBER(8, 2),
  EMBA_MD_CAL_MAXIMO               NUMBER(8, 2),
  EMBA_MD_NRT                      NUMBER(8, 0),
  EMBA_MD_GRT                      NUMBER(8, 0),
  EMBA_NR_DWT                      NUMBER(8, 0),
  EMBA_MD_LOA                      NUMBER(8, 2),
  EMBA_TX_PREFIXO                  VARCHAR2(10 CHAR),
  EMBA_DT_CONSTRUCAO               DATE,
  PAIS_CD_IBGE                     VARCHAR2(3 CHAR),
  PORT_CD_ID_REGISTRO              VARCHAR2(4 CHAR),
  EMBA_IN_TIPO_EMBARCACAO          VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
  PAIS_CD_ULTIMA_INSPECAO          VARCHAR2(3 CHAR),
  EMBA_NM_PROPRIETARIO             VARCHAR2(50 CHAR),
  EMBA_NM_ARMADOR                  VARCHAR2(50 CHAR),
  EMBA_TX_EMAIL                    VARCHAR2(100 CHAR),
  EMBA_NR_TELEFONE                 VARCHAR2(50 CHAR),
  EMBA_TX_CENTRO_CUSTO             VARCHAR2(10 CHAR), 
  EMBA_TX_SOC_CLASSIFICADORA       VARCHAR2(70 CHAR),

  CONSTRAINT PK_EMCO PRIMARY KEY (EMBA_CD_ID)
)ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE STAM.EMBARCACAO_CERTIFICADO
(
  EMCE_SQ_CERTIFICADO NUMBER(8, 0) NOT NULL,
  EMCE_NR_CERTIFICADO NUMBER(8, 0),
  EMCE_DT_CERTIFICADO DATE NOT NULL,
  EMCE_DT_VALIDADE DATE,
  AGEC_SQ_AGENCIAMENTO NUMBER(8, 0),
  EMCE_IN_CERTIFICADO NUMBER(1, 0) NOT NULL,
  EMBA_CD_ID VARCHAR2(4 CHAR) DEFAULT '4758' NOT NULL,
  EMCE_NM_PORTO VARCHAR2(50 CHAR),
  AGTA_SQ_AGENCIAMENTO_TAXA NUMBER(8, 0), 
	CONSTRAINT PK_EMCE PRIMARY KEY (EMCE_SQ_CERTIFICADO)
)ON COMMIT PRESERVE ROWS;



CREATE GLOBAL TEMPORARY TABLE STAM.AGENCIAMENTO_PENDENCIA 
(
  AGPE_SQ_PENDENCIA           NUMBER(8, 0) NOT NULL, 
  AGEC_SQ_AGENCIAMENTO        NUMBER(8, 0) NOT NULL, 
  AGPE_IN_TIPO_PENDENCIA      NUMBER(3, 0) NOT NULL,
  AGPE_IN_RESOLVIDA           VARCHAR2(1 CHAR) DEFAULT 'N', 
  AGPE_NM_RESPONSAVEL_SOLUCAO VARCHAR2(50 CHAR), 
  AGPE_CD_CHAVE_RESPONSAVEL   VARCHAR2(4 CHAR), 
  AGPE_DT_SOLUCAO             DATE,
  AGTA_SQ_AGENCIAMENTO_TAXA   NUMBER(8,0),
  AGDO_SQ_AGENCIAMENTO_DOC    NUMBER(8,0),
  CONSTRAINT PK_AGPE PRIMARY KEY (AGPE_SQ_PENDENCIA )  
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.PONTO_ATRACACAO 
(
  POAT_SQ_PONTO_ATRACACAO NUMBER(6, 0) NOT NULL 
, POAT_NM_COMPLETO VARCHAR2(50 CHAR) 
, POAT_CD_ID NUMBER(4, 0) 
, POOP_CD_ID VARCHAR2(4 BYTE) NOT NULL 
,POAT_SG_PONTO_ATRACACAO VARCHAR2(6 CHAR)
, CONSTRAINT PK_POAT PRIMARY KEY 
  (
    POAT_SQ_PONTO_ATRACACAO 
  )
)  ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.EMBARCACAO_ESCALA
(
	EMES_SQ_ESCALA            NUMBER(8) NOT NULL ,
	PORT_CD_ID                VARCHAR2(4) NOT NULL ,
	EMBA_CD_ID                VARCHAR2(4) NOT NULL ,
	EMES_DT_ESCALA            DATE, 
     CONSTRAINT  PK_EMES PRIMARY KEY (EMES_SQ_ESCALA)
)ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE STAM.NUMERACAO_AGENCIAMENTO
(
        AGEN_SQ_AGENCIA NUMBER(6, 0) NOT NULL,
        NUAG_NR_ANO_PROCESSO NUMBER(4, 0) NOT NULL,
        NUAG_CD_AGENCIAMENTO NUMBER(10, 0) NOT NULL, 
    CONSTRAINT PK_NUAG PRIMARY KEY (AGEN_SQ_AGENCIA, NUAG_NR_ANO_PROCESSO)
)ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.DESVIO 
(
  AGEC_SQ_AGENCIAMENTO NUMBER(8, 0) NOT NULL 
, PORT_CD_ID VARCHAR2(4 CHAR) NOT NULL 
, DESV_DT_DESVIO DATE NOT NULL 
, DESV_IN_MOTIVO NUMBER(1, 0) NOT NULL 
, DESV_CD_CHAVE_CADASTRADOR VARCHAR2(4 CHAR) NOT NULL 
, DESV_NM_CADASTRADOR VARCHAR2(60 CHAR) NOT NULL 
, DESV_TX_DESTINO VARCHAR2(150 CHAR) 
, CONSTRAINT PK_DESV PRIMARY KEY 
  (
    AGEC_SQ_AGENCIAMENTO 
  )
)ON COMMIT PRESERVE ROWS; 

CREATE GLOBAL TEMPORARY TABLE STAM.PAIS
(
  PAIS_CD_IBGE        VARCHAR2(3 CHAR) NOT NULL,
  PAIS_NM_COMPLETO    VARCHAR2(40 BYTE),
  REGI_CD_REGIAO      VARCHAR2(4 BYTE),
  PAIS_NR_ONU         VARCHAR2(3 BYTE), 
  PAIS_TX_ISO_ALPHA3  VARCHAR2(3 BYTE),
  CONSTRAINT PK_PAIS PRIMARY KEY(PAIS_CD_IBGE)

)ON COMMIT PRESERVE ROWS;



CREATE GLOBAL TEMPORARY TABLE STAM.AGENCIAMENTO_ANEXO
(
  AGAN_SQ_AGENCIAMENTO_ANEXO         NUMBER(8, 0) NOT NULL,
  AGEC_SQ_AGENCIAMENTO               NUMBER(8, 0) NOT NULL,
  AGAN_NM_ANEXO                      VARCHAR2(60 CHAR) NOT NULL,
  AGAN_QN_TAMANHO                    NUMBER(8, 0) NOT NULL,
  AGAN_IN_PASTA                      VARCHAR2(20 CHAR) NOT NULL,
  AGAN_TX_EXTENSAO                   VARCHAR2(4 CHAR) NOT NULL,
  AGAN_DT_ANEXO                      DATE NOT NULL,
  AGAN_NM_CADASTRADOR                VARCHAR2(50 CHAR) NOT NULL,
  AGAN_CD_CHAVE_CADASTRADOR          VARCHAR2(4 CHAR) NOT NULL,
  
  CONSTRAINT PK_AGAN PRIMARY KEY (AGAN_SQ_AGENCIAMENTO_ANEXO)

)ON COMMIT PRESERVE ROWS;



CREATE GLOBAL TEMPORARY TABLE STAM.ANEXO
(
  AGAN_SQ_AGENCIAMENTO_ANEXO         NUMBER(8, 0) NOT NULL,
  ANEX_MM_ANEXO                      BLOB NOT NULL,
  
  CONSTRAINT PK_ANEX PRIMARY KEY (AGAN_SQ_AGENCIAMENTO_ANEXO)

)ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE STAM.VISITA
(
  VISI_SQ_VISITA NUMBER(6, 0) NOT NULL,
  VISI_DT_INICIO DATE,
  VISI_TX_OBSERVACAO VARCHAR2(1000 CHAR),
  AGEC_SQ_AGENCIAMENTO NUMBER(8, 0) NOT NULL,
  VISI_DT_TERMINO DATE,
  VISI_CD_CHAVE VARCHAR2(4 CHAR),
  VISI_NM_VISITANTE VARCHAR2(50 CHAR),
  VISI_CD_CHAVE_ALTERACAO VARCHAR2(4) NOT NULL ,
  VISI_NM_USU_ALTERACAO VARCHAR2(60) NOT NULL ,
  VISI_DT_ALTERACAO    DATE NOT NULL,
  VISI_DT_PROGRAMADA DATE,
    CONSTRAINT PK_VISI PRIMARY KEY (VISI_SQ_VISITA)
)ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.VISITA_TRANSPORTE
(
    VITR_SQ_TRANSPORTE    NUMBER(6, 0) NOT NULL,
    VISI_SQ_VISITA        NUMBER(6, 0) NOT NULL,
    VITR_IN_TIPO_TRANSPORTE   VARCHAR2(1 CHAR) NOT NULL,
    RECU_SQ_RESP_CUSTO    NUMBER(8, 0) NOT NULL,
    VITR_VL_CUSTO         NUMBER(8, 2) NOT NULL,
    VITR_TX_DESCRICAO VARCHAR2(100 CHAR),
    VITR_TX_SERVICO VARCHAR2(100 CHAR),
    VITR_IN_CONDICAO_NAVIO VARCHAR2(1 CHAR),
    CONSTRAINT PK_VITR PRIMARY KEY (VITR_SQ_TRANSPORTE)
)ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.PROTECAO_SERVICO 
(
  PRSE_SQ_PROTECAO NUMBER(8, 0) NOT NULL 
, PRSE_DT_SERVICO DATE NOT NULL 
, PRSE_IN_ATENDIMENTO_SERVICO NUMBER(2, 0) NOT NULL 
, PRSE_TX_OBSERVACAO VARCHAR2(512 CHAR) 
, AGEC_SQ_AGENCIAMENTO NUMBER(8, 0) NOT NULL 
, PRSE_TX_JUSTIFICATIVA VARCHAR2(512 CHAR) 
, PRSE_DT_CANCELAMENTO DATE 
, PRSE_CD_CHAVE_INCLUSAO VARCHAR2(4 CHAR) 
, PRSE_IN_NOVO VARCHAR2(1 BYTE) DEFAULT 'S' NOT NULL 
, PRSE_NM_USUARIO_INCLUSAO VARCHAR2(60 BYTE) 
, PRSE_CD_CHAVE_ALTERACAO VARCHAR2(4 BYTE) 
, PRSE_NM_USUARIO_ALTERACAO VARCHAR2(60 BYTE) 
, PRSE_CD_CHAVE_CANCELAMENTO VARCHAR2(4 BYTE) 
, PRSE_NM_USUARIO_CANCELAMENTO VARCHAR2(60 BYTE) 
, PRSE_DT_ALTERACAO DATE 
, PRSE_IN_EMAIL_ENVIADO VARCHAR2(1 BYTE) DEFAULT 'N' 
, PRSE_DT_EMAIL_ENVIADO DATE
, PRSE_IN_FORMULARIO_GERADO VARCHAR2(1 CHAR)
, CONSTRAINT PK_PRSE PRIMARY KEY (PRSE_SQ_PROTECAO)
)ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.SERVICO_MEDICO_ODONTOLOGICO
(
	PRSE_SQ_PROTECAO     NUMBER(8) NOT NULL ,
	SEMO_NM_TRIPULANTE   VARCHAR2(200) NOT NULL,
    CONSTRAINT  PK_SEMO PRIMARY KEY (PRSE_SQ_PROTECAO)
)ON COMMIT PRESERVE ROWS;





CREATE GLOBAL TEMPORARY TABLE STAM.SERVICO_TRANSPORTE
(
PRSE_SQ_PROTECAO NUMBER(8, 0) NOT NULL 
, SETR_DT_HORA_SERVICO DATE NOT NULL 
, SETR_TX_ORIGEM VARCHAR2(200 BYTE) 
, SETR_TX_DESTINO VARCHAR2(200 BYTE) 
, SETR_TX_AUTORIZACAO VARCHAR2(200 BYTE) 
, SETR_TX_VOO VARCHAR2(100 BYTE) 
, SETR_IN_TIPO_TRANSPORTE VARCHAR2(1 BYTE) NOT NULL 
, EMSE_SQ_EMPRESA_SERVICO NUMBER(5, 0) NULL 
    ,CONSTRAINT  PK_SETR PRIMARY KEY (PRSE_SQ_PROTECAO)	
)ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.AGENCIAMENTO_CANCELAMENTO 
(
  AGEC_SQ_AGENCIAMENTO NUMBER(8, 0) NOT NULL 
, AGCA_IN_CANCELAMENTO VARCHAR2(1 CHAR) NOT NULL 
, AGCA_TX_MOTIVO_CANCELAMENTO VARCHAR2(256 CHAR) 
, AGCA_CD_CHAVE_CANCELAMENTO VARCHAR2(4 CHAR) NOT NULL 
, AGCA_NM_CANCELAMENTO VARCHAR2(60 CHAR) NOT NULL 
, AGCA_DT_CANCELAMENTO DATE NOT NULL 
, CONSTRAINT PK_AGCA PRIMARY KEY 
  (
    AGEC_SQ_AGENCIAMENTO 
  )
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE STAM.DESTINATARIO 
(
    DEST_SQ_DESTINATARIO    NUMBER(5) NOT NULL,
    DEST_NM_DESTINATARIO    VARCHAR2(512) NOT NULL,
    DEST_TX_EMAIL           VARCHAR2(512) NOT NULL,
    AGEN_SQ_AGENCIA         NUMBER(6) NOT NULL,

    CONSTRAINT PK_DEST PRIMARY KEY (DEST_SQ_DESTINATARIO)

)ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.AGENCIAMENTO_ACOMPANHAMENTO 
(
  AGAC_SQ_ACOMPANHAMENTO NUMBER(8, 0) NOT NULL 
, AGAC_DT_ACOMPANHAMENTO DATE NOT NULL 
, AGAC_CD_CHAVE_CADASTRADOR VARCHAR2(4 CHAR) NOT NULL 
, AGAC_NM_CADASTRADOR VARCHAR2(100 CHAR) NOT NULL 
, AGAC_TX_ACOMPANHAMENTO VARCHAR2(512 CHAR) NOT NULL 
, AGEC_SQ_AGENCIAMENTO NUMBER(8, 0) NOT NULL 
, CONSTRAINT PK_AGAC PRIMARY KEY (AGAC_SQ_ACOMPANHAMENTO)
) ON COMMIT PRESERVE ROWS;


CREATE OR REPLACE VIEW STAM.VW_ESCALA_EMBARCACAO 
    AS SELECT DISTINCT STAM.PROGRAMACAO_NAVIO.EMBA_CD_ID,
                       STAM.PROGRAMACAO_NAVIO.PORT_CD_ID,
                       to_date(substr(saida,5,16),'dd/MM/yyyy hh24:mi') data_saida,
                       to_date(substr(chegada,5,16),'dd/MM/yyyy hh24:mi') data_chegada
	FROM STAM.PROGRAMACAO_NAVIO 
	WHERE to_date(substr(saida,5,16),'dd/MM/yyyy hh24:mi') > trunc(sysdate) - 30;


CREATE OR REPLACE VIEW STAM.VW_AGENCIA_SIGO 
AS Select distinct AGEN_CD_ID, AGEN_NM_COMPLETO, AGEN_TX_EMAIL 
From STAM.AGENCIA_SIGO;

CREATE GLOBAL TEMPORARY TABLE STAM.HOSPEDE 
(
  HOSP_SQ_HOSPEDE NUMBER(8, 0) NOT NULL 
, HOSP_NM_HOSPEDE VARCHAR2(100 BYTE) NOT NULL 
, HOSP_TX_DOCUMENTO VARCHAR2(50 BYTE) 
, HOSP_TX_NR_CPF VARCHAR2(11 BYTE) 
, PRSE_SQ_PROTECAO NUMBER(8, 0) NOT NULL 
, HOSP_IN_ATIVO VARCHAR2(1 BYTE) DEFAULT 'S' NOT NULL 
, CONSTRAINT PK_HOSP PRIMARY KEY (HOSP_SQ_HOSPEDE)
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE STAM.SERVICO_HOSPEDAGEM 
(
  PRSE_SQ_PROTECAO NUMBER(8, 0) NOT NULL 
, EMSE_SQ_EMPRESA_SERVICO NUMBER(5, 0) NOT NULL 
, SEHO_DT_CHEGADA DATE NOT NULL 
, SEHO_DT_SAIDA DATE NOT NULL 
, SEHO_TX_AUTORIZACAO VARCHAR2(200 BYTE) 
, CONSTRAINT PK_SEHO PRIMARY KEY (PRSE_SQ_PROTECAO)
)ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.PASSAGEIRO 
(
PASS_SQ_PASSAGEIRO NUMBER(8, 0) NOT NULL 
, PASS_NM_PASSAGEIRO VARCHAR2(100 BYTE) NOT NULL 
, PASS_TX_DOCUMENTO VARCHAR2(50 BYTE) 
, PASS_TX_NR_CPF VARCHAR2(11 BYTE) 
, PASS_IN_ATIVO VARCHAR2(1 BYTE) DEFAULT 'S' 
, PRSE_SQ_PROTECAO NUMBER(8, 0) 
, CONSTRAINT PK_PASS PRIMARY KEY (PASS_SQ_PASSAGEIRO)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.SERVICO_ACESSO_PESSOA(
    PRSE_SQ_PROTECAO            NUMBER(8,0) NOT NULL,
    SEAP_IN_TIPO_SOLI_TRANSITO  VARCHAR2(1 BYTE) NOT NULL,
    SEAP_IN_TIPO_ACESSO         VARCHAR2(1 BYTE) NOT NULL,
    SEAP_IN_TIPO_CATEGORIA      VARCHAR2(1 BYTE) NOT NULL,
    SEAP_IN_TIPO_NACIONALIDADE  VARCHAR2(1 BYTE) NOT NULL,
    SEAP_IN_COMPANHIA_DOCAS     VARCHAR2(1 BYTE) DEFAULT 'S', 
    SEAP_IN_TERMINAL            VARCHAR2(1 BYTE) DEFAULT 'N', 
    SEAP_TX_TERMINAL            VARCHAR2(50 BYTE),
    SEAP_TX_ATIVIDADE_BORDO     VARCHAR2(1000 BYTE),
    SEAP_TX_EMPRESA_PROTECAO    VARCHAR2(100 BYTE),
    SEAP_NR_CNPJ                VARCHAR2(20 CHAR),
    SEAP_TX_NR_TELEFONE_EMPRESA VARCHAR2(50 CHAR),
    CONSTRAINT  PK_SEAP PRIMARY KEY (PRSE_SQ_PROTECAO)	
)ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.PESSOA_ACESSO(
    PEAC_SQ_PESSOA	NUMBER(8,0) NOT NULL,
    PEAC_NM_RESPONSAVEL	VARCHAR2(100 BYTE),
    PEAC_NR_VOLUME	NUMBER(2,0),
    PEAC_TX_BAGAGEM	VARCHAR2(512 BYTE),
    PEAC_IN_GERADO_PF	VARCHAR2(1 BYTE) DEFAULT 'S', 
    PEAC_IN_GERADO_RF	VARCHAR2(1 BYTE) DEFAULT 'S', 
    PEAC_IN_ATIVO	VARCHAR2(1 BYTE) DEFAULT 'S', 
    PRSE_SQ_PROTECAO	NUMBER(8,0),
    PEAC_TX_DOCUMENTO VARCHAR2(50 CHAR), 
    PEAC_CD_CPF VARCHAR2(11 CHAR), 
    PEAC_DT_NASCIMENTO DATE, 
    PEAC_TX_EMPRESA VARCHAR2(100 CHAR), 
    PEAC_TX_NACIONALIDADE VARCHAR2(100 CHAR), 
    PEAC_IN_GERADO_RF_EMB_DES VARCHAR2(1 CHAR) DEFAULT 'N', 
    PEAC_IN_GERADO_RF_ACESSO VARCHAR2(1 CHAR) DEFAULT 'N', 
    PEAC_NM_PESSOA VARCHAR2(100 CHAR), 
    PEAC_NR_CNPJ VARCHAR2(20 CHAR), 
    PEAC_TX_TIPO_DOCUMENTO VARCHAR2(40 CHAR),
    CONSTRAINT PK_PEAC PRIMARY KEY (PEAC_SQ_PESSOA)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.PORTO_COMPLEMENTO (
    PCOM_SQ_PORTO_COMPLEMENTO NUMBER(8, 0) NOT NULL,
    PORT_CD_ID VARCHAR2(4 BYTE) NOT NULL,
    PCOM_TX_ENDERECO VARCHAR2(256 CHAR) NOT NULL,
    PCOM_NM_CIDADE VARCHAR2(30 CHAR) NOT NULL,
    PCOM_SG_ESTADO VARCHAR2(2 CHAR) NOT NULL,
    PCOM_TX_INSCRICAO_ESTADUAL VARCHAR2(12 CHAR) NOT NULL,
    PCOM_TX_NR_CNPJ VARCHAR2(14 BYTE) NOT NULL,
    PCOM_NM_CTAC VARCHAR2(30 CHAR), 
    CONSTRAINT PK_PCOM PRIMARY KEY (PCOM_SQ_PORTO_COMPLEMENTO)
)ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.EMPRESA_PROTECAO(
    EMPR_SQ_EMPRESA_PROTECAO NUMBER(8,0) NOT NULL ,
    EMPR_NR_CNPJ         VARCHAR2(20 CHAR) NOT NULL ,
    EMPR_NM_RAZAO_SOCIAL VARCHAR2(100 CHAR) NOT NULL ,
    EMPR_TX_EMAIL        VARCHAR2(100 CHAR),
    EMPR_TX_NR_FAX       VARCHAR2(20 CHAR),
    EMPR_TX_NR_TELEFONE  VARCHAR2(50 CHAR),
    EMPR_IN_EMPRESA_ATIVA VARCHAR2(1 CHAR) DEFAULT  'S'  NOT NULL ,
    EMPR_TX_CIDADE       VARCHAR2(100 CHAR),
    EMPR_CD_ESTADO       VARCHAR2(2 CHAR),
    CONSTRAINT PK_EMPR PRIMARY KEY (EMPR_SQ_EMPRESA_PROTECAO)
)ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE STAM.EMPRESA_PROTECAO_SERVICO(
    EMPS_SQ_EMP_PROTECAO_SERVICO NUMBER(8,0) NOT NULL ,
    EMPS_IN_TIPO_SERVICO_PROTECAO NUMBER(5) NOT NULL ,
    EMPR_SQ_EMPRESA_PROTECAO NUMBER(8,0) NOT NULL,
    CONSTRAINT PK_EMPS PRIMARY KEY (EMPS_SQ_EMP_PROTECAO_SERVICO)
)ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE STAM.PESSOA (
  PESS_SQ_PESSOA NUMBER(8, 0) NOT NULL,
  PESS_NM_PESSOA VARCHAR2(100 CHAR) NOT NULL,
  PESS_TX_DOCUMENTO VARCHAR2(50 CHAR),
  PESS_CD_CPF VARCHAR2(11 CHAR),
  PESS_DT_NASCIMENTO DATE,
  EMPR_SQ_EMPRESA_PROTECAO NUMBER(8, 0),
  PESS_TX_NACIONALIDADE	VARCHAR2(100 CHAR),
  PESS_IN_PESSOA_ATIVA	VARCHAR2(1 CHAR),
  PESS_TX_TIPO_DOCUMENTO VARCHAR2(40 CHAR),
  CONSTRAINT PK_PESS PRIMARY KEY (PESS_SQ_PESSOA)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.SERVICO_SUPRIMENTO (	
    PRSE_SQ_PROTECAO NUMBER(8,0) NOT NULL, 
    SESU_DT_INICIO_OPERACAO DATE NOT NULL, 
    SESU_DT_FIM_OPERACAO DATE NOT NULL, 
    SESU_VL_TRANSP_RODOVIARIO NUMBER(15,2), 
    SESU_VL_TRANSP_MARITIMO NUMBER(15,2), 
    SESU_TX_CENTRO_CUSTO VARCHAR2(50 BYTE), 
    SESU_VL_OPER_PORTUARIO NUMBER(15,2), 
    SESU_VL_HR_EXCEDENTE NUMBER(15,2), 
    SESU_VL_OGMO NUMBER(15,2), 
    SESU_VL_OGMO_DOBRA NUMBER(15,2), 
    SESU_VL_ANTERIOR_DO NUMBER(15,2), 
    SESU_TX_CENTRO_CUSTO_DO VARCHAR2(50 BYTE), 
    SESU_TX_JUSTIFICATIVA_DO VARCHAR2(512 CHAR), 
    SESU_VL_TOTAL_OP_PORTUARIA NUMBER(15,2), 
    SESU_VL_TOTAL_MERCADORIAS NUMBER(15,2), 
    EMMA_SQ_EMPRESA_MARITIMA NUMBER(8,0) NOT NULL, 
    EMSE_SQ_EMPRESA_SERVICO NUMBER(5,0) NOT NULL, 
     CONSTRAINT PK_SESU PRIMARY KEY (PRSE_SQ_PROTECAO)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.SUPRIMENTO_TRANSITO (
    SUTR_SQ_SOLICITACAO NUMBER(8,0) NOT NULL, 
    PRSE_SQ_PROTECAO NUMBER(8,0) NOT NULL, 
    SUTR_IN_COMPANHIA_DOCAS VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL, 
    SUTR_IN_TERMINAL VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL, 
    SUTR_TX_TERMINAL VARCHAR2(50 CHAR), 
    SUTR_IN_TIPO_ACESSO VARCHAR2(1 CHAR) NOT NULL, 
    SUTR_IN_TIPO_MATERIAL VARCHAR2(1 CHAR) NOT NULL, 
    SUTR_IN_FORMULARIO_GERADO VARCHAR2(1 CHAR), 
     CONSTRAINT PK_SUTR PRIMARY KEY (SUTR_SQ_SOLICITACAO)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.SUPRIMENTO_TRANSITO_VEICULO (
    SUTV_SQ_VEICULO NUMBER(8,0) NOT NULL, 
    SUTR_SQ_SOLICITACAO NUMBER(8,0), 
    SUTV_NM_CONDUTOR VARCHAR2(100 CHAR), 
    SUTV_CD_CPF VARCHAR2(20 CHAR), 
    SUTV_TX_VEICULO VARCHAR2(40 CHAR), 
    SUTV_TX_PLACA VARCHAR2(20 CHAR), 
    CONSTRAINT PK_SUTV PRIMARY KEY (SUTV_SQ_VEICULO)
) ON COMMIT PRESERVE ROWS;

 CREATE GLOBAL TEMPORARY TABLE STAM.SUPRIMENTO_TRANSITO_EMPRESA (
    SUTE_SQ_EMPRESA NUMBER(8,0) NOT NULL, 
    SUTR_SQ_SOLICITACAO NUMBER(8,0) NOT NULL, 
    SUTE_TX_EMPRESA VARCHAR2(100 CHAR), 
    SUTE_NR_CNPJ VARCHAR2(20 CHAR), 
    SUTE_TX_PESO_BRUTO VARCHAR2(30 CHAR), 
    SUTE_QN_VOLUMES NUMBER(8,0), 
    SUTE_TX_NOTA_FISCAL_GTRM VARCHAR2(50 CHAR), 
    SUTE_VL_MERCADORIAS NUMBER(15,2), 
    CONSTRAINT PK_SUTE PRIMARY KEY (SUTE_SQ_EMPRESA)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.SERVICO_RETIRADA_RESIDUO (	
  PRSE_SQ_PROTECAO NUMBER(8,0) NOT NULL, 
  SERR_IN_EMPRESA_REQUERENTE VARCHAR2(1 CHAR) NOT NULL, 
  EMMA_SQ_EMPRESA_MARITIMA NUMBER(8,0) NOT NULL, 
  EMSE_SQ_EMPRESA_SERVICO NUMBER(5,0) NOT NULL, 
  EMMA_SQ_EMPRESA_MARITIMA_RODOV NUMBER(8,0), 
  SERR_IN_TIPO_RESIDUO VARCHAR2(1 CHAR) NOT NULL, 
  SERR_TX_CARACTERIZACAO VARCHAR2(50 CHAR) NOT NULL, 
  SERR_TX_ESTADO_FISICO VARCHAR2(15 CHAR) NOT NULL, 
  SERR_TX_CLASSIFICACAO VARCHAR2(30 CHAR) NOT NULL, 
  SERR_TX_CODIGO_ONU VARCHAR2(10 CHAR) NOT NULL, 
  SERR_QN_RESIDUO NUMBER(10,2) NOT NULL, 
  SERR_IN_UNIDADE_MEDIDA VARCHAR2(1 CHAR) NOT NULL, 
  SERR_DT_INICIO_OPERACAO DATE NOT NULL, 
  SERR_DT_TERMINO_OPERACAO DATE NOT NULL, 
  SERR_TX_LOCAL_ARMAZENAGEM VARCHAR2(100 CHAR), 
  SERR_TX_LONR_ARMAZENAGEM VARCHAR2(20 CHAR), 
  SERR_TX_CADRI_ARMAZENAGEM VARCHAR2(30 CHAR), 
  SERR_TX_LOCAL_DESTINO VARCHAR2(100 CHAR) NOT NULL, 
  SERR_TX_LONR_DESTINO VARCHAR2(20 CHAR) NOT NULL, 
  SERR_TX_CADRI_DESTINO VARCHAR2(20 CHAR) NOT NULL, 
  SERR_VL_SERVIVCO NUMBER(10,2) NOT NULL, 
  CONSTRAINT PK_SERR PRIMARY KEY (PRSE_SQ_PROTECAO)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE STAM.RESPONSAVEL_CUSTO (	
  RECU_SQ_RESP_CUSTO NUMBER(8,0) NOT NULL, 
  RECU_SG_RESP_CUSTO VARCHAR2(2 CHAR) NOT NULL, 
  RECU_TX_RESP_CUSTO VARCHAR2(50 CHAR) NOT NULL,   
  CONSTRAINT PK_RECU PRIMARY KEY (RECU_SQ_RESP_CUSTO)
) ON COMMIT PRESERVE ROWS;

