package br.com.petrobras.sistam.desktop.embarcacao;

import br.com.petrobras.fcorp.common.support.AssertUtils;
import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SCheckBox;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SNumericTextField;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Embarcacao;
import br.com.petrobras.sistam.common.util.ConstantesI18N;
import br.com.petrobras.sistam.common.util.SistamUtils;
import br.com.petrobras.sistam.desktop.SistamApp;
import br.com.petrobras.sistam.desktop.components.SistamDateChooser;
import br.com.petrobras.sistam.desktop.components.lookups.pais.PaisLookup;
import br.com.petrobras.sistam.desktop.components.lookups.porto.PortoLookup;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

public class DetalheEmbarcacaoDialog extends SDialog {
    private DetalheEmbarcacaoModel model;
    
    public DetalheEmbarcacaoDialog(java.awt.Frame parent, Embarcacao embarcacao, boolean inclusao) {
        super(parent, true);
        this.model = new DetalheEmbarcacaoModel(embarcacao);
        initComponents();
        setLocationRelativeTo(parent);
        txtCodigo.setEnabled(inclusao);
        
        
        txtCodigo.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e){
                model.verificarCodigo();
            }
        });
                
        
    }

    public DetalheEmbarcacaoModel getModel() {
        return model;
    }
    
    public void salvar() {
      AssertUtils.assertExpression(this.txtEmail.getText().trim().isEmpty() || SistamUtils.validarEmail(this.txtEmail.getText()), ConstantesI18N.EMBARCACAO_EMAIL_INVALIDO);
        model.salvar();
        SistamApp.getSistamApp().atualizarCaixaEntrada();
        dispose();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        GenericAction actionSalvar = new GenericAction();
        SCheckBox sCheckBox2 = new SCheckBox();
        SPanel painelInformacoes = new SPanel();
        SPanel sPanel1 = new SPanel();
        SPanel pnlInfBasicas = new SPanel();
        SLabel sLabel13 = new SLabel();
        lblBandeira = new SLabel();
        STextField sTextField3 = new STextField();
        SLabel sLabel9 = new SLabel();
        STextField sTextField4 = new STextField();
        SLabel labelQtdEstimada = new SLabel();
        STextField sTextField2 = new STextField();
        SLabel labelProduto = new SLabel();
        SComboBox sComboBox1 = new SComboBox();
        txtIrin = new STextField();
        SLabel sLabel17 = new SLabel();
        txtImo = new STextField();
        SLabel sLabel18 = new SLabel();
        PaisLookup paisLookup2 = new PaisLookup();
        SLabel sLabel24 = new SLabel();
        txtCodigo = new STextField();
        SPanel pnlCapacidadeSIGO = new SPanel();
        SLabel sLabel16 = new SLabel();
        SLabel sLabel15 = new SLabel();
        SLabel sLabel11 = new SLabel();
        SLabel sLabel12 = new SLabel();
        SLabel sLabel3 = new SLabel();
        SLabel sLabel4 = new SLabel();
        SNumericTextField nrAqueacaoBruta = new SNumericTextField();
        SNumericTextField nrLoa = new SNumericTextField();
        SNumericTextField nrDWT = new SNumericTextField();
        SNumericTextField nrCaladoMaximo = new SNumericTextField();
        SNumericTextField nrCapacidadeAqua = new SNumericTextField();
        SNumericTextField nrArqueacaoLiquida = new SNumericTextField();
        SPanel pnlUltimaInspecao = new SPanel();
        SLabel sLabel8 = new SLabel();
        SLabel sLabel19 = new SLabel();
        SistamDateChooser sistamDateChooser1 = new SistamDateChooser();
        PaisLookup paisLookup1 = new PaisLookup();
        SPanel sPanel2 = new SPanel();
        SLabel sLabel20 = new SLabel();
        SLabel sLabel21 = new SLabel();
        SistamDateChooser sistamDateChooser2 = new SistamDateChooser();
        SistamDateChooser sistamDateChooser3 = new SistamDateChooser();
        SPanel sPanel3 = new SPanel();
        SLabel sLabel1 = new SLabel();
        SLabel sLabel2 = new SLabel();
        SLabel sLabel22 = new SLabel();
        SNumericTextField sNumericTextField1 = new SNumericTextField();
        SistamDateChooser sistamDateChooser4 = new SistamDateChooser();
        PortoLookup portoLookup1 = new PortoLookup();
        SPanel sPanel4 = new SPanel();
        STextField sTextField1 = new STextField();
        SLabel sLabel6 = new SLabel();
        STextField sTextField5 = new STextField();
        SLabel sLabel7 = new SLabel();
        SLabel sLabel5 = new SLabel();
        SistamDateChooser sistamDateChooser5 = new SistamDateChooser();
        SCheckBox sCheckBox1 = new SCheckBox();
        SLabel sLabel23 = new SLabel();
        STextField sTextField6 = new STextField();
        SLabel sLabel25 = new SLabel();
        STextField sTextField7 = new STextField();
        SPanel sPanel5 = new SPanel();
        SLabel sLabel10 = new SLabel();
        SLabel sLabel14 = new SLabel();
        STextField txtTelefone = new STextField();
        txtEmail = new STextField();
        SPanel painelBotoes = new SPanel();
        SButton botaoSalvar = new SButton();

        actionSalvar.setIcon(new ImageIcon(getClass().getResource("/icons/disk.png"))); // NOI18N
        actionSalvar.setMethodName("salvar");
        actionSalvar.setTarget(this);
        actionSalvar.setText("Salvar");
        actionSalvar.setToolTipText("Salva as alterações");

        sCheckBox2.setText("sCheckBox2");
        sCheckBox2.setName("sCheckBox2"); // NOI18N

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dados da Embarcação");

        painelInformacoes.setBorder(BorderFactory.createTitledBorder("Dados da Embarcação"));
        painelInformacoes.setName("painelInformacoes"); // NOI18N

        sPanel1.setName("sPanel1"); // NOI18N

        pnlInfBasicas.setBorder(BorderFactory.createTitledBorder("Identificação"));
        pnlInfBasicas.setName("pnlInfBasicas"); // NOI18N

        ResourceBundle bundle = ResourceBundle.getBundle("sistam-labels"); // NOI18N
        sLabel13.setText(bundle.getString("lblnomeEmbarcacao")); // NOI18N
        sLabel13.setName("sLabel13"); // NOI18N

        lblBandeira.setText(bundle.getString("lblBandeiraEmbarcacao")); // NOI18N
        lblBandeira.setName("lblBandeira"); // NOI18N

        sTextField3.setDocument(new GenericDocument(30, 
            GenericDocument.OPTION_APPLY_UPPERCASE ));
    sTextField3.setName("sTextField3"); // NOI18N

        Binding binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.nomeCompleto}"), sTextField3, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    sLabel9.setText("Apelido:");
    sLabel9.setName("sLabel9"); // NOI18N

    sTextField4.setDocument(new GenericDocument(13, 
        GenericDocument.OPTION_APPLY_UPPERCASE ));
sTextField4.setName("sTextField4"); // NOI18N

binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.apelido}"), sTextField4, BeanProperty.create("text"));
bindingGroup.addBinding(binding);

labelQtdEstimada.setText("Nr. Inscrição:");
labelQtdEstimada.setName("labelQtdEstimada"); // NOI18N

sTextField2.setDocument(new GenericDocument(15, 
    GenericDocument.OPTION_APPLY_UPPERCASE ));
    sTextField2.setName("sTextField2"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.inscricao}"), sTextField2, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    labelProduto.setText("Classificação:");
    labelProduto.setName("labelProduto"); // NOI18N

    sComboBox1.setName("sComboBox1"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.classificacoes}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE, this, eLProperty, sComboBox1);
    bindingGroup.addBinding(jComboBoxBinding);
    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.classificacao}"), sComboBox1, BeanProperty.create("selectedItem"));
    bindingGroup.addBinding(binding);

    txtIrin.setDocument(new GenericDocument(10, GenericDocument.OPTION_APPLY_UPPERCASE));
    txtIrin.setName("txtIrin"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.irin}"), txtIrin, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    sLabel17.setText(bundle.getString("lblIrin")); // NOI18N
    sLabel17.setName("sLabel17"); // NOI18N

    txtImo.setDocument(new GenericDocument(9));
    txtImo.setName("txtImo"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.imo}"), txtImo, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    sLabel18.setText(bundle.getString("lblIMOEmbarcacao")); // NOI18N
    sLabel18.setName("sLabel18"); // NOI18N

    paisLookup2.setText("paisLookupBandeira");
    paisLookup2.setName("paisLookup2"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.bandeira}"), paisLookup2, BeanProperty.create("value"));
    bindingGroup.addBinding(binding);

    sLabel24.setText("Código:");
    sLabel24.setName("sLabel24"); // NOI18N

    txtCodigo.setDocument(new GenericDocument(4, 
        GenericDocument.OPTION_APPLY_UPPERCASE ));
txtCodigo.setEnabled(false);
txtCodigo.setName("txtCodigo"); // NOI18N

binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.id}"), txtCodigo, BeanProperty.create("text"));
bindingGroup.addBinding(binding);

        GroupLayout pnlInfBasicasLayout = new GroupLayout(pnlInfBasicas);
pnlInfBasicas.setLayout(pnlInfBasicasLayout);
pnlInfBasicasLayout.setHorizontalGroup(
    pnlInfBasicasLayout.createParallelGroup(Alignment.LEADING)
    .addGroup(pnlInfBasicasLayout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(pnlInfBasicasLayout.createParallelGroup(Alignment.TRAILING)
            .addComponent(sLabel17, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addComponent(sLabel24, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(ComponentPlacement.RELATED)
        .addGroup(pnlInfBasicasLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlInfBasicasLayout.createSequentialGroup()
                .addGroup(pnlInfBasicasLayout.createParallelGroup(Alignment.TRAILING)
                    .addGroup(pnlInfBasicasLayout.createSequentialGroup()
                        .addComponent(sLabel18, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(txtImo, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE))
                    .addComponent(sTextField4, GroupLayout.PREFERRED_SIZE, 229, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(pnlInfBasicasLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(lblBandeira, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProduto, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(pnlInfBasicasLayout.createParallelGroup(Alignment.LEADING)
                    .addGroup(pnlInfBasicasLayout.createSequentialGroup()
                        .addComponent(sComboBox1, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(labelQtdEstimada, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(sTextField2, GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                    .addComponent(paisLookup2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(pnlInfBasicasLayout.createSequentialGroup()
                .addComponent(txtIrin, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlInfBasicasLayout.createSequentialGroup()
                .addComponent(txtCodigo, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(sLabel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(sTextField3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    pnlInfBasicasLayout.setVerticalGroup(
        pnlInfBasicasLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(pnlInfBasicasLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlInfBasicasLayout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel24, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(txtCodigo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addGap(5, 5, 5)
            .addGroup(pnlInfBasicasLayout.createParallelGroup(Alignment.CENTER)
                .addComponent(sTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(lblBandeira, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(paisLookup2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(pnlInfBasicasLayout.createParallelGroup(Alignment.CENTER)
                .addComponent(sComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(txtImo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(txtIrin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel17, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel18, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(labelProduto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(labelQtdEstimada, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnlCapacidadeSIGO.setBorder(BorderFactory.createTitledBorder(bundle.getString("capacidade"))); // NOI18N
    pnlCapacidadeSIGO.setName("pnlCapacidadeSIGO"); // NOI18N

    sLabel16.setText(bundle.getString("lblArqueacaoBruta")); // NOI18N
    sLabel16.setName("sLabel16"); // NOI18N

    sLabel15.setText(bundle.getString("lblArqueacaoLiquida")); // NOI18N
    sLabel15.setName("sLabel15"); // NOI18N

    sLabel11.setText(bundle.getString("lblDWT")); // NOI18N
    sLabel11.setName("sLabel11"); // NOI18N

    sLabel12.setText(bundle.getString("lblLOA")); // NOI18N
    sLabel12.setName("sLabel12"); // NOI18N

    sLabel3.setText("Calado Máximo:");
    sLabel3.setName("sLabel3"); // NOI18N

    sLabel4.setText("Capacidade água:");
    sLabel4.setName("sLabel4"); // NOI18N

    nrAqueacaoBruta.setDecimalPlaces(new Short((short)0));
    nrAqueacaoBruta.setIntegerPlaces(new Short((short)8));
    nrAqueacaoBruta.setNumberClass(Long.class);
    nrAqueacaoBruta.setText("sNumericTextField2");
    nrAqueacaoBruta.setName("nrAqueacaoBruta"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.arqueacaoBruta}"), nrAqueacaoBruta, BeanProperty.create("longValue"));
    bindingGroup.addBinding(binding);

    nrLoa.setIntegerPlaces(new Short((short)6));
    nrLoa.setNumberClass(Double.class);
    nrLoa.setText("sNumericTextField4");
    nrLoa.setName("nrLoa"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.loa}"), nrLoa, BeanProperty.create("doubleValue"));
    bindingGroup.addBinding(binding);

    nrDWT.setIntegerPlaces(new Short((short)6));
    nrDWT.setNumberClass(Long.class);
    nrDWT.setText("sNumericTextField5");
    nrDWT.setName("nrDWT"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.dwt}"), nrDWT, BeanProperty.create("longValue"));
    bindingGroup.addBinding(binding);

    nrCaladoMaximo.setIntegerPlaces(new Short((short)3));
    nrCaladoMaximo.setNumberClass(Double.class);
    nrCaladoMaximo.setText("sNumericTextField6");
    nrCaladoMaximo.setName("nrCaladoMaximo"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.caladoMaximo}"), nrCaladoMaximo, BeanProperty.create("doubleValue"));
    bindingGroup.addBinding(binding);

    nrCapacidadeAqua.setIntegerPlaces(new Short((short)6));
    nrCapacidadeAqua.setNumberClass(Double.class);
    nrCapacidadeAqua.setText("sNumericTextField7");
    nrCapacidadeAqua.setName("nrCapacidadeAqua"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.capacidadeAgua}"), nrCapacidadeAqua, BeanProperty.create("doubleValue"));
    bindingGroup.addBinding(binding);

    nrArqueacaoLiquida.setDecimalPlaces(new Short((short)0));
    nrArqueacaoLiquida.setIntegerPlaces(new Short((short)8));
    nrArqueacaoLiquida.setNumberClass(Long.class);
    nrArqueacaoLiquida.setText("sNumericTextField2");
    nrArqueacaoLiquida.setName("nrArqueacaoLiquida"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.arqueacaoLiquida}"), nrArqueacaoLiquida, BeanProperty.create("longValue"));
    bindingGroup.addBinding(binding);

        GroupLayout pnlCapacidadeSIGOLayout = new GroupLayout(pnlCapacidadeSIGO);
    pnlCapacidadeSIGO.setLayout(pnlCapacidadeSIGOLayout);
    pnlCapacidadeSIGOLayout.setHorizontalGroup(
        pnlCapacidadeSIGOLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(pnlCapacidadeSIGOLayout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(pnlCapacidadeSIGOLayout.createParallelGroup(Alignment.LEADING)
                .addComponent(sLabel15, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel16, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.UNRELATED)
            .addGroup(pnlCapacidadeSIGOLayout.createParallelGroup(Alignment.LEADING)
                .addComponent(nrAqueacaoBruta, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(nrArqueacaoLiquida, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(pnlCapacidadeSIGOLayout.createParallelGroup(Alignment.LEADING)
                .addComponent(sLabel12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(pnlCapacidadeSIGOLayout.createParallelGroup(Alignment.LEADING)
                .addComponent(nrDWT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(nrLoa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
            .addGroup(pnlCapacidadeSIGOLayout.createParallelGroup(Alignment.TRAILING)
                .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.UNRELATED)
            .addGroup(pnlCapacidadeSIGOLayout.createParallelGroup(Alignment.LEADING)
                .addComponent(nrCaladoMaximo, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(nrCapacidadeAqua, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );
    pnlCapacidadeSIGOLayout.setVerticalGroup(
        pnlCapacidadeSIGOLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(pnlCapacidadeSIGOLayout.createSequentialGroup()
            .addGroup(pnlCapacidadeSIGOLayout.createParallelGroup(Alignment.LEADING)
                .addGroup(pnlCapacidadeSIGOLayout.createSequentialGroup()
                    .addGroup(pnlCapacidadeSIGOLayout.createParallelGroup(Alignment.LEADING)
                        .addGroup(pnlCapacidadeSIGOLayout.createParallelGroup(Alignment.BASELINE)
                            .addComponent(sLabel15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(nrArqueacaoLiquida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlCapacidadeSIGOLayout.createParallelGroup(Alignment.BASELINE)
                            .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(nrCaladoMaximo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addComponent(sLabel12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addGroup(pnlCapacidadeSIGOLayout.createParallelGroup(Alignment.CENTER)
                        .addComponent(sLabel16, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(nrAqueacaoBruta, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(nrCapacidadeAqua, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlCapacidadeSIGOLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(nrDWT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addComponent(nrLoa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnlUltimaInspecao.setBorder(BorderFactory.createTitledBorder(bundle.getString("dtUltimaInspecao"))); // NOI18N
    pnlUltimaInspecao.setName("pnlUltimaInspecao"); // NOI18N

    sLabel8.setText(bundle.getString("lblFlagStatePortState")); // NOI18N
    sLabel8.setName("sLabel8"); // NOI18N

    sLabel19.setText(bundle.getString("lblPais")); // NOI18N
    sLabel19.setName("sLabel19"); // NOI18N

    sistamDateChooser1.setName("sistamDateChooser1"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.dataUltimaInspecao}"), sistamDateChooser1, BeanProperty.create("date"));
    bindingGroup.addBinding(binding);

    paisLookup1.setText("paisLookup1");
    paisLookup1.setName("paisLookup1"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.paisInspecao}"), paisLookup1, BeanProperty.create("value"));
    bindingGroup.addBinding(binding);

        GroupLayout pnlUltimaInspecaoLayout = new GroupLayout(pnlUltimaInspecao);
    pnlUltimaInspecao.setLayout(pnlUltimaInspecaoLayout);
    pnlUltimaInspecaoLayout.setHorizontalGroup(
        pnlUltimaInspecaoLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(pnlUltimaInspecaoLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlUltimaInspecaoLayout.createParallelGroup(Alignment.LEADING)
                .addGroup(pnlUltimaInspecaoLayout.createSequentialGroup()
                    .addComponent(sLabel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(sistamDateChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlUltimaInspecaoLayout.createSequentialGroup()
                    .addComponent(sLabel19, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(paisLookup1, GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
            .addContainerGap())
    );
    pnlUltimaInspecaoLayout.setVerticalGroup(
        pnlUltimaInspecaoLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(pnlUltimaInspecaoLayout.createSequentialGroup()
            .addGroup(pnlUltimaInspecaoLayout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sistamDateChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.UNRELATED)
            .addGroup(pnlUltimaInspecaoLayout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel19, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(paisLookup1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addGap(0, 7, Short.MAX_VALUE))
    );

    sPanel2.setBorder(BorderFactory.createTitledBorder(bundle.getString("dtValidade"))); // NOI18N
    sPanel2.setName("sPanel2"); // NOI18N

    sLabel20.setText(bundle.getString("lblDeclaracaoConformidade")); // NOI18N
    sLabel20.setName("sLabel20"); // NOI18N

    sLabel21.setText(bundle.getString("lblDeclaracaoProvisoria")); // NOI18N
    sLabel21.setName("sLabel21"); // NOI18N

    sistamDateChooser2.setName("sistamDateChooser2"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.dataValidadeDeclaracaoProvisoria}"), sistamDateChooser2, BeanProperty.create("date"));
    bindingGroup.addBinding(binding);

    sistamDateChooser3.setName("sistamDateChooser3"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.dataValidadeDeclaracaoConformidade}"), sistamDateChooser3, BeanProperty.create("date"));
    bindingGroup.addBinding(binding);

        GroupLayout sPanel2Layout = new GroupLayout(sPanel2);
    sPanel2.setLayout(sPanel2Layout);
    sPanel2Layout.setHorizontalGroup(
        sPanel2Layout.createParallelGroup(Alignment.LEADING)
        .addGroup(sPanel2Layout.createSequentialGroup()
            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sPanel2Layout.createParallelGroup(Alignment.TRAILING)
                .addComponent(sLabel21, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel20, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(sPanel2Layout.createParallelGroup(Alignment.TRAILING)
                .addComponent(sistamDateChooser2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sistamDateChooser3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
    );
    sPanel2Layout.setVerticalGroup(
        sPanel2Layout.createParallelGroup(Alignment.LEADING)
        .addGroup(sPanel2Layout.createSequentialGroup()
            .addGroup(sPanel2Layout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel20, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sistamDateChooser3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sPanel2Layout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel21, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sistamDateChooser2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    sPanel3.setBorder(BorderFactory.createTitledBorder("Provisão de Registro de Propriedade (PRPM) ou Certificado de Registro"));
    sPanel3.setName("sPanel3"); // NOI18N

    sLabel1.setText(bundle.getString("lblNrCertificado")); // NOI18N
    sLabel1.setName("sLabel1"); // NOI18N

    sLabel2.setText(bundle.getString("lblDtRegistro")); // NOI18N
    sLabel2.setName("sLabel2"); // NOI18N

    sLabel22.setText(bundle.getString("lblPorto")); // NOI18N
    sLabel22.setName("sLabel22"); // NOI18N

    sNumericTextField1.setDecimalPlaces(new Short((short)0));
    sNumericTextField1.setIntegerPlaces(new Short((short)8));
    sNumericTextField1.setNumberClass(Long.class);
    sNumericTextField1.setText("sNumericTextField1");
    sNumericTextField1.setName("sNumericTextField1"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.numeroRegistro}"), sNumericTextField1, BeanProperty.create("longValue"));
    bindingGroup.addBinding(binding);

    sistamDateChooser4.setName("sistamDateChooser4"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.dataRegistro}"), sistamDateChooser4, BeanProperty.create("date"));
    bindingGroup.addBinding(binding);

    portoLookup1.setText("portoLookup1");
    portoLookup1.setName("portoLookup1"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.portoRegistro}"), portoLookup1, BeanProperty.create("value"));
    bindingGroup.addBinding(binding);

        GroupLayout sPanel3Layout = new GroupLayout(sPanel3);
    sPanel3.setLayout(sPanel3Layout);
    sPanel3Layout.setHorizontalGroup(
        sPanel3Layout.createParallelGroup(Alignment.LEADING)
        .addGroup(sPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(sNumericTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(sistamDateChooser4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(sLabel22, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(portoLookup1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    sPanel3Layout.setVerticalGroup(
        sPanel3Layout.createParallelGroup(Alignment.LEADING)
        .addGroup(sPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(sPanel3Layout.createParallelGroup(Alignment.LEADING)
                .addGroup(sPanel3Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(sLabel22, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(portoLookup1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGroup(sPanel3Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sNumericTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sistamDateChooser4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    sPanel4.setBorder(BorderFactory.createTitledBorder(""));
    sPanel4.setName("sPanel4"); // NOI18N

    sTextField1.setDocument(new GenericDocument(50, 
        GenericDocument.OPTION_APPLY_UPPERCASE ));
sTextField1.setName("sTextField1"); // NOI18N

binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.proprietario}"), sTextField1, BeanProperty.create("text"));
bindingGroup.addBinding(binding);

sLabel6.setText("Proprietário:");
sLabel6.setName("sLabel6"); // NOI18N

sTextField5.setDocument(new GenericDocument(30, 
    GenericDocument.OPTION_APPLY_UPPERCASE ));
    sTextField5.setName("sTextField5"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.armador}"), sTextField5, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    sLabel7.setText("Armador:");
    sLabel7.setName("sLabel7"); // NOI18N

    sLabel5.setText("Data Construção:");
    sLabel5.setName("sLabel5"); // NOI18N

    sistamDateChooser5.setName("sistamDateChooser5"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.dataConstrucao}"), sistamDateChooser5, BeanProperty.create("date"));
    bindingGroup.addBinding(binding);

    sCheckBox1.setText("Possui heliporto");
    sCheckBox1.setName("sCheckBox1"); // NOI18N
    sCheckBox1.setOpaque(false);

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.heliporto}"), sCheckBox1, BeanProperty.create("selected"));
    bindingGroup.addBinding(binding);

    sLabel23.setText("Centro de Custo:");
    sLabel23.setName("sLabel23"); // NOI18N

    sTextField6.setDocument(new GenericDocument(10, 
        GenericDocument.OPTION_APPLY_UPPERCASE ));
sTextField6.setName("sTextField6"); // NOI18N

binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.centro_custo}"), sTextField6, BeanProperty.create("text"));
bindingGroup.addBinding(binding);

sLabel25.setText("Sociedade Classificadora:");
sLabel25.setName("sLabel25"); // NOI18N

sTextField7.setDocument(new GenericDocument(70, 
    GenericDocument.OPTION_APPLY_UPPERCASE ));
    sTextField7.setName("sTextField7"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.sociedade_classificadora}"), sTextField7, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

        GroupLayout sPanel4Layout = new GroupLayout(sPanel4);
    sPanel4.setLayout(sPanel4Layout);
    sPanel4Layout.setHorizontalGroup(
        sPanel4Layout.createParallelGroup(Alignment.LEADING)
        .addGroup(sPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(sPanel4Layout.createParallelGroup(Alignment.LEADING)
                .addComponent(sLabel25, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel7, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel6, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel23, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(sPanel4Layout.createParallelGroup(Alignment.LEADING)
                .addGroup(sPanel4Layout.createSequentialGroup()
                    .addComponent(sTextField6, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                    .addComponent(sCheckBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addComponent(sTextField7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Alignment.TRAILING, sPanel4Layout.createSequentialGroup()
                    .addGroup(sPanel4Layout.createParallelGroup(Alignment.LEADING)
                        .addComponent(sTextField1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sTextField5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addGroup(sPanel4Layout.createParallelGroup(Alignment.LEADING)
                        .addComponent(sLabel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sistamDateChooser5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
            .addContainerGap())
    );
    sPanel4Layout.setVerticalGroup(
        sPanel4Layout.createParallelGroup(Alignment.LEADING)
        .addGroup(sPanel4Layout.createSequentialGroup()
            .addGroup(sPanel4Layout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(sPanel4Layout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sistamDateChooser5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sPanel4Layout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel25, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.UNRELATED)
            .addGroup(sPanel4Layout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sCheckBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel23, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
    );

    sPanel5.setBorder(BorderFactory.createTitledBorder("Contato"));
    sPanel5.setName("sPanel5"); // NOI18N

    sLabel10.setText("Telefone:");
    sLabel10.setName("sLabel10"); // NOI18N

    sLabel14.setText("E-mail:");
    sLabel14.setName("sLabel14"); // NOI18N

    txtTelefone.setDocument(new GenericDocument(50));
    txtTelefone.setName("txtTelefone"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.telefone}"), txtTelefone, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    txtEmail.setDocument(new GenericDocument(100 ));
    txtEmail.setName("txtEmail"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.embarcacao.email}"), txtEmail, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

        GroupLayout sPanel5Layout = new GroupLayout(sPanel5);
    sPanel5.setLayout(sPanel5Layout);
    sPanel5Layout.setHorizontalGroup(
        sPanel5Layout.createParallelGroup(Alignment.LEADING)
        .addGroup(sPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(sLabel10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(txtTelefone, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(sLabel14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(txtEmail, GroupLayout.PREFERRED_SIZE, 251, GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    sPanel5Layout.setVerticalGroup(
        sPanel5Layout.createParallelGroup(Alignment.LEADING)
        .addGroup(sPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(sPanel5Layout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(txtTelefone, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(txtEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

        GroupLayout sPanel1Layout = new GroupLayout(sPanel1);
    sPanel1.setLayout(sPanel1Layout);
    sPanel1Layout.setHorizontalGroup(
        sPanel1Layout.createParallelGroup(Alignment.LEADING)
        .addGroup(sPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(sPanel1Layout.createParallelGroup(Alignment.LEADING)
                .addComponent(sPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sPanel1Layout.createSequentialGroup()
                    .addGroup(sPanel1Layout.createParallelGroup(Alignment.LEADING, false)
                        .addComponent(pnlInfBasicas, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlCapacidadeSIGO, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(sPanel1Layout.createSequentialGroup()
                    .addComponent(pnlUltimaInspecao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(sPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addContainerGap())
    );
    sPanel1Layout.setVerticalGroup(
        sPanel1Layout.createParallelGroup(Alignment.LEADING)
        .addGroup(Alignment.TRAILING, sPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(pnlInfBasicas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(pnlCapacidadeSIGO, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(sPanel1Layout.createParallelGroup(Alignment.LEADING)
                .addComponent(sPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(pnlUltimaInspecao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(sPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(sPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(sPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

        GroupLayout painelInformacoesLayout = new GroupLayout(painelInformacoes);
    painelInformacoes.setLayout(painelInformacoesLayout);
    painelInformacoesLayout.setHorizontalGroup(
        painelInformacoesLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(Alignment.TRAILING, painelInformacoesLayout.createSequentialGroup()
            .addComponent(sPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    painelInformacoesLayout.setVerticalGroup(
        painelInformacoesLayout.createParallelGroup(Alignment.LEADING)
        .addComponent(sPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    painelBotoes.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
    painelBotoes.setName("painelBotoes"); // NOI18N

    botaoSalvar.setAction(actionSalvar);
    botaoSalvar.setName("botaoSalvar"); // NOI18N
    painelBotoes.add(botaoSalvar);

        GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(Alignment.LEADING)
        .addComponent(painelBotoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelInformacoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(painelInformacoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(ComponentPlacement.UNRELATED)
            .addComponent(painelBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
    );

    bindingGroup.bind();

    pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    SLabel lblBandeira;
    public STextField txtCodigo;
    STextField txtEmail;
    STextField txtImo;
    STextField txtIrin;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
