package br.com.petrobras.sistam.desktop.components;

import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.snarf.common.util.SerializableObservableList;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;

public class PropriedadesPainel extends SPanel {

    public static class Propriedade {
        private Object nome;
        private Object valor;

        public Propriedade(Object nome, Object valor) {
            this.nome = nome;
            this.valor = valor;
        }

        public Object getNome() {
            return nome;
        }

        public Object getValor() {
            return valor;
        }
    }

    private List<Propriedade> listaPropriedades = new SerializableObservableList<Propriedade>();

    public PropriedadesPainel() {
        initComponents();    
        this.setSize(200, 200);
        setMaximumSize(new Dimension(200, 200));
    }

    @Override
    public void setMaximumSize(Dimension maximumSize) {
        super.setMaximumSize(maximumSize); //To change body of generated methods, choose Tools | Templates.
    }
    
    

    @Override
    public void setMinimumSize(Dimension minimumSize) {
        throw new UnsupportedOperationException("Não é permitido alterar o tamanho mínimo deste componente");
    }


    public List<Propriedade> getListaPropriedades() {
        return listaPropriedades;
    }

    public void adicionarPropriedade(Object nome, Object valor){
        listaPropriedades.add(new Propriedade(nome, valor));
        this.firePropertyChange("listaPropriedades", null, this.listaPropriedades);
    }
    
    public void limparPropriedades(){
        listaPropriedades.clear();
        this.firePropertyChange("listaPropriedades", null, this.listaPropriedades);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        painelTitulo = new br.com.petrobras.fcorp.swing.components.SPanel();
        lblTitulo = new br.com.petrobras.fcorp.swing.components.SLabel();
        painelComando = new br.com.petrobras.fcorp.swing.components.SPanel();
        btnAcao = new br.com.petrobras.fcorp.swing.components.SButton();
        scroll = new javax.swing.JScrollPane();
        tabelaPropriedades = new br.com.petrobras.fcorp.swing.components.STable();

        setLayout(new java.awt.BorderLayout());

        painelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelTitulo.setMinimumSize(new java.awt.Dimension(127, 20));
        painelTitulo.setPreferredSize(new java.awt.Dimension(400, 25));
        painelTitulo.setLayout(new java.awt.BorderLayout());

        lblTitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 4, 0, 0));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/props.png"))); // NOI18N
        lblTitulo.setText("Propriedades");
        painelTitulo.add(lblTitulo, java.awt.BorderLayout.CENTER);

        painelComando.setMinimumSize(new java.awt.Dimension(36, 12));
        painelComando.setPreferredSize(new java.awt.Dimension(20, 14));

        btnAcao.setClockwise(true);
        btnAcao.setBorderPainted(false);
        btnAcao.setContentAreaFilled(false);
        btnAcao.setFocusPainted(false);
        btnAcao.setFocusable(false);
        btnAcao.setPreferredSize(new java.awt.Dimension(16, 10));
        painelComando.add(btnAcao);

        painelTitulo.add(painelComando, java.awt.BorderLayout.EAST);

        add(painelTitulo, java.awt.BorderLayout.NORTH);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${listaPropriedades}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tabelaPropriedades);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("");
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valor}"));
        columnBinding.setColumnName("");
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        scroll.setViewportView(tabelaPropriedades);

        add(scroll, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.petrobras.fcorp.swing.components.SButton btnAcao;
    private br.com.petrobras.fcorp.swing.components.SLabel lblTitulo;
    private br.com.petrobras.fcorp.swing.components.SPanel painelComando;
    private br.com.petrobras.fcorp.swing.components.SPanel painelTitulo;
    private javax.swing.JScrollPane scroll;
    private br.com.petrobras.fcorp.swing.components.STable tabelaPropriedades;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
