package br.com.petrobras.sistam.desktop.servicoprotecao;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SDateChooser;
import br.com.petrobras.fcorp.swing.components.SFormattedTextField;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Pessoa;
import br.com.petrobras.sistam.desktop.components.lookups.servicoprotecao.EmpresaProtecaoLookup;
import br.com.petrobras.sistam.desktop.util.DesktopUtil;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 * @author adzk
 */
public class DetalhesPessoaProtecaoDialog extends SDialog {

    private DetalhesPessoaProtecaoModel model;

    /**
     * Constrói um dialog modal centralizado no frame pai.
     */
    public DetalhesPessoaProtecaoDialog(java.awt.Frame parent, Pessoa pessoa) {
        super(parent, true);
        model = new DetalhesPessoaProtecaoModel(pessoa);
        initComponents();
        setLocationRelativeTo(parent);
        DesktopUtil.configurarComponenteCPF(campoCpf, actionSalvar);
    }

    public DetalhesPessoaProtecaoModel getModel() {
        return model;
    }

    public void salvar() {
        model.salvar();
        if (model.isSalvo()) {
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"})
    @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        actionSalvar = new GenericAction();
        SPanel panelInformacoes = new SPanel();
        SLabel sLabel1 = new SLabel();
        SLabel sLabel2 = new SLabel();
        SLabel sLabel3 = new SLabel();
        SLabel sLabel4 = new SLabel();
        SLabel sLabel7 = new SLabel();
        STextField sTextField1 = new STextField();
        campoCpf = new SFormattedTextField();
        STextField sTextField2 = new STextField();
        SDateChooser sDateChooser1 = new SDateChooser();
        SLabel sLabel8 = new SLabel();
        SComboBox sComboBox2 = new SComboBox();
        SLabel sLabel5 = new SLabel();
        STextField sTextField3 = new STextField();
        EmpresaProtecaoLookup empresaProtecaoLookup1 = new EmpresaProtecaoLookup();
        SLabel sLabel6 = new SLabel();
        STextField sTextField4 = new STextField();
        SPanel panelBotoes = new SPanel();
        SButton botaoSalvar = new SButton();

        actionSalvar.setIcon(new ImageIcon(getClass().getResource("/icons/disk.png"))); // NOI18N
        actionSalvar.setMethodName("salvar");
        actionSalvar.setTarget(this);
        actionSalvar.setText("Salvar");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pessoa do Serviço de Proteção");
        setResizable(false);

        panelInformacoes.setBorder(BorderFactory.createTitledBorder("Informações"));
        panelInformacoes.setMaximumSize(new Dimension(700, 170));
        panelInformacoes.setName("panelInformacoes"); // NOI18N
        panelInformacoes.setPreferredSize(new Dimension(700, 170));

        sLabel1.setText("CPF:");
        sLabel1.setName("sLabel1"); // NOI18N

        sLabel2.setText("Nome:");
        sLabel2.setName("sLabel2"); // NOI18N

        sLabel3.setText("Nº Documento:");
        sLabel3.setName("sLabel3"); // NOI18N

        sLabel4.setText("Empresa:");
        sLabel4.setName("sLabel4"); // NOI18N

        sLabel7.setText("Data de Nascimento:");
        sLabel7.setName("sLabel7"); // NOI18N

        sTextField1.setDocument(new GenericDocument(50));
        sTextField1.setName("sTextField1"); // NOI18N

        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.pessoa.documento}"), sTextField1, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        campoCpf.setName("campoCpf"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.pessoa.cpfComMascara}"), campoCpf, BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        sTextField2.setDocument(new GenericDocument(100));
        sTextField2.setName("sTextField2"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.pessoa.nome}"), sTextField2, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sDateChooser1.setName("sDateChooser1"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.pessoa.dataNascimento}"), sDateChooser1, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel8.setText("Ativa:");
        sLabel8.setName("sLabel8"); // NOI18N

        sComboBox2.setName("sComboBox2"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.tiposSimNao}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, sComboBox2);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.ativoSimNaoSelecionado}"), sComboBox2, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        sLabel5.setText("Nacionalidade:");
        sLabel5.setName("sLabel5"); // NOI18N

        sTextField3.setDocument(new GenericDocument(100));
        sTextField3.setName("sTextField3"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.pessoa.nacionalidade}"), sTextField3, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        empresaProtecaoLookup1.setText("empresaProtecaoLookup1");
        empresaProtecaoLookup1.setName("empresaProtecaoLookup1"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.pessoa.empresa}"), empresaProtecaoLookup1, BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        sLabel6.setText("Tipo do Documento:");
        sLabel6.setName("sLabel6"); // NOI18N

        sTextField4.setDocument(new GenericDocument(40));
        sTextField4.setName("sTextField4"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.pessoa.tipoDocumentoIdentificacao}"), sTextField4, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        GroupLayout panelInformacoesLayout = new GroupLayout(panelInformacoes);
        panelInformacoes.setLayout(panelInformacoesLayout);
        panelInformacoesLayout.setHorizontalGroup(
            panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacoesLayout.createSequentialGroup()
                .addGroup(panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformacoesLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(sLabel2, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel1, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel5, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel4, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInformacoesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sLabel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sTextField3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empresaProtecaoLookup1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.TRAILING, panelInformacoesLayout.createSequentialGroup()
                        .addComponent(campoCpf, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(94, 94, 94)
                        .addComponent(sLabel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sDateChooser1, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE))
                    .addGroup(GroupLayout.Alignment.TRAILING, panelInformacoesLayout.createSequentialGroup()
                        .addComponent(sTextField2, GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addGap(65, 65, 65)
                        .addComponent(sLabel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sComboBox2, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInformacoesLayout.createSequentialGroup()
                        .addComponent(sTextField4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sTextField1, GroupLayout.PREFERRED_SIZE, 213, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelInformacoesLayout.setVerticalGroup(
            panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCpf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sDateChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(empresaProtecaoLookup1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBotoes.setName("panelBotoes"); // NOI18N

        botaoSalvar.setAction(actionSalvar);
        botaoSalvar.setName("botaoSalvar"); // NOI18N
        panelBotoes.add(botaoSalvar);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(panelBotoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInformacoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInformacoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON
    // Variables declaration - do not modify//GEN-BEGIN:variables
    GenericAction actionSalvar;
    SFormattedTextField campoCpf;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
