package br.com.petrobras.sistam.desktop.agenciamento.protecao.formularios.retiradaResiduoLixo;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SDateChooser;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.renderers.ImageBooleanRenderer;
import br.com.petrobras.sistam.common.entity.ServicoRetiradaResiduoLixo;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

public class FormularioRetiradaResiduoLixoDialog extends SDialog {
    private FormularioRetiradaResiduoLixoModel model;
    
    public FormularioRetiradaResiduoLixoDialog(java.awt.Frame parent, ServicoRetiradaResiduoLixo servicoRetiradaResiduoLixo) {
        super(parent, true);
        model = new FormularioRetiradaResiduoLixoModel(servicoRetiradaResiduoLixo);
        initComponents();        
        setLocationRelativeTo(parent);        
    }

    public FormularioRetiradaResiduoLixoModel getModel() {
        return model;
    }
    
    public void gerarFormulario(){
        model.validar();
        model.gerarFormulario();
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        GenericAction actionGerarFormulario = new GenericAction();
        ImageBooleanRenderer imageBooleanGerado = new ImageBooleanRenderer();
        SPanel pnlPrincipal = new SPanel();
        SPanel panelPessoas = new SPanel();
        SComboBox sComboBox1 = new SComboBox();
        SPanel pnlBotoes = new SPanel();
        SButton sButton1 = new SButton();
        SLabel sLabel4 = new SLabel();
        SDateChooser sDateChooser2 = new SDateChooser();

        actionGerarFormulario.setIcon(new ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        actionGerarFormulario.setMethodName("gerarFormulario");
        actionGerarFormulario.setTarget(this);
        actionGerarFormulario.setText("Gerar Formulário");
        actionGerarFormulario.setToolTipText("Gera o formulário");

        imageBooleanGerado.setFalseIcon(new ImageIcon(getClass().getResource("/icons/props.png"))); // NOI18N
        imageBooleanGerado.setTrueIcon(new ImageIcon(getClass().getResource("/icons/document-accept.png"))); // NOI18N

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário Retirada Resíduo/Lixo");

        pnlPrincipal.setBorder(BorderFactory.createEtchedBorder());
        pnlPrincipal.setName("pnlPrincipal"); // NOI18N

        panelPessoas.setBorder(BorderFactory.createTitledBorder("Representante Legal"));
        panelPessoas.setName("panelPessoas"); // NOI18N

        sComboBox1.setName("sComboBox1"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.listaRepresentante}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, sComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);
        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.listaRepresentante}"), sComboBox1, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        GroupLayout panelPessoasLayout = new GroupLayout(panelPessoas);
        panelPessoas.setLayout(panelPessoasLayout);
        panelPessoasLayout.setHorizontalGroup(
            panelPessoasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sComboBox1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPessoasLayout.setVerticalGroup(
            panelPessoasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlBotoes.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        pnlBotoes.setName("pnlBotoes"); // NOI18N

        sButton1.setAction(actionGerarFormulario);
        sButton1.setName("sButton1"); // NOI18N
        pnlBotoes.add(sButton1);

        sLabel4.setText("Data:");
        sLabel4.setName("sLabel4"); // NOI18N

        sDateChooser2.setName("sDateChooser2"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.dataPeriodo}"), sDateChooser2, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        GroupLayout pnlPrincipalLayout = new GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(panelPessoas, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sDateChooser2, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                        .addGap(374, 374, 374)))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPessoas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sDateChooser2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlPrincipal, BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
