package br.com.petrobras.sistam.desktop.pontoatracacao;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.PontoAtracacao;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

public class DetalhesPontoAtracacaoDialog extends SDialog {
    private DetalhesPontoAtracacaoModel model;
    
    public DetalhesPontoAtracacaoDialog(java.awt.Frame parent, PontoAtracacao pontoAtracacao) {
        super(parent, true);
        this.model = new DetalhesPontoAtracacaoModel(pontoAtracacao);
        initComponents();
        setLocationRelativeTo(parent);
    }
    
    public DetalhesPontoAtracacaoModel getModel() {
        return model;
    }
    
    public void salvar() {
        model.salvar();
        dispose();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        actionSalvar = new GenericAction();
        SPanel painelBotoes = new SPanel();
        SButton botaoSalvar = new SButton();
        SPanel sPanel1 = new SPanel();
        SLabel labelPorto = new SLabel();
        SLabel labelPontoOperacional = new SLabel();
        SLabel labelNome = new SLabel();
        SComboBox comboPorto = new SComboBox();
        SComboBox comboPontoOperacional = new SComboBox();
        STextField campoNome = new STextField();
        SLabel sLabel1 = new SLabel();
        STextField sTextField1 = new STextField();

        actionSalvar.setIcon(new ImageIcon(getClass().getResource("/icons/disk.png"))); // NOI18N
        actionSalvar.setMethodName("salvar");
        actionSalvar.setTarget(this);
        actionSalvar.setText("Salvar");
        actionSalvar.setToolTipText("Salva as alterações");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dados do Ponto de Atracação");

        painelBotoes.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        painelBotoes.setName("painelBotoes"); // NOI18N

        botaoSalvar.setAction(actionSalvar);
        botaoSalvar.setName("botaoSalvar"); // NOI18N
        painelBotoes.add(botaoSalvar);

        sPanel1.setBorder(BorderFactory.createTitledBorder("Informações do Ponto"));
        sPanel1.setName("sPanel1"); // NOI18N

        labelPorto.setText("Porto:");
        labelPorto.setName("labelPorto"); // NOI18N

        labelPontoOperacional.setText("Ponto Operacional:");
        labelPontoOperacional.setName("labelPontoOperacional"); // NOI18N

        labelNome.setText("Nome:");
        labelNome.setName("labelNome"); // NOI18N

        comboPorto.setName("comboPorto"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.listaPorto}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE, this, eLProperty, comboPorto);
        bindingGroup.addBinding(jComboBoxBinding);
        Binding binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.portoSelecionado}"), comboPorto, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        comboPontoOperacional.setName("comboPontoOperacional"); // NOI18N

        eLProperty = ELProperty.create("${model.listaPontoOperacional}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE, this, eLProperty, comboPontoOperacional);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.pontoOperacionalSelecionado}"), comboPontoOperacional, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        campoNome.setDocument(new GenericDocument(50,
            GenericDocument.OPTION_APPLY_UPPERCASE));
    campoNome.setName("campoNome"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.pontoAtracacao.nome}"), campoNome, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    sLabel1.setText("Sigla:");
    sLabel1.setName("sLabel1"); // NOI18N

    sTextField1.setDocument(new GenericDocument(6,
        GenericDocument.OPTION_APPLY_UPPERCASE));
sTextField1.setName("sTextField1"); // NOI18N

binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.pontoAtracacao.sigla}"), sTextField1, BeanProperty.create("text"));
bindingGroup.addBinding(binding);

        GroupLayout sPanel1Layout = new GroupLayout(sPanel1);
sPanel1.setLayout(sPanel1Layout);
sPanel1Layout.setHorizontalGroup(
    sPanel1Layout.createParallelGroup(Alignment.LEADING)
    .addGroup(sPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(sPanel1Layout.createParallelGroup(Alignment.TRAILING)
            .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addComponent(labelPorto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addComponent(labelPontoOperacional, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addComponent(labelNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(ComponentPlacement.RELATED)
        .addGroup(sPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addComponent(comboPontoOperacional, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(campoNome, GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
            .addComponent(comboPorto, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addComponent(sTextField1, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    sPanel1Layout.setVerticalGroup(
        sPanel1Layout.createParallelGroup(Alignment.LEADING)
        .addGroup(sPanel1Layout.createSequentialGroup()
            .addGroup(sPanel1Layout.createParallelGroup(Alignment.BASELINE)
                .addComponent(labelPorto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(comboPorto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(sPanel1Layout.createParallelGroup(Alignment.BASELINE)
                .addComponent(labelPontoOperacional, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(comboPontoOperacional, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(sPanel1Layout.createParallelGroup(Alignment.BASELINE)
                .addComponent(labelNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(campoNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(sPanel1Layout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

        GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(sPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(10, 10, 10))
                .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(painelBotoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(sPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(painelBotoes, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    bindingGroup.bind();

    pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    GenericAction actionSalvar;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
