package br.com.petrobras.sistam.desktop.relatorio;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SCheckList;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import javax.swing.AbstractListModel;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.JListBinding;
import org.jdesktop.swingbinding.SwingBindings;

public class RelatorioTimesheetDialog extends SDialog {
    
    private RelatorioTimesheetModel model;

    /** 
     * Constrói um dialog modal centralizado no frame pai.
     */
    public RelatorioTimesheetDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.model = new RelatorioTimesheetModel();
        initComponents();
        setLocationRelativeTo(parent);
    }

    public RelatorioTimesheetModel getModel() {
        return model;
    }
    
    public void enviar() {
        model.enviarRelatorio();
        dispose();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        GenericAction actionEnviar = new GenericAction();
        SPanel panelGeral = new SPanel();
        SPanel panelInformacoes = new SPanel();
        SLabel labelAgencia = new SLabel();
        SLabel labelPorto = new SLabel();
        SLabel labelEmbarcacoes = new SLabel();
        SComboBox comboAgencia = new SComboBox();
        SComboBox comboPorto = new SComboBox();
        JScrollPane jScrollPane1 = new JScrollPane();
        SCheckList checkListEmbarcacoes = new SCheckList();
        SLabel labelSituacao1 = new SLabel();
        SComboBox comboSituacao1 = new SComboBox();
        SPanel panelBotoes = new SPanel();
        SButton botaoEnviar = new SButton();

        actionEnviar.setMethodName("enviar");
        actionEnviar.setTarget(this);
        actionEnviar.setText("Enviar relatório");
        actionEnviar.setToolTipText("Enviar relatório de timesheet");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório Timesheet");

        panelGeral.setName("panelGeral"); // NOI18N

        panelInformacoes.setBorder(BorderFactory.createTitledBorder("Filtro para o Relatório"));
        panelInformacoes.setName("panelInformacoes"); // NOI18N

        labelAgencia.setText("Agência:");
        labelAgencia.setName("labelAgencia"); // NOI18N

        labelPorto.setText("Porto:");
        labelPorto.setName("labelPorto"); // NOI18N

        labelEmbarcacoes.setText("Embarcações:");
        labelEmbarcacoes.setName("labelEmbarcacoes"); // NOI18N

        comboAgencia.setName("comboAgencia"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.agencias}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, comboAgencia);
        bindingGroup.addBinding(jComboBoxBinding);
        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.agencia}"), comboAgencia, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        comboPorto.setName("comboPorto"); // NOI18N

        eLProperty = ELProperty.create("${model.portos}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, comboPorto);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.porto}"), comboPorto, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        checkListEmbarcacoes.setBorder(BorderFactory.createEmptyBorder(1, 5, 1, 1));
        checkListEmbarcacoes.setModel(new AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        checkListEmbarcacoes.setName("checkListEmbarcacoes"); // NOI18N
        checkListEmbarcacoes.setVisibleRowCount(5);

        eLProperty = ELProperty.create("${model.embarcacoes}");
        JListBinding jListBinding = SwingBindings.createJListBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, checkListEmbarcacoes);
        bindingGroup.addBinding(jListBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.embarcacoes}"), checkListEmbarcacoes, BeanProperty.create("selectedElements"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(checkListEmbarcacoes);

        labelSituacao1.setText("Frota:");
        labelSituacao1.setName("labelSituacao1"); // NOI18N

        comboSituacao1.setName("comboSituacao1"); // NOI18N

        eLProperty = ELProperty.create("${model.tipoFrota}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, comboSituacao1);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.tipoFrota}"), comboSituacao1, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        GroupLayout panelInformacoesLayout = new GroupLayout(panelInformacoes);
        panelInformacoes.setLayout(panelInformacoesLayout);
        panelInformacoesLayout.setHorizontalGroup(
            panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(labelAgencia, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPorto, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSituacao1, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmbarcacoes, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(comboPorto, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboAgencia, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(comboSituacao1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelInformacoesLayout.setVerticalGroup(
            panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAgencia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAgencia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPorto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPorto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSituacao1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSituacao1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmbarcacoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBotoes.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        panelBotoes.setName("panelBotoes"); // NOI18N

        botaoEnviar.setAction(actionEnviar);
        botaoEnviar.setIcon(new ImageIcon(getClass().getResource("/icons/send.png"))); // NOI18N
        botaoEnviar.setName("botaoEnviar"); // NOI18N
        panelBotoes.add(botaoEnviar);

        GroupLayout panelGeralLayout = new GroupLayout(panelGeral);
        panelGeral.setLayout(panelGeralLayout);
        panelGeralLayout.setHorizontalGroup(
            panelGeralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(panelBotoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addComponent(panelInformacoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelGeralLayout.setVerticalGroup(
            panelGeralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, panelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInformacoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelGeral, BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
