package br.com.petrobras.sistam.desktop.relatorio;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SCheckList;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.sistam.desktop.components.SistamDateChooser;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.sistam.desktop.components.SistamTimeChooser;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import java.util.ResourceBundle;
import javax.swing.AbstractListModel;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.JListBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 * @author adzk
 */
public class RelatorioSiscomexDialog extends SDialog {
    
    private RelatorioSiscomexModel model;

    /** 
     * Constrói um dialog modal centralizado no frame pai.
     */
    public RelatorioSiscomexDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        model = new RelatorioSiscomexModel();
        initComponents();
        setLocationRelativeTo(parent);
    }

    public RelatorioSiscomexModel getModel() {
        return model;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        actionGerar = new GenericAction();
        pabelGeral = new SPanel();
        panelFiltros1 = new SPanel();
        sLabel1 = new SLabel();
        sLabel2 = new SLabel();
        sLabel3 = new SLabel();
        sLabel5 = new SLabel();
        sLabel6 = new SLabel();
        ordenacoes = new SComboBox();
        inicioOficialChegada = new SistamDateChooser();
        sLabel7 = new SLabel();
        fimOficialChegada = new SistamDateChooser();
        tiposComManisfestos = new SComboBox();
        sLabel8 = new SLabel();
        sLabel9 = new SLabel();
        sLabel10 = new SLabel();
        inicioOficialSaida = new SistamDateChooser();
        sLabel11 = new SLabel();
        fimOficialSaida = new SistamDateChooser();
        inicioInicioOperacao = new SistamDateChooser();
        sLabel12 = new SLabel();
        fimInicioOperacao = new SistamDateChooser();
        inicioFimOperacao = new SistamDateChooser();
        sLabel13 = new SLabel();
        fimFimOperacao = new SistamDateChooser();
        sLabel14 = new SLabel();
        sLabel15 = new SLabel();
        inicioInclusao = new SistamDateChooser();
        sLabel18 = new SLabel();
        fimInclusao = new SistamDateChooser();
        inicioEta = new SistamDateChooser();
        sLabel19 = new SLabel();
        fimEta = new SistamDateChooser();
        sLabel23 = new SLabel();
        jScrollPane1 = new JScrollPane();
        sCheckList1 = new SCheckList();
        jScrollPane2 = new JScrollPane();
        sCheckList2 = new SCheckList();
        jScrollPane3 = new JScrollPane();
        sCheckList3 = new SCheckList();
        sLabel22 = new SLabel();
        inicioEts = new SistamDateChooser();
        sLabel24 = new SLabel();
        fimEts = new SistamDateChooser();
        sLabel4 = new SLabel();
        tiposComManisfestos1 = new SComboBox();
        sLabel25 = new SLabel();
        tiposComEscalaMercante = new SComboBox();
        inicioOficialChegadaH = new SistamTimeChooser();
        fimOficialChegadaH = new SistamTimeChooser();
        fimEtaH = new SistamTimeChooser();
        fimOficialSaidaH = new SistamTimeChooser();
        fimEtsH = new SistamTimeChooser();
        inicioEtsH = new SistamTimeChooser();
        inicioEtaH = new SistamTimeChooser();
        inicioOficialSaidaH = new SistamTimeChooser();
        sLabel16 = new SLabel();
        comboPortos = new SComboBox();
        panelBotao = new SPanel();
        btGerar = new SButton();

        actionGerar.setIcon(new ImageIcon(getClass().getResource("/icons/excel.png"))); // NOI18N
        actionGerar.setMethodName("gerar");
        actionGerar.setTarget(model);
        actionGerar.setText("Gerar");
        actionGerar.setToolTipText("Gerar o relatório de análise geral do Siscomex carga");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Análise Geral do Siscomex Carga");

        pabelGeral.setName("pabelGeral"); // NOI18N
        pabelGeral.setLayout(new BorderLayout());

        panelFiltros1.setBorder(BorderFactory.createTitledBorder("Filtro para o Relatório"));
        panelFiltros1.setName("panelFiltros1"); // NOI18N

        sLabel1.setText("Tipo de Operação:");
        sLabel1.setName("sLabel1"); // NOI18N

        sLabel2.setText("Tipo de Contrato:");
        sLabel2.setName("sLabel2"); // NOI18N

        sLabel3.setText("Situação da Embarcação no Porto:");
        sLabel3.setName("sLabel3"); // NOI18N

        sLabel5.setText("Ordenar por:");
        sLabel5.setName("sLabel5"); // NOI18N

        sLabel6.setText("Hora Oficial de Chegada:");
        sLabel6.setName("sLabel6"); // NOI18N

        ordenacoes.setName("ordenacoes"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.tiposOrdenacao}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, ordenacoes);
        bindingGroup.addBinding(jComboBoxBinding);
        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.ordenacao}"), ordenacoes, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        inicioOficialChegada.setName("inicioOficialChegada"); // NOI18N
        inicioOficialChegada.setTimeChooser(inicioOficialChegadaH);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoOficialChegada.dataInicio}"), inicioOficialChegada, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        ResourceBundle bundle = ResourceBundle.getBundle("sistam-labels"); // NOI18N
        sLabel7.setText(bundle.getString("lblAte")); // NOI18N
        sLabel7.setName("sLabel7"); // NOI18N

        fimOficialChegada.setName("fimOficialChegada"); // NOI18N
        fimOficialChegada.setTimeChooser(fimOficialChegadaH);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoOficialChegada.dataFim}"), fimOficialChegada, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        tiposComManisfestos.setName("tiposComManisfestos"); // NOI18N

        eLProperty = ELProperty.create("${model.tiposSimNao}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tiposComManisfestos);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.comManisfesto}"), tiposComManisfestos, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        sLabel8.setText("Hora Oficial de Saída:");
        sLabel8.setName("sLabel8"); // NOI18N

        sLabel9.setText("Início da Operação:");
        sLabel9.setName("sLabel9"); // NOI18N

        sLabel10.setText("Termino da Operação:");
        sLabel10.setName("sLabel10"); // NOI18N

        inicioOficialSaida.setName("inicioOficialSaida"); // NOI18N
        inicioOficialSaida.setTimeChooser(inicioOficialSaidaH);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoOficialSaida.dataInicio}"), inicioOficialSaida, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel11.setText(bundle.getString("lblAte")); // NOI18N
        sLabel11.setName("sLabel11"); // NOI18N

        fimOficialSaida.setName("fimOficialSaida"); // NOI18N
        fimOficialSaida.setTimeChooser(fimOficialSaidaH);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoOficialSaida.dataFim}"), fimOficialSaida, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        inicioInicioOperacao.setName("inicioInicioOperacao"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoInicioOperacao.dataInicio}"), inicioInicioOperacao, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel12.setText(bundle.getString("lblAte")); // NOI18N
        sLabel12.setName("sLabel12"); // NOI18N

        fimInicioOperacao.setName("fimInicioOperacao"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoInicioOperacao.dataFim}"), fimInicioOperacao, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        inicioFimOperacao.setName("inicioFimOperacao"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoTerminoOperacao.dataInicio}"), inicioFimOperacao, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel13.setText(bundle.getString("lblAte")); // NOI18N
        sLabel13.setName("sLabel13"); // NOI18N

        fimFimOperacao.setName("fimFimOperacao"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoTerminoOperacao.dataFim}"), fimFimOperacao, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel14.setText("Data de Inclusão no Sistam:");
        sLabel14.setName("sLabel14"); // NOI18N

        sLabel15.setText("ETA:");
        sLabel15.setName("sLabel15"); // NOI18N

        inicioInclusao.setName("inicioInclusao"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoInclusao.dataInicio}"), inicioInclusao, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel18.setText(bundle.getString("lblAte")); // NOI18N
        sLabel18.setName("sLabel18"); // NOI18N

        fimInclusao.setName("fimInclusao"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoInclusao.dataFim}"), fimInclusao, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        inicioEta.setName("inicioEta"); // NOI18N
        inicioEta.setTimeChooser(inicioEtaH);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoEta.dataInicio}"), inicioEta, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel19.setText(bundle.getString("lblAte")); // NOI18N
        sLabel19.setName("sLabel19"); // NOI18N

        fimEta.setName("fimEta"); // NOI18N
        fimEta.setTimeChooser(fimEtaH);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoEta.dataFim}"), fimEta, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel23.setText("Com Manisfesto?");
        sLabel23.setName("sLabel23"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        sCheckList1.setBorder(BorderFactory.createEmptyBorder(1, 5, 1, 1));
        sCheckList1.setModel(new AbstractListModel() {
            String[] strings = { "Item 1", "Item 2" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        sCheckList1.setName("sCheckList1"); // NOI18N
        sCheckList1.setVisibleRowCount(2);

        eLProperty = ELProperty.create("${model.tiposContrato}");
        JListBinding jListBinding = SwingBindings.createJListBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, sCheckList1);
        bindingGroup.addBinding(jListBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.tiposContrato}"), sCheckList1, BeanProperty.create("selectedElements"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(sCheckList1);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        sCheckList2.setBorder(BorderFactory.createEmptyBorder(1, 5, 1, 1));
        sCheckList2.setModel(new AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        sCheckList2.setName("sCheckList2"); // NOI18N
        sCheckList2.setVisibleRowCount(4);

        eLProperty = ELProperty.create("${model.situacoesEmbarcacao}");
        jListBinding = SwingBindings.createJListBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, sCheckList2);
        bindingGroup.addBinding(jListBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.situacoesEmbarcacao}"), sCheckList2, BeanProperty.create("selectedElements"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(sCheckList2);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        sCheckList3.setBorder(BorderFactory.createEmptyBorder(1, 5, 1, 1));
        sCheckList3.setModel(new AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        sCheckList3.setName("sCheckList3"); // NOI18N
        sCheckList3.setVisibleRowCount(4);

        eLProperty = ELProperty.create("${model.tiposOperacao}");
        jListBinding = SwingBindings.createJListBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, sCheckList3);
        bindingGroup.addBinding(jListBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.tiposOperacao}"), sCheckList3, BeanProperty.create("selectedElements"));
        bindingGroup.addBinding(binding);

        jScrollPane3.setViewportView(sCheckList3);

        sLabel22.setText("ETS:");
        sLabel22.setName("sLabel22"); // NOI18N

        inicioEts.setName("inicioEts"); // NOI18N
        inicioEts.setTimeChooser(inicioEtsH);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoEts.dataInicio}"), inicioEts, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel24.setText(bundle.getString("lblAte")); // NOI18N
        sLabel24.setName("sLabel24"); // NOI18N

        fimEts.setName("fimEts"); // NOI18N
        fimEts.setTimeChooser(fimEtsH);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoEts.dataFim}"), fimEts, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel4.setText("Agência:");
        sLabel4.setName("sLabel4"); // NOI18N

        tiposComManisfestos1.setName("tiposComManisfestos1"); // NOI18N

        eLProperty = ELProperty.create("${model.agencias}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tiposComManisfestos1);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.agencia}"), tiposComManisfestos1, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        sLabel25.setText("Com Escala Mercante?");
        sLabel25.setName("sLabel25"); // NOI18N

        tiposComEscalaMercante.setName("tiposComEscalaMercante"); // NOI18N

        eLProperty = ELProperty.create("${model.tiposSimNao}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tiposComEscalaMercante);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.comEscalaMercante}"), tiposComEscalaMercante, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        inicioOficialChegadaH.setName("inicioOficialChegadaH"); // NOI18N

        fimOficialChegadaH.setName("fimOficialChegadaH"); // NOI18N

        fimEtaH.setName("fimEtaH"); // NOI18N

        fimOficialSaidaH.setName("fimOficialSaidaH"); // NOI18N

        fimEtsH.setName("fimEtsH"); // NOI18N

        inicioEtsH.setName("inicioEtsH"); // NOI18N

        inicioEtaH.setName("inicioEtaH"); // NOI18N

        inicioOficialSaidaH.setName("inicioOficialSaidaH"); // NOI18N

        sLabel16.setText(bundle.getString("lblPorto")); // NOI18N
        sLabel16.setName("sLabel16"); // NOI18N

        comboPortos.setName("comboPortos"); // NOI18N

        eLProperty = ELProperty.create("${model.portos}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, comboPortos);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.porto}"), comboPortos, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        GroupLayout panelFiltros1Layout = new GroupLayout(panelFiltros1);
        panelFiltros1.setLayout(panelFiltros1Layout);
        panelFiltros1Layout.setHorizontalGroup(
            panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltros1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sLabel4, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel16, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel1, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel2, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel3, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel6, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel15, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel8, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel22, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel23, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel25, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel9, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel10, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel14, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel5, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, panelFiltros1Layout.createSequentialGroup()
                        .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(GroupLayout.Alignment.TRAILING, panelFiltros1Layout.createSequentialGroup()
                                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFiltros1Layout.createSequentialGroup()
                                        .addComponent(inicioOficialChegada, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inicioOficialChegadaH, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sLabel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelFiltros1Layout.createSequentialGroup()
                                        .addComponent(inicioOficialSaida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inicioOficialSaidaH, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sLabel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelFiltros1Layout.createSequentialGroup()
                                        .addComponent(inicioEta, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inicioEtaH, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sLabel19, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelFiltros1Layout.createSequentialGroup()
                                        .addComponent(inicioEts, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inicioEtsH, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sLabel24, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFiltros1Layout.createSequentialGroup()
                                        .addComponent(fimOficialSaida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fimOficialSaidaH, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelFiltros1Layout.createSequentialGroup()
                                        .addComponent(fimEta, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fimEtaH, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelFiltros1Layout.createSequentialGroup()
                                        .addComponent(fimEts, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fimEtsH, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelFiltros1Layout.createSequentialGroup()
                                        .addComponent(fimOficialChegada, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fimOficialChegadaH, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3)
                            .addComponent(comboPortos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tiposComManisfestos1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(panelFiltros1Layout.createSequentialGroup()
                        .addComponent(ordenacoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelFiltros1Layout.createSequentialGroup()
                        .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(panelFiltros1Layout.createSequentialGroup()
                                .addComponent(inicioInicioOperacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sLabel12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fimInicioOperacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFiltros1Layout.createSequentialGroup()
                                .addComponent(inicioFimOperacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sLabel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fimFimOperacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFiltros1Layout.createSequentialGroup()
                                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inicioInclusao, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tiposComManisfestos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tiposComEscalaMercante, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sLabel18, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fimInclusao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelFiltros1Layout.setVerticalGroup(
            panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltros1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiposComManisfestos1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel16, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPortos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(inicioOficialChegada, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(inicioOficialChegadaH, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(fimOficialChegada, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(fimOficialChegadaH, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(inicioEta, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(inicioEtaH, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(fimEta, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel19, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(fimEtaH, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(inicioOficialSaida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(inicioOficialSaidaH, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(fimOficialSaida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(fimOficialSaidaH, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(inicioEts, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel22, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(inicioEtsH, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(fimEts, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel24, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(fimEtsH, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel23, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiposComManisfestos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel25, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiposComEscalaMercante, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(inicioInicioOperacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(fimInicioOperacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(inicioFimOperacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(fimFimOperacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(inicioInclusao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(fimInclusao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel18, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltros1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordenacoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pabelGeral.add(panelFiltros1, BorderLayout.PAGE_START);

        panelBotao.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        panelBotao.setName("panelBotao"); // NOI18N

        btGerar.setAction(actionGerar);
        btGerar.setName("btGerar"); // NOI18N
        panelBotao.add(btGerar);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(pabelGeral, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelBotao, GroupLayout.PREFERRED_SIZE, 549, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pabelGeral, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    GenericAction actionGerar;
    SButton btGerar;
    SComboBox comboPortos;
    SistamDateChooser fimEta;
    SistamTimeChooser fimEtaH;
    SistamDateChooser fimEts;
    SistamTimeChooser fimEtsH;
    SistamDateChooser fimFimOperacao;
    SistamDateChooser fimInclusao;
    SistamDateChooser fimInicioOperacao;
    SistamDateChooser fimOficialChegada;
    SistamTimeChooser fimOficialChegadaH;
    SistamDateChooser fimOficialSaida;
    SistamTimeChooser fimOficialSaidaH;
    SistamDateChooser inicioEta;
    SistamTimeChooser inicioEtaH;
    SistamDateChooser inicioEts;
    SistamTimeChooser inicioEtsH;
    SistamDateChooser inicioFimOperacao;
    SistamDateChooser inicioInclusao;
    SistamDateChooser inicioInicioOperacao;
    SistamDateChooser inicioOficialChegada;
    SistamTimeChooser inicioOficialChegadaH;
    SistamDateChooser inicioOficialSaida;
    SistamTimeChooser inicioOficialSaidaH;
    JScrollPane jScrollPane1;
    JScrollPane jScrollPane2;
    JScrollPane jScrollPane3;
    SComboBox ordenacoes;
    SPanel pabelGeral;
    SPanel panelBotao;
    SPanel panelFiltros1;
    SCheckList sCheckList1;
    SCheckList sCheckList2;
    SCheckList sCheckList3;
    SLabel sLabel1;
    SLabel sLabel10;
    SLabel sLabel11;
    SLabel sLabel12;
    SLabel sLabel13;
    SLabel sLabel14;
    SLabel sLabel15;
    SLabel sLabel16;
    SLabel sLabel18;
    SLabel sLabel19;
    SLabel sLabel2;
    SLabel sLabel22;
    SLabel sLabel23;
    SLabel sLabel24;
    SLabel sLabel25;
    SLabel sLabel3;
    SLabel sLabel4;
    SLabel sLabel5;
    SLabel sLabel6;
    SLabel sLabel7;
    SLabel sLabel8;
    SLabel sLabel9;
    SComboBox tiposComEscalaMercante;
    SComboBox tiposComManisfestos;
    SComboBox tiposComManisfestos1;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
