package br.com.petrobras.sistam.desktop.relatorio;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SNumericTextField;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.sistam.desktop.components.JMesPanel;
import br.com.petrobras.sistam.desktop.components.TimeZoneComboBox;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

public class RelatorioAgenciamentoAtendimentoDialog extends SDialog {
    private RelatorioAgenciamentoAtendimentoModel model = new RelatorioAgenciamentoAtendimentoModel();;
    

    public RelatorioAgenciamentoAtendimentoDialog(java.awt.Frame parent, boolean modal) {        
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    public RelatorioAgenciamentoAtendimentoModel getModel() {
        return model;
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        GenericAction actionImprimir = new GenericAction();
        SPanel pnlCentral = new SPanel();
        SPanel pnlBotoes = new SPanel();
        SButton botalImprimir = new SButton();
        SPanel pnlFiltro = new SPanel();
        SLabel lblAgencia = new SLabel();
        comboAgencias = new SComboBox();
        SLabel sLabel1 = new SLabel();
        SLabel sLabel5 = new SLabel();
        comboFuso = new TimeZoneComboBox();
        SLabel lblTipoContrato = new SLabel();
        SComboBox comboTipoContrato = new SComboBox();
        SLabel sLabel7 = new SLabel();
        SLabel lblCiclo = new SLabel();
        SNumericTextField txtCiclo = new SNumericTextField();
        SLabel lblDias = new SLabel();
        JMesPanel sistamMesAnoFinal = new JMesPanel();
        JMesPanel sistamMesAnoFinal1 = new JMesPanel();
        SLabel sLabel3 = new SLabel();
        SComboBox comboPortos = new SComboBox();

        actionImprimir.setComponentToRepaint(botalImprimir);
        actionImprimir.setIcon(new ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        actionImprimir.setMethodName("imprimir");
        actionImprimir.setTarget(model);
        actionImprimir.setText("Imprimir");
        actionImprimir.setToolTipText("Imprime o relatório de produtividade por agência");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Atendimento de Embarcação");
        setIconImage(null);

        pnlCentral.setName("pnlCentral"); // NOI18N

        pnlBotoes.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        pnlBotoes.setName("pnlBotoes"); // NOI18N
        pnlBotoes.setPreferredSize(new Dimension(14, 40));

        botalImprimir.setAction(actionImprimir);
        botalImprimir.setName("botalImprimir"); // NOI18N
        pnlBotoes.add(botalImprimir);

        pnlFiltro.setBorder(BorderFactory.createTitledBorder("Filtro para o Relatório"));
        pnlFiltro.setName("pnlFiltro"); // NOI18N

        ResourceBundle bundle = ResourceBundle.getBundle("sistam-labels"); // NOI18N
        lblAgencia.setText(bundle.getString("lblAgencia")); // NOI18N
        lblAgencia.setName("lblAgencia"); // NOI18N

        comboAgencias.setName("comboAgencias"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.agencias}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE, this, eLProperty, comboAgencias);
        bindingGroup.addBinding(jComboBoxBinding);
        Binding binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.agencia}"), comboAgencias, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        sLabel1.setText("Período:");
        sLabel1.setName("sLabel1"); // NOI18N

        sLabel5.setText(bundle.getString("fusoHorario")); // NOI18N
        sLabel5.setName("sLabel5"); // NOI18N

        comboFuso.setEnabled(false);
        comboFuso.setName("comboFuso"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.timeZone}"), comboFuso, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        lblTipoContrato.setText("Tipo de Contrato:");
        lblTipoContrato.setName("lblTipoContrato"); // NOI18N

        comboTipoContrato.setName("comboTipoContrato"); // NOI18N

        eLProperty = ELProperty.create("${model.tipoContrato}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE, this, eLProperty, comboTipoContrato);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.tipoContrato}"), comboTipoContrato, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        sLabel7.setText("até");
        sLabel7.setName("sLabel7"); // NOI18N

        lblCiclo.setText("Ciclo:");
        lblCiclo.setToolTipText("");
        lblCiclo.setName("lblCiclo"); // NOI18N

        txtCiclo.setDecimalPlaces(new Short((short)0));
        txtCiclo.setIntegerPlaces(new Short((short)2));
        txtCiclo.setText("sNumericTextField1");
        txtCiclo.setUseGroupDigit(false);
        txtCiclo.setName("txtCiclo"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.qtdeDiasAtendimento}"), txtCiclo, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        lblDias.setText("dias");
        lblDias.setToolTipText("");
        lblDias.setName("lblDias"); // NOI18N

        sistamMesAnoFinal.setName("sistamMesAnoFinal"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.dataFinal}"), sistamMesAnoFinal, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sistamMesAnoFinal1.setName("sistamMesAnoFinal1"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.dataInicial}"), sistamMesAnoFinal1, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel3.setText(bundle.getString("lblPorto")); // NOI18N
        sLabel3.setName("sLabel3"); // NOI18N

        comboPortos.setName("comboPortos"); // NOI18N

        eLProperty = ELProperty.create("${model.portos}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE, this, eLProperty, comboPortos);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.porto}"), comboPortos, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        GroupLayout pnlFiltroLayout = new GroupLayout(pnlFiltro);
        pnlFiltro.setLayout(pnlFiltroLayout);
        pnlFiltroLayout.setHorizontalGroup(
            pnlFiltroLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlFiltroLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlFiltroLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(lblAgencia, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel3, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel5, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel1, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoContrato, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCiclo, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(pnlFiltroLayout.createParallelGroup(Alignment.LEADING)
                    .addGroup(pnlFiltroLayout.createSequentialGroup()
                        .addGroup(pnlFiltroLayout.createParallelGroup(Alignment.TRAILING)
                            .addComponent(comboAgencias, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboFuso, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(comboPortos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                    .addGroup(pnlFiltroLayout.createSequentialGroup()
                        .addGroup(pnlFiltroLayout.createParallelGroup(Alignment.LEADING)
                            .addGroup(pnlFiltroLayout.createSequentialGroup()
                                .addComponent(sistamMesAnoFinal1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(sLabel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                .addComponent(sistamMesAnoFinal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboTipoContrato, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFiltroLayout.createSequentialGroup()
                                .addComponent(txtCiclo, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(lblDias, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlFiltroLayout.setVerticalGroup(
            pnlFiltroLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlFiltroLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlFiltroLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(lblAgencia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAgencias, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(pnlFiltroLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPortos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(pnlFiltroLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(sLabel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFuso, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(pnlFiltroLayout.createParallelGroup(Alignment.CENTER)
                    .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sistamMesAnoFinal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sistamMesAnoFinal1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(pnlFiltroLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(lblTipoContrato, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipoContrato, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(pnlFiltroLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(lblCiclo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCiclo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDias, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout pnlCentralLayout = new GroupLayout(pnlCentral);
        pnlCentral.setLayout(pnlCentralLayout);
        pnlCentralLayout.setHorizontalGroup(
            pnlCentralLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCentralLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(pnlBotoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addComponent(pnlFiltro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCentralLayout.setVerticalGroup(
            pnlCentralLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFiltro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlCentral, BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    SComboBox comboAgencias;
    TimeZoneComboBox comboFuso;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
