package br.com.petrobras.sistam.desktop.agenciamento.protecao;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SNumericTextField;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STextArea;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.renderers.ImageBooleanRenderer;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Servico;
import br.com.petrobras.sistam.common.entity.ServicoRetiradaResiduoLixo;
import br.com.petrobras.sistam.common.entity.ServicoSuprimentoTransito;
import br.com.petrobras.sistam.common.entity.ServicoSuprimento;
import br.com.petrobras.sistam.common.enums.TipoCategoria;
import br.com.petrobras.sistam.common.enums.TipoResiduo;
import br.com.petrobras.sistam.common.enums.TipoUnidadeMedida;
import br.com.petrobras.sistam.common.util.ConstantesI18N;
import br.com.petrobras.sistam.desktop.components.SistamDateChooser;
import br.com.petrobras.sistam.desktop.components.SistamTimeChooser;
import br.com.petrobras.sistam.desktop.util.DesktopUtil;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.math.BigDecimal;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

public class DetalheServicoProtecaoRetiradaResiduoLixoDialog extends SDialog implements PropertyChangeListener{

    private DetalheServicoProtecaoRetiradaResiduoLixoModel model;

    public DetalheServicoProtecaoRetiradaResiduoLixoDialog(java.awt.Frame parent, ServicoRetiradaResiduoLixo servicoRetiradaResiduoLixo, boolean editar, boolean consultar) {
        super(parent, true);
        model = new DetalheServicoProtecaoRetiradaResiduoLixoModel(servicoRetiradaResiduoLixo, editar, consultar);
        model.setDialog(this);
        
        initComponents();
        setLocationRelativeTo(parent); 

        if (!editar) {
            DesktopUtil.habilitarComponentes(editar, this.pnlSuprimentoAoNavio);
        }
    }
    
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public DetalheServicoProtecaoRetiradaResiduoLixoModel getModel() {
        return model;
    }  

    public void salvar() {
        model.salvar();
        dispose();
    }
    
    
    
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"})
    @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        GenericAction actionSalvar = new GenericAction();
        pnlSuprimentoAoNavio = new SPanel();
        SPanel pnlBotoes = new SPanel();
        SButton btnSalvar = new SButton();
        SPanel pnlSuprimentosAosNavios = new SPanel();
        labelAgente = new SLabel();
        txtServicoExecutado = new STextField();
        lblDatasolicitacao = new SLabel();
        sistamDateChooserServicoExecutado = new SistamDateChooser();
        SistamDateChooser sistamDateChooserInicio = new SistamDateChooser();
        SistamTimeChooser sistamTimeChooserInicio = new SistamTimeChooser();
        labelAgente1 = new SLabel();
        labelAgente2 = new SLabel();
        SistamDateChooser sistamDateChooserTermino = new SistamDateChooser();
        SistamTimeChooser sistamTimeChooserTermino = new SistamTimeChooser();
        SPanel pnlCustoDaOperacao = new SPanel();
        labelAgente6 = new SLabel();
        txtLocal = new STextField();
        labelAgente7 = new SLabel();
        STextField txtLON = new STextField();
        labelAgente8 = new SLabel();
        txtCadri = new STextField();
        cboServico = new SComboBox();
        labelEmbarcacaoTransbordo = new SLabel();
        labelEmpresaRespTransbordo = new SLabel();
        cboEmpresa = new SComboBox();
        labelAgente4 = new SLabel();
        JScrollPane jScrollPane1 = new JScrollPane();
        STextArea sTextArea1 = new STextArea();
        lbEMpresaRequeridas = new SLabel();
        cboEmpresaRequerida = new SComboBox();
        labelTranspRodoviaria = new SLabel();
        cboTranspRodoviaria = new SComboBox();
        labelTipoResiduo = new SLabel();
        cboTipoResiduo = new SComboBox();
        labelCaracteristica = new SLabel();
        txtCaracterizacao = new STextField();
        labelEstadoFisico = new SLabel();
        txtEstadoFisico = new STextField();
        labelCodigoAbnt = new SLabel();
        txtCodigoABNT = new STextField();
        labelCodigoONU = new SLabel();
        txtCodigoONU = new STextField();
        labelQtdResiduos = new SLabel();
        sntfQtdResiduos = new SNumericTextField();
        labelUndMedida = new SLabel();
        cboUndMedida = new SComboBox();
        SPanel pnlCustoDaOperacao1 = new SPanel();
        labelAgente9 = new SLabel();
        txtLocalFinal = new STextField();
        labelAgente10 = new SLabel();
        txtLONFinal = new STextField();
        labelAgente11 = new SLabel();
        txtCadriFinal = new STextField();
        labelEmpresa9 = new SLabel();
        sntfValorServico = new SNumericTextField();

        actionSalvar.setIcon(new ImageIcon(getClass().getResource("/icons/disk.png"))); // NOI18N
        actionSalvar.setMethodName("salvar");
        actionSalvar.setTarget(this);
        actionSalvar.setText("Salvar");
        actionSalvar.setToolTipText("Salva as informações do serviço de proteção");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Serviço de Proteção");

        pnlSuprimentoAoNavio.setMaximumSize(new Dimension(2147483647, 2147483647));
        pnlSuprimentoAoNavio.setName("pnlSuprimentoAoNavio"); // NOI18N
        pnlSuprimentoAoNavio.setPreferredSize(new Dimension(970, 740));

        pnlBotoes.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        pnlBotoes.setName("pnlBotoes"); // NOI18N

        btnSalvar.setAction(actionSalvar);
        btnSalvar.setName("btnSalvar"); // NOI18N
        pnlBotoes.add(btnSalvar);

        pnlSuprimentosAosNavios.setBorder(BorderFactory.createTitledBorder(""));
        pnlSuprimentosAosNavios.setName("pnlSuprimentosAosNavios"); // NOI18N
        pnlSuprimentosAosNavios.setPreferredSize(new Dimension(840, 790));

        labelAgente.setText("Serviço Executado:");
        labelAgente.setName("labelAgente"); // NOI18N

        txtServicoExecutado.setEnabled(false);
        txtServicoExecutado.setName("txtServicoExecutado"); // NOI18N

        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoExecutado}"), txtServicoExecutado, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblDatasolicitacao.setText("Data da Solicitação:");
        lblDatasolicitacao.setName("lblDatasolicitacao"); // NOI18N

        sistamDateChooserServicoExecutado.setName("sistamDateChooserServicoExecutado"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.servicoProtecao.dataExecucao}"), sistamDateChooserServicoExecutado, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sistamDateChooserInicio.setName("sistamDateChooserInicio"); // NOI18N
        sistamDateChooserInicio.setTimeChooser(sistamTimeChooserInicio);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.dataInicioOperacao}"), sistamDateChooserInicio, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sistamTimeChooserInicio.setName("sistamTimeChooserInicio"); // NOI18N
        sistamTimeChooserInicio.setTimeZone(model.getTimeZone());

        labelAgente1.setText("Data/Hora Início da Operação:");
        labelAgente1.setName("labelAgente1"); // NOI18N

        labelAgente2.setText("Data/Hora Término da Operação:");
        labelAgente2.setName("labelAgente2"); // NOI18N

        sistamDateChooserTermino.setName("sistamDateChooserTermino"); // NOI18N
        sistamDateChooserTermino.setTimeChooser(sistamTimeChooserTermino);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.dataFimOperacao}"), sistamDateChooserTermino, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sistamTimeChooserTermino.setName("sistamTimeChooserTermino"); // NOI18N
        sistamTimeChooserTermino.setTimeZone(model.getTimeZone());

        pnlCustoDaOperacao.setBorder(BorderFactory.createTitledBorder("Local de Armazenagem Temporária dos Resíduos"));
        pnlCustoDaOperacao.setName("pnlCustoDaOperacao"); // NOI18N

        labelAgente6.setText("Local:");
        labelAgente6.setName("labelAgente6"); // NOI18N

        txtLocal.setDocument(new GenericDocument(100));
        txtLocal.setName("txtLocal"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.localArmazenagem}"), txtLocal, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        labelAgente7.setText("L.O Nº:");
        labelAgente7.setName("labelAgente7"); // NOI18N

        txtLON.setDocument(new GenericDocument(20));
        txtLON.setName("txtLON"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.lonArmazenagem}"), txtLON, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        labelAgente8.setText("CADRI:");
        labelAgente8.setName("labelAgente8"); // NOI18N

        txtCadri.setDocument(new GenericDocument(30));
        txtCadri.setName("txtCadri"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.descCadri}"), txtCadri, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        GroupLayout pnlCustoDaOperacaoLayout = new GroupLayout(pnlCustoDaOperacao);
        pnlCustoDaOperacao.setLayout(pnlCustoDaOperacaoLayout);
        pnlCustoDaOperacaoLayout.setHorizontalGroup(
            pnlCustoDaOperacaoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustoDaOperacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAgente6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLocal, GroupLayout.PREFERRED_SIZE, 259, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAgente7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLON, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAgente8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCadri, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCustoDaOperacaoLayout.setVerticalGroup(
            pnlCustoDaOperacaoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustoDaOperacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustoDaOperacaoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAgente6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAgente7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLON, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAgente8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadri, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cboServico.setDisplayProperty(Servico.PROP_NOME_SERVICO);
        cboServico.setName("cboServico"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.servicos}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cboServico);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.empresaServico}"), cboServico, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        labelEmbarcacaoTransbordo.setText("Embarcação Transbordo:");
        labelEmbarcacaoTransbordo.setName("labelEmbarcacaoTransbordo"); // NOI18N

        labelEmpresaRespTransbordo.setText("Empresa Resp. Transbordo:");
        labelEmpresaRespTransbordo.setName("labelEmpresaRespTransbordo"); // NOI18N

        cboEmpresa.setName("cboEmpresa"); // NOI18N
        cboEmpresa.setPopupResizeEnabled(true);

        eLProperty = ELProperty.create("${model.empresasMaritimas}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cboEmpresa);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.empresaMaritima}"), cboEmpresa, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        labelAgente4.setText("Observações:");
        labelAgente4.setName("labelAgente4"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        sTextArea1.setColumns(20);
        sTextArea1.setDocument(new GenericDocument(500));
        sTextArea1.setLineWrap(true);
        sTextArea1.setRows(5);
        sTextArea1.setName("sTextArea1"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.servicoProtecao.observacao}"), sTextArea1, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(sTextArea1);

        lbEMpresaRequeridas.setText("Empresa Requerente:");
        lbEMpresaRequeridas.setName("lbEMpresaRequeridas"); // NOI18N

        cboEmpresaRequerida.setName("cboEmpresaRequerida"); // NOI18N

        eLProperty = ELProperty.create("${model.listaResponsavelCustos}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cboEmpresaRequerida);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.responsavelCusto}"), cboEmpresaRequerida, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        labelTranspRodoviaria.setText("Transportadora Rodoviária:");
        labelTranspRodoviaria.setName("labelTranspRodoviaria"); // NOI18N

        cboTranspRodoviaria.setName("cboTranspRodoviaria"); // NOI18N
        cboTranspRodoviaria.setPopupResizeEnabled(true);

        eLProperty = ELProperty.create("${model.empresasMaritimasRodoviaria}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cboTranspRodoviaria);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.empresaMaritimaRodoviaria}"), cboTranspRodoviaria, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        labelTipoResiduo.setText("Tipo de Resíduo:");
        labelTipoResiduo.setName("labelTipoResiduo"); // NOI18N

        cboTipoResiduo.setName("cboTipoResiduo"); // NOI18N
        cboTipoResiduo.setPopupResizeEnabled(true);

        eLProperty = ELProperty.create("${model.listaTipoResiduos}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cboTipoResiduo);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.tipoResiduo}"), cboTipoResiduo, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        labelCaracteristica.setText("Caracterização:");
        labelCaracteristica.setName("labelCaracteristica"); // NOI18N

        txtCaracterizacao.setDocument(new GenericDocument(45));
        txtCaracterizacao.setName("txtCaracterizacao"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.caracterizacao}"), txtCaracterizacao, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        labelEstadoFisico.setText("Estado Físico:");
        labelEstadoFisico.setName("labelEstadoFisico"); // NOI18N

        txtEstadoFisico.setDocument(new GenericDocument(12));
        txtEstadoFisico.setName("txtEstadoFisico"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.estadoFisico}"), txtEstadoFisico, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        labelCodigoAbnt.setText("Classif. Código (ABNT NBR 10.004):");
        labelCodigoAbnt.setName("labelCodigoAbnt"); // NOI18N

        txtCodigoABNT.setDocument(new GenericDocument(25));
        txtCodigoABNT.setName("txtCodigoABNT"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.classificacao}"), txtCodigoABNT, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        labelCodigoONU.setText("Código ONU:");
        labelCodigoONU.setName("labelCodigoONU"); // NOI18N

        txtCodigoONU.setDocument(new GenericDocument(10));
        txtCodigoONU.setName("txtCodigoONU"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.codigoOnu}"), txtCodigoONU, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        labelQtdResiduos.setText("Quantidade de Resíduos:");
        labelQtdResiduos.setName("labelQtdResiduos"); // NOI18N

        sntfQtdResiduos.setIntegerPlaces(new Short((short)8));
        sntfQtdResiduos.setName("sntfQtdResiduos"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.quantidadeResiduo}"), sntfQtdResiduos, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        labelUndMedida.setText("Unidade de Medida:");
        labelUndMedida.setName("labelUndMedida"); // NOI18N

        cboUndMedida.setName("cboUndMedida"); // NOI18N
        cboUndMedida.setPopupResizeEnabled(true);

        eLProperty = ELProperty.create("${model.listaTipoUnidadeMedidas}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cboUndMedida);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.tipoUnidadeMedida}"), cboUndMedida, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        pnlCustoDaOperacao1.setBorder(BorderFactory.createTitledBorder("Destino Final do Resíduo"));
        pnlCustoDaOperacao1.setName("pnlCustoDaOperacao1"); // NOI18N

        labelAgente9.setText("Local:");
        labelAgente9.setName("labelAgente9"); // NOI18N

        txtLocalFinal.setDocument(new GenericDocument(100));
        txtLocalFinal.setName("txtLocalFinal"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.localDestinoFinal}"), txtLocalFinal, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        labelAgente10.setText("L.O Nº:");
        labelAgente10.setName("labelAgente10"); // NOI18N

        txtLONFinal.setDocument(new GenericDocument(20));
        txtLONFinal.setToolTipText("");
        txtLONFinal.setName("txtLONFinal"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.lonDestinoFinal}"), txtLONFinal, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        labelAgente11.setText("CADRI:");
        labelAgente11.setName("labelAgente11"); // NOI18N

        txtCadriFinal.setDocument(new GenericDocument(20));
        txtCadriFinal.setName("txtCadriFinal"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.cadriDestinoFinal}"), txtCadriFinal, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        GroupLayout pnlCustoDaOperacao1Layout = new GroupLayout(pnlCustoDaOperacao1);
        pnlCustoDaOperacao1.setLayout(pnlCustoDaOperacao1Layout);
        pnlCustoDaOperacao1Layout.setHorizontalGroup(
            pnlCustoDaOperacao1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustoDaOperacao1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAgente9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLocalFinal, GroupLayout.PREFERRED_SIZE, 259, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAgente10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLONFinal, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAgente11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCadriFinal, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCustoDaOperacao1Layout.setVerticalGroup(
            pnlCustoDaOperacao1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustoDaOperacao1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustoDaOperacao1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAgente9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocalFinal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAgente10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLONFinal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAgente11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadriFinal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelEmpresa9.setText("Valor do Serviço:");
        labelEmpresa9.setName("labelEmpresa9"); // NOI18N

        sntfValorServico.setIntegerPlaces(new Short((short)8));
        sntfValorServico.setNumberClass(BigDecimal.class);
        sntfValorServico.setText("sNumericTextField2");
        sntfValorServico.setName("sntfValorServico"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.servicoRetiradaResiduoLixo.valorServico}"), sntfValorServico, BeanProperty.create("bigDecimalValue"));
        bindingGroup.addBinding(binding);

        GroupLayout pnlSuprimentosAosNaviosLayout = new GroupLayout(pnlSuprimentosAosNavios);
        pnlSuprimentosAosNavios.setLayout(pnlSuprimentosAosNaviosLayout);
        pnlSuprimentosAosNaviosLayout.setHorizontalGroup(
            pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuprimentosAosNaviosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSuprimentosAosNaviosLayout.createSequentialGroup()
                        .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(labelEmpresa9, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAgente4, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSuprimentosAosNaviosLayout.createSequentialGroup()
                                .addComponent(sntfValorServico, GroupLayout.PREFERRED_SIZE, 165, GroupLayout.PREFERRED_SIZE)
                                .addGap(476, 516, Short.MAX_VALUE))
                            .addGroup(pnlSuprimentosAosNaviosLayout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addContainerGap())))
                    .addGroup(pnlSuprimentosAosNaviosLayout.createSequentialGroup()
                        .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSuprimentosAosNaviosLayout.createSequentialGroup()
                                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAgente, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEMpresaRequeridas, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEmpresaRespTransbordo, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEmbarcacaoTransbordo, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTranspRodoviaria, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTipoResiduo, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCaracteristica, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEstadoFisico, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCodigoAbnt, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCodigoONU, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelUndMedida, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelQtdResiduos, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlSuprimentosAosNaviosLayout.createSequentialGroup()
                                        .addComponent(sntfQtdResiduos, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cboTipoResiduo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboTranspRodoviaria, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(GroupLayout.Alignment.TRAILING, pnlSuprimentosAosNaviosLayout.createSequentialGroup()
                                        .addComponent(txtServicoExecutado, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDatasolicitacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sistamDateChooserServicoExecutado, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cboServico, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboEmpresa, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboEmpresaRequerida, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCaracterizacao, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEstadoFisico, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCodigoABNT, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCodigoONU, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboUndMedida, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(pnlCustoDaOperacao1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCustoDaOperacao, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlSuprimentosAosNaviosLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(labelAgente1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sistamDateChooserInicio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sistamTimeChooserInicio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelAgente2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sistamDateChooserTermino, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sistamTimeChooserTermino, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        pnlSuprimentosAosNaviosLayout.setVerticalGroup(
            pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuprimentosAosNaviosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAgente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServicoExecutado, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sistamDateChooserServicoExecutado, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatasolicitacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEMpresaRequeridas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEmpresaRequerida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmpresaRespTransbordo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEmpresa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmbarcacaoTransbordo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboServico, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTranspRodoviaria, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTranspRodoviaria, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoResiduo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipoResiduo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(labelCaracteristica, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaracterizacao, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(labelEstadoFisico, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoFisico, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(labelCodigoAbnt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoABNT, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigoONU, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoONU, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cboUndMedida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUndMedida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQtdResiduos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sntfQtdResiduos, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAgente1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sistamTimeChooserInicio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sistamTimeChooserTermino, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sistamDateChooserTermino, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAgente2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sistamDateChooserInicio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCustoDaOperacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCustoDaOperacao1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmpresa9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sntfValorServico, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSuprimentosAosNaviosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(labelAgente4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlSuprimentosAosNaviosLayout.linkSize(SwingConstants.VERTICAL, new Component[] {labelAgente, labelAgente1, labelCaracteristica, labelCodigoAbnt, labelCodigoONU, labelEmbarcacaoTransbordo, labelEmpresaRespTransbordo, labelEstadoFisico, labelQtdResiduos, labelTipoResiduo, labelTranspRodoviaria, labelUndMedida, lbEMpresaRequeridas});

        pnlSuprimentosAosNaviosLayout.linkSize(SwingConstants.VERTICAL, new Component[] {cboEmpresa, cboEmpresaRequerida, cboServico, cboTipoResiduo, cboTranspRodoviaria, cboUndMedida, sistamDateChooserInicio, sntfQtdResiduos, txtCaracterizacao, txtCodigoABNT, txtCodigoONU, txtEstadoFisico, txtServicoExecutado});

        GroupLayout pnlSuprimentoAoNavioLayout = new GroupLayout(pnlSuprimentoAoNavio);
        pnlSuprimentoAoNavio.setLayout(pnlSuprimentoAoNavioLayout);
        pnlSuprimentoAoNavioLayout.setHorizontalGroup(
            pnlSuprimentoAoNavioLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnlBotoes, GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(pnlSuprimentoAoNavioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSuprimentosAosNavios, GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSuprimentoAoNavioLayout.setVerticalGroup(
            pnlSuprimentoAoNavioLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuprimentoAoNavioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSuprimentosAosNavios, GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotoes, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlSuprimentoAoNavio, BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON
    // Variables declaration - do not modify//GEN-BEGIN:variables
    SComboBox cboEmpresa;
    SComboBox cboEmpresaRequerida;
    SComboBox cboServico;
    SComboBox cboTipoResiduo;
    SComboBox cboTranspRodoviaria;
    SComboBox cboUndMedida;
    SLabel labelAgente;
    SLabel labelAgente1;
    SLabel labelAgente10;
    SLabel labelAgente11;
    SLabel labelAgente2;
    SLabel labelAgente4;
    SLabel labelAgente6;
    SLabel labelAgente7;
    SLabel labelAgente8;
    SLabel labelAgente9;
    SLabel labelCaracteristica;
    SLabel labelCodigoAbnt;
    SLabel labelCodigoONU;
    SLabel labelEmbarcacaoTransbordo;
    SLabel labelEmpresa9;
    SLabel labelEmpresaRespTransbordo;
    SLabel labelEstadoFisico;
    SLabel labelQtdResiduos;
    SLabel labelTipoResiduo;
    SLabel labelTranspRodoviaria;
    SLabel labelUndMedida;
    SLabel lbEMpresaRequeridas;
    SLabel lblDatasolicitacao;
    SPanel pnlSuprimentoAoNavio;
    SistamDateChooser sistamDateChooserServicoExecutado;
    SNumericTextField sntfQtdResiduos;
    SNumericTextField sntfValorServico;
    STextField txtCadri;
    STextField txtCadriFinal;
    STextField txtCaracterizacao;
    STextField txtCodigoABNT;
    STextField txtCodigoONU;
    STextField txtEstadoFisico;
    STextField txtLONFinal;
    STextField txtLocal;
    STextField txtLocalFinal;
    STextField txtServicoExecutado;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

   
}
