package br.com.petrobras.sistam.desktop.agencia;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SFormattedTextField;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STextArea;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.dialog.DialogMessages;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Agencia;
import br.com.petrobras.sistam.desktop.components.TimeZoneComboBox;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;

public class DetalheAgenciaDialog extends SDialog {
    private DetalheAgenciaModel model;
    
    public DetalheAgenciaDialog(java.awt.Frame parent, Agencia agencia) {
        super(parent, true);
        this.model = new DetalheAgenciaModel(agencia);
        initComponents();
        setLocationRelativeTo(parent);
        
        campoCNPJ.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                actionSalvar.setEnabled(false);
            }
            
            @Override
            public void focusLost(FocusEvent e){
                actionSalvar.setEnabled(true);
            }
        });
        
        
        campoCNPJ.setTemplate(SFormattedTextField.Template.CNPJ);
        GenericAction actionErroCnpj = new GenericAction();
        actionErroCnpj.setMethodName("erroCnpj");
        actionErroCnpj.setTarget(this);        
        campoCNPJ.getActionMap().put("postTip", actionErroCnpj);
        campoTimeZone.setSelectedItem(agencia.obterTimezone());
        
        txtSigla.setEnabled(agencia.getId()!= null ? false : true);
        campoTimeZone.setEnabled(agencia.getId()!= null ? false : true);
        
    }
    
    public void erroCnpj() {
        DialogMessages.error(this, "Cnpj inválido.");
    }

    public DetalheAgenciaModel getModel() {
        return model;
    }
    
    public void salvar() {
        model.salvar();
        dispose();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        actionSalvar = new GenericAction();
        SPanel painelBotoes = new SPanel();
        SButton botaoSalvar = new SButton();
        SPanel pnlIdentificacao = new SPanel();
        SLabel sLabel13 = new SLabel();
        lblBandeira = new SLabel();
        STextField sTextField3 = new STextField();
        SLabel sLabel9 = new SLabel();
        txtSigla = new STextField();
        campoCNPJ = new SFormattedTextField();
        SPanel pnlLocalizacao = new SPanel();
        SLabel sLabel16 = new SLabel();
        SLabel sLabel15 = new SLabel();
        SLabel sLabel11 = new SLabel();
        SLabel sLabel12 = new SLabel();
        SLabel sLabel3 = new SLabel();
        STextField sTextField6 = new STextField();
        STextField sTextField7 = new STextField();
        STextField sTextField8 = new STextField();
        JScrollPane jScrollPane1 = new JScrollPane();
        STextArea sTextArea1 = new STextArea();
        SLabel sLabel1 = new SLabel();
        campoTimeZone = new TimeZoneComboBox();
        STextField sTextField11 = new STextField();
        SPanel pnlContato = new SPanel();
        SLabel sLabel18 = new SLabel();
        SLabel sLabel19 = new SLabel();
        SLabel sLabel4 = new SLabel();
        STextField sTextField9 = new STextField();
        STextField sTextField10 = new STextField();
        STextField sTextField12 = new STextField();
        SPanel sPanel1 = new SPanel();
        SLabel sLabel2 = new SLabel();
        STextField sTextField5 = new STextField();

        actionSalvar.setIcon(new ImageIcon(getClass().getResource("/icons/disk.png"))); // NOI18N
        actionSalvar.setMethodName("salvar");
        actionSalvar.setTarget(this);
        actionSalvar.setText("Salvar");
        actionSalvar.setToolTipText("Salva as alterações");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dados da Agência");

        painelBotoes.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        painelBotoes.setName("painelBotoes"); // NOI18N

        botaoSalvar.setAction(actionSalvar);
        botaoSalvar.setName("botaoSalvar"); // NOI18N
        painelBotoes.add(botaoSalvar);

        pnlIdentificacao.setBorder(BorderFactory.createTitledBorder("Identificação"));
        pnlIdentificacao.setName("pnlIdentificacao"); // NOI18N

        ResourceBundle bundle = ResourceBundle.getBundle("sistam-labels"); // NOI18N
        sLabel13.setText(bundle.getString("lblnomeEmbarcacao")); // NOI18N
        sLabel13.setName("sLabel13"); // NOI18N

        lblBandeira.setText("CNPJ:");
        lblBandeira.setName("lblBandeira"); // NOI18N

        sTextField3.setDocument(new GenericDocument(50, 
            GenericDocument.OPTION_APPLY_UPPERCASE ));
    sTextField3.setName("sTextField3"); // NOI18N

        Binding binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agencia.nome}"), sTextField3, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    sLabel9.setText("Sigla:");
    sLabel9.setName("sLabel9"); // NOI18N

    txtSigla.setDocument(new GenericDocument(3, 
        GenericDocument.OPTION_APPLY_UPPERCASE ));
txtSigla.setEnabled(false);
txtSigla.setName("txtSigla"); // NOI18N

binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agencia.sigla}"), txtSigla, BeanProperty.create("text"));
bindingGroup.addBinding(binding);

campoCNPJ.setName("campoCNPJ"); // NOI18N

binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agencia.cnpjComMascara}"), campoCNPJ, BeanProperty.create("value"));
bindingGroup.addBinding(binding);

        GroupLayout pnlIdentificacaoLayout = new GroupLayout(pnlIdentificacao);
pnlIdentificacao.setLayout(pnlIdentificacaoLayout);
pnlIdentificacaoLayout.setHorizontalGroup(
    pnlIdentificacaoLayout.createParallelGroup(Alignment.LEADING)
    .addGroup(pnlIdentificacaoLayout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addComponent(sLabel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(ComponentPlacement.RELATED)
        .addComponent(sTextField3, GroupLayout.PREFERRED_SIZE, 206, GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(ComponentPlacement.RELATED)
        .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(ComponentPlacement.RELATED)
        .addComponent(txtSigla, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(ComponentPlacement.RELATED)
        .addComponent(lblBandeira, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(ComponentPlacement.RELATED)
        .addComponent(campoCNPJ, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    pnlIdentificacaoLayout.setVerticalGroup(
        pnlIdentificacaoLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(pnlIdentificacaoLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlIdentificacaoLayout.createParallelGroup(Alignment.LEADING)
                .addGroup(pnlIdentificacaoLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(sLabel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlIdentificacaoLayout.createParallelGroup(Alignment.CENTER)
                    .addComponent(txtSigla, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBandeira, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCNPJ, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnlLocalizacao.setBorder(BorderFactory.createTitledBorder("Localização"));
    pnlLocalizacao.setName("pnlLocalizacao"); // NOI18N

    sLabel16.setText("Estado:");
    sLabel16.setName("sLabel16"); // NOI18N

    sLabel15.setText("Endereço:");
    sLabel15.setName("sLabel15"); // NOI18N

    sLabel11.setText("CEP:");
    sLabel11.setName("sLabel11"); // NOI18N

    sLabel12.setText("Bairro:");
    sLabel12.setName("sLabel12"); // NOI18N

    sLabel3.setText("Cidade:");
    sLabel3.setName("sLabel3"); // NOI18N

    sTextField6.setDocument(new GenericDocument(100, 
        GenericDocument.OPTION_APPLY_UPPERCASE ));
sTextField6.setName("sTextField6"); // NOI18N

binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agencia.cidade}"), sTextField6, BeanProperty.create("text"));
bindingGroup.addBinding(binding);

sTextField7.setDocument(new GenericDocument(60, 
    GenericDocument.OPTION_APPLY_UPPERCASE ));
    sTextField7.setName("sTextField7"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agencia.bairro}"), sTextField7, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    sTextField8.setDocument(new GenericDocument(2, 
        GenericDocument.OPTION_APPLY_UPPERCASE ));
sTextField8.setName("sTextField8"); // NOI18N

binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agencia.estado}"), sTextField8, BeanProperty.create("text"));
bindingGroup.addBinding(binding);

jScrollPane1.setName("jScrollPane1"); // NOI18N

sTextArea1.setColumns(20);
sTextArea1.setDocument(new GenericDocument(500));
sTextArea1.setRows(3);
sTextArea1.setName("sTextArea1"); // NOI18N

binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agencia.endereco}"), sTextArea1, BeanProperty.create("text"));
bindingGroup.addBinding(binding);

jScrollPane1.setViewportView(sTextArea1);

sLabel1.setText("Fuso Horário:");
sLabel1.setName("sLabel1"); // NOI18N

campoTimeZone.setEnabled(false);
campoTimeZone.setName("campoTimeZone"); // NOI18N

binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.timeZoneSelecionado}"), campoTimeZone, BeanProperty.create("selectedItem"));
bindingGroup.addBinding(binding);

sTextField11.setDocument(new GenericDocument(9, GenericDocument.OPTION_APPLY_UPPERCASE ));
sTextField11.setName("sTextField11"); // NOI18N

binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agencia.cep}"), sTextField11, BeanProperty.create("text"));
bindingGroup.addBinding(binding);

        GroupLayout pnlLocalizacaoLayout = new GroupLayout(pnlLocalizacao);
pnlLocalizacao.setLayout(pnlLocalizacaoLayout);
pnlLocalizacaoLayout.setHorizontalGroup(
    pnlLocalizacaoLayout.createParallelGroup(Alignment.LEADING)
    .addGroup(pnlLocalizacaoLayout.createSequentialGroup()
        .addGap(6, 6, 6)
        .addGroup(pnlLocalizacaoLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(sLabel12, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addComponent(sLabel3, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addComponent(sLabel16, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addComponent(sLabel15, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(ComponentPlacement.RELATED)
        .addGroup(pnlLocalizacaoLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(sTextField7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(pnlLocalizacaoLayout.createSequentialGroup()
                .addComponent(sTextField8, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(sLabel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(sTextField11, GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(campoTimeZone, GroupLayout.PREFERRED_SIZE, 214, GroupLayout.PREFERRED_SIZE))
            .addComponent(sTextField6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    pnlLocalizacaoLayout.setVerticalGroup(
        pnlLocalizacaoLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(pnlLocalizacaoLayout.createSequentialGroup()
            .addGroup(pnlLocalizacaoLayout.createParallelGroup(Alignment.LEADING)
                .addComponent(sLabel15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(pnlLocalizacaoLayout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(pnlLocalizacaoLayout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLocalizacaoLayout.createParallelGroup(Alignment.CENTER)
                .addComponent(sLabel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlLocalizacaoLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(sLabel16, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTextField8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(campoTimeZone, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    pnlContato.setBorder(BorderFactory.createTitledBorder("Contato"));
    pnlContato.setName("pnlContato"); // NOI18N

    sLabel18.setText("E-mail:");
    sLabel18.setName("sLabel18"); // NOI18N

    sLabel19.setText("Telefone(s):");
    sLabel19.setName("sLabel19"); // NOI18N

    sLabel4.setText("Fax:");
    sLabel4.setName("sLabel4"); // NOI18N

    sTextField9.setDocument(new GenericDocument(60, 
        GenericDocument.OPTION_APPLY_UPPERCASE ));
sTextField9.setName("sTextField9"); // NOI18N

binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agencia.email}"), sTextField9, BeanProperty.create("text"));
bindingGroup.addBinding(binding);

sTextField10.setDocument(new GenericDocument(60, 
    GenericDocument.OPTION_APPLY_UPPERCASE ));
    sTextField10.setName("sTextField10"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agencia.telefone}"), sTextField10, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    sTextField12.setDocument(new GenericDocument(60, 
        GenericDocument.OPTION_APPLY_UPPERCASE ));
sTextField12.setName("sTextField12"); // NOI18N

binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agencia.fax}"), sTextField12, BeanProperty.create("text"));
bindingGroup.addBinding(binding);

        GroupLayout pnlContatoLayout = new GroupLayout(pnlContato);
pnlContato.setLayout(pnlContatoLayout);
pnlContatoLayout.setHorizontalGroup(
    pnlContatoLayout.createParallelGroup(Alignment.LEADING)
    .addGroup(pnlContatoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlContatoLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(sLabel18, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addComponent(sLabel19, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(ComponentPlacement.RELATED)
        .addGroup(pnlContatoLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlContatoLayout.createSequentialGroup()
                .addComponent(sTextField9, GroupLayout.PREFERRED_SIZE, 264, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(sTextField12, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sTextField10, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    pnlContatoLayout.setVerticalGroup(
        pnlContatoLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(pnlContatoLayout.createSequentialGroup()
            .addGroup(pnlContatoLayout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel18, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.UNRELATED)
            .addGroup(pnlContatoLayout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel19, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    sPanel1.setBorder(BorderFactory.createTitledBorder("ANVISA"));
    sPanel1.setName("sPanel1"); // NOI18N

    sLabel2.setText("Nr. AFE:");
    sLabel2.setName("sLabel2"); // NOI18N

    sTextField5.setDocument(new GenericDocument(10));
    sTextField5.setName("sTextField5"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agencia.afe}"), sTextField5, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

        GroupLayout sPanel1Layout = new GroupLayout(sPanel1);
    sPanel1.setLayout(sPanel1Layout);
    sPanel1Layout.setHorizontalGroup(
        sPanel1Layout.createParallelGroup(Alignment.LEADING)
        .addGroup(sPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(sTextField5, GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
            .addGap(18, 18, 18))
    );
    sPanel1Layout.setVerticalGroup(
        sPanel1Layout.createParallelGroup(Alignment.LEADING)
        .addGroup(sPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(sPanel1Layout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

        GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(Alignment.LEADING)
        .addComponent(painelBotoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(Alignment.LEADING)
                .addComponent(pnlContato, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlLocalizacao, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlIdentificacao, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(sPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(pnlIdentificacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(pnlLocalizacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(pnlContato, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.UNRELATED)
            .addComponent(painelBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
    );

    bindingGroup.bind();

    pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    GenericAction actionSalvar;
    SFormattedTextField campoCNPJ;
    TimeZoneComboBox campoTimeZone;
    SLabel lblBandeira;
    STextField txtSigla;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
