package br.com.petrobras.sistam.desktop.agenciamento.documento;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STable;
import br.com.petrobras.sistam.common.entity.Operacao;
import br.com.petrobras.sistam.common.entity.Produto;
import br.com.petrobras.sistam.common.enums.FinalidadeManobra;
import br.com.petrobras.sistam.common.enums.StatusManobra;
import br.com.petrobras.sistam.common.enums.UnidadeMedida;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.JTableBinding.ColumnBinding;
import org.jdesktop.swingbinding.SwingBindings;

public class SelecionarOperacaoDialog extends SDialog {
    private SelecionarOperacaoModel model;
    
    public SelecionarOperacaoDialog(java.awt.Frame parent, List<Operacao> listaOperacao) {
        super(parent, true);
        model = new SelecionarOperacaoModel(listaOperacao);
        initComponents();        
        setLocationRelativeTo(parent);      
    }

    public SelecionarOperacaoModel getModel() {
        return model;
    }
    
    public void selecionar(){
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();
        GenericAction actionSelecionar = new GenericAction();
        SPanel pnlEscalas = new SPanel();
        SPanel pnlManobras = new SPanel();
        SPanel pnlListaManobras = new SPanel();
        JScrollPane jScrollPane8 = new JScrollPane();
        tabelaManobras = new STable();
        SPanel pnlBotoes = new SPanel();
        SButton sButton1 = new SButton();

        actionSelecionar.setIcon(new ImageIcon(getClass().getResource("/icons/accept.png"))); // NOI18N
        actionSelecionar.setMethodName("selecionar");
        actionSelecionar.setTarget(this);
        ResourceBundle bundle = ResourceBundle.getBundle("sistam-labels"); // NOI18N
        actionSelecionar.setText(bundle.getString("confirmar")); // NOI18N

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleção de Produto");

        pnlEscalas.setBorder(BorderFactory.createEtchedBorder());
        pnlEscalas.setName("pnlEscalas"); // NOI18N

        pnlManobras.setName("pnlManobras"); // NOI18N

        pnlListaManobras.setBorder(BorderFactory.createTitledBorder("Produtos de Carga Exportação"));
        pnlListaManobras.setName("pnlListaManobras"); // NOI18N

        jScrollPane8.setName("jScrollPane8"); // NOI18N

        tabelaManobras.setSortable(true);
        tabelaManobras.setName("tabelaManobras"); // NOI18N
        ELProperty eLProperty = ELProperty.create("${model.listaOperacoes}");
        JTableBinding jTableBinding = SwingBindings.createJTableBinding(UpdateStrategy.READ_WRITE, this, eLProperty, tabelaManobras);
        ColumnBinding columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${produto}"));
        columnBinding.setColumnName("Produto");
        columnBinding.setColumnClass(Produto.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${quantidadeFormatada}"));
        columnBinding.setColumnName("Qt. Estimada");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${unidadeMedida}"));
        columnBinding.setColumnName("Unidade de Medida");
        columnBinding.setColumnClass(UnidadeMedida.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();        Binding binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.operacaoSelecionada}"), tabelaManobras, BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane8.setViewportView(tabelaManobras);

        GroupLayout pnlListaManobrasLayout = new GroupLayout(pnlListaManobras);
        pnlListaManobras.setLayout(pnlListaManobrasLayout);
        pnlListaManobrasLayout.setHorizontalGroup(
            pnlListaManobrasLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlListaManobrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlListaManobrasLayout.setVerticalGroup(
            pnlListaManobrasLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, pnlListaManobrasLayout.createSequentialGroup()
                .addComponent(jScrollPane8, GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        GroupLayout pnlManobrasLayout = new GroupLayout(pnlManobras);
        pnlManobras.setLayout(pnlManobrasLayout);
        pnlManobrasLayout.setHorizontalGroup(
            pnlManobrasLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlManobrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlListaManobras, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlManobrasLayout.setVerticalGroup(
            pnlManobrasLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlManobrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlListaManobras, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBotoes.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        pnlBotoes.setName("pnlBotoes"); // NOI18N

        sButton1.setAction(actionSelecionar);
        sButton1.setName("sButton1"); // NOI18N
        pnlBotoes.add(sButton1);

        GroupLayout pnlEscalasLayout = new GroupLayout(pnlEscalas);
        pnlEscalas.setLayout(pnlEscalasLayout);
        pnlEscalasLayout.setHorizontalGroup(
            pnlEscalasLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(pnlManobras, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Alignment.TRAILING, pnlEscalasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBotoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlEscalasLayout.setVerticalGroup(
            pnlEscalasLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlEscalasLayout.createSequentialGroup()
                .addComponent(pnlManobras, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(pnlBotoes, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlEscalas, BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    STable tabelaManobras;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
