package br.com.petrobras.sistam.desktop.servicoprotecao;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SCheckList;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SFormattedTextField;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.EmpresaProtecao;
import br.com.petrobras.sistam.desktop.util.DesktopUtil;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.Dimension;
import javax.swing.AbstractListModel;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.JListBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 * @author adzk
 */
public class DetalhesEmpresaProtecaoDialog extends SDialog {

    private DetalhesEmpresaProtecaoModel model;

    /**
     * Constrói um dialog modal centralizado no frame pai.
     */
    public DetalhesEmpresaProtecaoDialog(java.awt.Frame parent, EmpresaProtecao empresa) {
        super(parent, true);
        this.model = new DetalhesEmpresaProtecaoModel(empresa);
        initComponents();
        setLocationRelativeTo(parent);
        DesktopUtil.configurarComponenteCNPJ(campoCnpj, actionSalvar);
        model.checkTiposServicoProtecaoSelecionado(checkListTipos);
    }

    public DetalhesEmpresaProtecaoModel getModel() {
        return model;
    }

    public void salvar() {
        model.salvar();
        if (model.isSalvo()) {
            dispose();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"})
    @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        actionSalvar = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        br.com.petrobras.fcorp.swing.components.SCheckList sCheckList1 = new br.com.petrobras.fcorp.swing.components.SCheckList();
        br.com.petrobras.fcorp.swing.components.SPanel panelInformacoes = new br.com.petrobras.fcorp.swing.components.SPanel();
        br.com.petrobras.fcorp.swing.components.SLabel sLabel1 = new br.com.petrobras.fcorp.swing.components.SLabel();
        br.com.petrobras.fcorp.swing.components.SLabel sLabel2 = new br.com.petrobras.fcorp.swing.components.SLabel();
        br.com.petrobras.fcorp.swing.components.SLabel sLabel3 = new br.com.petrobras.fcorp.swing.components.SLabel();
        br.com.petrobras.fcorp.swing.components.SLabel sLabel4 = new br.com.petrobras.fcorp.swing.components.SLabel();
        br.com.petrobras.fcorp.swing.components.SLabel sLabel5 = new br.com.petrobras.fcorp.swing.components.SLabel();
        br.com.petrobras.fcorp.swing.components.SLabel sLabel6 = new br.com.petrobras.fcorp.swing.components.SLabel();
        br.com.petrobras.fcorp.swing.components.SLabel sLabel7 = new br.com.petrobras.fcorp.swing.components.SLabel();
        br.com.petrobras.fcorp.swing.components.STextField sTextField1 = new br.com.petrobras.fcorp.swing.components.STextField();
        campoCnpj = new br.com.petrobras.fcorp.swing.components.SFormattedTextField();
        br.com.petrobras.fcorp.swing.components.STextField sTextField2 = new br.com.petrobras.fcorp.swing.components.STextField();
        br.com.petrobras.fcorp.swing.components.STextField sTextField3 = new br.com.petrobras.fcorp.swing.components.STextField();
        br.com.petrobras.fcorp.swing.components.STextField sTextField4 = new br.com.petrobras.fcorp.swing.components.STextField();
        br.com.petrobras.fcorp.swing.components.STextField sTextField5 = new br.com.petrobras.fcorp.swing.components.STextField();
        br.com.petrobras.fcorp.swing.components.SComboBox sComboBox1 = new br.com.petrobras.fcorp.swing.components.SComboBox();
        br.com.petrobras.fcorp.swing.components.SPanel panelBotoes = new br.com.petrobras.fcorp.swing.components.SPanel();
        br.com.petrobras.fcorp.swing.components.SButton botaoSalvar = new br.com.petrobras.fcorp.swing.components.SButton();
        br.com.petrobras.fcorp.swing.components.SPanel panelServicos = new br.com.petrobras.fcorp.swing.components.SPanel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        checkListTipos = new br.com.petrobras.fcorp.swing.components.SCheckList();

        actionSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/disk.png"))); // NOI18N
        actionSalvar.setMethodName("salvar");
        actionSalvar.setTarget(this);
        actionSalvar.setText("Salvar");

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        sCheckList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        sCheckList1.setName("sCheckList1"); // NOI18N
        jScrollPane1.setViewportView(sCheckList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Empresa do Serviço de Proteção");
        setResizable(false);

        panelInformacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));
        panelInformacoes.setMaximumSize(new java.awt.Dimension(700, 32767));
        panelInformacoes.setName("panelInformacoes"); // NOI18N
        panelInformacoes.setPreferredSize(new java.awt.Dimension(700, 140));

        sLabel1.setText("CNPJ:");
        sLabel1.setName("sLabel1"); // NOI18N

        sLabel2.setText("Empresa:");
        sLabel2.setName("sLabel2"); // NOI18N

        sLabel3.setText("Telefone(s):");
        sLabel3.setName("sLabel3"); // NOI18N

        sLabel4.setText("E-mail:");
        sLabel4.setName("sLabel4"); // NOI18N

        sLabel5.setText("Cidade:");
        sLabel5.setName("sLabel5"); // NOI18N

        sLabel6.setText("Estado:");
        sLabel6.setName("sLabel6"); // NOI18N

        sLabel7.setText("Ativa:");
        sLabel7.setName("sLabel7"); // NOI18N

        sTextField1.setDocument(new GenericDocument(50));
        sTextField1.setName("sTextField1"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.empresa.telefone}"), sTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        campoCnpj.setName("campoCnpj"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.empresa.cnpjComMascara}"), campoCnpj, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        sTextField2.setDocument(new GenericDocument(100));
        sTextField2.setName("sTextField2"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.empresa.razaoSocial}"), sTextField2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sTextField3.setDocument(new GenericDocument(100));
        sTextField3.setName("sTextField3"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.empresa.email}"), sTextField3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sTextField4.setDocument(new GenericDocument(100, 
            GenericDocument.OPTION_APPLY_UPPERCASE ));
    sTextField4.setName("sTextField4"); // NOI18N

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.empresa.cidade}"), sTextField4, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    sTextField5.setDocument(new GenericDocument(2, 
        GenericDocument.OPTION_APPLY_UPPERCASE ));
sTextField5.setName("sTextField5"); // NOI18N

binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.empresa.estado}"), sTextField5, org.jdesktop.beansbinding.BeanProperty.create("text"));
bindingGroup.addBinding(binding);

sComboBox1.setName("sComboBox1"); // NOI18N

org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${model.tiposSimNao}");
org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, sComboBox1);
bindingGroup.addBinding(jComboBoxBinding);
binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.ativoSimNaoSelecionado}"), sComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
bindingGroup.addBinding(binding);

javax.swing.GroupLayout panelInformacoesLayout = new javax.swing.GroupLayout(panelInformacoes);
panelInformacoes.setLayout(panelInformacoesLayout);
panelInformacoesLayout.setHorizontalGroup(
    panelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelInformacoesLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(sLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacoesLayout.createSequentialGroup()
                .addComponent(campoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformacoesLayout.createSequentialGroup()
                .addComponent(sTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(sLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformacoesLayout.createSequentialGroup()
                .addComponent(sTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(sLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    panelInformacoesLayout.setVerticalGroup(
        panelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelInformacoesLayout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(panelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(sLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(sLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(campoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(sLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(sLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    panelBotoes.setName("panelBotoes"); // NOI18N

    botaoSalvar.setAction(actionSalvar);
    botaoSalvar.setName("botaoSalvar"); // NOI18N
    panelBotoes.add(botaoSalvar);

    panelServicos.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipos de Serviços de Proteção"));
    panelServicos.setMaximumSize(new java.awt.Dimension(700, 32767));
    panelServicos.setName("panelServicos"); // NOI18N
    panelServicos.setPreferredSize(new java.awt.Dimension(700, 120));

    jScrollPane2.setName("jScrollPane2"); // NOI18N

    checkListTipos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
    checkListTipos.setModel(new javax.swing.AbstractListModel() {
        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
        public int getSize() { return strings.length; }
        public Object getElementAt(int i) { return strings[i]; }
    });
    checkListTipos.setName("checkListTipos"); // NOI18N
    checkListTipos.setVisibleRowCount(5);

    eLProperty = org.jdesktop.beansbinding.ELProperty.create("${model.tiposServicoProtecao}");
    org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, checkListTipos);
    bindingGroup.addBinding(jListBinding);
    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.tiposServicoProtecaoSelecionado}"), checkListTipos, org.jdesktop.beansbinding.BeanProperty.create("selectedElements"));
    bindingGroup.addBinding(binding);

    jScrollPane2.setViewportView(checkListTipos);

    javax.swing.GroupLayout panelServicosLayout = new javax.swing.GroupLayout(panelServicos);
    panelServicos.setLayout(panelServicosLayout);
    panelServicosLayout.setHorizontalGroup(
        panelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelServicosLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2)
            .addContainerGap())
    );
    panelServicosLayout.setVerticalGroup(
        panelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelServicosLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2)
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addComponent(panelServicos, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(panelInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panelServicos, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    bindingGroup.bind();

    pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON
    // Variables declaration - do not modify//GEN-BEGIN:variables
    br.com.petrobras.fcorp.swing.base.action.GenericAction actionSalvar;
    br.com.petrobras.fcorp.swing.components.SFormattedTextField campoCnpj;
    br.com.petrobras.fcorp.swing.components.SCheckList checkListTipos;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
