package br.com.petrobras.sistam.desktop.agenciamento.panels;

import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Agenciamento;
import br.com.petrobras.sistam.common.enums.StatusEmbarcacao;
import br.com.petrobras.sistam.common.enums.TipoSimNao;
import br.com.petrobras.sistam.desktop.util.DesktopUtil;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

public class AgenciamentoViagemPainel extends SPanel {
    private AgenciamentoViagemModel model;

    public AgenciamentoViagemPainel() {        
        model = new AgenciamentoViagemModel();                
        initComponents();
        configurarHelps();
    }
  
    public AgenciamentoViagemModel getModel() {
        return model;
    }
    
    public void setAgenciamento(Agenciamento agenciamento){
        model.setAgenciamento(agenciamento);
        
        if (agenciamento != null && StatusEmbarcacao.CANCELADO.equals(agenciamento.getStatusEmbarcacao())){
            colocarEmModoVisualizacao();
        }
    }
    
    public void colocarEmModoVisualizacao(){
        DesktopUtil.habilitarComponentes(false, this);
    }
    
    public void configurarHelps() {
        srpAcidente.addFocusListener( new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (model.getAcidente().equals(TipoSimNao.SIM)) {
                    model.setHelpText("Teste");
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                model.setHelpText(null);
            }
        });
                
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        pnlDoencas = new br.com.petrobras.fcorp.swing.components.SPanel();
        sLabel28 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel19 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel20 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel21 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel23 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel22 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sRadioPanel3 = new br.com.petrobras.fcorp.swing.components.SRadioPanel();
        sRadioPanel5 = new br.com.petrobras.fcorp.swing.components.SRadioPanel();
        sRadioPanel6 = new br.com.petrobras.fcorp.swing.components.SRadioPanel();
        sRadioPanel7 = new br.com.petrobras.fcorp.swing.components.SRadioPanel();
        sRadioPanel8 = new br.com.petrobras.fcorp.swing.components.SRadioPanel();
        sRadioPanel9 = new br.com.petrobras.fcorp.swing.components.SRadioPanel();
        pnlMedicamento = new br.com.petrobras.fcorp.swing.components.SPanel();
        sLabel26 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel27 = new br.com.petrobras.fcorp.swing.components.SLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMedicamento = new br.com.petrobras.fcorp.swing.components.STextArea();
        sRadioPanel12 = new br.com.petrobras.fcorp.swing.components.SRadioPanel();
        pnlObitoSepultamento = new br.com.petrobras.fcorp.swing.components.SPanel();
        sLabel31 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel32 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sRadioPanel1 = new br.com.petrobras.fcorp.swing.components.SRadioPanel();
        sRadioPanel2 = new br.com.petrobras.fcorp.swing.components.SRadioPanel();
        pnlMortandadeRoedores = new br.com.petrobras.fcorp.swing.components.SPanel();
        sLabel25 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel30 = new br.com.petrobras.fcorp.swing.components.SLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCompartimento = new br.com.petrobras.fcorp.swing.components.STextArea();
        sRadioPanel11 = new br.com.petrobras.fcorp.swing.components.SRadioPanel();
        pnlAcidente = new br.com.petrobras.fcorp.swing.components.SPanel();
        sLabel24 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel29 = new br.com.petrobras.fcorp.swing.components.SLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTpAcidente = new br.com.petrobras.fcorp.swing.components.STextArea();
        srpAcidente = new br.com.petrobras.fcorp.swing.components.SRadioPanel();
        sPanel1 = new br.com.petrobras.fcorp.swing.components.SPanel();
        sTabbedPane1 = new br.com.petrobras.fcorp.swing.components.STabbedPane();
        pnlTripulacaoPassageiros = new br.com.petrobras.fcorp.swing.components.SPanel();
        sLabel38 = new br.com.petrobras.fcorp.swing.components.SLabel();
        nrTripulantes = new br.com.petrobras.fcorp.swing.components.SNumericTextField();
        sLabel39 = new br.com.petrobras.fcorp.swing.components.SLabel();
        nrPassageiros = new br.com.petrobras.fcorp.swing.components.SNumericTextField();
        txtNomeExtensoComandante = new br.com.petrobras.fcorp.swing.components.STextField();
        sLabel40 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel41 = new br.com.petrobras.fcorp.swing.components.SLabel();
        txtNacionalidadeComandante = new br.com.petrobras.fcorp.swing.components.STextField();
        pnlTripulacaoPassageiros1 = new br.com.petrobras.fcorp.swing.components.SPanel();
        sLabel42 = new br.com.petrobras.fcorp.swing.components.SLabel();
        nrTripulantes1 = new br.com.petrobras.fcorp.swing.components.SNumericTextField();
        sLabel43 = new br.com.petrobras.fcorp.swing.components.SLabel();
        nrPassageiros1 = new br.com.petrobras.fcorp.swing.components.SNumericTextField();
        txtNomeExtensoComandante1 = new br.com.petrobras.fcorp.swing.components.STextField();
        sLabel44 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel45 = new br.com.petrobras.fcorp.swing.components.SLabel();
        txtNacionalidadeComandante1 = new br.com.petrobras.fcorp.swing.components.STextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sistam-labels"); // NOI18N
        pnlDoencas.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("doencas"))); // NOI18N

        sLabel28.setText(bundle.getString("ocorrenciaDoenca")); // NOI18N

        sLabel19.setText(bundle.getString("sinaisFebre")); // NOI18N

        sLabel20.setText(bundle.getString("sinaisIctericia")); // NOI18N

        sLabel21.setText(bundle.getString("sinaisDiarreia")); // NOI18N

        sLabel23.setText(bundle.getString("sinaisTosse")); // NOI18N

        sLabel22.setText(bundle.getString("sinaisDisfuncoesNeurologicas")); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.listaSimNao}"), sRadioPanel3, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.doenca}"), sRadioPanel3, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        sRadioPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.listaSimNao}"), sRadioPanel5, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.habilitarCamposDoenca}"), sRadioPanel5, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.febreHemorragia}"), sRadioPanel5, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        sRadioPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.listaSimNao}"), sRadioPanel6, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.habilitarCamposDoenca}"), sRadioPanel6, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.ictericia}"), sRadioPanel6, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        sRadioPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.listaSimNao}"), sRadioPanel7, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.habilitarCamposDoenca}"), sRadioPanel7, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.diarreia}"), sRadioPanel7, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        sRadioPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.listaSimNao}"), sRadioPanel8, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.habilitarCamposDoenca}"), sRadioPanel8, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.disfuncoesNeurologicas}"), sRadioPanel8, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        sRadioPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.listaSimNao}"), sRadioPanel9, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.habilitarCamposDoenca}"), sRadioPanel9, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.dificuldadeRespiratoria}"), sRadioPanel9, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        sRadioPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        javax.swing.GroupLayout pnlDoencasLayout = new javax.swing.GroupLayout(pnlDoencas);
        pnlDoencas.setLayout(pnlDoencasLayout);
        pnlDoencasLayout.setHorizontalGroup(
            pnlDoencasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoencasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDoencasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDoencasLayout.createSequentialGroup()
                        .addGroup(pnlDoencasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDoencasLayout.createSequentialGroup()
                                .addComponent(sLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sRadioPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDoencasLayout.createSequentialGroup()
                                .addComponent(sLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sRadioPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlDoencasLayout.createSequentialGroup()
                        .addGroup(pnlDoencasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDoencasLayout.createSequentialGroup()
                                .addGroup(pnlDoencasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlDoencasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sRadioPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sRadioPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlDoencasLayout.createSequentialGroup()
                                .addComponent(sLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sRadioPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlDoencasLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(sLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sRadioPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlDoencasLayout.setVerticalGroup(
            pnlDoencasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoencasLayout.createSequentialGroup()
                .addGroup(pnlDoencasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sRadioPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDoencasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sRadioPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDoencasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sRadioPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDoencasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sRadioPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDoencasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sRadioPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDoencasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sRadioPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMedicamento.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("medicamentoABordo"))); // NOI18N

        sLabel26.setText(bundle.getString("ocorrenciaMedicamento")); // NOI18N

        sLabel27.setText(bundle.getString("lblmedicamentosABordo")); // NOI18N

        txtMedicamento.setColumns(20);
        txtMedicamento.setDocument(new GenericDocument(50) );
        txtMedicamento.setLineWrap(true);
        txtMedicamento.setRows(1);
        txtMedicamento.setWrapStyleWord(true);
        txtMedicamento.setSize(new java.awt.Dimension(162, 38));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.agenciementoViagem.nomeMedicamento}"), txtMedicamento, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.consumoMedicamento.id == true}"), txtMedicamento, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jScrollPane3.setViewportView(txtMedicamento);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.listaSimNao}"), sRadioPanel12, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.consumoMedicamento}"), sRadioPanel12, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        sRadioPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        javax.swing.GroupLayout pnlMedicamentoLayout = new javax.swing.GroupLayout(pnlMedicamento);
        pnlMedicamento.setLayout(pnlMedicamentoLayout);
        pnlMedicamentoLayout.setHorizontalGroup(
            pnlMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(pnlMedicamentoLayout.createSequentialGroup()
                        .addGroup(pnlMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMedicamentoLayout.createSequentialGroup()
                                .addComponent(sLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sRadioPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMedicamentoLayout.setVerticalGroup(
            pnlMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicamentoLayout.createSequentialGroup()
                .addGroup(pnlMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sRadioPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addGap(7, 7, 7))
        );

        pnlObitoSepultamento.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("obitoESepultamento"))); // NOI18N

        sLabel31.setText(bundle.getString("obitoABordo")); // NOI18N

        sLabel32.setText(bundle.getString("sepultamentoABordo")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.listaSimNao}"), sRadioPanel1, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.obito}"), sRadioPanel1, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        sRadioPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.listaSimNao}"), sRadioPanel2, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.sepultamento}"), sRadioPanel2, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        sRadioPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        javax.swing.GroupLayout pnlObitoSepultamentoLayout = new javax.swing.GroupLayout(pnlObitoSepultamento);
        pnlObitoSepultamento.setLayout(pnlObitoSepultamentoLayout);
        pnlObitoSepultamentoLayout.setHorizontalGroup(
            pnlObitoSepultamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObitoSepultamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlObitoSepultamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlObitoSepultamentoLayout.createSequentialGroup()
                        .addComponent(sLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sRadioPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlObitoSepultamentoLayout.createSequentialGroup()
                        .addComponent(sLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sRadioPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlObitoSepultamentoLayout.setVerticalGroup(
            pnlObitoSepultamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObitoSepultamentoLayout.createSequentialGroup()
                .addGroup(pnlObitoSepultamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sRadioPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlObitoSepultamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sRadioPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlMortandadeRoedores.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("mortandadeRoedores"))); // NOI18N

        sLabel25.setText(bundle.getString("ocorrenciaMortandandeRoedores")); // NOI18N

        sLabel30.setText(bundle.getString("lblCompartimentoMortandade")); // NOI18N

        txtCompartimento.setColumns(20);
        txtCompartimento.setDocument(new GenericDocument(50) );
        txtCompartimento.setLineWrap(true);
        txtCompartimento.setRows(2);
        txtCompartimento.setWrapStyleWord(true);
        txtCompartimento.setSize(new java.awt.Dimension(162, 38));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.agenciementoViagem.compartimentoRoedores}"), txtCompartimento, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.roedores.id == true}"), txtCompartimento, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(txtCompartimento);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.listaSimNao}"), sRadioPanel11, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.roedores}"), sRadioPanel11, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        sRadioPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        javax.swing.GroupLayout pnlMortandadeRoedoresLayout = new javax.swing.GroupLayout(pnlMortandadeRoedores);
        pnlMortandadeRoedores.setLayout(pnlMortandadeRoedoresLayout);
        pnlMortandadeRoedoresLayout.setHorizontalGroup(
            pnlMortandadeRoedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMortandadeRoedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMortandadeRoedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(sLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMortandadeRoedoresLayout.createSequentialGroup()
                        .addComponent(sLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sRadioPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlMortandadeRoedoresLayout.setVerticalGroup(
            pnlMortandadeRoedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMortandadeRoedoresLayout.createSequentialGroup()
                .addGroup(pnlMortandadeRoedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sRadioPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(sLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );

        pnlAcidente.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("acidenteABordo"))); // NOI18N

        sLabel24.setText(bundle.getString("ocorrenciaAcidente")); // NOI18N

        sLabel29.setText(bundle.getString("lblTipoAcidente")); // NOI18N

        txtTpAcidente.setColumns(20);
        txtTpAcidente.setDocument(new GenericDocument(150) );
        txtTpAcidente.setLineWrap(true);
        txtTpAcidente.setRows(1);
        txtTpAcidente.setWrapStyleWord(true);
        txtTpAcidente.setSize(new java.awt.Dimension(162, 38));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.agenciementoViagem.nomeAcidente}"), txtTpAcidente, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.acidente.id == true}"), txtTpAcidente, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(txtTpAcidente);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.listaSimNao}"), srpAcidente, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.acidente}"), srpAcidente, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        srpAcidente.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        javax.swing.GroupLayout pnlAcidenteLayout = new javax.swing.GroupLayout(pnlAcidente);
        pnlAcidente.setLayout(pnlAcidenteLayout);
        pnlAcidenteLayout.setHorizontalGroup(
            pnlAcidenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcidenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAcidenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlAcidenteLayout.createSequentialGroup()
                        .addGroup(pnlAcidenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAcidenteLayout.createSequentialGroup()
                                .addComponent(sLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(srpAcidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 57, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAcidenteLayout.setVerticalGroup(
            pnlAcidenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcidenteLayout.createSequentialGroup()
                .addGroup(pnlAcidenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srpAcidente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(sLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        sLabel38.setText(bundle.getString("lblNrTripulante")); // NOI18N

        nrTripulantes.setIntegerPlaces(new java.lang.Short((short)6));
        nrTripulantes.setUseGroupDigit(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.agenciementoViagem.numeroTripulantesEntrada}"), nrTripulantes, org.jdesktop.beansbinding.BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        sLabel39.setText(bundle.getString("lblNrPassageiros")); // NOI18N

        nrPassageiros.setIntegerPlaces(new java.lang.Short((short)6));
        nrPassageiros.setUseGroupDigit(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.agenciementoViagem.numeroPassageirosEntrada}"), nrPassageiros, org.jdesktop.beansbinding.BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        txtNomeExtensoComandante.setDocument(new GenericDocument(80) );

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.agenciementoViagem.comandanteEntrada}"), txtNomeExtensoComandante, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sLabel40.setText(bundle.getString("lblNomeComandante")); // NOI18N

        sLabel41.setText(bundle.getString("lblNacionalidadeComandante")); // NOI18N

        txtNacionalidadeComandante.setDocument(new GenericDocument(50, true, false, true) );

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.agenciementoViagem.nacionalidadeEntrada}"), txtNacionalidadeComandante, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout pnlTripulacaoPassageirosLayout = new javax.swing.GroupLayout(pnlTripulacaoPassageiros);
        pnlTripulacaoPassageiros.setLayout(pnlTripulacaoPassageirosLayout);
        pnlTripulacaoPassageirosLayout.setHorizontalGroup(
            pnlTripulacaoPassageirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTripulacaoPassageirosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtNomeExtensoComandante, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtNacionalidadeComandante, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(nrPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(nrTripulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlTripulacaoPassageirosLayout.setVerticalGroup(
            pnlTripulacaoPassageirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTripulacaoPassageirosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTripulacaoPassageirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeExtensoComandante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNacionalidadeComandante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrTripulantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        sTabbedPane1.addTab("Tripulação e Passageiros na Chegada", pnlTripulacaoPassageiros);

        sLabel42.setText(bundle.getString("lblNrTripulante")); // NOI18N

        nrTripulantes1.setIntegerPlaces(new java.lang.Short((short)6));
        nrTripulantes1.setUseGroupDigit(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.agenciementoViagem.numeroTripulantesSaida}"), nrTripulantes1, org.jdesktop.beansbinding.BeanProperty.create("intValue"));
        bindingGroup.addBinding(binding);

        sLabel43.setText(bundle.getString("lblNrPassageiros")); // NOI18N

        nrPassageiros1.setIntegerPlaces(new java.lang.Short((short)6));
        nrPassageiros1.setUseGroupDigit(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.agenciementoViagem.numeroPassageirosSaida}"), nrPassageiros1, org.jdesktop.beansbinding.BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        txtNomeExtensoComandante1.setDocument(new GenericDocument(80) );

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.agenciementoViagem.comandanteSaida}"), txtNomeExtensoComandante1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sLabel44.setText(bundle.getString("lblNomeComandante")); // NOI18N

        sLabel45.setText(bundle.getString("lblNacionalidadeComandante")); // NOI18N

        txtNacionalidadeComandante1.setDocument(new GenericDocument(50, true, false, true) );

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.agenciementoViagem.nacionalidadeSaida}"), txtNacionalidadeComandante1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout pnlTripulacaoPassageiros1Layout = new javax.swing.GroupLayout(pnlTripulacaoPassageiros1);
        pnlTripulacaoPassageiros1.setLayout(pnlTripulacaoPassageiros1Layout);
        pnlTripulacaoPassageiros1Layout.setHorizontalGroup(
            pnlTripulacaoPassageiros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTripulacaoPassageiros1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtNomeExtensoComandante1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtNacionalidadeComandante1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(nrPassageiros1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(nrTripulantes1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlTripulacaoPassageiros1Layout.setVerticalGroup(
            pnlTripulacaoPassageiros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTripulacaoPassageiros1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTripulacaoPassageiros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeExtensoComandante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNacionalidadeComandante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrPassageiros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrTripulantes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        sTabbedPane1.addTab("Tripulação e Passageiros na Saída", pnlTripulacaoPassageiros1);

        javax.swing.GroupLayout sPanel1Layout = new javax.swing.GroupLayout(sPanel1);
        sPanel1.setLayout(sPanel1Layout);
        sPanel1Layout.setHorizontalGroup(
            sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sPanel1Layout.setVerticalGroup(
            sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDoencas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAcidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlObitoSepultamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMortandadeRoedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlObitoSepultamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlDoencas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlMortandadeRoedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAcidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMedicamento.getAccessibleContext().setAccessibleName("Medicamento Durante a Viagem");

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void nrTripulantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrTripulantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrTripulantesActionPerformed

    private void nrTripulantes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrTripulantes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrTripulantes1ActionPerformed

    private void nrTripulantes1ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrTripulantes1ActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_nrTripulantes1ActionPerformed1
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private br.com.petrobras.fcorp.swing.components.SNumericTextField nrPassageiros;
    private br.com.petrobras.fcorp.swing.components.SNumericTextField nrPassageiros1;
    private br.com.petrobras.fcorp.swing.components.SNumericTextField nrTripulantes;
    private br.com.petrobras.fcorp.swing.components.SNumericTextField nrTripulantes1;
    private br.com.petrobras.fcorp.swing.components.SPanel pnlAcidente;
    private br.com.petrobras.fcorp.swing.components.SPanel pnlDoencas;
    private br.com.petrobras.fcorp.swing.components.SPanel pnlMedicamento;
    private br.com.petrobras.fcorp.swing.components.SPanel pnlMortandadeRoedores;
    private br.com.petrobras.fcorp.swing.components.SPanel pnlObitoSepultamento;
    private br.com.petrobras.fcorp.swing.components.SPanel pnlTripulacaoPassageiros;
    private br.com.petrobras.fcorp.swing.components.SPanel pnlTripulacaoPassageiros1;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel19;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel20;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel21;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel22;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel23;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel24;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel25;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel26;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel27;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel28;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel29;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel30;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel31;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel32;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel38;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel39;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel40;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel41;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel42;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel43;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel44;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel45;
    private br.com.petrobras.fcorp.swing.components.SPanel sPanel1;
    private br.com.petrobras.fcorp.swing.components.SRadioPanel sRadioPanel1;
    private br.com.petrobras.fcorp.swing.components.SRadioPanel sRadioPanel11;
    private br.com.petrobras.fcorp.swing.components.SRadioPanel sRadioPanel12;
    private br.com.petrobras.fcorp.swing.components.SRadioPanel sRadioPanel2;
    private br.com.petrobras.fcorp.swing.components.SRadioPanel sRadioPanel3;
    private br.com.petrobras.fcorp.swing.components.SRadioPanel sRadioPanel5;
    private br.com.petrobras.fcorp.swing.components.SRadioPanel sRadioPanel6;
    private br.com.petrobras.fcorp.swing.components.SRadioPanel sRadioPanel7;
    private br.com.petrobras.fcorp.swing.components.SRadioPanel sRadioPanel8;
    private br.com.petrobras.fcorp.swing.components.SRadioPanel sRadioPanel9;
    private br.com.petrobras.fcorp.swing.components.STabbedPane sTabbedPane1;
    private br.com.petrobras.fcorp.swing.components.SRadioPanel srpAcidente;
    private br.com.petrobras.fcorp.swing.components.STextArea txtCompartimento;
    private br.com.petrobras.fcorp.swing.components.STextArea txtMedicamento;
    private br.com.petrobras.fcorp.swing.components.STextField txtNacionalidadeComandante;
    private br.com.petrobras.fcorp.swing.components.STextField txtNacionalidadeComandante1;
    private br.com.petrobras.fcorp.swing.components.STextField txtNomeExtensoComandante;
    private br.com.petrobras.fcorp.swing.components.STextField txtNomeExtensoComandante1;
    private br.com.petrobras.fcorp.swing.components.STextArea txtTpAcidente;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
