package br.com.petrobras.sistam.desktop.agenciamento.panels;

import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Acompanhamento;
import br.com.petrobras.sistam.common.entity.Agenciamento;
import br.com.petrobras.sistam.desktop.SistamApp;
import br.com.petrobras.sistam.desktop.agenciamento.acompanhamento.DetalheAcompanhamentoDialog;
import br.com.petrobras.sistam.desktop.util.DesktopUtil;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.util.Date;

public class InformacoesGeraisPainel extends SPanel{
    private InformacoesGeraisPainelModel model;
    
    public InformacoesGeraisPainel() {
        this.model = new InformacoesGeraisPainelModel();
        initComponents();
        
        DesktopUtil.adicionarMascaraLatitude(campoLatitude);
        DesktopUtil.adicionarMascaraLongititude(campoLongitude);
        
    }

    public InformacoesGeraisPainelModel getModel() {
        return model;
    }
    
    public void setAgenciamento(Agenciamento agenciamento){
        model.setAgenciamento(agenciamento);
        
        if (agenciamento != null) {
            if(agenciamento.getAgencia() != null){
                comboFusoHorario.setSelectedItem(agenciamento.getAgencia().obterTimezone());
            }
            model.carregarAcompanhamentos();
        }
    } 
    
    public void colocarEmModoVisualizacao(){
        DesktopUtil.habilitarComponentes(false, this);
    }
    
    public void colocarEmModoVisualizacaoParaADM(){
        DesktopUtil.habilitarComponentes(true, this);
    }
    
    public void adicionarAcompanhamento() {
        Acompanhamento acompanhamento = new Acompanhamento();
        acompanhamento.setAgenciamento(model.getAgenciamento());
        acompanhamento.setData(new Date());
        acompanhamento.setChaveCadastrador(SistamApp.getSistamApp().getCredentialsBean().getLogon());
        acompanhamento.setNomeCadastrador(SistamApp.getSistamApp().getCredentialsBean().getUsername());
        DetalheAcompanhamentoDialog dialog = new DetalheAcompanhamentoDialog(SistamApp.getSistamApp().getMainFrame(), acompanhamento, false);
        dialog.setVisible(true);
        model.carregarAcompanhamentos();
    }

    public void editarAcompanhamento() {
        DetalheAcompanhamentoDialog dialog = new DetalheAcompanhamentoDialog(SistamApp.getSistamApp().getMainFrame(), model.getAcompanhamentoSelecionado(), true);
        dialog.setVisible(true);
        model.carregarAcompanhamentos();
    }
   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        actionAdicionarAcompanhamento = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        actionEditarAcompanhamento = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        labelAgencia = new br.com.petrobras.fcorp.swing.components.SLabel();
        campoAgencia = new br.com.petrobras.fcorp.swing.components.STextField();
        labelFusoHorario = new br.com.petrobras.fcorp.swing.components.SLabel();
        comboFusoHorario = new br.com.petrobras.sistam.desktop.components.TimeZoneComboBox();
        labelPorto = new br.com.petrobras.fcorp.swing.components.SLabel();
        campoPorto = new br.com.petrobras.fcorp.swing.components.STextField();
        labelArmador = new br.com.petrobras.fcorp.swing.components.SLabel();
        comboArmador = new br.com.petrobras.fcorp.swing.components.SComboBox();
        labelTipoAgenciamento = new br.com.petrobras.fcorp.swing.components.SLabel();
        checkBoxCarga = new br.com.petrobras.fcorp.swing.components.SCheckBox();
        checkBoxProtecao = new br.com.petrobras.fcorp.swing.components.SCheckBox();
        sPanel1 = new br.com.petrobras.fcorp.swing.components.SPanel();
        pnlInformacoesExternas = new br.com.petrobras.fcorp.swing.components.SPanel();
        sLabel13 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel14 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sNumericTextField7 = new br.com.petrobras.fcorp.swing.components.SNumericTextField();
        sTextField5 = new br.com.petrobras.fcorp.swing.components.STextField();
        sLabel18 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sTextField6 = new br.com.petrobras.fcorp.swing.components.STextField();
        pnlEscalas = new br.com.petrobras.fcorp.swing.components.SPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtListaEscalas = new br.com.petrobras.fcorp.swing.components.STextArea();
        sPanel2 = new br.com.petrobras.fcorp.swing.components.SPanel();
        tabbedPaneChegadaSaida = new br.com.petrobras.fcorp.swing.components.STabbedPane();
        painelChegadaEmbarcacao = new br.com.petrobras.fcorp.swing.components.SPanel();
        sPanel8 = new br.com.petrobras.fcorp.swing.components.SPanel();
        sLabel35 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel36 = new br.com.petrobras.fcorp.swing.components.SLabel();
        dataChooserEta = new br.com.petrobras.sistam.desktop.components.SistamDateChooser();
        br.com.petrobras.sistam.desktop.components.SistamDateChooser dataChooserHoraOficial = new br.com.petrobras.sistam.desktop.components.SistamDateChooser();
        timeChooserHoraEta = new br.com.petrobras.sistam.desktop.components.SistamTimeChooser();
        timeChooserHoraOficialChegada = new br.com.petrobras.sistam.desktop.components.SistamTimeChooser();
        pnlDestino2 = new br.com.petrobras.fcorp.swing.components.SPanel();
        sLabel39 = new br.com.petrobras.fcorp.swing.components.SLabel();
        portoOrigem1 = new br.com.petrobras.sistam.desktop.components.lookups.porto.PortoLookup();
        sLabel15 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel16 = new br.com.petrobras.fcorp.swing.components.SLabel();
        campoLatitude = new br.com.petrobras.fcorp.swing.components.SFormattedTextField();
        campoLongitude = new br.com.petrobras.fcorp.swing.components.SFormattedTextField();
        sPanel9 = new br.com.petrobras.fcorp.swing.components.SPanel();
        sNumericTextField6 = new br.com.petrobras.fcorp.swing.components.SNumericTextField();
        sLabel17 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel69 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sNumericTextField9 = new br.com.petrobras.fcorp.swing.components.SNumericTextField();
        labelAreaNavegacao = new br.com.petrobras.fcorp.swing.components.SLabel();
        comboAreaNavegacao = new br.com.petrobras.fcorp.swing.components.SComboBox();
        labelViagem = new br.com.petrobras.fcorp.swing.components.SLabel();
        campoViagem = new br.com.petrobras.fcorp.swing.components.STextField();
        painelSaidaEmbarcacao = new br.com.petrobras.fcorp.swing.components.SPanel();
        sPanel10 = new br.com.petrobras.fcorp.swing.components.SPanel();
        sLabel37 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel38 = new br.com.petrobras.fcorp.swing.components.SLabel();
        dateChooserDataEstimadaSaida = new br.com.petrobras.sistam.desktop.components.SistamDateChooser();
        br.com.petrobras.sistam.desktop.components.SistamDateChooser dateChooserHoraOficialSaida = new br.com.petrobras.sistam.desktop.components.SistamDateChooser();
        timeChooserEts = new br.com.petrobras.sistam.desktop.components.SistamTimeChooser();
        timeChosserHoraOficialSaida = new br.com.petrobras.sistam.desktop.components.SistamTimeChooser();
        sPanel11 = new br.com.petrobras.fcorp.swing.components.SPanel();
        sNumericTextField10 = new br.com.petrobras.fcorp.swing.components.SNumericTextField();
        sLabel19 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sLabel70 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sNumericTextField11 = new br.com.petrobras.fcorp.swing.components.SNumericTextField();
        pnlDestino = new br.com.petrobras.fcorp.swing.components.SPanel();
        sLabel40 = new br.com.petrobras.fcorp.swing.components.SLabel();
        portoDestino = new br.com.petrobras.sistam.desktop.components.lookups.porto.PortoLookup();
        sLabel20 = new br.com.petrobras.fcorp.swing.components.SLabel();
        dateChooserEtaProxPorto = new br.com.petrobras.sistam.desktop.components.SistamDateChooser();
        timeChooserEtaProxPorto = new br.com.petrobras.sistam.desktop.components.SistamTimeChooser();
        sLabel41 = new br.com.petrobras.fcorp.swing.components.SLabel();
        sTextField7 = new br.com.petrobras.fcorp.swing.components.STextField();
        labelAreaNavegacao1 = new br.com.petrobras.fcorp.swing.components.SLabel();
        comboAreaNavegacao1 = new br.com.petrobras.fcorp.swing.components.SComboBox();
        labelViagem1 = new br.com.petrobras.fcorp.swing.components.SLabel();
        campoViagem1 = new br.com.petrobras.fcorp.swing.components.STextField();
        textAreaComContador1 = new br.com.petrobras.sistam.desktop.components.TextAreaComContador();
        painelAcompanhamento = new br.com.petrobras.fcorp.swing.components.SPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sTable2 = new br.com.petrobras.fcorp.swing.components.STable();
        sButton1 = new br.com.petrobras.fcorp.swing.components.SButton();
        sButton2 = new br.com.petrobras.fcorp.swing.components.SButton();
        labelTipoContrato = new br.com.petrobras.fcorp.swing.components.SLabel();
        campoTipoContrato = new br.com.petrobras.fcorp.swing.components.STextField();
        labelArmador1 = new br.com.petrobras.fcorp.swing.components.SLabel();
        comboArmador1 = new br.com.petrobras.fcorp.swing.components.SComboBox();
        checkBoxPlataforma = new br.com.petrobras.fcorp.swing.components.SCheckBox();

        actionAdicionarAcompanhamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        actionAdicionarAcompanhamento.setMethodName("adicionarAcompanhamento");
        actionAdicionarAcompanhamento.setTarget(this);
        actionAdicionarAcompanhamento.setText("");
        actionAdicionarAcompanhamento.setToolTipText("Adicionar Acompanhamento");

        actionEditarAcompanhamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/listagem_busca.png"))); // NOI18N
        actionEditarAcompanhamento.setMethodName("editarAcompanhamento");
        actionEditarAcompanhamento.setTarget(this);
        actionEditarAcompanhamento.setText("");
        actionEditarAcompanhamento.setToolTipText("Visualizar Acompanhamento");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${not empty model.acompanhamentoSelecionado}"), actionEditarAcompanhamento, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        labelAgencia.setText("Agência:");

        campoAgencia.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.agencia.nome}"), campoAgencia, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        labelFusoHorario.setText("Fuso Horário:");

        comboFusoHorario.setEnabled(false);

        labelPorto.setText("Porto:");

        campoPorto.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.porto.nomeCompleto}"), campoPorto, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        labelArmador.setText("Armador:");

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${model.tipoArmador}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, comboArmador);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.tipoArmador}"), comboArmador, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        labelTipoAgenciamento.setText("Tipo Agenciamento:");

        checkBoxCarga.setText("Carga");
        checkBoxCarga.setOpaque(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.agenciamentoCarga}"), checkBoxCarga, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.habilitar}"), checkBoxCarga, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        checkBoxProtecao.setText("Proteção");
        checkBoxProtecao.setOpaque(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.agenciamentoProtecao}"), checkBoxProtecao, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.habilitar}"), checkBoxProtecao, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        pnlInformacoesExternas.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações Externas"));

        sLabel13.setText("Nr. DUV:");

        sLabel14.setText("Escala (Mercante):");

        sNumericTextField7.setDecimalPlaces(new java.lang.Short((short)0));
        sNumericTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sNumericTextField7.setIntegerPlaces(new java.lang.Short((short)11));
        sNumericTextField7.setNumberClass(java.lang.Long.class);
        sNumericTextField7.setUseGroupDigit(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.numeroEscalaMercante}"), sNumericTextField7, org.jdesktop.beansbinding.BeanProperty.create("longValue"));
        bindingGroup.addBinding(binding);

        sTextField5.setDocument(new GenericDocument(15,GenericDocument.OPTION_APPLY_UPPERCASE ));
        sTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.numeroDUV}"), sTextField5, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sLabel18.setText("Processo de Despacho:");

        sTextField6.setDocument(new GenericDocument(20,GenericDocument.OPTION_APPLY_UPPERCASE ));
        sTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.numeroProcessoDespacho}"), sTextField6, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout pnlInformacoesExternasLayout = new javax.swing.GroupLayout(pnlInformacoesExternas);
        pnlInformacoesExternas.setLayout(pnlInformacoesExternasLayout);
        pnlInformacoesExternasLayout.setHorizontalGroup(
            pnlInformacoesExternasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacoesExternasLayout.createSequentialGroup()
                .addGroup(pnlInformacoesExternasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInformacoesExternasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sNumericTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInformacoesExternasLayout.setVerticalGroup(
            pnlInformacoesExternasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacoesExternasLayout.createSequentialGroup()
                .addGroup(pnlInformacoesExternasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInformacoesExternasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInformacoesExternasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sNumericTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEscalas.setBorder(javax.swing.BorderFactory.createTitledBorder("Escalas últimos 30 dias"));

        txtListaEscalas.setColumns(20);
        txtListaEscalas.setDocument(new GenericDocument(1200));
        txtListaEscalas.setLineWrap(true);
        txtListaEscalas.setRows(2);
        txtListaEscalas.setWrapStyleWord(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.escalas}"), txtListaEscalas, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane4.setViewportView(txtListaEscalas);

        javax.swing.GroupLayout pnlEscalasLayout = new javax.swing.GroupLayout(pnlEscalas);
        pnlEscalas.setLayout(pnlEscalasLayout);
        pnlEscalasLayout.setHorizontalGroup(
            pnlEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEscalasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnlEscalasLayout.setVerticalGroup(
            pnlEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEscalasLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sPanel1Layout = new javax.swing.GroupLayout(sPanel1);
        sPanel1.setLayout(sPanel1Layout);
        sPanel1Layout.setHorizontalGroup(
            sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInformacoesExternas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEscalas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sPanel1Layout.setVerticalGroup(
            sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEscalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlInformacoesExternas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        sPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pnlEscalas, pnlInformacoesExternas});

        painelChegadaEmbarcacao.setPreferredSize(new java.awt.Dimension(790, 158));

        sPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Data e hora"));

        sLabel35.setText("Hora Oficial:");

        sLabel36.setText("ETA:");

        dataChooserEta.setTimeChooser(timeChooserHoraEta);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.eta}"), dataChooserEta, org.jdesktop.beansbinding.BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        dataChooserHoraOficial.setTimeChooser(timeChooserHoraOficialChegada);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.dataChegada}"), dataChooserHoraOficial, org.jdesktop.beansbinding.BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout sPanel8Layout = new javax.swing.GroupLayout(sPanel8);
        sPanel8.setLayout(sPanel8Layout);
        sPanel8Layout.setHorizontalGroup(
            sPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataChooserEta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeChooserHoraEta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataChooserHoraOficial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeChooserHoraOficialChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        sPanel8Layout.setVerticalGroup(
            sPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanel8Layout.createSequentialGroup()
                .addGroup(sPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataChooserEta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeChooserHoraEta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timeChooserHoraOficialChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataChooserHoraOficial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDestino2.setBorder(javax.swing.BorderFactory.createTitledBorder("Origem e Posição na Chegada"));

        sLabel39.setText("Porto Origem:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.portoOrigem}"), portoOrigem1, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        sLabel15.setText("Latitude:");

        sLabel16.setText("Longitude:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.latitudeEntrada}"), campoLatitude, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.longitudeEntrada}"), campoLongitude, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout pnlDestino2Layout = new javax.swing.GroupLayout(pnlDestino2);
        pnlDestino2.setLayout(pnlDestino2Layout);
        pnlDestino2Layout.setHorizontalGroup(
            pnlDestino2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestino2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(portoOrigem1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDestino2Layout.setVerticalGroup(
            pnlDestino2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestino2Layout.createSequentialGroup()
                .addGroup(pnlDestino2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(portoOrigem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Calado"));

        sNumericTextField6.setIntegerPlaces(new java.lang.Short((short)3));
        sNumericTextField6.setNumberClass(java.lang.Double.class);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.caladoChegadaRe}"), sNumericTextField6, org.jdesktop.beansbinding.BeanProperty.create("doubleValue"));
        bindingGroup.addBinding(binding);

        sLabel17.setText("A Ré:");

        sLabel69.setText("A vante:");

        sNumericTextField9.setIntegerPlaces(new java.lang.Short((short)3));
        sNumericTextField9.setNumberClass(java.lang.Double.class);
        sNumericTextField9.setText("sNumericTextField8");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.caladoChegadaVante}"), sNumericTextField9, org.jdesktop.beansbinding.BeanProperty.create("doubleValue"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout sPanel9Layout = new javax.swing.GroupLayout(sPanel9);
        sPanel9.setLayout(sPanel9Layout);
        sPanel9Layout.setHorizontalGroup(
            sPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sNumericTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(sNumericTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        sPanel9Layout.setVerticalGroup(
            sPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanel9Layout.createSequentialGroup()
                .addGroup(sPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sNumericTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sNumericTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelAreaNavegacao.setText("Área  Navegação:");

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${model.areasNavegacao}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, comboAreaNavegacao);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.areaNavegacao}"), comboAreaNavegacao, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        labelViagem.setText("Viagem:");

        campoViagem.setDocument(new GenericDocument(10,
            GenericDocument.OPTION_APPLY_UPPERCASE));

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.vgm}"), campoViagem, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    javax.swing.GroupLayout painelChegadaEmbarcacaoLayout = new javax.swing.GroupLayout(painelChegadaEmbarcacao);
    painelChegadaEmbarcacao.setLayout(painelChegadaEmbarcacaoLayout);
    painelChegadaEmbarcacaoLayout.setHorizontalGroup(
        painelChegadaEmbarcacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelChegadaEmbarcacaoLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(painelChegadaEmbarcacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelChegadaEmbarcacaoLayout.createSequentialGroup()
                    .addGroup(painelChegadaEmbarcacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pnlDestino2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelChegadaEmbarcacaoLayout.createSequentialGroup()
                            .addComponent(sPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                            .addComponent(sPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(16, 16, 16))
                .addGroup(painelChegadaEmbarcacaoLayout.createSequentialGroup()
                    .addComponent(labelAreaNavegacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(comboAreaNavegacao, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(labelViagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(campoViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    painelChegadaEmbarcacaoLayout.setVerticalGroup(
        painelChegadaEmbarcacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelChegadaEmbarcacaoLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(painelChegadaEmbarcacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelAreaNavegacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(comboAreaNavegacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelViagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(campoViagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(painelChegadaEmbarcacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(sPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(pnlDestino2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(25, Short.MAX_VALUE))
    );

    tabbedPaneChegadaSaida.addTab("Chegada da Embarcação", painelChegadaEmbarcacao);

    sPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Data e hora"));

    sLabel37.setText("Hora Oficial:");

    sLabel38.setText("ETS:");

    dateChooserDataEstimadaSaida.setTimeChooser(timeChooserEts);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.dataEstimadaSaida}"), dateChooserDataEstimadaSaida, org.jdesktop.beansbinding.BeanProperty.create("date"));
    bindingGroup.addBinding(binding);

    dateChooserHoraOficialSaida.setTimeChooser(timeChosserHoraOficialSaida);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.dataSaida}"), dateChooserHoraOficialSaida, org.jdesktop.beansbinding.BeanProperty.create("date"));
    bindingGroup.addBinding(binding);

    javax.swing.GroupLayout sPanel10Layout = new javax.swing.GroupLayout(sPanel10);
    sPanel10.setLayout(sPanel10Layout);
    sPanel10Layout.setHorizontalGroup(
        sPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(sPanel10Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(sLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(dateChooserDataEstimadaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(timeChooserEts, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(17, 17, 17)
            .addComponent(sLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(dateChooserHoraOficialSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(timeChosserHoraOficialSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(35, Short.MAX_VALUE))
    );
    sPanel10Layout.setVerticalGroup(
        sPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(sPanel10Layout.createSequentialGroup()
            .addGroup(sPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(sLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dateChooserDataEstimadaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(timeChooserEts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(sPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeChosserHoraOficialSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserHoraOficialSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    sPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Calado"));

    sNumericTextField10.setIntegerPlaces(new java.lang.Short((short)3));
    sNumericTextField10.setNumberClass(java.lang.Double.class);
    sNumericTextField10.setText("sNumericTextField5");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.caladoSaidaRe}"), sNumericTextField10, org.jdesktop.beansbinding.BeanProperty.create("doubleValue"));
    bindingGroup.addBinding(binding);

    sLabel19.setText("A Ré:");

    sLabel70.setText("A vante:");

    sNumericTextField11.setIntegerPlaces(new java.lang.Short((short)3));
    sNumericTextField11.setNumberClass(java.lang.Double.class);
    sNumericTextField11.setText("sNumericTextField8");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.caladoSaidaVante}"), sNumericTextField11, org.jdesktop.beansbinding.BeanProperty.create("doubleValue"));
    bindingGroup.addBinding(binding);

    javax.swing.GroupLayout sPanel11Layout = new javax.swing.GroupLayout(sPanel11);
    sPanel11.setLayout(sPanel11Layout);
    sPanel11Layout.setHorizontalGroup(
        sPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(sPanel11Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(sLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(sNumericTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(sLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(sNumericTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    sPanel11Layout.setVerticalGroup(
        sPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(sPanel11Layout.createSequentialGroup()
            .addGroup(sPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(sNumericTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sNumericTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnlDestino.setBorder(javax.swing.BorderFactory.createTitledBorder("Destino Embarcação"));

    sLabel40.setText("Porto:");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.portoDestino}"), portoDestino, org.jdesktop.beansbinding.BeanProperty.create("value"));
    bindingGroup.addBinding(binding);

    sLabel20.setText("ETA próx. porto:");

    dateChooserEtaProxPorto.setTimeChooser(timeChooserEtaProxPorto);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.etaProximoPorto}"), dateChooserEtaProxPorto, org.jdesktop.beansbinding.BeanProperty.create("date"));
    bindingGroup.addBinding(binding);

    sLabel41.setText("Dest. Intermed.:");

    sTextField7.setDocument(new GenericDocument(120,
        GenericDocument.OPTION_APPLY_UPPERCASE));

binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.destinoIntermediario}"), sTextField7, org.jdesktop.beansbinding.BeanProperty.create("text"));
bindingGroup.addBinding(binding);

javax.swing.GroupLayout pnlDestinoLayout = new javax.swing.GroupLayout(pnlDestino);
pnlDestino.setLayout(pnlDestinoLayout);
pnlDestinoLayout.setHorizontalGroup(
    pnlDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(pnlDestinoLayout.createSequentialGroup()
        .addContainerGap(19, Short.MAX_VALUE)
        .addComponent(sLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(portoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(sLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(dateChooserEtaProxPorto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(timeChooserEtaProxPorto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(sLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(sTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    pnlDestinoLayout.setVerticalGroup(
        pnlDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlDestinoLayout.createSequentialGroup()
            .addGroup(pnlDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(portoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserEtaProxPorto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeChooserEtaProxPorto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    labelAreaNavegacao1.setText("Área  Navegação:");

    eLProperty = org.jdesktop.beansbinding.ELProperty.create("${model.areasNavegacao}");
    jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, comboAreaNavegacao1);
    bindingGroup.addBinding(jComboBoxBinding);
    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.areaNavegacaoSaida}"), comboAreaNavegacao1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
    bindingGroup.addBinding(binding);

    labelViagem1.setText("Viagem:");

    campoViagem1.setDocument(new GenericDocument(10,
        GenericDocument.OPTION_APPLY_UPPERCASE));

binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.vgmSaida}"), campoViagem1, org.jdesktop.beansbinding.BeanProperty.create("text"));
bindingGroup.addBinding(binding);

javax.swing.GroupLayout painelSaidaEmbarcacaoLayout = new javax.swing.GroupLayout(painelSaidaEmbarcacao);
painelSaidaEmbarcacao.setLayout(painelSaidaEmbarcacaoLayout);
painelSaidaEmbarcacaoLayout.setHorizontalGroup(
    painelSaidaEmbarcacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(painelSaidaEmbarcacaoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(painelSaidaEmbarcacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelSaidaEmbarcacaoLayout.createSequentialGroup()
                .addComponent(sPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelSaidaEmbarcacaoLayout.createSequentialGroup()
                .addComponent(labelAreaNavegacao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboAreaNavegacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelViagem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoViagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    painelSaidaEmbarcacaoLayout.setVerticalGroup(
        painelSaidaEmbarcacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSaidaEmbarcacaoLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(painelSaidaEmbarcacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelAreaNavegacao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(comboAreaNavegacao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelViagem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(campoViagem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(painelSaidaEmbarcacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(sPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(pnlDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(25, Short.MAX_VALUE))
    );

    tabbedPaneChegadaSaida.addTab("Saída da Embarcação", painelSaidaEmbarcacao);

    textAreaComContador1.setMaxCaracteres(50);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.observacoes}"), textAreaComContador1, org.jdesktop.beansbinding.BeanProperty.create("texto"));
    bindingGroup.addBinding(binding);

    tabbedPaneChegadaSaida.addTab("Obs. Painel", textAreaComContador1);

    eLProperty = org.jdesktop.beansbinding.ELProperty.create("${model.acompanhamentos}");
    org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, sTable2);
    org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataHoraFormatada}"));
    columnBinding.setColumnName("Data");
    columnBinding.setColumnClass(String.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cadastradorFormatado}"));
    columnBinding.setColumnName("Cadastrador");
    columnBinding.setColumnClass(String.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${texto}"));
    columnBinding.setColumnName("Texto");
    columnBinding.setColumnClass(String.class);
    columnBinding.setEditable(false);
    bindingGroup.addBinding(jTableBinding);
    jTableBinding.bind();binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.acompanhamentoSelecionado}"), sTable2, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
    bindingGroup.addBinding(binding);

    jScrollPane2.setViewportView(sTable2);

    sButton1.setAction(actionAdicionarAcompanhamento);

    sButton2.setAction(actionEditarAcompanhamento);

    javax.swing.GroupLayout painelAcompanhamentoLayout = new javax.swing.GroupLayout(painelAcompanhamento);
    painelAcompanhamento.setLayout(painelAcompanhamentoLayout);
    painelAcompanhamentoLayout.setHorizontalGroup(
        painelAcompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelAcompanhamentoLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(painelAcompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(sButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );
    painelAcompanhamentoLayout.setVerticalGroup(
        painelAcompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAcompanhamentoLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelAcompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(painelAcompanhamentoLayout.createSequentialGroup()
                    .addComponent(sButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(sButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(308, 308, 308))
    );

    tabbedPaneChegadaSaida.addTab("Acompanhamentos", painelAcompanhamento);

    javax.swing.GroupLayout sPanel2Layout = new javax.swing.GroupLayout(sPanel2);
    sPanel2.setLayout(sPanel2Layout);
    sPanel2Layout.setHorizontalGroup(
        sPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(sPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(tabbedPaneChegadaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    sPanel2Layout.setVerticalGroup(
        sPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(tabbedPaneChegadaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 201, Short.MAX_VALUE)
    );

    labelTipoContrato.setText("Tipo Contrato:");

    campoTipoContrato.setEnabled(false);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.tipoContrato.porExtenso}"), campoTipoContrato, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    labelArmador1.setText("Frota:");

    eLProperty = org.jdesktop.beansbinding.ELProperty.create("${model.tipoFrota}");
    jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, comboArmador1);
    bindingGroup.addBinding(jComboBoxBinding);
    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.tipoFrota}"), comboArmador1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
    bindingGroup.addBinding(binding);

    checkBoxPlataforma.setText("Plataforma");
    checkBoxPlataforma.setOpaque(false);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.agenciamento.agenciamentoPlataforma}"), checkBoxPlataforma, org.jdesktop.beansbinding.BeanProperty.create("selected"));
    bindingGroup.addBinding(binding);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(4, 4, 4)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(labelAgencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelTipoContrato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelTipoAgenciamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoTipoContrato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelFusoHorario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelArmador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboFusoHorario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboArmador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelPorto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoPorto, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelArmador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboArmador1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(checkBoxCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(checkBoxProtecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(checkBoxPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(sPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE))
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {sPanel1, sPanel2});

    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(campoAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelFusoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(comboFusoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelPorto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(campoPorto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelArmador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(comboArmador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelTipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(campoTipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelArmador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(comboArmador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelTipoAgenciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(checkBoxCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(checkBoxProtecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(checkBoxPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(sPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(sPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.petrobras.fcorp.swing.base.action.GenericAction actionAdicionarAcompanhamento;
    private br.com.petrobras.fcorp.swing.base.action.GenericAction actionEditarAcompanhamento;
    private br.com.petrobras.fcorp.swing.components.STextField campoAgencia;
    br.com.petrobras.fcorp.swing.components.SFormattedTextField campoLatitude;
    br.com.petrobras.fcorp.swing.components.SFormattedTextField campoLongitude;
    private br.com.petrobras.fcorp.swing.components.STextField campoPorto;
    private br.com.petrobras.fcorp.swing.components.STextField campoTipoContrato;
    private br.com.petrobras.fcorp.swing.components.STextField campoViagem;
    private br.com.petrobras.fcorp.swing.components.STextField campoViagem1;
    private br.com.petrobras.fcorp.swing.components.SCheckBox checkBoxCarga;
    private br.com.petrobras.fcorp.swing.components.SCheckBox checkBoxPlataforma;
    private br.com.petrobras.fcorp.swing.components.SCheckBox checkBoxProtecao;
    private br.com.petrobras.fcorp.swing.components.SComboBox comboAreaNavegacao;
    private br.com.petrobras.fcorp.swing.components.SComboBox comboAreaNavegacao1;
    private br.com.petrobras.fcorp.swing.components.SComboBox comboArmador;
    private br.com.petrobras.fcorp.swing.components.SComboBox comboArmador1;
    private br.com.petrobras.sistam.desktop.components.TimeZoneComboBox comboFusoHorario;
    br.com.petrobras.sistam.desktop.components.SistamDateChooser dataChooserEta;
    br.com.petrobras.sistam.desktop.components.SistamDateChooser dateChooserDataEstimadaSaida;
    private br.com.petrobras.sistam.desktop.components.SistamDateChooser dateChooserEtaProxPorto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private br.com.petrobras.fcorp.swing.components.SLabel labelAgencia;
    private br.com.petrobras.fcorp.swing.components.SLabel labelAreaNavegacao;
    private br.com.petrobras.fcorp.swing.components.SLabel labelAreaNavegacao1;
    private br.com.petrobras.fcorp.swing.components.SLabel labelArmador;
    private br.com.petrobras.fcorp.swing.components.SLabel labelArmador1;
    private br.com.petrobras.fcorp.swing.components.SLabel labelFusoHorario;
    private br.com.petrobras.fcorp.swing.components.SLabel labelPorto;
    private br.com.petrobras.fcorp.swing.components.SLabel labelTipoAgenciamento;
    private br.com.petrobras.fcorp.swing.components.SLabel labelTipoContrato;
    private br.com.petrobras.fcorp.swing.components.SLabel labelViagem;
    private br.com.petrobras.fcorp.swing.components.SLabel labelViagem1;
    private br.com.petrobras.fcorp.swing.components.SPanel painelAcompanhamento;
    private br.com.petrobras.fcorp.swing.components.SPanel painelChegadaEmbarcacao;
    private br.com.petrobras.fcorp.swing.components.SPanel painelSaidaEmbarcacao;
    private br.com.petrobras.fcorp.swing.components.SPanel pnlDestino;
    private br.com.petrobras.fcorp.swing.components.SPanel pnlDestino2;
    private br.com.petrobras.fcorp.swing.components.SPanel pnlEscalas;
    private br.com.petrobras.fcorp.swing.components.SPanel pnlInformacoesExternas;
    private br.com.petrobras.sistam.desktop.components.lookups.porto.PortoLookup portoDestino;
    private br.com.petrobras.sistam.desktop.components.lookups.porto.PortoLookup portoOrigem1;
    private br.com.petrobras.fcorp.swing.components.SButton sButton1;
    private br.com.petrobras.fcorp.swing.components.SButton sButton2;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel13;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel14;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel15;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel16;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel17;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel18;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel19;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel20;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel35;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel36;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel37;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel38;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel39;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel40;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel41;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel69;
    private br.com.petrobras.fcorp.swing.components.SLabel sLabel70;
    private br.com.petrobras.fcorp.swing.components.SNumericTextField sNumericTextField10;
    private br.com.petrobras.fcorp.swing.components.SNumericTextField sNumericTextField11;
    private br.com.petrobras.fcorp.swing.components.SNumericTextField sNumericTextField6;
    private br.com.petrobras.fcorp.swing.components.SNumericTextField sNumericTextField7;
    private br.com.petrobras.fcorp.swing.components.SNumericTextField sNumericTextField9;
    private br.com.petrobras.fcorp.swing.components.SPanel sPanel1;
    private br.com.petrobras.fcorp.swing.components.SPanel sPanel10;
    private br.com.petrobras.fcorp.swing.components.SPanel sPanel11;
    private br.com.petrobras.fcorp.swing.components.SPanel sPanel2;
    private br.com.petrobras.fcorp.swing.components.SPanel sPanel8;
    private br.com.petrobras.fcorp.swing.components.SPanel sPanel9;
    private br.com.petrobras.fcorp.swing.components.STable sTable2;
    private br.com.petrobras.fcorp.swing.components.STextField sTextField5;
    private br.com.petrobras.fcorp.swing.components.STextField sTextField6;
    private br.com.petrobras.fcorp.swing.components.STextField sTextField7;
    private br.com.petrobras.fcorp.swing.components.STabbedPane tabbedPaneChegadaSaida;
    private br.com.petrobras.sistam.desktop.components.TextAreaComContador textAreaComContador1;
    private br.com.petrobras.sistam.desktop.components.SistamTimeChooser timeChooserEtaProxPorto;
    private br.com.petrobras.sistam.desktop.components.SistamTimeChooser timeChooserEts;
    private br.com.petrobras.sistam.desktop.components.SistamTimeChooser timeChooserHoraEta;
    private br.com.petrobras.sistam.desktop.components.SistamTimeChooser timeChooserHoraOficialChegada;
    private br.com.petrobras.sistam.desktop.components.SistamTimeChooser timeChosserHoraOficialSaida;
    private br.com.petrobras.fcorp.swing.components.STextArea txtListaEscalas;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables


}
