package br.com.petrobras.sistam.desktop.agenciamento.panels;

import br.com.petrobras.fcorp.swing.components.SPanel;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;

public class ManobrasPainelPrototipo extends SPanel{

    public ManobrasPainelPrototipo() {
        initComponents();
    }
    
    public void programar(){
        //SolicitacaoManobraDialog dialog = new SolicitacaoManobraDialog(SistamApp.getApplication().getMainFrame(), true);
        //dialog.setVisible(true);
    }
    
    public void registrar(){
        //SolicitacaoManobraDialog dialog = new SolicitacaoManobraDialog(SistamApp.getApplication().getMainFrame(), false);
        //dialog.setVisible(true);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionProgramar = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        actionEditarProgramacao = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        actionEditarRegistro = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        actionExcluir = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        actionRegistrarProgramacao = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        actionRegistrarManobra = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        tabManobras = new br.com.petrobras.fcorp.swing.components.STabbedPane();
        painelManobrasProgramadas = new br.com.petrobras.fcorp.swing.components.SPanel();
        painelManobras = new br.com.petrobras.fcorp.swing.components.SPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sTable1 = new br.com.petrobras.fcorp.swing.components.STable();
        sButton1 = new br.com.petrobras.fcorp.swing.components.SButton();
        sButton2 = new br.com.petrobras.fcorp.swing.components.SButton();
        sButton3 = new br.com.petrobras.fcorp.swing.components.SButton();
        sButton4 = new br.com.petrobras.fcorp.swing.components.SButton();
        painelServicos = new br.com.petrobras.fcorp.swing.components.SPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sTable2 = new br.com.petrobras.fcorp.swing.components.STable();
        painelManobrasRegistradas = new br.com.petrobras.fcorp.swing.components.SPanel();
        painelManobras1 = new br.com.petrobras.fcorp.swing.components.SPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sTable3 = new br.com.petrobras.fcorp.swing.components.STable();
        sButton9 = new br.com.petrobras.fcorp.swing.components.SButton();
        sButton10 = new br.com.petrobras.fcorp.swing.components.SButton();
        painelServicos1 = new br.com.petrobras.fcorp.swing.components.SPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        sTable4 = new br.com.petrobras.fcorp.swing.components.STable();

        actionProgramar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        actionProgramar.setMethodName("programar");
        actionProgramar.setTarget(this);
        actionProgramar.setText("Programar");
        actionProgramar.setToolTipText("Programa uma nova manobra");

        actionEditarProgramacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        actionEditarProgramacao.setText("Editar");
        actionEditarProgramacao.setToolTipText("Edita a manobra selecionada");

        actionEditarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        actionEditarRegistro.setText("Editar");
        actionEditarRegistro.setToolTipText("Edita a manobra selecionada");

        actionExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        actionExcluir.setText("Excluir");
        actionExcluir.setToolTipText("Exclui a manobra selecionada");

        actionRegistrarProgramacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/concluir.png"))); // NOI18N
        actionRegistrarProgramacao.setMethodName("registrar");
        actionRegistrarProgramacao.setTarget(this);
        actionRegistrarProgramacao.setText("Registrar");
        actionRegistrarProgramacao.setToolTipText("Registra a manobra selecionada");

        actionRegistrarManobra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/concluir.png"))); // NOI18N
        actionRegistrarManobra.setMethodName("registrar");
        actionRegistrarManobra.setTarget(this);
        actionRegistrarManobra.setText("Registrar");
        actionRegistrarManobra.setToolTipText("Registra a manobra selecionada");

        tabManobras.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        painelManobras.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de manobras"));

        sTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(sTable1);

        sButton1.setAction(actionRegistrarProgramacao);

        sButton2.setAction(actionExcluir);

        sButton3.setAction(actionEditarProgramacao);

        sButton4.setAction(actionProgramar);

        javax.swing.GroupLayout painelManobrasLayout = new javax.swing.GroupLayout(painelManobras);
        painelManobras.setLayout(painelManobrasLayout);
        painelManobrasLayout.setHorizontalGroup(
            painelManobrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManobrasLayout.createSequentialGroup()
                .addGroup(painelManobrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelManobrasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelManobrasLayout.setVerticalGroup(
            painelManobrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManobrasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelManobrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        painelServicos.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de serviços"));

        sTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(sTable2);

        javax.swing.GroupLayout painelServicosLayout = new javax.swing.GroupLayout(painelServicos);
        painelServicos.setLayout(painelServicosLayout);
        painelServicosLayout.setHorizontalGroup(
            painelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelServicosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelServicosLayout.setVerticalGroup(
            painelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelManobrasProgramadasLayout = new javax.swing.GroupLayout(painelManobrasProgramadas);
        painelManobrasProgramadas.setLayout(painelManobrasProgramadasLayout);
        painelManobrasProgramadasLayout.setHorizontalGroup(
            painelManobrasProgramadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManobrasProgramadasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelManobrasProgramadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelManobras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelManobrasProgramadasLayout.setVerticalGroup(
            painelManobrasProgramadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManobrasProgramadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelManobras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabManobras.addTab("Programadas", painelManobrasProgramadas);

        painelManobras1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de manobras"));

        sTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(sTable3);

        sButton9.setAction(actionEditarRegistro);

        sButton10.setAction(actionRegistrarProgramacao);

        javax.swing.GroupLayout painelManobras1Layout = new javax.swing.GroupLayout(painelManobras1);
        painelManobras1.setLayout(painelManobras1Layout);
        painelManobras1Layout.setHorizontalGroup(
            painelManobras1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManobras1Layout.createSequentialGroup()
                .addGroup(painelManobras1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelManobras1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelManobras1Layout.setVerticalGroup(
            painelManobras1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManobras1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addGroup(painelManobras1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        painelServicos1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de serviços"));

        sTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane4.setViewportView(sTable4);

        javax.swing.GroupLayout painelServicos1Layout = new javax.swing.GroupLayout(painelServicos1);
        painelServicos1.setLayout(painelServicos1Layout);
        painelServicos1Layout.setHorizontalGroup(
            painelServicos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelServicos1Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelServicos1Layout.setVerticalGroup(
            painelServicos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelManobrasRegistradasLayout = new javax.swing.GroupLayout(painelManobrasRegistradas);
        painelManobrasRegistradas.setLayout(painelManobrasRegistradasLayout);
        painelManobrasRegistradasLayout.setHorizontalGroup(
            painelManobrasRegistradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManobrasRegistradasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelManobrasRegistradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelManobras1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelServicos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelManobrasRegistradasLayout.setVerticalGroup(
            painelManobrasRegistradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManobrasRegistradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelManobras1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelServicos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabManobras.addTab("Registradas", painelManobrasRegistradas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabManobras, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabManobras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.petrobras.fcorp.swing.base.action.GenericAction actionEditarProgramacao;
    private br.com.petrobras.fcorp.swing.base.action.GenericAction actionEditarRegistro;
    private br.com.petrobras.fcorp.swing.base.action.GenericAction actionExcluir;
    private br.com.petrobras.fcorp.swing.base.action.GenericAction actionProgramar;
    private br.com.petrobras.fcorp.swing.base.action.GenericAction actionRegistrarManobra;
    private br.com.petrobras.fcorp.swing.base.action.GenericAction actionRegistrarProgramacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private br.com.petrobras.fcorp.swing.components.SPanel painelManobras;
    private br.com.petrobras.fcorp.swing.components.SPanel painelManobras1;
    private br.com.petrobras.fcorp.swing.components.SPanel painelManobrasProgramadas;
    private br.com.petrobras.fcorp.swing.components.SPanel painelManobrasRegistradas;
    private br.com.petrobras.fcorp.swing.components.SPanel painelServicos;
    private br.com.petrobras.fcorp.swing.components.SPanel painelServicos1;
    private br.com.petrobras.fcorp.swing.components.SButton sButton1;
    private br.com.petrobras.fcorp.swing.components.SButton sButton10;
    private br.com.petrobras.fcorp.swing.components.SButton sButton2;
    private br.com.petrobras.fcorp.swing.components.SButton sButton3;
    private br.com.petrobras.fcorp.swing.components.SButton sButton4;
    private br.com.petrobras.fcorp.swing.components.SButton sButton9;
    private br.com.petrobras.fcorp.swing.components.STable sTable1;
    private br.com.petrobras.fcorp.swing.components.STable sTable2;
    private br.com.petrobras.fcorp.swing.components.STable sTable3;
    private br.com.petrobras.fcorp.swing.components.STable sTable4;
    private br.com.petrobras.fcorp.swing.components.STabbedPane tabManobras;
    // End of variables declaration//GEN-END:variables

}
