package br.com.petrobras.sistam.desktop.agenciamento.panels;

import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.renderers.TableCellRendererDecorator;
import br.com.petrobras.fcorp.swing.components.util.TableUtils;
import br.com.petrobras.sistam.common.entity.Agenciamento;
import br.com.petrobras.sistam.common.entity.Taxa;
import br.com.petrobras.sistam.common.enums.StatusEmbarcacao;
import br.com.petrobras.sistam.desktop.SistamApp;
import br.com.petrobras.sistam.desktop.agenciamento.taxa.DetalheTaxaDialog;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JLabel;
import javax.swing.JTable;

public class TaxasPainel extends SPanel implements PropertyChangeListener{
    public static final String PROP_TAXA_ADICIONADA = "PROP_TAXA_ADICIONADA";
    public static final String PROP_TAXA_EXCLUIDA = "PROP_TAXA_EXCLUIDA";
    private TaxasPainelModel model;
    
    public TaxasPainel() {
        this.model = new TaxasPainelModel();
        initComponents();
        
        TableUtils.applyDecorator(tabelaTaxas, new TableCellRendererDecorator() {
            @Override
            protected void decorateLabel(JLabel label, JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                label.setForeground(Color.BLACK);
                if (isSelected) {
                    label.setBackground(Color.decode("#fdd898"));
                } else {
                    
                    label.setBackground(Color.decode("#e2ecf9"));
                }
            }
        });
    }

    public TaxasPainelModel getModel() {
        return model;
    }
    
    public void setAgenciamento(Agenciamento agenciamento){
        model.setAgenciamento(agenciamento);
    }
    
    public void adicionarNova(){
        Taxa nova = model.obterNovaTaxa();
        DetalheTaxaDialog dialog = new DetalheTaxaDialog(SistamApp.getSistamApp().getMainFrame(), nova);
        dialog.addPropertyChangeListener(this);
        dialog.setVisible(true);
        
        if (dialog.getModel().taxaAdicionada()){
            firePropertyChange(PROP_TAXA_ADICIONADA, null, null);
        }
    }
    
    public void editar(){
        Taxa nova = model.obterTaxaParaEdicaoVisualizacao();
        DetalheTaxaDialog dialog = new DetalheTaxaDialog(SistamApp.getSistamApp().getMainFrame(), nova);
        dialog.addPropertyChangeListener(this);
        dialog.setVisible(true);
    }
    
    public void excluir(){
        model.excluirTaxa();
        firePropertyChange(PROP_TAXA_EXCLUIDA, null, null);
    }
    
    
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
         if (evt.getPropertyName().equals(DetalheTaxaDialog.TAXA_INSERIDO)){
            Taxa taxa = ((DetalheTaxaDialog)evt.getSource()).getModel().getTaxa();
            model.adicionarTaxa(taxa);
        }
        
        if (evt.getPropertyName().equals(DetalheTaxaDialog.TAXA_ALTERADO)){
            Taxa taxa = ((DetalheTaxaDialog)evt.getSource()).getModel().getTaxa();
            model.atualizarTaxa(taxa);
        }
          
    }

    public void colocarEmModoVisualizacao() {
        painelBotoes.setVisible(false);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        actionAdicionar = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        actionExcluir = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        actionEditar = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        numberCellRenderer1 = new br.com.petrobras.fcorp.swing.components.renderers.NumberCellRenderer();
        painelListaTaxas = new br.com.petrobras.fcorp.swing.components.SPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTaxas = new br.com.petrobras.fcorp.swing.components.STable();
        painelBotoes = new br.com.petrobras.fcorp.swing.components.SPanel();
        botaoAdicionar = new br.com.petrobras.fcorp.swing.components.SButton();
        botaoEditar = new br.com.petrobras.fcorp.swing.components.SButton();
        botaoExcluir = new br.com.petrobras.fcorp.swing.components.SButton();

        actionAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        actionAdicionar.setMethodName("adicionarNova");
        actionAdicionar.setTarget(this);
        actionAdicionar.setText("Adicionar");
        actionAdicionar.setToolTipText("Adiciona uma nova taxa");

        actionExcluir.setConfirm("Confirma a exclusão da taxa?");
        actionExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        actionExcluir.setMethodName("excluir");
        actionExcluir.setTarget(this);
        actionExcluir.setText("Excluir");
        actionExcluir.setToolTipText("Exclui a taxa selecionada");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${not empty model.taxaSelecionada}"), actionExcluir, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        actionEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        actionEditar.setMethodName("editar");
        actionEditar.setTarget(this);
        actionEditar.setText("Editar");
        actionEditar.setToolTipText("Edita a taxa selecionada");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${not empty model.taxaSelecionada}"), actionEditar, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        painelListaTaxas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Taxas")));

        tabelaTaxas.setSortable(true);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${model.listaDeTaxas}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tabelaTaxas);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tipoTaxa}"));
        columnBinding.setColumnName("Tipo");
        columnBinding.setColumnClass(br.com.petrobras.sistam.common.enums.TipoTaxa.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valor}"));
        columnBinding.setColumnName("Valor (R$)");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataPagamento}"));
        columnBinding.setColumnName("Data Pagamento");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numeroNecessidadeLiberacaoSap}"));
        columnBinding.setColumnName("NL");
        columnBinding.setColumnClass(Long.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomeUsuarioAlteracao}"));
        columnBinding.setColumnName("Alterado por");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataAlteracao}"));
        columnBinding.setColumnName("Dt Alteração");
        columnBinding.setColumnClass(java.util.Date.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.taxaSelecionada}"), tabelaTaxas, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(tabelaTaxas);
        tabelaTaxas.getColumnModel().getColumn(1).setCellRenderer(numberCellRenderer1);

        javax.swing.GroupLayout painelListaTaxasLayout = new javax.swing.GroupLayout(painelListaTaxas);
        painelListaTaxas.setLayout(painelListaTaxasLayout);
        painelListaTaxasLayout.setHorizontalGroup(
            painelListaTaxasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
            .addGroup(painelListaTaxasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
        );
        painelListaTaxasLayout.setVerticalGroup(
            painelListaTaxasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
            .addGroup(painelListaTaxasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
        );

        painelBotoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelBotoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        botaoAdicionar.setAction(actionAdicionar);
        painelBotoes.add(botaoAdicionar);

        botaoEditar.setAction(actionEditar);
        painelBotoes.add(botaoEditar);

        botaoExcluir.setAction(actionExcluir);
        painelBotoes.add(botaoExcluir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelListaTaxas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelListaTaxas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.petrobras.fcorp.swing.base.action.GenericAction actionAdicionar;
    private br.com.petrobras.fcorp.swing.base.action.GenericAction actionEditar;
    private br.com.petrobras.fcorp.swing.base.action.GenericAction actionExcluir;
    private br.com.petrobras.fcorp.swing.components.SButton botaoAdicionar;
    private br.com.petrobras.fcorp.swing.components.SButton botaoEditar;
    private br.com.petrobras.fcorp.swing.components.SButton botaoExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private br.com.petrobras.fcorp.swing.components.renderers.NumberCellRenderer numberCellRenderer1;
    private br.com.petrobras.fcorp.swing.components.SPanel painelBotoes;
    private br.com.petrobras.fcorp.swing.components.SPanel painelListaTaxas;
    private br.com.petrobras.fcorp.swing.components.STable tabelaTaxas;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables


}
