package br.com.petrobras.sistam.desktop.agenciamento.formularios.policiaFederal;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SDateChooser;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SNumericTextField;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.SRadioPanel;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.renderers.ImageBooleanRenderer;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Agenciamento;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;

public class FormularioPasseEntradaPoliciaFederalDialog extends SDialog {
    private FormularioPasseEntradaPoliciaFederalModel model;
    
    public FormularioPasseEntradaPoliciaFederalDialog(java.awt.Frame parent, Agenciamento agenciamento) {
        super(parent, true);
        model = new FormularioPasseEntradaPoliciaFederalModel(agenciamento);
        initComponents();        
        setLocationRelativeTo(parent);  
        model.getEntradaPoliciaFederalVO().addPropertyChangeListener(model); 
       
    }

    public FormularioPasseEntradaPoliciaFederalModel getModel() {
        return model;
    }
    
    public void gerarFormulario(){
        model.validar();
        model.carregarVO();
        model.gerarFormulario();
        dispose();
    }  
     

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        actionGerarFormulario = new GenericAction();
        ImageBooleanRenderer imageBooleanGerado = new ImageBooleanRenderer();
        SPanel pnlPrincipal = new SPanel();
        SPanel pnlBotoes = new SPanel();
        SButton sButton1 = new SButton();
        SPanel panelPessoas1 = new SPanel();
        pnlListaControleFiscalizacaoUnico = new SRadioPanel();
        SLabel sLabel1 = new SLabel();
        SLabel sLabel2 = new SLabel();
        STextField txtAgenteArmador = new STextField();
        SLabel sLabel3 = new SLabel();
        SLabel sLabel4 = new SLabel();
        SLabel sLabel5 = new SLabel();
        SNumericTextField sntfTransito = new SNumericTextField();
        SLabel sLabel9 = new SLabel();
        STextField txtEscalas2 = new STextField();
        SNumericTextField sntfClandestino = new SNumericTextField();
        SNumericTextField sntfClandestino2 = new SNumericTextField();
        SLabel sLabel14 = new SLabel();
        SDateChooser sDateChooser3 = new SDateChooser();

        actionGerarFormulario.setIcon(new ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        actionGerarFormulario.setMethodName("gerarFormulario");
        actionGerarFormulario.setTarget(this);
        actionGerarFormulario.setText("Gerar Formulário");
        actionGerarFormulario.setToolTipText("Gera o formulário");

        imageBooleanGerado.setFalseIcon(new ImageIcon(getClass().getResource("/icons/props.png"))); // NOI18N
        imageBooleanGerado.setTrueIcon(new ImageIcon(getClass().getResource("/icons/document-accept.png"))); // NOI18N

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário Polícia Federal");

        pnlPrincipal.setBorder(BorderFactory.createEtchedBorder());
        pnlPrincipal.setName("pnlPrincipal"); // NOI18N

        pnlBotoes.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        pnlBotoes.setName("pnlBotoes"); // NOI18N

        sButton1.setAction(actionGerarFormulario);
        sButton1.setName("sButton1"); // NOI18N
        pnlBotoes.add(sButton1);

        panelPessoas1.setBorder(BorderFactory.createTitledBorder("Passe de Entrada de Embarcação"));
        panelPessoas1.setName("panelPessoas1"); // NOI18N

        pnlListaControleFiscalizacaoUnico.setBorder(BorderFactory.createTitledBorder(""));
        pnlListaControleFiscalizacaoUnico.setHorizontalGap(8);
        pnlListaControleFiscalizacaoUnico.setName("pnlListaControleFiscalizacaoUnico"); // NOI18N

        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.listaPasseAcessoPoliciaFederal}"), pnlListaControleFiscalizacaoUnico, BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.entradaPoliciaFederalVO.tipoPasseAcessoPoliciaFederal}"), pnlListaControleFiscalizacaoUnico, BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        GroupLayout pnlListaControleFiscalizacaoUnicoLayout = new GroupLayout(pnlListaControleFiscalizacaoUnico);
        pnlListaControleFiscalizacaoUnico.setLayout(pnlListaControleFiscalizacaoUnicoLayout);
        pnlListaControleFiscalizacaoUnicoLayout.setHorizontalGroup(
            pnlListaControleFiscalizacaoUnicoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlListaControleFiscalizacaoUnicoLayout.setVerticalGroup(
            pnlListaControleFiscalizacaoUnicoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        sLabel1.setText("Escalas:");
        sLabel1.setName("sLabel1"); // NOI18N

        sLabel2.setText("Carga:");
        sLabel2.setName("sLabel2"); // NOI18N

        txtAgenteArmador.setDocument(new GenericDocument(35));
        txtAgenteArmador.setName("txtAgenteArmador"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.carga}"), txtAgenteArmador, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sLabel3.setText("Passageiros para este Porto:");
        sLabel3.setName("sLabel3"); // NOI18N

        sLabel4.setText("Clandestinos/Impedidos:");
        sLabel4.setName("sLabel4"); // NOI18N

        sLabel5.setText("Outros:");
        sLabel5.setName("sLabel5"); // NOI18N

        sntfTransito.setIntegerPlaces(new Short((short)6));
        sntfTransito.setText("sNumericTextField1");
        sntfTransito.setName("sntfTransito"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.outros}"), sntfTransito, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        sLabel9.setText("GRU:");
        sLabel9.setName("sLabel9"); // NOI18N

        txtEscalas2.setDocument(new GenericDocument(35));
        txtEscalas2.setName("txtEscalas2"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.nrEscala}"), txtEscalas2, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sntfClandestino.setIntegerPlaces(new Short((short)6));
        sntfClandestino.setText("sNumericTextField1");
        sntfClandestino.setName("sntfClandestino"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.passageiroTransito}"), sntfClandestino, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        sntfClandestino2.setIntegerPlaces(new Short((short)6));
        sntfClandestino2.setName("sntfClandestino2"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.clandestinoImpedidos}"), sntfClandestino2, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        sLabel14.setText("Data do Documento:");
        sLabel14.setName("sLabel14"); // NOI18N

        sDateChooser3.setName("sDateChooser3"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.entradaPoliciaFederalVO.dataDocumento}"), sDateChooser3, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        GroupLayout panelPessoas1Layout = new GroupLayout(panelPessoas1);
        panelPessoas1.setLayout(panelPessoas1Layout);
        panelPessoas1Layout.setHorizontalGroup(
            panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoas1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sLabel1, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel2, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel3, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel4, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel5, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel9, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel14, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelPessoas1Layout.createSequentialGroup()
                        .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(txtAgenteArmador, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sntfTransito, GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(pnlListaControleFiscalizacaoUnico, GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(txtEscalas2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sntfClandestino, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sntfClandestino2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(panelPessoas1Layout.createSequentialGroup()
                        .addComponent(sDateChooser3, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelPessoas1Layout.setVerticalGroup(
            panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEscalas2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAgenteArmador, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfClandestino, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfClandestino2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sntfTransito, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(pnlListaControleFiscalizacaoUnico, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sLabel14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sDateChooser3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        GroupLayout pnlPrincipalLayout = new GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(panelPessoas1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPessoas1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlPrincipal, BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    GenericAction actionGerarFormulario;
    SRadioPanel pnlListaControleFiscalizacaoUnico;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
