package br.com.petrobras.sistam.desktop.agenciamento.manobras;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SDateChooser;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STimeChooser;
import br.com.petrobras.sistam.desktop.components.lookups.porto.PortoLookup;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;

public class InformacoesDoAgenciamentoDialog extends SDialog{
    private InformacoesDoAgenciamentoDialogModel model;
    
    public InformacoesDoAgenciamentoDialog(java.awt.Frame parent) {
        super(parent, true);
        this.model = new InformacoesDoAgenciamentoDialogModel();
        initComponents();
        setLocationRelativeTo(parent); 
    }

    public InformacoesDoAgenciamentoDialogModel getModel() {
        return model;
    }
    
    public void confirmar(){
        model.confirmar();
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();
        GenericAction actionOk = new GenericAction();
        pnlBotoes = new SPanel();
        SButton btnSalvar = new SButton();
        painelInformacoesAgenciamento = new SPanel();
        SLabel sLabel37 = new SLabel();
        PortoLookup portoDestino = new PortoLookup();
        SLabel sLabel19 = new SLabel();
        SDateChooser dtEtaProxPorto = new SDateChooser();
        STimeChooser hrEtaProxPorto = new STimeChooser();

        actionOk.setMethodName("confirmar");
        actionOk.setTarget(this);
        actionOk.setText("Ok");
        actionOk.setToolTipText("Confirma os dados informados");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informações do agenciamento");

        pnlBotoes.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        pnlBotoes.setName("pnlBotoes"); // NOI18N

        btnSalvar.setAction(actionOk);
        btnSalvar.setName("btnSalvar"); // NOI18N
        pnlBotoes.add(btnSalvar);

        painelInformacoesAgenciamento.setBorder(BorderFactory.createTitledBorder("Informações do Agenciamento"));
        painelInformacoesAgenciamento.setName("painelInformacoesAgenciamento"); // NOI18N

        sLabel37.setText("Porto Destino:");
        sLabel37.setName("sLabel37"); // NOI18N

        portoDestino.setName("portoDestino"); // NOI18N

        Binding binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.portoDestino}"), portoDestino, BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        sLabel19.setText("ETA Próx. Porto:");
        sLabel19.setName("sLabel19"); // NOI18N

        dtEtaProxPorto.setTimeChooser(hrEtaProxPorto);
        dtEtaProxPorto.setName("dtEtaProxPorto"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.eta}"), dtEtaProxPorto, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        hrEtaProxPorto.setName("hrEtaProxPorto"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.habilitarEta}"), hrEtaProxPorto, BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        GroupLayout painelInformacoesAgenciamentoLayout = new GroupLayout(painelInformacoesAgenciamento);
        painelInformacoesAgenciamento.setLayout(painelInformacoesAgenciamentoLayout);
        painelInformacoesAgenciamentoLayout.setHorizontalGroup(
            painelInformacoesAgenciamentoLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(painelInformacoesAgenciamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInformacoesAgenciamentoLayout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(sLabel19, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel37, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(painelInformacoesAgenciamentoLayout.createParallelGroup(Alignment.LEADING)
                    .addGroup(painelInformacoesAgenciamentoLayout.createSequentialGroup()
                        .addComponent(dtEtaProxPorto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(hrEtaProxPorto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 125, Short.MAX_VALUE))
                    .addComponent(portoDestino, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelInformacoesAgenciamentoLayout.setVerticalGroup(
            painelInformacoesAgenciamentoLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(painelInformacoesAgenciamentoLayout.createSequentialGroup()
                .addGroup(painelInformacoesAgenciamentoLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(sLabel37, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(portoDestino, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(painelInformacoesAgenciamentoLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(sLabel19, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtEtaProxPorto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEtaProxPorto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addComponent(pnlBotoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelInformacoesAgenciamento, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(painelInformacoesAgenciamento, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(pnlBotoes, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    SPanel painelInformacoesAgenciamento;
    SPanel pnlBotoes;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
