package br.com.petrobras.sistam.desktop.servicoprotecao;

import br.com.petrobras.fcorp.swing.base.SInternalFrame;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SFormattedTextField;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STable;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.sistam.common.entity.EmpresaProtecao;
import br.com.petrobras.sistam.desktop.SistamApp;
import br.com.petrobras.sistam.desktop.util.DesktopUtil;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 * @author adzk
 */
public class EmpresaProtecaoFrame extends SInternalFrame {

    private EmpresaProtecaoModel model;

    /**
     * Construtor padrão.
     */
    public EmpresaProtecaoFrame() {
        this.model = new EmpresaProtecaoModel();
        initComponents();
        DesktopUtil.configurarComponenteCNPJ(campoCnpj, actionPesquisar);
    }

    public EmpresaProtecaoModel getModel() {
        return model;
    }

    public void pesquisar() {
        model.pesquisar();
    }

    public void limparPesquisa() {
        model.limparPesquisa();
    }

    public void adicionar() {
        EmpresaProtecao empresa = model.obterNovaEmpresa();
        DetalhesEmpresaProtecaoDialog dialog = new DetalhesEmpresaProtecaoDialog(SistamApp.getSistamApp().getMainFrame(), empresa);
        dialog.setVisible(true);

        if (dialog.getModel().isSalvo()) {
            limparPesquisa();
            pesquisar();
        }
    }

    public void editar() {
        EmpresaProtecao empresa = model.obterEmpresaParaEdicao();
        DetalhesEmpresaProtecaoDialog dialog = new DetalhesEmpresaProtecaoDialog(SistamApp.getSistamApp().getMainFrame(), empresa);
        dialog.setVisible(true);

        if (dialog.getModel().isSalvo()) {
            limparPesquisa();
            pesquisar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"})
    @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        br.com.petrobras.fcorp.swing.base.action.GenericAction actionAdicionar = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        br.com.petrobras.fcorp.swing.base.action.GenericAction actionEditar = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        actionPesquisar = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        br.com.petrobras.fcorp.swing.base.action.GenericAction actionLimpar = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        br.com.petrobras.fcorp.swing.components.SPanel panelFiltros = new br.com.petrobras.fcorp.swing.components.SPanel();
        br.com.petrobras.fcorp.swing.components.SLabel labelCnpj = new br.com.petrobras.fcorp.swing.components.SLabel();
        campoCnpj = new br.com.petrobras.fcorp.swing.components.SFormattedTextField();
        br.com.petrobras.fcorp.swing.components.SLabel labelEmpresa = new br.com.petrobras.fcorp.swing.components.SLabel();
        br.com.petrobras.fcorp.swing.components.SButton sButton3 = new br.com.petrobras.fcorp.swing.components.SButton();
        br.com.petrobras.fcorp.swing.components.SButton sButton4 = new br.com.petrobras.fcorp.swing.components.SButton();
        br.com.petrobras.fcorp.swing.components.STextField campoEmpresa = new br.com.petrobras.fcorp.swing.components.STextField();
        br.com.petrobras.fcorp.swing.components.SPanel panelLista = new br.com.petrobras.fcorp.swing.components.SPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        br.com.petrobras.fcorp.swing.components.STable sTable1 = new br.com.petrobras.fcorp.swing.components.STable();
        br.com.petrobras.fcorp.swing.components.SPanel panelBotos = new br.com.petrobras.fcorp.swing.components.SPanel();
        br.com.petrobras.fcorp.swing.components.SButton sButton1 = new br.com.petrobras.fcorp.swing.components.SButton();
        br.com.petrobras.fcorp.swing.components.SButton sButton2 = new br.com.petrobras.fcorp.swing.components.SButton();

        actionAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        actionAdicionar.setMethodName("adicionar");
        actionAdicionar.setTarget(this);
        actionAdicionar.setText("Adicionar");

        actionEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        actionEditar.setMethodName("editar");
        actionEditar.setTarget(this);
        actionEditar.setText("Editar");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.empresaSelecionada != null}"), actionEditar, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        actionPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/listagem_busca.png"))); // NOI18N
        actionPesquisar.setMethodName("pesquisar");
        actionPesquisar.setTarget(this);
        actionPesquisar.setText("Pesquisar");

        actionLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/limpar1.png"))); // NOI18N
        actionLimpar.setMethodName("limparPesquisa");
        actionLimpar.setTarget(this);
        actionLimpar.setText("Limpar");
        actionLimpar.setToolTipText("Limpar filltros de pesquisa");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empresas do Serviço de Proteção");

        panelFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));
        panelFiltros.setName("panelFiltros"); // NOI18N

        labelCnpj.setText("CNPJ:");
        labelCnpj.setName("labelCnpj"); // NOI18N

        campoCnpj.setName("campoCnpj"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.filtro.cnpjComMascara}"), campoCnpj, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        labelEmpresa.setText("Empresa:");
        labelEmpresa.setName("labelEmpresa"); // NOI18N

        sButton3.setAction(actionLimpar);
        sButton3.setName("sButton3"); // NOI18N

        sButton4.setAction(actionPesquisar);
        sButton4.setName("sButton4"); // NOI18N

        campoEmpresa.setName("campoEmpresa"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.filtro.razaoSocial}"), campoEmpresa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout panelFiltrosLayout = new javax.swing.GroupLayout(panelFiltros);
        panelFiltros.setLayout(panelFiltrosLayout);
        panelFiltrosLayout.setHorizontalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFiltrosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFiltrosLayout.createSequentialGroup()
                        .addComponent(labelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(labelCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelFiltrosLayout.setVerticalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelLista.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Empresas"));
        panelLista.setName("panelLista"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        sTable1.setSortable(true);
        sTable1.setName("sTable1"); // NOI18N

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${model.empresas}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, sTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${razaoSocial}"));
        columnBinding.setColumnName("Empresa");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cnpjComMascara}"));
        columnBinding.setColumnName("CNPJ");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${email}"));
        columnBinding.setColumnName("E-mail");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricaoServicos}"));
        columnBinding.setColumnName("Serviços");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ativa}"));
        columnBinding.setColumnName("Ativa?");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.empresaSelecionada}"), sTable1, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(sTable1);
        sTable1.getColumnModel().getColumn(1).setMinWidth(150);
        sTable1.getColumnModel().getColumn(1).setMaxWidth(150);
        sTable1.getColumnModel().getColumn(2).setMinWidth(200);
        sTable1.getColumnModel().getColumn(2).setMaxWidth(200);
        sTable1.getColumnModel().getColumn(4).setMinWidth(70);
        sTable1.getColumnModel().getColumn(4).setMaxWidth(70);

        javax.swing.GroupLayout panelListaLayout = new javax.swing.GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelListaLayout.setVerticalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBotos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBotos.setName("panelBotos"); // NOI18N

        sButton1.setAction(actionAdicionar);
        sButton1.setName("sButton1"); // NOI18N
        panelBotos.add(sButton1);

        sButton2.setAction(actionEditar);
        sButton2.setName("sButton2"); // NOI18N
        panelBotos.add(sButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON
    // Variables declaration - do not modify//GEN-BEGIN:variables
    br.com.petrobras.fcorp.swing.base.action.GenericAction actionPesquisar;
    br.com.petrobras.fcorp.swing.components.SFormattedTextField campoCnpj;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
