package br.com.petrobras.sistam.desktop.agenciamento.formularios.policiaFederal;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SDateChooser;
import br.com.petrobras.fcorp.swing.components.SFormattedTextField;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SNumericTextField;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.SRadioPanel;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.renderers.ImageBooleanRenderer;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Agenciamento;
import br.com.petrobras.sistam.desktop.util.DesktopUtil;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

public class FormularioControleFiscalizacaoUnicoDialog extends SDialog {
    private FormularioControleFiscalizacaoUnicoModel model;
    
    public FormularioControleFiscalizacaoUnicoDialog(java.awt.Frame parent, Agenciamento agenciamento) {
        super(parent, true);
        model = new FormularioControleFiscalizacaoUnicoModel(agenciamento);
        initComponents();        
        setLocationRelativeTo(parent); 
        DesktopUtil.configurarComponenteCNPJ(campoCnpj, actionGerarFormulario);
        model.getControleFiscalizacaoUnicoVO().addPropertyChangeListener(model);
        validarPainelEntradaSaida();
        borderPainelEntrdaSaidaEListaControleFiscalizacaoUnicoNull();
        pnlEntradaSaida.setEnabled(false);
       
    }

    public FormularioControleFiscalizacaoUnicoModel getModel() {
        return model;
    }
    
    public void gerarFormulario(){
        model.validar();
        model.carregarVO();
        model.gerarFormulario();
        dispose();
    }
    
    
    
    public final void validarPainelEntradaSaida() {

        if (model.isTipoAgenciaManaus()) {
            txtPortoEntradaBrasil.setEnabled(true);
             txtProcedencia.setEnabled(false);
            txtDestino.setEnabled(false);
        }  else{
            txtPortoEntradaBrasil.setEnabled(false);
            txtProcedencia.setEnabled(true);
            txtDestino.setEnabled(true);
        }
    }
     
    
    public final void borderPainelEntrdaSaidaEListaControleFiscalizacaoUnicoNull() {
        pnlEntradaSaida.setBorder(null);
        pnlListaControleFiscalizacaoUnico.setBorder(null);
    }
    
     

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        actionGerarFormulario = new GenericAction();
        ImageBooleanRenderer imageBooleanGerado = new ImageBooleanRenderer();
        SPanel pnlPrincipal = new SPanel();
        SPanel pnlBotoes = new SPanel();
        SButton sButton1 = new SButton();
        SPanel panelPessoas1 = new SPanel();
        pnlListaControleFiscalizacaoUnico = new SRadioPanel();
        SLabel sLabel1 = new SLabel();
        SLabel sLabel2 = new SLabel();
        STextField txtAgenteArmador = new STextField();
        SLabel sLabel3 = new SLabel();
        STextField txtEscalas = new STextField();
        SLabel sLabel4 = new SLabel();
        STextField txtProdutoCarga = new STextField();
        SLabel sLabel5 = new SLabel();
        SNumericTextField sntfTransito = new SNumericTextField();
        SLabel sLabel6 = new SLabel();
        SNumericTextField sntfClandestino = new SNumericTextField();
        SPanel panelPessoas = new SPanel();
        SComboBox sComboBox1 = new SComboBox();
        campoCnpj = new SFormattedTextField();
        SLabel sLabel7 = new SLabel();
        txtPortoEntradaBrasil = new STextField();
        pnlEntradaSaida = new SRadioPanel();
        SDateChooser sDateChooser2 = new SDateChooser();
        SLabel sLabel8 = new SLabel();
        SLabel sLabel9 = new SLabel();
        txtProcedencia = new STextField();
        SLabel sLabel10 = new SLabel();
        txtDestino = new STextField();

        actionGerarFormulario.setIcon(new ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        actionGerarFormulario.setMethodName("gerarFormulario");
        actionGerarFormulario.setTarget(this);
        actionGerarFormulario.setText("Gerar Formulário");
        actionGerarFormulario.setToolTipText("Gera o formulário");

        imageBooleanGerado.setFalseIcon(new ImageIcon(getClass().getResource("/icons/props.png"))); // NOI18N
        imageBooleanGerado.setTrueIcon(new ImageIcon(getClass().getResource("/icons/document-accept.png"))); // NOI18N

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário Polícia Federal");

        pnlPrincipal.setBorder(BorderFactory.createEtchedBorder());
        pnlPrincipal.setName("pnlPrincipal"); // NOI18N

        pnlBotoes.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        pnlBotoes.setName("pnlBotoes"); // NOI18N

        sButton1.setAction(actionGerarFormulario);
        sButton1.setName("sButton1"); // NOI18N
        pnlBotoes.add(sButton1);

        panelPessoas1.setBorder(BorderFactory.createTitledBorder("Informações Complementares"));
        panelPessoas1.setName("panelPessoas1"); // NOI18N

        pnlListaControleFiscalizacaoUnico.setBorder(BorderFactory.createTitledBorder(""));
        pnlListaControleFiscalizacaoUnico.setAlignment(0);
        pnlListaControleFiscalizacaoUnico.setHorizontalGap(0);
        pnlListaControleFiscalizacaoUnico.setName("pnlListaControleFiscalizacaoUnico"); // NOI18N

        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.listaControleFiscalizacaoUnico}"), pnlListaControleFiscalizacaoUnico, BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.controleFiscalizacaoUnicoVO.tipoControleFiscalizacaoUnico}"), pnlListaControleFiscalizacaoUnico, BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        GroupLayout pnlListaControleFiscalizacaoUnicoLayout = new GroupLayout(pnlListaControleFiscalizacaoUnico);
        pnlListaControleFiscalizacaoUnico.setLayout(pnlListaControleFiscalizacaoUnicoLayout);
        pnlListaControleFiscalizacaoUnicoLayout.setHorizontalGroup(
            pnlListaControleFiscalizacaoUnicoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );
        pnlListaControleFiscalizacaoUnicoLayout.setVerticalGroup(
            pnlListaControleFiscalizacaoUnicoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        sLabel1.setText("CNPJ Armador:");
        sLabel1.setName("sLabel1"); // NOI18N

        sLabel2.setText("Agente Armador:");
        sLabel2.setName("sLabel2"); // NOI18N

        txtAgenteArmador.setDocument(new GenericDocument(50));
        txtAgenteArmador.setName("txtAgenteArmador"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agenteArmador}"), txtAgenteArmador, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sLabel3.setText("Escalas:");
        sLabel3.setName("sLabel3"); // NOI18N

        txtEscalas.setDocument(new GenericDocument(50));
        txtEscalas.setName("txtEscalas"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.nrEscala}"), txtEscalas, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sLabel4.setText("Produto da Carga:");
        sLabel4.setName("sLabel4"); // NOI18N

        txtProdutoCarga.setDocument(new GenericDocument(50));
        txtProdutoCarga.setName("txtProdutoCarga"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.produtoCarga}"), txtProdutoCarga, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sLabel5.setText("Trânsito:");
        sLabel5.setName("sLabel5"); // NOI18N

        sntfTransito.setText("sNumericTextField1");
        sntfTransito.setName("sntfTransito"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.saidaTransito}"), sntfTransito, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        sLabel6.setText("Clandestinos/Impedidos:");
        sLabel6.setName("sLabel6"); // NOI18N

        sntfClandestino.setText("sNumericTextField1");
        sntfClandestino.setName("sntfClandestino"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.clandestinoImpedidos}"), sntfClandestino, BeanProperty.create("integerValue"));
        bindingGroup.addBinding(binding);

        panelPessoas.setBorder(BorderFactory.createTitledBorder("Representante Legal"));
        panelPessoas.setName("panelPessoas"); // NOI18N

        sComboBox1.setName("sComboBox1"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.agenciamento.agencia.representantes}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, sComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.representanteSelecionado}"), sComboBox1, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        GroupLayout panelPessoasLayout = new GroupLayout(panelPessoas);
        panelPessoas.setLayout(panelPessoasLayout);
        panelPessoasLayout.setHorizontalGroup(
            panelPessoasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sComboBox1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPessoasLayout.setVerticalGroup(
            panelPessoasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        campoCnpj.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter()));
        campoCnpj.setName("campoCnpj"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.armadorCnpjComMascara}"), campoCnpj, BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        sLabel7.setText("Porto de Entrada no Brasil/Data:");
        sLabel7.setName("sLabel7"); // NOI18N

        txtPortoEntradaBrasil.setDocument(new GenericDocument(50));
        txtPortoEntradaBrasil.setName("txtPortoEntradaBrasil"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.portoEntradaBrasil}"), txtPortoEntradaBrasil, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        pnlEntradaSaida.setBorder(BorderFactory.createTitledBorder(""));
        pnlEntradaSaida.setName("pnlEntradaSaida"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.listaEntradaSaida}"), pnlEntradaSaida, BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.habilitar}"), pnlEntradaSaida, BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.controleFiscalizacaoUnicoVO.controleFiscalizacaoUnicoEntradaSaida}"), pnlEntradaSaida, BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        GroupLayout pnlEntradaSaidaLayout = new GroupLayout(pnlEntradaSaida);
        pnlEntradaSaida.setLayout(pnlEntradaSaidaLayout);
        pnlEntradaSaidaLayout.setHorizontalGroup(
            pnlEntradaSaidaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        pnlEntradaSaidaLayout.setVerticalGroup(
            pnlEntradaSaidaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        sDateChooser2.setName("sDateChooser2"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.controleFiscalizacaoUnicoVO.dataDocumento}"), sDateChooser2, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel8.setText("Data:");
        sLabel8.setName("sLabel8"); // NOI18N

        sLabel9.setText("Procedência:");
        sLabel9.setName("sLabel9"); // NOI18N

        txtProcedencia.setDocument(new GenericDocument(50));
        txtProcedencia.setName("txtProcedencia"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.procedencia}"), txtProcedencia, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sLabel10.setText("Destino:");
        sLabel10.setName("sLabel10"); // NOI18N

        txtDestino.setDocument(new GenericDocument(50));
        txtDestino.setName("txtDestino"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.destino}"), txtDestino, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        GroupLayout panelPessoas1Layout = new GroupLayout(panelPessoas1);
        panelPessoas1.setLayout(panelPessoas1Layout);
        panelPessoas1Layout.setHorizontalGroup(
            panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sLabel8, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel7, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel6, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel5, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel4, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel3, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel10, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel9, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel2, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel1, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelPessoas1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(pnlListaControleFiscalizacaoUnico, GroupLayout.PREFERRED_SIZE, 205, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlEntradaSaida, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelPessoas1Layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(txtProcedencia, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAgenteArmador, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDestino, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtProdutoCarga, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sntfTransito, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sntfClandestino, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEscalas, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPortoEntradaBrasil, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoCnpj, GroupLayout.PREFERRED_SIZE, 165, GroupLayout.PREFERRED_SIZE)
                            .addComponent(sDateChooser2, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addComponent(panelPessoas, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPessoas1Layout.setVerticalGroup(
            panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoas1Layout.createSequentialGroup()
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelPessoas1Layout.createSequentialGroup()
                        .addComponent(pnlListaControleFiscalizacaoUnico, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(GroupLayout.Alignment.TRAILING, panelPessoas1Layout.createSequentialGroup()
                        .addComponent(pnlEntradaSaida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addGroup(panelPessoas1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelPessoas1Layout.createSequentialGroup()
                        .addComponent(campoCnpj, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAgenteArmador, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProcedencia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtDestino, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEscalas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProdutoCarga, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sntfTransito, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sntfClandestino, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPortoEntradaBrasil, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sDateChooser2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPessoas1Layout.createSequentialGroup()
                        .addComponent(sLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sLabel9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(sLabel10, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sLabel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sLabel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sLabel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sLabel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPessoas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GroupLayout pnlPrincipalLayout = new GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(panelPessoas1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotoes, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPessoas1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlPrincipal, BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    GenericAction actionGerarFormulario;
    SFormattedTextField campoCnpj;
    SRadioPanel pnlEntradaSaida;
    SRadioPanel pnlListaControleFiscalizacaoUnico;
    STextField txtDestino;
    STextField txtPortoEntradaBrasil;
    STextField txtProcedencia;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
