package br.com.petrobras.sistam.desktop.agenciamento.protecao.formularios.receita;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SDateChooser;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STable;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.renderers.ImageBooleanRenderer;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.ServicoAcessoPessoa;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

public class FormulatorioReceitaPrestacaoServicoDialog extends SDialog {
    private FormulatorioReceitaPrestacaoServicoModel model;
    
    public FormulatorioReceitaPrestacaoServicoDialog(java.awt.Frame parent, ServicoAcessoPessoa servicoAcessoPessoa) {
        super(parent, true);
        model = new FormulatorioReceitaPrestacaoServicoModel(servicoAcessoPessoa);
        initComponents();        
        setLocationRelativeTo(parent);        
    }

    public FormulatorioReceitaPrestacaoServicoModel getModel() {
        return model;
    }
    
    public void gerarFormulario(){
        model.validar();
        model.gerarFormulario();
        dispose();
    }

    public void adicionarVeiculo(){
        model.adicionarVeiculo();
    }
    
    public void excluirVeiculo(){
        model.excluirVeiculo();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        GenericAction actionGerarFormulario = new GenericAction();
        ImageBooleanRenderer imageBooleanGerado = new ImageBooleanRenderer();
        GenericAction actionAdicionarVeiculo = new GenericAction();
        GenericAction actionExcluirVeiculo = new GenericAction();
        SPanel pnlPrincipal = new SPanel();
        SPanel panelPessoas = new SPanel();
        JScrollPane jScrollPane2 = new JScrollPane();
        STable tabelaPessoa = new STable();
        SPanel sPanel1 = new SPanel();
        SLabel sLabel1 = new SLabel();
        SLabel sLabel3 = new SLabel();
        SPanel panelOutrasInfo = new SPanel();
        SLabel sLabel2 = new SLabel();
        SLabel sLabel4 = new SLabel();
        SLabel sLabel5 = new SLabel();
        STextField sTextField1 = new STextField();
        STextField sTextField2 = new STextField();
        SDateChooser sDateChooser1 = new SDateChooser();
        SDateChooser sDateChooser2 = new SDateChooser();
        SLabel sLabel6 = new SLabel();
        SLabel sLabel7 = new SLabel();
        SLabel sLabel8 = new SLabel();
        STextField sTextField3 = new STextField();
        STextField sTextField4 = new STextField();
        SPanel pnlBotoes = new SPanel();
        SButton sButton1 = new SButton();
        SPanel panelVeiculos = new SPanel();
        SLabel sLabel9 = new SLabel();
        SLabel sLabel10 = new SLabel();
        STextField sTextField5 = new STextField();
        STextField sTextField6 = new STextField();
        JScrollPane jScrollPane3 = new JScrollPane();
        STable tabelaVeiculo = new STable();
        SButton sButton2 = new SButton();
        SButton sButton3 = new SButton();

        actionGerarFormulario.setIcon(new ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        actionGerarFormulario.setMethodName("gerarFormulario");
        actionGerarFormulario.setTarget(this);
        actionGerarFormulario.setText("Gerar Formulário");
        actionGerarFormulario.setToolTipText("Gera o formulário");

        imageBooleanGerado.setFalseIcon(new ImageIcon(getClass().getResource("/icons/props.png"))); // NOI18N
        imageBooleanGerado.setTrueIcon(new ImageIcon(getClass().getResource("/icons/document-accept.png"))); // NOI18N

        actionAdicionarVeiculo.setIcon(new ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        actionAdicionarVeiculo.setMethodName("adicionarVeiculo");
        actionAdicionarVeiculo.setTarget(this);

        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.habilitarAdicionarVeiculo}"), actionAdicionarVeiculo, BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        actionExcluirVeiculo.setConfirm("");
        actionExcluirVeiculo.setIcon(new ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        actionExcluirVeiculo.setMethodName("excluirVeiculo");
        actionExcluirVeiculo.setTarget(this);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.veiculoSelecionado != null}"), actionExcluirVeiculo, BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Pedido para Prestação de Serviço");

        pnlPrincipal.setName("pnlPrincipal"); // NOI18N

        panelPessoas.setBorder(BorderFactory.createTitledBorder("Pessoas"));
        panelPessoas.setName("panelPessoas"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tabelaPessoa.setSortable(true);
        tabelaPessoa.setName("tabelaPessoa"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.filtro.pessoas}");
        JTableBinding jTableBinding = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tabelaPessoa);
        JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${selecionado}"));
        columnBinding.setColumnName("");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${pessoa.nome}"));
        columnBinding.setColumnName("Pessoa");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${pessoa.formularioGeradoPrestacaoServico}"));
        columnBinding.setColumnName("");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tabelaPessoa);
        tabelaPessoa.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabelaPessoa.getColumnModel().getColumn(0).setMaxWidth(20);
        tabelaPessoa.getColumnModel().getColumn(2).setPreferredWidth(20);
        tabelaPessoa.getColumnModel().getColumn(2).setMaxWidth(20);
        tabelaPessoa.getColumnModel().getColumn(2).setCellRenderer(imageBooleanGerado);

        GroupLayout panelPessoasLayout = new GroupLayout(panelPessoas);
        panelPessoas.setLayout(panelPessoasLayout);
        panelPessoasLayout.setHorizontalGroup(
            panelPessoasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(panelPessoasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(panelPessoasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelPessoasLayout.setVerticalGroup(
            panelPessoasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
            .addGroup(panelPessoasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(panelPessoasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        sPanel1.setBorder(BorderFactory.createTitledBorder("Legenda"));
        sPanel1.setName("sPanel1"); // NOI18N
        sPanel1.setOpaque(false);

        sLabel1.setIcon(new ImageIcon(getClass().getResource("/icons/document-accept.png"))); // NOI18N
        sLabel1.setText("Formulário Gerado");
        sLabel1.setName("sLabel1"); // NOI18N

        sLabel3.setIcon(new ImageIcon(getClass().getResource("/icons/props.png"))); // NOI18N
        sLabel3.setText("Formulário Não Gerado");
        sLabel3.setName("sLabel3"); // NOI18N

        GroupLayout sPanel1Layout = new GroupLayout(sPanel1);
        sPanel1.setLayout(sPanel1Layout);
        sPanel1Layout.setHorizontalGroup(
            sPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sPanel1Layout.setVerticalGroup(
            sPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOutrasInfo.setBorder(BorderFactory.createTitledBorder("Informações Complementares"));
        panelOutrasInfo.setName("panelOutrasInfo"); // NOI18N

        sLabel2.setText("Nº do Documento:");
        sLabel2.setName("sLabel2"); // NOI18N

        sLabel4.setText("Período:");
        sLabel4.setName("sLabel4"); // NOI18N

        sLabel5.setText("Lancha Apoio Marítimo:");
        sLabel5.setName("sLabel5"); // NOI18N

        sTextField1.setDocument(new GenericDocument(15));
        sTextField1.setName("sTextField1"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.numeroDocumento}"), sTextField1, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sTextField2.setDocument(new GenericDocument(50));
        sTextField2.setName("sTextField2"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.lancha}"), sTextField2, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sDateChooser1.setName("sDateChooser1"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoFim}"), sDateChooser1, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sDateChooser2.setName("sDateChooser2"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoInicio}"), sDateChooser2, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sLabel6.setText("a");
        sLabel6.setName("sLabel6"); // NOI18N

        sLabel7.setText("Descrição da Operação:");
        sLabel7.setName("sLabel7"); // NOI18N

        sLabel8.setText("Nº do Termo Responsabilidade:");
        sLabel8.setName("sLabel8"); // NOI18N

        sTextField3.setDocument(new GenericDocument(50));
        sTextField3.setName("sTextField3"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.descricaoOperacao}"), sTextField3, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sTextField4.setDocument(new GenericDocument(50));
        sTextField4.setName("sTextField4"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.numeroTermoResponsabilidade}"), sTextField4, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        GroupLayout panelOutrasInfoLayout = new GroupLayout(panelOutrasInfo);
        panelOutrasInfo.setLayout(panelOutrasInfoLayout);
        panelOutrasInfoLayout.setHorizontalGroup(
            panelOutrasInfoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelOutrasInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOutrasInfoLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(sLabel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOutrasInfoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sTextField2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelOutrasInfoLayout.createSequentialGroup()
                        .addGroup(panelOutrasInfoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(panelOutrasInfoLayout.createSequentialGroup()
                                .addComponent(sDateChooser2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sLabel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sDateChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addComponent(sTextField1, GroupLayout.PREFERRED_SIZE, 177, GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sTextField3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sTextField4, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelOutrasInfoLayout.setVerticalGroup(
            panelOutrasInfoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelOutrasInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOutrasInfoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOutrasInfoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOutrasInfoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOutrasInfoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOutrasInfoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sDateChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sDateChooser2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBotoes.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        pnlBotoes.setName("pnlBotoes"); // NOI18N

        sButton1.setAction(actionGerarFormulario);
        sButton1.setName("sButton1"); // NOI18N
        pnlBotoes.add(sButton1);

        panelVeiculos.setBorder(BorderFactory.createTitledBorder("Veículos"));
        panelVeiculos.setName("panelVeiculos"); // NOI18N

        sLabel9.setText("Modelo:");
        sLabel9.setName("sLabel9"); // NOI18N

        sLabel10.setText("Placa:");
        sLabel10.setName("sLabel10"); // NOI18N

        sTextField5.setDocument(new GenericDocument(30));
        sTextField5.setName("sTextField5"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.veiculo.modelo}"), sTextField5, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sTextField6.setDocument(new GenericDocument(15, 
            GenericDocument.OPTION_APPLY_UPPERCASE ));
    sTextField6.setName("sTextField6"); // NOI18N

    binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.veiculo.placa}"), sTextField6, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jScrollPane3.setName("jScrollPane3"); // NOI18N

    tabelaVeiculo.setSortable(true);
    tabelaVeiculo.setName("tabelaVeiculo"); // NOI18N

    eLProperty = ELProperty.create("${model.filtro.veiculos}");
    jTableBinding = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tabelaVeiculo);
    columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${modelo}"));
    columnBinding.setColumnName("Modelo");
    columnBinding.setColumnClass(String.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${placa}"));
    columnBinding.setColumnName("Placa");
    columnBinding.setColumnClass(String.class);
    columnBinding.setEditable(false);
    bindingGroup.addBinding(jTableBinding);
    jTableBinding.bind();binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.veiculoSelecionado}"), tabelaVeiculo, BeanProperty.create("selectedElement"));
    bindingGroup.addBinding(binding);

    jScrollPane3.setViewportView(tabelaVeiculo);

    sButton2.setAction(actionAdicionarVeiculo);
    sButton2.setName("sButton2"); // NOI18N

    sButton3.setAction(actionExcluirVeiculo);
    sButton3.setName("sButton3"); // NOI18N

        GroupLayout panelVeiculosLayout = new GroupLayout(panelVeiculos);
    panelVeiculos.setLayout(panelVeiculosLayout);
    panelVeiculosLayout.setHorizontalGroup(
        panelVeiculosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(panelVeiculosLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelVeiculosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(panelVeiculosLayout.createSequentialGroup()
                    .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addGroup(panelVeiculosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(sButton2, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sButton3, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelVeiculosLayout.createSequentialGroup()
                    .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(sTextField5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(sLabel10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(sTextField6, GroupLayout.PREFERRED_SIZE, 169, GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    panelVeiculosLayout.setVerticalGroup(
        panelVeiculosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(panelVeiculosLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelVeiculosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(panelVeiculosLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                .addGroup(panelVeiculosLayout.createSequentialGroup()
                    .addComponent(sButton2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(sButton3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

        GroupLayout pnlPrincipalLayout = new GroupLayout(pnlPrincipal);
    pnlPrincipal.setLayout(pnlPrincipalLayout);
    pnlPrincipalLayout.setHorizontalGroup(
        pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(pnlPrincipalLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(panelPessoas, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelOutrasInfo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBotoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelVeiculos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    pnlPrincipalLayout.setVerticalGroup(
        pnlPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(panelPessoas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panelOutrasInfo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panelVeiculos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(sPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
    );

    getContentPane().add(pnlPrincipal, BorderLayout.PAGE_START);

    bindingGroup.bind();

    pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
