package br.com.petrobras.sistam.desktop.relatorio;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SCheckBox;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.sistam.desktop.components.SistamDateChooser;
import br.com.petrobras.sistam.desktop.components.SistamTimeChooser;
import br.com.petrobras.sistam.desktop.components.lookups.embarcacao.EmbarcacaoLookup;
import br.com.petrobras.sistam.desktop.components.lookups.servicoprotecao.EmpresaProtecaoLookup;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

public class RelatorioServicoSuprimentoAosNaviosDialog extends SDialog {

    private RelatorioServicoSuprimentoAosNaviosModel model;
    /** 
     * Constrói um dialog modal centralizado no frame pai.
     */
    public RelatorioServicoSuprimentoAosNaviosDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        model = new RelatorioServicoSuprimentoAosNaviosModel();
        initComponents();
        setLocationRelativeTo(parent);
    }

    public RelatorioServicoSuprimentoAosNaviosModel getModel() {
        return model;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        GenericAction actionGerar = new GenericAction();
        SPanel pabelGeral = new SPanel();
        SPanel panelBotao = new SPanel();
        SButton btGerar = new SButton();
        SPanel panelFiltros = new SPanel();
        SLabel sLabel1 = new SLabel();
        SLabel sLabel2 = new SLabel();
        SLabel sLabel3 = new SLabel();
        SLabel sLabel4 = new SLabel();
        SLabel sLabel5 = new SLabel();
        SLabel sLabel6 = new SLabel();
        SComboBox cboAgencia = new SComboBox();
        SComboBox cboTipoMercadoria = new SComboBox();
        SLabel sLabel7 = new SLabel();
        SComboBox cboTipoMaterial = new SComboBox();
        SLabel sLabel8 = new SLabel();
        EmbarcacaoLookup embarcacaoLookup = new EmbarcacaoLookup();
        SLabel sLabel9 = new SLabel();
        STextField txtNumViagem = new STextField();
        STextField txtNotaFiscal = new STextField();
        chkTerminal = new SCheckBox();
        chkCompanhia = new SCheckBox();
        SLabel sLabel10 = new SLabel();
        SLabel sLabel11 = new SLabel();
        SComboBox cboEmpresaTransporte = new SComboBox();
        SComboBox cboEmbarcacoes = new SComboBox();
        SLabel sLabel12 = new SLabel();
        EmpresaProtecaoLookup empresaProtecaoLookup = new EmpresaProtecaoLookup();
        SistamDateChooser dtPeriodoInicio = new SistamDateChooser();
        SistamTimeChooser dtPeriodoInicioTime = new SistamTimeChooser();
        SistamDateChooser dtPeriodoFim = new SistamDateChooser();
        SistamTimeChooser dtPeriodoFimTime = new SistamTimeChooser();
        SLabel sLabel13 = new SLabel();
        SComboBox comboPortos = new SComboBox();

        actionGerar.setIcon(new ImageIcon(getClass().getResource("/icons/excel.png"))); // NOI18N
        actionGerar.setMethodName("gerar");
        actionGerar.setTarget(model);
        actionGerar.setText("Gerar");
        actionGerar.setToolTipText("Gerar o relatório de visitas");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Serviço de Suprimento a Embarcação");

        pabelGeral.setName("pabelGeral"); // NOI18N
        pabelGeral.setLayout(new BorderLayout());

        panelBotao.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        panelBotao.setName("panelBotao"); // NOI18N

        btGerar.setAction(actionGerar);
        btGerar.setName("btGerar"); // NOI18N
        panelBotao.add(btGerar);

        pabelGeral.add(panelBotao, BorderLayout.CENTER);

        panelFiltros.setBorder(BorderFactory.createTitledBorder("Filtro para o Relatório"));
        panelFiltros.setName("panelFiltros"); // NOI18N

        sLabel1.setText("Agência:");
        sLabel1.setName("sLabel1"); // NOI18N

        sLabel2.setText("Tipo de Acesso:");
        sLabel2.setName("sLabel2"); // NOI18N

        sLabel3.setText("Tipo de Material:");
        sLabel3.setName("sLabel3"); // NOI18N

        sLabel4.setText("Nota Fiscal/GTRM/DTA/Outros:");
        sLabel4.setName("sLabel4"); // NOI18N

        sLabel5.setText("Local do Acesso:");
        sLabel5.setName("sLabel5"); // NOI18N

        sLabel6.setText("Período Início da Operação:");
        sLabel6.setName("sLabel6"); // NOI18N

        cboAgencia.setName("cboAgencia"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.agencias}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cboAgencia);
        bindingGroup.addBinding(jComboBoxBinding);
        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.agencia}"), cboAgencia, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        cboTipoMercadoria.setName("cboTipoMercadoria"); // NOI18N

        eLProperty = ELProperty.create("${model.tiposAcesso}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cboTipoMercadoria);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.tipoAcesso}"), cboTipoMercadoria, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        cboTipoMercadoria.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cboTipoMercadoriaActionPerformed(evt);
            }
        });
        cboTipoMercadoria.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cboTipoMercadoriaActionPerformed(evt);
            }
        });

        ResourceBundle bundle = ResourceBundle.getBundle("sistam-labels"); // NOI18N
        sLabel7.setText(bundle.getString("lblAte")); // NOI18N
        sLabel7.setName("sLabel7"); // NOI18N

        cboTipoMaterial.setName("cboTipoMaterial"); // NOI18N

        eLProperty = ELProperty.create("${model.tiposMaterial}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cboTipoMaterial);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.tipoMaterial}"), cboTipoMaterial, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        sLabel8.setText("Nome da Embarcação:");
        sLabel8.setName("sLabel8"); // NOI18N

        embarcacaoLookup.setName("embarcacaoLookup"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.navio}"), embarcacaoLookup, BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        sLabel9.setText("Número da Viagem:");
        sLabel9.setName("sLabel9"); // NOI18N

        txtNumViagem.setName("txtNumViagem"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.numeroViagem}"), txtNumViagem, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtNumViagem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtNumViagemActionPerformed(evt);
            }
        });
        txtNumViagem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtNumViagemActionPerformed(evt);
            }
        });

        txtNotaFiscal.setName("txtNotaFiscal"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.notaFiscal}"), txtNotaFiscal, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtNotaFiscal.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtNotaFiscalActionPerformed1(evt);
            }
        });
        txtNotaFiscal.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtNotaFiscalActionPerformed1(evt);
            }
        });

        chkTerminal.setText("Terminal");
        chkTerminal.setName("chkTerminal"); // NOI18N
        chkTerminal.setOpaque(false);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.terminal}"), chkTerminal, BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        chkCompanhia.setText("Companhia Docas");
        chkCompanhia.setName("chkCompanhia"); // NOI18N
        chkCompanhia.setOpaque(false);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.companhiaDocas}"), chkCompanhia, BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        sLabel10.setText("Empresa Transporte:");
        sLabel10.setName("sLabel10"); // NOI18N

        sLabel11.setText("Embarcação:");
        sLabel11.setName("sLabel11"); // NOI18N

        cboEmpresaTransporte.setName("cboEmpresaTransporte"); // NOI18N

        eLProperty = ELProperty.create("${model.empresasMaritima}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cboEmpresaTransporte);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.empresaMaritima}"), cboEmpresaTransporte, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        cboEmbarcacoes.setName("cboEmbarcacoes"); // NOI18N

        eLProperty = ELProperty.create("${model.servicos}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cboEmbarcacoes);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.servico}"), cboEmbarcacoes, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        sLabel12.setText("Fornecedor:");
        sLabel12.setName("sLabel12"); // NOI18N

        empresaProtecaoLookup.setName("empresaProtecaoLookup"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.fornecedor}"), empresaProtecaoLookup, BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        dtPeriodoInicio.setName("dtPeriodoInicio"); // NOI18N
        dtPeriodoInicio.setTimeChooser(dtPeriodoInicioTime);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoOperacao.dataInicio}"), dtPeriodoInicio, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        dtPeriodoInicioTime.setName("dtPeriodoInicioTime"); // NOI18N

        dtPeriodoFim.setName("dtPeriodoFim"); // NOI18N
        dtPeriodoFim.setTimeChooser(dtPeriodoFimTime);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.periodoOperacao.dataFim}"), dtPeriodoFim, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        dtPeriodoFimTime.setName("dtPeriodoFimTime"); // NOI18N

        sLabel13.setText(bundle.getString("lblPorto")); // NOI18N
        sLabel13.setName("sLabel13"); // NOI18N

        comboPortos.setName("comboPortos"); // NOI18N

        eLProperty = ELProperty.create("${model.portos}");
        jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, comboPortos);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.porto}"), comboPortos, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        GroupLayout panelFiltrosLayout = new GroupLayout(panelFiltros);
        panelFiltros.setLayout(panelFiltrosLayout);
        panelFiltrosLayout.setHorizontalGroup(
            panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sLabel1, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel13, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel8, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel9, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel2, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel3, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel12, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel4, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel6, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel5, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel10, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel11, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(comboPortos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboAgencia, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(embarcacaoLookup, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboTipoMaterial, GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(cboTipoMercadoria, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboEmbarcacoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboEmpresaTransporte, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNotaFiscal, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empresaProtecaoLookup, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelFiltrosLayout.createSequentialGroup()
                        .addComponent(dtPeriodoInicio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtPeriodoInicioTime, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sLabel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtPeriodoFim, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtPeriodoFimTime, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFiltrosLayout.createSequentialGroup()
                        .addComponent(chkCompanhia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkTerminal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNumViagem, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelFiltrosLayout.setVerticalGroup(
            panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAgencia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPortos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(embarcacaoLookup, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumViagem, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipoMercadoria, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipoMaterial, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(empresaProtecaoLookup, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNotaFiscal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(dtPeriodoInicio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtPeriodoInicioTime, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtPeriodoFim, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtPeriodoFimTime, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(sLabel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkCompanhia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkTerminal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEmpresaTransporte, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEmbarcacoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pabelGeral, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFiltros, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFiltros, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pabelGeral, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumViagemActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtNumViagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumViagemActionPerformed

    private void cboTipoMercadoriaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cboTipoMercadoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoMercadoriaActionPerformed

    private void txtNotaFiscalActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtNotaFiscalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaFiscalActionPerformed

    private void txtNotaFiscalActionPerformed1(ActionEvent evt) {//GEN-FIRST:event_txtNotaFiscalActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaFiscalActionPerformed1
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    SCheckBox chkCompanhia;
    SCheckBox chkTerminal;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
