package br.com.petrobras.sistam.desktop.empresa;

import br.com.petrobras.fcorp.swing.base.SInternalFrame;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SFormattedTextField;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STable;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.EmpresaMaritima;
import br.com.petrobras.sistam.desktop.SistamApp;
import br.com.petrobras.sistam.desktop.util.DesktopUtil;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.JTableBinding.ColumnBinding;
import org.jdesktop.swingbinding.SwingBindings;

public class EmpresaFrame extends SInternalFrame {
    private EmpresaFrameModel model;
    
    public EmpresaFrame() {
        this.model = new EmpresaFrameModel();
        initComponents();
        DesktopUtil.configurarComponenteCNPJ(campoCnpj, actionPesquisar);
    }

    public EmpresaFrameModel getModel() {
        return model;
    }
    
    public void adicionar(){
        EmpresaMaritima nova = model.obterNovaEmpresa();
        DetalhesEmpresaDialog dialog = new DetalhesEmpresaDialog(SistamApp.getSistamApp().getMainFrame(), nova);
        dialog.setVisible(true);
        
        if (dialog.getModel().isSalvo()){
            model.adicionar(dialog.getModel().getEmpresa());
        }
    }
    
    public void editar(){
        EmpresaMaritima empresaSelecionada = model.obterEmpresaParaEdicao();
        DetalhesEmpresaDialog dialog = new DetalhesEmpresaDialog(SistamApp.getSistamApp().getMainFrame(), empresaSelecionada);
        dialog.setVisible(true);
        
        if (dialog.getModel().isSalvo()){
            model.atualizar(dialog.getModel().getEmpresa());
        }
    }
    
    public void excluir() {
        model.excluir();
        model.pesquisar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        GenericAction actionAdicionar = new GenericAction();
        GenericAction actionEditar = new GenericAction();
        actionPesquisar = new GenericAction();
        GenericAction actionLimpar = new GenericAction();
        GenericAction actionExcluir = new GenericAction();
        SPanel painelBotoes = new SPanel();
        SButton botaoAdicionar = new SButton();
        SButton botaoEditar = new SButton();
        SButton botaoEditar1 = new SButton();
        SPanel sPanel1 = new SPanel();
        JScrollPane jScrollPane1 = new JScrollPane();
        STable sTable1 = new STable();
        SPanel painelFiltros = new SPanel();
        SButton botaoLimpar = new SButton();
        SButton botaoPesquisar = new SButton();
        SLabel labelAgencia = new SLabel();
        SComboBox comboAgencias = new SComboBox();
        SLabel labelEmpresa = new SLabel();
        STextField sTextField1 = new STextField();
        SLabel labelCnpj = new SLabel();
        campoCnpj = new SFormattedTextField();

        actionAdicionar.setIcon(new ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        actionAdicionar.setMethodName("adicionar");
        actionAdicionar.setTarget(this);
        actionAdicionar.setText("Adicionar");
        actionAdicionar.setToolTipText("Adiciona uma nova empresa");

        actionEditar.setIcon(new ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        actionEditar.setMethodName("editar");
        actionEditar.setTarget(this);
        actionEditar.setText("Editar");
        actionEditar.setToolTipText("Edita a empresa selecionada");

        Binding binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${not empty model.empresaSelecionada}"), actionEditar, BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        actionPesquisar.setIcon(new ImageIcon(getClass().getResource("/icons/listagem_busca.png"))); // NOI18N
        actionPesquisar.setMethodName("pesquisar");
        actionPesquisar.setTarget(model);
        actionPesquisar.setText("Pesquisar");
        actionPesquisar.setToolTipText("Pesquisa as empresas de acordo com os filtros informados");

        actionLimpar.setIcon(new ImageIcon(getClass().getResource("/icons/limpar1.png"))); // NOI18N
        actionLimpar.setMethodName("limpar");
        actionLimpar.setTarget(model);
        actionLimpar.setText("Limpar");
        actionLimpar.setToolTipText("Limpa os filtros informados");

        actionExcluir.setConfirm("Deseja realmente excluir a empresa ?");
        actionExcluir.setIcon(new ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        actionExcluir.setMethodName("excluir");
        actionExcluir.setTarget(this);
        actionExcluir.setText("Excluir");
        actionExcluir.setToolTipText("Excluir empresa");

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${not empty model.empresaSelecionada}"), actionExcluir, BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        setTitle("Empresas e Serviços");

        painelBotoes.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        painelBotoes.setName("painelBotoes"); // NOI18N

        botaoAdicionar.setAction(actionAdicionar);
        botaoAdicionar.setName("botaoAdicionar"); // NOI18N
        painelBotoes.add(botaoAdicionar);

        botaoEditar.setAction(actionEditar);
        botaoEditar.setName("botaoEditar"); // NOI18N
        painelBotoes.add(botaoEditar);

        botaoEditar1.setAction(actionExcluir);
        botaoEditar1.setName("botaoEditar1"); // NOI18N
        painelBotoes.add(botaoEditar1);

        sPanel1.setBorder(BorderFactory.createTitledBorder("Lista de Empresas"));
        sPanel1.setName("sPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        sTable1.setSortable(true);
        sTable1.setName("sTable1"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.listaDeEmpresas}");
        JTableBinding jTableBinding = SwingBindings.createJTableBinding(UpdateStrategy.READ_WRITE, this, eLProperty, sTable1);
        ColumnBinding columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${razaoSocial}"));
        columnBinding.setColumnName("Empresa");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${cnpjComMascara}"));
        columnBinding.setColumnName("CNPJ");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${email}"));
        columnBinding.setColumnName("E-mail");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${ativo}"));
        columnBinding.setColumnName("Ativa?");
        columnBinding.setColumnClass(Boolean.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.empresaSelecionada}"), sTable1, BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(sTable1);

        GroupLayout sPanel1Layout = new GroupLayout(sPanel1);
        sPanel1.setLayout(sPanel1Layout);
        sPanel1Layout.setHorizontalGroup(
            sPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );
        sPanel1Layout.setVerticalGroup(
            sPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelFiltros.setBorder(BorderFactory.createTitledBorder("Filtros"));
        painelFiltros.setName("painelFiltros"); // NOI18N

        botaoLimpar.setAction(actionLimpar);
        botaoLimpar.setName("botaoLimpar"); // NOI18N

        botaoPesquisar.setAction(actionPesquisar);
        botaoPesquisar.setName("botaoPesquisar"); // NOI18N

        labelAgencia.setText("Agência:");
        labelAgencia.setName("labelAgencia"); // NOI18N

        comboAgencias.setName("comboAgencias"); // NOI18N

        eLProperty = ELProperty.create("${model.listaDeAgencias}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE, this, eLProperty, comboAgencias);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.agencia}"), comboAgencias, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        labelEmpresa.setText("Empresa:");
        labelEmpresa.setName("labelEmpresa"); // NOI18N

        sTextField1.setDocument(new GenericDocument(100));
        sTextField1.setName("sTextField1"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.empresa}"), sTextField1, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        labelCnpj.setText("CNPJ:");
        labelCnpj.setName("labelCnpj"); // NOI18N

        campoCnpj.setName("campoCnpj"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.filtro.cnpj}"), campoCnpj, BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        GroupLayout painelFiltrosLayout = new GroupLayout(painelFiltros);
        painelFiltros.setLayout(painelFiltrosLayout);
        painelFiltrosLayout.setHorizontalGroup(
            painelFiltrosLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(painelFiltrosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(painelFiltrosLayout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(labelCnpj, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAgencia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(painelFiltrosLayout.createParallelGroup(Alignment.LEADING, false)
                    .addComponent(comboAgencias, GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(campoCnpj, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(painelFiltrosLayout.createParallelGroup(Alignment.LEADING)
                    .addGroup(painelFiltrosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoPesquisar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(botaoLimpar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelFiltrosLayout.createSequentialGroup()
                        .addComponent(labelEmpresa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(sTextField1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelFiltrosLayout.setVerticalGroup(
            painelFiltrosLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, painelFiltrosLayout.createSequentialGroup()
                .addGroup(painelFiltrosLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(labelAgencia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAgencias, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmpresa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(painelFiltrosLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(labelCnpj, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCnpj, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(painelFiltrosLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(botaoLimpar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(painelBotoes, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelFiltros, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelFiltros, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(sPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(painelBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    GenericAction actionPesquisar;
    SFormattedTextField campoCnpj;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
