package br.com.petrobras.sistam.desktop.components;

import br.com.petrobras.fcorp.common.support.AssertUtils;
import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;


public class DialogObservacao extends SDialog {
    private boolean confirmado = false;
    private boolean textoObrigatorio;

    public DialogObservacao(java.awt.Frame parent, String titulo, String mensagem, int tamanho){
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
        setTitle(titulo);
        lbMotivo.setText(mensagem);
        textArea.setDocument(new GenericDocument(tamanho));
    }

    public String getText() {
        return textArea.getText();
    }

    public boolean isConfirmado() {
        return confirmado;
    }

    public void setTextoObrigatorio(boolean textoObrigatorio) {
        this.textoObrigatorio = textoObrigatorio;
    }

    public void confirmar(){
        if (this.textoObrigatorio){
            AssertUtils.assertNotNullNotEmpty(getText().trim(), "É necessário informar o " + lbMotivo.getText() + ".");
        }
        confirmado = true;
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    // CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionOk = new br.com.petrobras.fcorp.swing.base.action.GenericAction();
        lbMotivo = new br.com.petrobras.fcorp.swing.components.SLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new br.com.petrobras.fcorp.swing.components.STextArea();
        sButton1 = new br.com.petrobras.fcorp.swing.components.SButton();

        actionOk.setMethodName("confirmar");
        actionOk.setTarget(this);
        actionOk.setText("Ok");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("");

        lbMotivo.setText("sLabel1");

        textArea.setColumns(20);
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textArea);

        sButton1.setAction(actionOk);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(lbMotivo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(sButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(lbMotivo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // CHECKSTYLE:ON


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.petrobras.fcorp.swing.base.action.GenericAction actionOk;
    private javax.swing.JScrollPane jScrollPane2;
    private br.com.petrobras.fcorp.swing.components.SLabel lbMotivo;
    private br.com.petrobras.fcorp.swing.components.SButton sButton1;
    private br.com.petrobras.fcorp.swing.components.STextArea textArea;
    // End of variables declaration//GEN-END:variables

}
