package br.com.petrobras.sistam.desktop.components.lookups.servicoprotecao;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SFormattedTextField;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STable;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.sistam.common.entity.EmpresaProtecao;
import br.com.petrobras.sistam.desktop.SistamApp;
import br.com.petrobras.sistam.desktop.servicoprotecao.DetalhesEmpresaProtecaoDialog;
import br.com.petrobras.sistam.desktop.util.DesktopUtil;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.GroupLayout;
import javax.swing.InputMap;
import javax.swing.JScrollPane;
import javax.swing.KeyStroke;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 * @author adzk
 */
public class EmpresaProtecaoInputDialog extends SDialog {

    private EmpresaProtecaoInputPresentationModel model;

    /**
     * Constrói um dialog modal centralizado no frame pai.
     */
    public EmpresaProtecaoInputDialog(java.awt.Frame parent) {
        super(parent, true);
        this.model = new EmpresaProtecaoInputPresentationModel();
        initComponents();
        
        DesktopUtil.configurarComponenteCNPJ(campoCnpj, actionConsultar);
        
        InputMap im = tabela.getInputMap(STable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        KeyStroke enter = KeyStroke.getKeyStroke("ENTER");
        im.put(enter, im.get(KeyStroke.getKeyStroke(KeyEvent.VK_GREATER, 0)));
        tabela.getActionMap().put(im.get(enter), actionConfirmar);
        setLocationRelativeTo(parent);

        tabela.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() > 1 && null != model.getEmpresaSelecionada()) {
                    confirmar();
                }
            }
        });
    }

    public EmpresaProtecaoInputPresentationModel getModel() {
        return model;
    }

    public void confirmar() {
        model.setConfirmado(true);
        dispose();
    }
    
    public void adicionar() {
        EmpresaProtecao empresa = new EmpresaProtecao();
        if (model.getTipoServicoProtecao() != null) {
            empresa.adicionarTipoServico(model.getTipoServicoProtecao());
        }
        DetalhesEmpresaProtecaoDialog dialog = new DetalhesEmpresaProtecaoDialog(SistamApp.getSistamApp().getMainFrame(), empresa);
        dialog.setVisible(true);
        if (dialog.getModel().isSalvo()) {
            empresa = dialog.getModel().getEmpresa();
            model.setNome(empresa.getRazaoSocial());
            model.setCnpjComMascara(empresa.getCnpjComMascara());
        }
    }

    @Override
    public void setVisible(boolean visible) {
        if (visible) {
            if (model.getEmpresas() != null) {
                if (!model.getEmpresas().isEmpty()) {
                    tabela.requestFocus();
                    tabela.getSelectionModel().setSelectionInterval(0, 0);
                } else {
                    campoNome.requestFocus();
                    getRootPane().setDefaultButton(btConsultar);
                }
            } else {
                campoNome.requestFocus();
                getRootPane().setDefaultButton(btConsultar);
            }
        }
        super.setVisible(visible);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"})
    @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        actionConsultar = new GenericAction();
        actionConfirmar = new GenericAction();
        GenericAction actionCancelar = new GenericAction();
        actionAdicionar = new GenericAction();
        SPanel sPanel1 = new SPanel();
        SLabel sLabel1 = new SLabel();
        SLabel sLabel2 = new SLabel();
        campoNome = new STextField();
        campoCnpj = new SFormattedTextField();
        btConsultar = new SButton();
        JScrollPane jScrollPane1 = new JScrollPane();
        tabela = new STable();
        btConsultar1 = new SButton();
        SButton btCancelar = new SButton();
        SButton btOk = new SButton();

        actionConsultar.setMethodName("consultar");
        actionConsultar.setTarget(model);
        actionConsultar.setText("Consultar");

        actionConfirmar.setMethodName("confirmar");
        actionConfirmar.setTarget(this);
        actionConfirmar.setText("OK");

        actionCancelar.setMethodName("dispose");
        actionCancelar.setTarget(this);
        actionCancelar.setText("Cancelar");

        actionAdicionar.setMethodName("adicionar");
        actionAdicionar.setTarget(this);
        actionAdicionar.setText("Nova Empresa");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Empresas do Serviço de Proteção");

        sPanel1.setName("sPanel1"); // NOI18N

        sLabel1.setText("Nome:");
        sLabel1.setName("sLabel1"); // NOI18N

        sLabel2.setText("CNPJ:");
        sLabel2.setName("sLabel2"); // NOI18N

        campoNome.setName("campoNome"); // NOI18N

        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.nome}"), campoNome, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        campoCnpj.setName("campoCnpj"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.cnpjComMascara}"), campoCnpj, BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        btConsultar.setAction(actionConsultar);
        btConsultar.setName("btConsultar"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tabela.setToolTipText("");
        tabela.setName("tabela"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.empresas}");
        JTableBinding jTableBinding = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tabela);
        JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${razaoSocial}"));
        columnBinding.setColumnName("Empresa");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${cnpjComMascara}"));
        columnBinding.setColumnName("CNPJ");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${cidade}"));
        columnBinding.setColumnName("Cidade");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${estado}"));
        columnBinding.setColumnName("Estado");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.empresaSelecionada}"), tabela, BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(tabela);
        tabela.getColumnModel().getColumn(1).setMinWidth(120);
        tabela.getColumnModel().getColumn(1).setMaxWidth(120);
        tabela.getColumnModel().getColumn(3).setMinWidth(60);
        tabela.getColumnModel().getColumn(3).setMaxWidth(60);

        btConsultar1.setAction(actionAdicionar);
        btConsultar1.setName("btConsultar1"); // NOI18N

        btCancelar.setAction(actionCancelar);
        btCancelar.setName("btCancelar"); // NOI18N

        btOk.setAction(actionConfirmar);
        btOk.setName("btOk"); // NOI18N

        GroupLayout sPanel1Layout = new GroupLayout(sPanel1);
        sPanel1.setLayout(sPanel1Layout);
        sPanel1Layout.setHorizontalGroup(
            sPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
            .addGroup(GroupLayout.Alignment.TRAILING, sPanel1Layout.createSequentialGroup()
                .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNome, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCnpj, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btConsultar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConsultar1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addGroup(GroupLayout.Alignment.TRAILING, sPanel1Layout.createSequentialGroup()
                .addComponent(btOk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCancelar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        sPanel1Layout.setVerticalGroup(
            sPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(sPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCnpj, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON
    // Variables declaration - do not modify//GEN-BEGIN:variables
    GenericAction actionAdicionar;
    GenericAction actionConfirmar;
    GenericAction actionConsultar;
    SButton btConsultar;
    SButton btConsultar1;
    SFormattedTextField campoCnpj;
    STextField campoNome;
    STable tabela;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
