package br.com.petrobras.sistam.desktop.agenciamento.formularios.capitania;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SDateChooser;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.SRadioPanel;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Agenciamento;
import br.com.petrobras.sistam.desktop.util.RelatorioUtil;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

public class NotaDespachoDialog extends SDialog {

    private NotaDespachoModel model;
    
    

    public NotaDespachoDialog(java.awt.Frame parent, Agenciamento agenciamento) {
        super(parent, true);
        model = new NotaDespachoModel(agenciamento);
        initComponents();
        setLocationRelativeTo(parent);

    }
    

  
    public NotaDespachoModel getModel() {
        return model;
    }

    public void imprimir() {
        model.validar();
        model.carregarVO();
        model.registrarEmissao();
        RelatorioUtil.abrirRelatorioNotaDespacho(model.getVoFormulario());
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"})
    @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        GenericAction actionImprimir = new GenericAction();
        ButtonGroup isentoGroup = new ButtonGroup();
        ButtonGroup cargaGroup = new ButtonGroup();
        SPanel pnlCabecalho = new SPanel();
        SLabel labelNome = new SLabel();
        SLabel labelNomeConteudo = new SLabel();
        SLabel sLabel10 = new SLabel();
        SLabel labelNome1 = new SLabel();
        SPanel pnlEscalas = new SPanel();
        SPanel pnlManobras = new SPanel();
        SLabel sLabel1 = new SLabel();
        JLabel jLabel1 = new JLabel();
        JLabel jLabel2 = new JLabel();
        txtAtracacao = new STextField();
        SRadioPanel sRadioPanel1 = new SRadioPanel();
        SRadioPanel sRadioPanel2 = new SRadioPanel();
        SLabel sLabel3 = new SLabel();
        SComboBox sComboBox1 = new SComboBox();
        SComboBox sComboBox2 = new SComboBox();
        SLabel sLabel4 = new SLabel();
        SPanel pnlBotoes = new SPanel();
        SButton sButton1 = new SButton();
        SDateChooser sDateChooser3 = new SDateChooser();
        SLabel sLabel13 = new SLabel();
        STextField sTextField1 = new STextField();
        SLabel sLabel2 = new SLabel();

        actionImprimir.setIcon(new ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        actionImprimir.setMethodName("imprimir");
        actionImprimir.setTarget(this);
        actionImprimir.setText("Gerar Formulário");

        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.possuiPermissao}"), actionImprimir, BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nota de Despacho Marítimo");

        pnlCabecalho.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        pnlCabecalho.setName("pnlCabecalho"); // NOI18N

        labelNome.setText("Nome:");
        labelNome.setName("labelNome"); // NOI18N

        labelNomeConteudo.setName("labelNomeConteudo"); // NOI18N
        labelNomeConteudo.setRequiredField(true);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agenciamento.embarcacao.nomeCompleto}"), labelNomeConteudo, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sLabel10.setName("sLabel10"); // NOI18N
        sLabel10.setRequiredField(true);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agenciamento.vgm}"), sLabel10, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        labelNome1.setText("Viagem:");
        labelNome1.setName("labelNome1"); // NOI18N

        GroupLayout pnlCabecalhoLayout = new GroupLayout(pnlCabecalho);
        pnlCabecalho.setLayout(pnlCabecalhoLayout);
        pnlCabecalhoLayout.setHorizontalGroup(pnlCabecalhoLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(labelNomeConteudo, GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addGap(80, 80, 80)
                .addComponent(labelNome1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(sLabel10, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        pnlCabecalhoLayout.setVerticalGroup(pnlCabecalhoLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCabecalhoLayout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(labelNome1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel10, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNomeConteudo, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(pnlCabecalho, BorderLayout.PAGE_START);

        pnlEscalas.setBorder(BorderFactory.createEtchedBorder());
        pnlEscalas.setName("pnlEscalas"); // NOI18N

        pnlManobras.setName("pnlManobras"); // NOI18N

        sLabel1.setText("Atracação:");
        sLabel1.setName("sLabel1"); // NOI18N

        jLabel1.setText("Isento:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Conduz Carga:");
        jLabel2.setName("jLabel2"); // NOI18N

        txtAtracacao.setDocument(new GenericDocument(100, 
            GenericDocument.OPTION_APPLY_UPPERCASE ));
    txtAtracacao.setName("txtAtracacao"); // NOI18N

    binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.atracacao}"), txtAtracacao, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    sRadioPanel1.setName("sRadioPanel1"); // NOI18N

    binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.tipoSimNao}"), sRadioPanel1, BeanProperty.create("elements"));
    bindingGroup.addBinding(binding);
    binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.voFormulario.isento}"), sRadioPanel1, BeanProperty.create("selectedElement"));
    bindingGroup.addBinding(binding);

    sRadioPanel2.setName("sRadioPanel2"); // NOI18N

    binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.tipoSimNao}"), sRadioPanel2, BeanProperty.create("elements"));
    bindingGroup.addBinding(binding);
    binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.voFormulario.carga}"), sRadioPanel2, BeanProperty.create("selectedElement"));
    bindingGroup.addBinding(binding);

    sLabel3.setText("Representante Legal:");
    sLabel3.setName("sLabel3"); // NOI18N

    sComboBox1.setName("sComboBox1"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.agenciamento.agencia.representantes}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, sComboBox1);
    bindingGroup.addBinding(jComboBoxBinding);
    binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.representanteSelecionado}"), sComboBox1, BeanProperty.create("selectedItem"));
    bindingGroup.addBinding(binding);

    sComboBox2.setName("sComboBox2"); // NOI18N

    eLProperty = ELProperty.create("${model.agenciamento.agencia.agenciaOrgao}");
    jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, sComboBox2);
    bindingGroup.addBinding(jComboBoxBinding);
    binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agenciaOrgaoSelecionado}"), sComboBox2, BeanProperty.create("selectedItem"));
    bindingGroup.addBinding(binding);

    sLabel4.setText("Órgão de Despacho:");
    sLabel4.setName("sLabel4"); // NOI18N

        GroupLayout pnlManobrasLayout = new GroupLayout(pnlManobras);
    pnlManobras.setLayout(pnlManobrasLayout);
    pnlManobrasLayout.setHorizontalGroup(pnlManobrasLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(pnlManobrasLayout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.TRAILING)
                .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1)
                .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.LEADING)
                .addGroup(Alignment.TRAILING, pnlManobrasLayout.createSequentialGroup()
                    .addComponent(sComboBox1, GroupLayout.PREFERRED_SIZE, 414, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE))
                .addGroup(Alignment.TRAILING, pnlManobrasLayout.createSequentialGroup()
                    .addComponent(sRadioPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addPreferredGap(ComponentPlacement.UNRELATED)
                    .addComponent(sRadioPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23))
                .addGroup(pnlManobrasLayout.createSequentialGroup()
                    .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.LEADING)
                        .addComponent(sComboBox2, GroupLayout.PREFERRED_SIZE, 414, GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAtracacao, GroupLayout.PREFERRED_SIZE, 412, GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE))))
    );
    pnlManobrasLayout.setVerticalGroup(pnlManobrasLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(Alignment.TRAILING, pnlManobrasLayout.createSequentialGroup()
            .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.BASELINE)
                .addComponent(txtAtracacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.TRAILING)
                .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addComponent(sRadioPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sRadioPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
    );

    pnlBotoes.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
    pnlBotoes.setName("pnlBotoes"); // NOI18N

    sButton1.setAction(actionImprimir);
    sButton1.setName("sButton1"); // NOI18N
    pnlBotoes.add(sButton1);

    sDateChooser3.setName("sDateChooser3"); // NOI18N

    binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.voFormulario.dataDocumento}"), sDateChooser3, BeanProperty.create("date"));
    bindingGroup.addBinding(binding);

    sLabel13.setText("Data do Documento:");
    sLabel13.setName("sLabel13"); // NOI18N

    sTextField1.setName("sTextField1"); // NOI18N

    binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.numeroOficiais}"), sTextField1, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    sTextField1.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            sTextField1ActionPerformed(evt);
        }
    });
    sTextField1.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            sTextField1ActionPerformed(evt);
        }
    });

    sLabel2.setText("Número de Oficiais:");
    sLabel2.setName("sLabel2"); // NOI18N

        GroupLayout pnlEscalasLayout = new GroupLayout(pnlEscalas);
    pnlEscalas.setLayout(pnlEscalasLayout);
    pnlEscalasLayout.setHorizontalGroup(pnlEscalasLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(pnlEscalasLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlEscalasLayout.createParallelGroup(Alignment.LEADING)
                .addGroup(pnlEscalasLayout.createSequentialGroup()
                    .addComponent(pnlBotoes, GroupLayout.PREFERRED_SIZE, 531, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addComponent(pnlManobras, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
        .addGroup(pnlEscalasLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(sLabel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.UNRELATED)
            .addComponent(sDateChooser3, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(sTextField1, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
            .addGap(31, 31, 31))
    );
    pnlEscalasLayout.setVerticalGroup(pnlEscalasLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(pnlEscalasLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(pnlManobras, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(pnlEscalasLayout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sDateChooser3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
            .addComponent(pnlBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    getContentPane().add(pnlEscalas, BorderLayout.CENTER);

    bindingGroup.bind();

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sTextField1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_sTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sTextField1ActionPerformed
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    STextField txtAtracacao;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
