package br.com.petrobras.sistam.desktop.agenciamento.formularios.capitania;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SCheckBox;
import br.com.petrobras.fcorp.swing.components.SDateChooser;
import br.com.petrobras.fcorp.swing.components.SFormattedTextField;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SNumericTextField;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.SRadioButton;
import br.com.petrobras.fcorp.swing.components.SRadioPanel;
import br.com.petrobras.fcorp.swing.components.STextArea;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Agenciamento;
import br.com.petrobras.sistam.desktop.util.DesktopUtil;
import br.com.petrobras.sistam.desktop.util.RelatorioUtil;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;

public class AvisoEntradaDialog extends SDialog {
    private AvisoEntradaModel model;
    
    public AvisoEntradaDialog(java.awt.Frame parent, Agenciamento agenciamento) {
        super(parent, true);
        model = new AvisoEntradaModel(agenciamento);
        initComponents();        
        setLocationRelativeTo(parent); 
    }

    public AvisoEntradaModel getModel() {
        return model;
    }
    
    public void imprimir(){
         model.validarAvisoEntrada();
        model.carregarVO();
        model.registrarEmissao();
        RelatorioUtil.abrirRelatorioAvisoDeEntradaCapitania(model.getVoFormulario());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        actionImprimir = new GenericAction();
        SPanel pnlEscalas = new SPanel();
        SPanel pnlBotoes = new SPanel();
        SButton sButton1 = new SButton();
        SPanel pnlCabecalho = new SPanel();
        SLabel sLabel3 = new SLabel();
        SLabel sLabel4 = new SLabel();
        SLabel labelNomeConteudo = new SLabel();
        SLabel labeVgmConteudo = new SLabel();
        SLabel sLabel13 = new SLabel();
        SDateChooser sDateChooser3 = new SDateChooser();
        SPanel pnlInfComplementares = new SPanel();
        SLabel sLabel9 = new SLabel();
        SLabel sLabel10 = new SLabel();
        SRadioPanel sRadioPanel2 = new SRadioPanel();
        SLabel sLabel11 = new SLabel();
        SRadioPanel sRadioPanel3 = new SRadioPanel();
        SRadioPanel sRadioPanel5 = new SRadioPanel();
        SPanel pnlNavioGraneleiroCombinado = new SPanel();
        SRadioPanel sRadioPanel4 = new SRadioPanel();
        SLabel sLabel12 = new SLabel();
        lblPonto = new SLabel();
        JScrollPane jScrollPane1 = new JScrollPane();
        STextArea sTextArea1 = new STextArea();

        actionImprimir.setIcon(new ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        actionImprimir.setMethodName("imprimir");
        actionImprimir.setTarget(this);
        actionImprimir.setText("Gerar Formulário");

        Binding binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.possuiPermissao}"), actionImprimir, BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aviso Entrada");

        pnlEscalas.setBorder(BorderFactory.createEtchedBorder());
        pnlEscalas.setName("pnlEscalas"); // NOI18N

        pnlBotoes.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        pnlBotoes.setName("pnlBotoes"); // NOI18N

        sButton1.setAction(actionImprimir);
        sButton1.setName("sButton1"); // NOI18N
        pnlBotoes.add(sButton1);

        pnlCabecalho.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        pnlCabecalho.setName("pnlCabecalho"); // NOI18N
        pnlCabecalho.setPreferredSize(new Dimension(400, 40));

        ResourceBundle bundle = ResourceBundle.getBundle("sistam-labels"); // NOI18N
        sLabel3.setText(bundle.getString("lblNome")); // NOI18N
        sLabel3.setName("sLabel3"); // NOI18N

        sLabel4.setText(bundle.getString("lblViagem")); // NOI18N
        sLabel4.setName("sLabel4"); // NOI18N

        labelNomeConteudo.setName("labelNomeConteudo"); // NOI18N
        labelNomeConteudo.setRequiredField(true);

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agenciamento.embarcacao.nomeCompleto}"), labelNomeConteudo, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        labeVgmConteudo.setName("labeVgmConteudo"); // NOI18N
        labeVgmConteudo.setRequiredField(true);

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agenciamento.vgm}"), labeVgmConteudo, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        GroupLayout pnlCabecalhoLayout = new GroupLayout(pnlCabecalho);
        pnlCabecalho.setLayout(pnlCabecalhoLayout);
        pnlCabecalhoLayout.setHorizontalGroup(
            pnlCabecalhoLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(labelNomeConteudo, GroupLayout.PREFERRED_SIZE, 255, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(labeVgmConteudo, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlCabecalhoLayout.setVerticalGroup(
            pnlCabecalhoLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCabecalhoLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(labelNomeConteudo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labeVgmConteudo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                        .addGroup(pnlCabecalhoLayout.createParallelGroup(Alignment.BASELINE)
                            .addComponent(sLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );

        sLabel13.setText("Data do Documento:");
        sLabel13.setName("sLabel13"); // NOI18N

        sDateChooser3.setName("sDateChooser3"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.dataDocumento}"), sDateChooser3, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        pnlInfComplementares.setBorder(BorderFactory.createTitledBorder(bundle.getString("informacoesComplementares"))); // NOI18N
        pnlInfComplementares.setName("pnlInfComplementares"); // NOI18N

        sLabel9.setText(bundle.getString("lblDeficienciaTratadas")); // NOI18N
        sLabel9.setName("sLabel9"); // NOI18N

        sLabel10.setText(bundle.getString("lblTransportaCarga")); // NOI18N
        sLabel10.setName("sLabel10"); // NOI18N

        sRadioPanel2.setName("sRadioPanel2"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.listaSimNao}"), sRadioPanel2, BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.voFormulario.deficienciasNestePorto}"), sRadioPanel2, BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        GroupLayout sRadioPanel2Layout = new GroupLayout(sRadioPanel2);
        sRadioPanel2.setLayout(sRadioPanel2Layout);
        sRadioPanel2Layout.setHorizontalGroup(
            sRadioPanel2Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        sRadioPanel2Layout.setVerticalGroup(
            sRadioPanel2Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        sLabel11.setText(bundle.getString("lblTransportaCargaPerigosa")); // NOI18N
        sLabel11.setName("sLabel11"); // NOI18N

        sRadioPanel3.setName("sRadioPanel3"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.listaSimNao}"), sRadioPanel3, BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.voFormulario.cargaPerigosa}"), sRadioPanel3, BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        GroupLayout sRadioPanel3Layout = new GroupLayout(sRadioPanel3);
        sRadioPanel3.setLayout(sRadioPanel3Layout);
        sRadioPanel3Layout.setHorizontalGroup(
            sRadioPanel3Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        sRadioPanel3Layout.setVerticalGroup(
            sRadioPanel3Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        sRadioPanel5.setName("sRadioPanel5"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.listaSimNao}"), sRadioPanel5, BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.voFormulario.cargaNoConves}"), sRadioPanel5, BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        GroupLayout sRadioPanel5Layout = new GroupLayout(sRadioPanel5);
        sRadioPanel5.setLayout(sRadioPanel5Layout);
        sRadioPanel5Layout.setHorizontalGroup(
            sRadioPanel5Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        sRadioPanel5Layout.setVerticalGroup(
            sRadioPanel5Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        GroupLayout pnlInfComplementaresLayout = new GroupLayout(pnlInfComplementares);
        pnlInfComplementares.setLayout(pnlInfComplementaresLayout);
        pnlInfComplementaresLayout.setHorizontalGroup(
            pnlInfComplementaresLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, pnlInfComplementaresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfComplementaresLayout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlInfComplementaresLayout.createParallelGroup(Alignment.TRAILING)
                        .addComponent(sLabel10, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLabel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(pnlInfComplementaresLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(sRadioPanel3, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sRadioPanel2, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sRadioPanel5, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        pnlInfComplementaresLayout.linkSize(SwingConstants.HORIZONTAL, new Component[] {sRadioPanel2, sRadioPanel3, sRadioPanel5});

        pnlInfComplementaresLayout.setVerticalGroup(
            pnlInfComplementaresLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlInfComplementaresLayout.createSequentialGroup()
                .addGroup(pnlInfComplementaresLayout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sRadioPanel2, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(pnlInfComplementaresLayout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(sRadioPanel5, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel10, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(pnlInfComplementaresLayout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(sRadioPanel3, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pnlInfComplementaresLayout.linkSize(SwingConstants.VERTICAL, new Component[] {sRadioPanel2, sRadioPanel3, sRadioPanel5});

        pnlNavioGraneleiroCombinado.setBorder(BorderFactory.createTitledBorder(bundle.getString("navioGraneleiro"))); // NOI18N
        pnlNavioGraneleiroCombinado.setName("pnlNavioGraneleiroCombinado"); // NOI18N

        sRadioPanel4.setName("sRadioPanel4"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.listaSimNao}"), sRadioPanel4, BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.voFormulario.navioGraneiroOuCombinado}"), sRadioPanel4, BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        GroupLayout sRadioPanel4Layout = new GroupLayout(sRadioPanel4);
        sRadioPanel4.setLayout(sRadioPanel4Layout);
        sRadioPanel4Layout.setHorizontalGroup(
            sRadioPanel4Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        sRadioPanel4Layout.setVerticalGroup(
            sRadioPanel4Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        sLabel12.setText(bundle.getString("lblIgualMaior18")); // NOI18N
        sLabel12.setName("sLabel12"); // NOI18N

        GroupLayout pnlNavioGraneleiroCombinadoLayout = new GroupLayout(pnlNavioGraneleiroCombinado);
        pnlNavioGraneleiroCombinado.setLayout(pnlNavioGraneleiroCombinadoLayout);
        pnlNavioGraneleiroCombinadoLayout.setHorizontalGroup(
            pnlNavioGraneleiroCombinadoLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlNavioGraneleiroCombinadoLayout.createSequentialGroup()
                .addGroup(pnlNavioGraneleiroCombinadoLayout.createParallelGroup(Alignment.LEADING)
                    .addGroup(pnlNavioGraneleiroCombinadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sLabel12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNavioGraneleiroCombinadoLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(sRadioPanel4, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavioGraneleiroCombinadoLayout.setVerticalGroup(
            pnlNavioGraneleiroCombinadoLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlNavioGraneleiroCombinadoLayout.createSequentialGroup()
                .addComponent(sLabel12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(sRadioPanel4, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblPonto.setText(bundle.getString("lblLocalizacaoPorto")); // NOI18N
        lblPonto.setName("lblPonto"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        sTextArea1.setColumns(20);
        sTextArea1.setDocument(new GenericDocument(80));
        sTextArea1.setLineWrap(true);
        sTextArea1.setRows(5);
        sTextArea1.setName("sTextArea1"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.localizacaoPorto}"), sTextArea1, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(sTextArea1);

        GroupLayout pnlEscalasLayout = new GroupLayout(pnlEscalas);
        pnlEscalas.setLayout(pnlEscalasLayout);
        pnlEscalasLayout.setHorizontalGroup(
            pnlEscalasLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(pnlBotoes, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlEscalasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEscalasLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(pnlInfComplementares, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNavioGraneleiroCombinado, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlEscalasLayout.createSequentialGroup()
                        .addComponent(lblPonto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(pnlEscalasLayout.createSequentialGroup()
                        .addComponent(sLabel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(sDateChooser3, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlCabecalho, GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlEscalasLayout.setVerticalGroup(
            pnlEscalasLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pnlEscalasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCabecalho, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(pnlInfComplementares, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(pnlNavioGraneleiroCombinado, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(pnlEscalasLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(lblPonto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(pnlEscalasLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(sDateChooser3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(pnlBotoes, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlEscalas, BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    GenericAction actionImprimir;
    SLabel lblPonto;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
