package br.com.petrobras.sistam.desktop.agenciamento.formularios.capitania;

import br.com.petrobras.fcorp.swing.base.SDialog;
import br.com.petrobras.fcorp.swing.base.action.GenericAction;
import br.com.petrobras.fcorp.swing.components.SButton;
import br.com.petrobras.fcorp.swing.components.SComboBox;
import br.com.petrobras.fcorp.swing.components.SDateChooser;
import br.com.petrobras.fcorp.swing.components.SHelpLabel;
import br.com.petrobras.fcorp.swing.components.SLabel;
import br.com.petrobras.fcorp.swing.components.SPanel;
import br.com.petrobras.fcorp.swing.components.STextField;
import br.com.petrobras.fcorp.swing.components.util.GenericDocument;
import br.com.petrobras.sistam.common.entity.Agenciamento;
import br.com.petrobras.sistam.desktop.components.SistamDateChooser;
import br.com.petrobras.sistam.desktop.components.SistamTimeChooser;
import br.com.petrobras.sistam.desktop.components.TimeZoneComboBox;
import br.com.petrobras.sistam.desktop.util.RelatorioUtil;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ResourceBundle;
import java.util.TimeZone;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

public class PasseSaidaDialog extends SDialog {
    private PasseSaidaModel model;
    
    public PasseSaidaDialog(java.awt.Frame parent, Agenciamento agenciamento) {
        super(parent, true);
        model = new PasseSaidaModel(agenciamento);
        initComponents();        
        setLocationRelativeTo(parent);        
        txtProximoPortoFormatado.setText(agenciamento.getDestinoFormatado());
        timeZoneComboBox.setSelectedItem(TimeZone.getTimeZone(agenciamento.getAgencia().getTimezone()));
    }

    public PasseSaidaModel getModel() {
        return model;
    }
    
    public void imprimir(){
        model.validar();
        model.carregarVO();
        model.registrarEmissao();
        RelatorioUtil.abrirRelatorioPasseSaidaCapitania(model.getVoFormulario());
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        GenericAction actionImprimir = new GenericAction();
        SPanel pnlCabecalho = new SPanel();
        SLabel sLabel8 = new SLabel();
        SLabel sLabel10 = new SLabel();
        SLabel labelNome = new SLabel();
        SLabel labelNomeConteudo = new SLabel();
        SPanel pnlEscalas = new SPanel();
        SPanel pnlManobras = new SPanel();
        SLabel sLabel2 = new SLabel();
        SComboBox sComboBox1 = new SComboBox();
        SLabel sLabel9 = new SLabel();
        timeZoneComboBox = new TimeZoneComboBox();
        SLabel sLabel7 = new SLabel();
        SistamDateChooser sistamDateChooser1 = new SistamDateChooser();
        SistamTimeChooser sistamTimeChooser1 = new SistamTimeChooser();
        SLabel sLabel1 = new SLabel();
        txtProximoPortoFormatado = new STextField();
        SLabel sLabel13 = new SLabel();
        SDateChooser sDateChooser3 = new SDateChooser();
        SHelpLabel sHelpLabel1 = new SHelpLabel();
        SPanel pnlBotoes = new SPanel();
        SButton sButton1 = new SButton();

        actionImprimir.setIcon(new ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        actionImprimir.setMethodName("imprimir");
        actionImprimir.setTarget(this);
        actionImprimir.setText("Gerar Formulário");

        Binding binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.possuiPermissao}"), actionImprimir, BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Passe de Saída");

        pnlCabecalho.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        pnlCabecalho.setName("pnlCabecalho"); // NOI18N

        sLabel8.setText("Viagem:");
        sLabel8.setName("sLabel8"); // NOI18N

        sLabel10.setName("sLabel10"); // NOI18N
        sLabel10.setRequiredField(true);

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agenciamento.vgm}"), sLabel10, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        labelNome.setText("Nome:");
        labelNome.setName("labelNome"); // NOI18N

        labelNomeConteudo.setName("labelNomeConteudo"); // NOI18N
        labelNomeConteudo.setRequiredField(true);

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agenciamento.embarcacao.nomeCompleto}"), labelNomeConteudo, BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        GroupLayout pnlCabecalhoLayout = new GroupLayout(pnlCabecalho);
        pnlCabecalho.setLayout(pnlCabecalhoLayout);
        pnlCabecalhoLayout.setHorizontalGroup(pnlCabecalhoLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(labelNomeConteudo, GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(sLabel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(sLabel10, GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );
        pnlCabecalhoLayout.setVerticalGroup(pnlCabecalhoLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCabecalhoLayout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(labelNomeConteudo, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCabecalhoLayout.createParallelGroup(Alignment.LEADING)
                        .addComponent(sLabel10, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlCabecalhoLayout.createParallelGroup(Alignment.BASELINE)
                            .addComponent(sLabel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        getContentPane().add(pnlCabecalho, BorderLayout.PAGE_START);

        pnlEscalas.setBorder(BorderFactory.createEtchedBorder());
        pnlEscalas.setName("pnlEscalas"); // NOI18N

        pnlManobras.setName("pnlManobras"); // NOI18N

        sLabel2.setText("Órgão de Despacho:");
        sLabel2.setName("sLabel2"); // NOI18N

        sComboBox1.setName("sComboBox1"); // NOI18N

        ELProperty eLProperty = ELProperty.create("${model.agenciamento.agencia.agenciaOrgao}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE, this, eLProperty, sComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.agenciaOrgaoSelecionado}"), sComboBox1, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        ResourceBundle bundle = ResourceBundle.getBundle("sistam-labels"); // NOI18N
        sLabel9.setText(bundle.getString("fusoHorario")); // NOI18N
        sLabel9.setName("sLabel9"); // NOI18N

        timeZoneComboBox.setEnabled(false);
        timeZoneComboBox.setName("timeZoneComboBox"); // NOI18N

        sLabel7.setText("Suspender até:");
        sLabel7.setName("sLabel7"); // NOI18N

        sistamDateChooser1.setName("sistamDateChooser1"); // NOI18N
        sistamDateChooser1.setTimeChooser(sistamTimeChooser1);
        sistamDateChooser1.setTimeZoneComboBox(timeZoneComboBox);

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.data}"), sistamDateChooser1, BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        sistamTimeChooser1.setName("sistamTimeChooser1"); // NOI18N

        sLabel1.setText("Próximo Porto:");
        sLabel1.setName("sLabel1"); // NOI18N

        txtProximoPortoFormatado.setDocument(new GenericDocument(100, 
            GenericDocument.OPTION_APPLY_UPPERCASE ));
    txtProximoPortoFormatado.setName("txtProximoPortoFormatado"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.proximoPortoFormatado}"), txtProximoPortoFormatado, BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    sLabel13.setText("Data do Documento:");
    sLabel13.setName("sLabel13"); // NOI18N

    sDateChooser3.setName("sDateChooser3"); // NOI18N

    binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.voFormulario.dataDocumento}"), sDateChooser3, BeanProperty.create("date"));
    bindingGroup.addBinding(binding);

    sHelpLabel1.setText("Quando necessário, acrescente a UF e escala do Próximo Porto");
    sHelpLabel1.setName("sHelpLabel1"); // NOI18N

        GroupLayout pnlManobrasLayout = new GroupLayout(pnlManobras);
    pnlManobras.setLayout(pnlManobrasLayout);
    pnlManobrasLayout.setHorizontalGroup(pnlManobrasLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(pnlManobrasLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.LEADING)
                .addComponent(sLabel2, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel7, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel1, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel13, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.LEADING)
                .addComponent(sDateChooser3, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(sHelpLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.LEADING, false)
                        .addComponent(txtProximoPortoFormatado, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Alignment.TRAILING, pnlManobrasLayout.createSequentialGroup()
                            .addComponent(sistamDateChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(sistamTimeChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(timeZoneComboBox, GroupLayout.PREFERRED_SIZE, 138, GroupLayout.PREFERRED_SIZE))
                        .addComponent(sComboBox1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addContainerGap(19, Short.MAX_VALUE))
    );
    pnlManobrasLayout.setVerticalGroup(pnlManobrasLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(pnlManobrasLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sLabel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(timeZoneComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sistamDateChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sistamTimeChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.CENTER)
                .addComponent(txtProximoPortoFormatado, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(pnlManobrasLayout.createParallelGroup(Alignment.BASELINE)
                .addComponent(sDateChooser3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(sLabel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(sHelpLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnlBotoes.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
    pnlBotoes.setName("pnlBotoes"); // NOI18N

    sButton1.setAction(actionImprimir);
    sButton1.setName("sButton1"); // NOI18N
    pnlBotoes.add(sButton1);

        GroupLayout pnlEscalasLayout = new GroupLayout(pnlEscalas);
    pnlEscalas.setLayout(pnlEscalasLayout);
    pnlEscalasLayout.setHorizontalGroup(pnlEscalasLayout.createParallelGroup(Alignment.LEADING)
        .addComponent(pnlBotoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(pnlEscalasLayout.createSequentialGroup()
            .addComponent(pnlManobras, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    pnlEscalasLayout.setVerticalGroup(pnlEscalasLayout.createParallelGroup(Alignment.LEADING)
        .addGroup(pnlEscalasLayout.createSequentialGroup()
            .addComponent(pnlManobras, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED)
            .addComponent(pnlBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    getContentPane().add(pnlEscalas, BorderLayout.CENTER);

    bindingGroup.bind();

    pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    TimeZoneComboBox timeZoneComboBox;
    STextField txtProximoPortoFormatado;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
